### ISSUE TITLE
Bags don't let you take items out of them

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#1001]
### Expected Behaviour

You can take items out of plant bags, chemistry bags, etc. by clicking on them the same way as a backpack.
### Actual Behaviour

You have to drag the bag to a tile and dump all of its contents on the ground to get anything out of it.
### Steps to reproduce the problem
1. Put items in a plant bag, chemistry bag, etc.
2. Open the bag and click on them.
3. They don't come out of the bag.

**Comment by ToGWtF** [comment]
I can't recreate this?

**Comment by Cruix** [comment]
Are you able to take pills out of chemistry bags, or are you using a backpack?

**Comment by ShadowDeath6** [comment]
Drag the bag onto your sprite, or put it into your belt/exosuit slot. Putting them into your pockets won't work without dragging and dropping.

**Comment by Cruix** [comment]
It does not work for me no matter what slot the bag is in.

**Comment by Cruix** [comment]
Is your client on 509 or 510?

**Comment by Cruix** [comment]
Looks like it was an issue with 510, fixed now.
