### ISSUE TITLE
Porting /tg/'s new hardsuits discussion

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#1011]
So it's appeared to me that we haven't ported a pretty badass hardsuit from /tg/ while other servers have. This came to me a few weeks ago, but I was busy with other things and forgot about it.

Now here's the brilliant PR implementing the elite hardsuit. Credit to @TheNightingale
[tgstation/-tg-station#13024](https://github.com/tgstation/-tg-station/pull/13024)

So the elite hardsuit doesn't have anything special about it, other than being a more elite version than the normal syndicate suit as well as being MUCH STRONGER.
The armor values are as following:
melee = 60,
bullet = 60 
laser = 50 
energy = 25 
bomb = 55
bio = 100 
rad = 70

Basically ,it'll be the strongest hardsuit ingame excluding the DS's own.
Only thing is, once I port this I will also be excluding the blood-red syndicate hardsuit from the uplink. Based on the fact that this hardsuit will cost 8 TC ... and as a nukeop you are already provided a bloodred hardsuit. Why would you buy another, WHO buys another? It's basically clickbait to anyone playing nukeop for the first time without realizing they are in the syndicate infiltrators suit storages.

I'll also be porting the shielded hardsuit, which was pretty cool and created by @KorPhaeron.
[tgstation/-tg-station#13717](https://github.com/tgstation/-tg-station/pull/13717)

In short is a hardsuit that has an energy shield built into it. The energy shield does **NOT** reflect energy projectiles, they are just destroyed upon hitting the shield.

The hardsuit with an energy shield built into it will also rapidly recharge upon each hit.

I was thinking of making the shielded hardsuit's shield toggable, lasting at least an entire 15 seconds blocking bullets / energy projectiles, at the same time the user interact with anything. After the 15 seconds, the shield takes an 45 seconds - an entire minute to recharge (like a spell) until it can be used again.

So I'll leave it up to discussion instead of going forward and porting it like a zombie, because I want to hear what you guys think about this.

**Comment by Groudonmaster** [comment]
Can we just port everything kor makes?

**Comment by imtakingabreakdontatme** [comment]
Start with lavaland if you're gonna do that.

Though lavaland might be a bit of a nightmare to port since it's all over the codebase

**Comment by ghost** [comment]
no lavaland, yog miners are very bad

**Comment by ShadowDeath6** [comment]
Shielded hardsuits are badass but it's going to cause so much salt from the playerbase

**Comment by Super3222** [comment]
I'll get started on this in the next couple of days, but don't expect it too soon.
