### ISSUE TITLE
Whitelist Prefs Reset

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1018]
### Expected Behaviour

Your "Ultra" preference for AI stays Ultra.
### Actual Behaviour

I encountered this once, but I haven't tried to reproduce it, but the "Ultra" preference or whitelist preference for heads/AI resets after a round.

**Comment by X-TheDark** [comment]
Duplicate of #752 
Nonetheless, don't close this. I'll take a look at this.
