### ISSUE TITLE
Portable Mirrors as a Syndie/Craftable Item

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#1027]
### Expected Behaviour

Players could craft portable mirrors or make them in autolathes, and they would work just like a regular mirror, but be able to fit in a pocket. Alternatively, a syndicate variation exists with makeup to change appearance like skin color, eye color, etc. and would cost about 6-ish TC. Could be used along with an agent card to create a nice disguise.
### Actual Behaviour

No such thing exists
### Steps to reproduce the problem
1. Try to be a cool syndie spy
2. Fail
3. Cri

**Comment by Super3222** [comment]
Just the feature of changing your looks in the mirror troubles me already.

Having a portable one which you can carry around and change your looks at any given time? No thank you.

I'd rather keep SS13 in the realm of magical realism, with a little more realism.

**Comment by Kmc2000** [comment]
Portable surgery, skin pigmentation, hair styling, 

Not really a fan of this, it makes no sense and would be strong as hell, if you want to be a "cool syndie spy" , just get plastic surgery, wear a gas mask, and carry a spare change of clothes

**Comment by ToGWtF** [comment]
MAYBE a one time use disguise kit to change hair, but idk about infinate use pocket mirror
