### ISSUE TITLE
Add surgical crates to cargo, make surgery operating tables moveable

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1028]
Add a surgical crate to cargo under the medical section.

Colored the same as other medical crates.

Comes with a saw, scapel, hemostat, retractor, cautery, and drill, plus a surgery operating table, drapes, a breathmask, anesthetic tank, gauze, and medical scrubs and the surgery apron.

Surgery operating tables can be unwrenched to be moveable and wrenched to become immobile.

Why?

Significantly makes surgery easier-the main reason nobody does it is because nobody can reach the rooms.

Also allows deconversion-based surgery to be less obnoxious. No needing to map in a surgery room to security either-you have a crate for it that you can order.

Also means that drapes are finally a replenishable resource rather than being able to stop surgery entirely by spacing all drapes and bedsheets

**Comment by Kmc2000** [comment]
can_be_unanchored = 1

Anchor_tool = obj/item/whatever

Should be pretty doable

**Comment by ToGWtF** [comment]
just use a regular table for surgery

will add surgery crates to cargo

**Comment by ghost** [comment]
regular tables are diff from op tables

op tables:

allow you to check surgery with the computer

allow you to buckle people to it

do not have a fail chance

so yes, make surgery tables moveable it makes no sense that you can't make a dedicated surgery room except for the one shitty room in medbay or robotics

**Comment by Cruix** [comment]
Please don't close issues when the PR has not been merged yet.
