### ISSUE TITLE
Borer Paralysis causing infect to autofail.

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation-classic#1031]
### Expected Behaviour

Target gets stunned by psychic lance, borer climbs into ear with no resistance
### Actual Behaviour

Borer constantly gets dislodged despite host paralysed and not moving at all.
### Steps to reproduce the problem
1. Position yourself next to someone
2. Hit them with psychic lance
3. Attempt to infect but get the error message saying that the host is moving around.

I think the problem is the victim is spamming their move keys so the infect registers that as them moving despite their sprite unable to move from the psychic paralyze.

Wasnt just me, other borer said it happened to him too.

**Comment by X-TheDark** [comment]
Yup, just tested this. They don't even have to move, it automatically fails during the paralysis. I can fix this.

**Comment by Stealthkibbler** [comment]
Changed title, Also it works when you normal infect without paralysing them.
