### ISSUE TITLE
THE GREAT GOOFCHEM REWORK

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1033]
So basically goon has a lot more chems and a lot more fun than we do.

But also their chem is absurdly, meme-tier robust to the point where their scientists don't even have access to grenades unless they're traitors and a lot of chems are jealously guarded secrets.

So this issue hopes to mix goonchem's fun with compensating for the advantages /tg/chemists get (easy access to injection mechanisms, for one).

PORT THIS.

https://github.com/tgstation/-tg-station/pull/17098

That's like 50% of what you have to do. Port that.

Port.

PORT.

Aaaaanyway.

In other terms...
# Poisons

Oxygen + Copper + Ethanol + 549K = Acetaldehyde. Depletes at 0.4, penetrates skin, +1 burn damage per tick, to plants or phytosians +4 tox a tick.

Sulphuric Acid +  Acetic Acid + Sulfur + 3 oxygen + 1 Hydrogen @ 544K  = Amantin.

No longer a traitor only chem.

Overheating it at 548K leads to it causing a (1, 2, 2) explosion. Does not scale. Now you can't just spam a lighter to watch it heat.

Neurotoxin- GONE, GOODBYE MEME BAR NEURO

Chem Neuro-Buffed.

No upper limit on how much brain or toxin damage it can cause. Knocks out on the 14th cycle.

Chem neuro + chlorine + hydrogen = Capulettium. Causes blurred vision (like being hit with a laser/morphine/chloral) and dizzied movement. KO's on the 11th cycle, makes them appear dead on examine. Past two minutes, all capulettium in the bloodstream is instantly purged.

Capulettium Plus -Intended as a replacement for zombie powder, which is an instant FUCK YOU. Capulettium + Amantin + Morphine = Capulettium Plus, which doesn't KO you, but makes you appear dead with either a random amount of brute or burn damage on examine, if laying down or sleeping. Means that the zombie implant is actually useable, since you can pretend to be dead but still get up and run around.

Cyanide- Changed so that on mixing, makes a smoke cloud containing only cyanide, if not mixed with stabilizing reagent first.

Dragon's Breath-

Made with Toxins Special + 3 CLF3 + Pyrosium + Capicascin, heated to 666K. Is a bar drink-Decays into 20 units of ethanol per 3 ticks, randomly applies weaken (2) or stun (2). If on fire, adds 20 firestacks, does +7 BURN damage a tick. Overheating to 668K emits a flash and splashes the drink on anyone in radius of the overheat-Usually you.

Ketamine-

Replaces incredibly fucking obnoxious and gross tirizine. Caps stamina regen at 30%, does significant stamina damage, and KO's on the 10th cycle. Replaces tirizine in sleepy pens. Counterable with Coffee, Iced Tea, Antitoxin, Iced Coffee, Hot Chocolate, or Nuka Cola.

Rajajiah-Traitor only chemical. On injection/ingestion, causes minor brain damage and bombards you with scary text messages such as 'Your arm moves without your control' or 'You hear screams from nowhere at all.' Causes you to randomly scream or cry. On the 29th cycle, kicks you out of your body (u r gost now), provides a meth tier speed buff and stun resist buff, and puts a hostile mob in control of your body (Y'know those dummy agressive humans, the ones that go around screaming yOU SHIT DICK FUCK SHIT, grab items to beat you up with, ect? That.) On expiry from the body, puts you back in control. Intent is to have, if not caught or treated or restrained in time, a rampaging, stun resistant greytide abomination that's going to try to beat the shit out of a bunch of confused and terrified doctors.

Spiders-

Squish a spiderling. Scoop up spiderling goo. 

Spiderling goo + Life @200K (Cool it with cyrostolane)= Spiders.

Ingest spiders. Burst into spiders after 15 ticks-One Drone and one hunter.

Have fun.

Also if applied, you are covered in spiders. This has no effect aside from being REALLY FUCKING GROSS JESUS CHRIST

Stable mutagen -

Unstable mutagen + Bromine + Acetone + Lithium = A chem that, if mixed with blood, allows for temporary assuming of the target's UI (as long as the chemical is in you.). Basically, mix with blood and either yourself, or whoever you injected, now looks like whoever that blood's DNA belonged to. Also does +2 Rad +1 Toxin a tick, so you can't keep it in you for too long.
# Pyrotechnics

The big kablamo.

Smoke -CHANGE HOW SMOKE WORKS.

Currently smoke won't apply reagents to walls or floors, only people. Or, it'll barely apply reagents to floors.

Revamped smoke-

Smoke can hold up to three chemicals. Smoke can apply chemical deposits to floors, or in the case of certain chemicals (IE spacelube) do the thing smoke already does with them. So a blackpowder smoke will scatter piles of blackpowder dust everywhere. 

Smoke can also apply it's reagents to walls as well. For example, a thermite smoke cloud will apply thermite to walls, and to floors. A thermite CLF3 smoke cloud will IGNITE those walls and floors.

Chlorine Azide-2 Chlorine + Oxygen, + Sodium + 3 Nitrogen = Chlorine Azide.

Explodes immediately on reaction in a (1, 1, 3) explosion. Exists to screw people over who just hammer buttons on the chem dispenser like an idiot. Doesn't scale with volume.

Kerosene - Carbon + Oil + Space Cleaner heated to (523K). Creates a very large fireball on mixing-Not like phlog's plasma fireball-more like CLF3's 'FWOOSH'. Otherwise just a stronger version of napalm-more firestacks, heats faster. Scales with volume-a bluespace kerosene grenade is probably going to create a fireball that will (briefly, no plasma fuel) encompass the brig.

Liquid Dark Matter- MODIFY

Throwforce of objects thrown by LDM is increased, actual suction force is increased to ALWAYS knock objects to or near the point of detonation. On application of floor tile, creates (as long as the tile is wet with it, tile will shine a dark purple) a space-wind like constant tug to that floor tile. The floor tile LDM can still be heated to be activated later, and then promptly suck everything in again. Very mean when paired with something like CLF3 foam, moreso than it usually is.

Sorium-MODIFY

Reactions greater than 50u have a chance of stripping metal sheets right off the walls (making them girders, but not for cultwalls or rwalls), or knocking non-rwindows out of their frames. Throwforce and power is once again, increased. Can be applied to floor tiles-unlike LDM, it isn't a passive effect, but stepping on the floor tile will launch you backwards (with no stun or weaken, just as though you were thrown, make sure not to hit a wall though). Heating the Sorium on the floor will activate it as normal.

Phlogisition Dust-Burns weaker than Phlogistion. Made with Phlog + Charcoal + Sulphur + Phosphorus. On application to someone on fire, adds more firestack, does heavy burn damage. On ingest, burns from the inside out. As with most other dust chems like BP, can be scattered on the floor-on iginition, creates a weaker version of the phlogistion effect that scales with volume. Ignites at standard stabilizing reagent activation temps.

Pyrosium-No longer heats only the container, but the entire tile itself and anything on it. Meaning standing on an active pyrosium beaker is going to very quickly make the air temperature very unpleasant to stand in, and anything flammable is gonna catch fire really quickly-including thermite or blackpowder.

Blackpowder-Now has a dust form, in that splashing it or spraying it or using it in a smoke reaction will leave black powder dust (using the same sprite as ash) on the floor. Otherwise, can be ignited and used exactly as usual-so yes, you can have sparking bomb trails leading all the way to a massive blackpowder storage in the bar backroom, a la Looney Toons.

Thermite-Can now be applied to floor tiles for a (50% or so) chance of melting right through them. Can be used in smoke or foam reactions to also apply thermite to floor or walls-So yes, you can set off thermite foam grenades and run through the hallways blasting a flamethrower until everything catches fire and melts. That being said, it won't work on reinforced floors and takes a lot of direct heat to ignite, so it's really only going to happen in combination with a dedicated plasmafire, pyrosium, other explosions (assuming the space doesn't cool it down near immediately) or fire chems that create a sustained reaction, like CLF3

Cyrostolane-Instantly extinguishes fire and removes all fire stacks if splashed or sprayed. If not on fire, freezes those caught in it in a block of ice that can be resisted out of in 0.3 minutes-about the same time as cablecuffs or zipties. You cannot be moved or dragged otherwise in the block of ice, the ice can be shattered (having a health of 250 if you're whacking it with a melee item) and negates external and internal temperatures in favor of setting you to normal body temp and reducing yours constantly while in the ice. 

In a smoke or foam or splash reaction on the floor, functions also the same as a nanofrost puff, extinguishing burning plasma and turning it into cold N2, in addition to making the floor icey, slipping about the same as soap and slowing down temperature increase and fire spread on that tile.

yay fun

**Comment by Kmc2000** [comment]
What is this.....adam making a meme issue....?

**Comment by ghost** [comment]
i pressed enter too early hold the fuck on it showed up

**Comment by Nirnael** [comment]
Tag WTF ADAM?

**Comment by EMT321** [comment]
My hype can only sustain itself without sustenance for so long...

Also, I fully expect to be associated with the death chems by way of Adams chem sprayer

**Comment by ShadowDeath6** [comment]
In what way will this actually benefit the server? I'm not a fan of literally every single thing in the game being lethal, especially chem. Chem is way too powerful for its own good and adding this shit just makes them that much more so. That being said, it would be cool for chem to have other uses, like cryostylane smoke nades to put out fires. 

> Goonchem isn't somehow inherently better than /tg/chem, it was considered better because of the existence of more weird overpowered shit that almost nobody knew. But we're open source, so trying to mimic that aspect of goonchem is neither feasible nor desirable.

**Comment by ghost** [comment]
more creativity

also right now we're quite literally half-assed goonchem

so we can either go back to trekkchem or go moreso for goonchem w.o copying it 1 for 1 and their absurd potency and lethality

**Comment by ShadowDeath6** [comment]
Why go for one chem to another when we can glean a bit from both? It's nice being our own server with different bay and goon and tg and some of our own, I don't see a huge need to forfeit that. It's what makes our server different. If they wanted one or the other, they could play on the respective servers.

**Comment by ghost** [comment]
the issue is that half-assing goonchem makes it asschem

at the least, smoke and powder reactions offer a variety more creativity without touching shit like makeable initropidil

**Comment by ShadowDeath6** [comment]
How does if make it asschem
"Oh no the deadly shit in chemistry is still marginally weaker than the deadly shit in the traitor poisons kit"

**Comment by ParagonPrime** [comment]
Rajajiah and Capulettium (took me way too long to get that reference) are the only two chems I really have any interest in at all because they actually do some unique, fun shit.

Everything else- mehhhhhhhhhhhhhhhhhhh. Agreed that Chemistry is already kinda fucking powerful as it is,

**Comment by Stealthkibbler** [comment]
Rajajiah turns people into automatons? yes pls

**Comment by ghost** [comment]
Most of these aren't actually too deadly or powerful.

Cyanide is flat out terrible-this should see it getting more use.

Smoke and foam reactions got nerfed pretty badly (THANKS EPH) so this should lead to their effectiveness again.

Sorium and Dark Matter, you have to admit, are at the least fun. They're also never used chems-this could get them more use.

Kill dragon's breath if you want, scrap it, that's fine.

Ketamine is infinitely superior to Tirizine and nowhere near as stunlock obnoxious.

The neurotoxin change is sorely needed from an obnoxious instant stun to a delayed KO along the lines of sulfonal or chloral.

Spiders is fun and also very very hard to make.

Remember that almost all of these poisons are injection chems, so no smoke or foam polykill grenades without serious effort.

Thermite is a very fun chem with very little use-this should see it being treated as it should be (dangerous and useful) and thermite foam grenades will be the talk of the town.

Phlog dust is really only powerful in high amounts, good for making areas hazardous to pass but not for actual damage, and not very effective otherwise compared to already existing phlog-it's the lazyman's way of laying booby traps.

Black powder is literally supposed to have that functionality and it not is a major oversight, and it used to have that functionality too.

Pyrosium and Cyrostolane are rarely used chems, which is a shame, because they have some amazingly useful applications, but due to oversights it's easier just to spamclick a beaker with a lighter. This should see them getting some use.

None of this is particularly overpowered or heavy damaging (aside from dragons breath which we can scrap) and mostly just good in the hands of a skilled chemist with a good mix.

It's less a chem buff and more adding new ways to apply chems.

**Comment by ShadowDeath6** [comment]
Unless we nerf chemistry's ability to crank out this shit, this is going to be a buff to a ton of things, especially stuff like explosive or firestarting chemicals being MORE powerful than they already are.
