### ISSUE TITLE
Make loose Tesla lose energy

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1035]
I don't exactly see how it works now, but when released, Tesla should gradually lose some of its power since it discharges energy to wreck things, electrocuting APCs and other machines, as opposed to the singularity, which is a black hole, so, with its erractic, unpredictable jumping movement, it wouldn't do an instant kill that easily over a much greater distance even after some 10 minutes, because it's much more unpredictable, and faster than the singularity.
Also, As far as I know the tesla either decreases or gradually gains balls depending on the PA setting, cannot be kept as steadily as the singularity, and my guess is that engineers just keep it in an increasing state, because they don't want to sit around the tesla all day.. that's just an afterthought.

Any ideas about this?

**Comment by ShadowDeath6** [comment]
it does lose energy when outside the PA generator, it just doesn't dissipate. It usually hovers around toxins test, zapping it for the entire round since it teleports like ~3 tiles at 0 energy.

**Comment by ghost** [comment]
it does lose energy

tbh make it not lose energy since it barely does anything when released

**Comment by ShadowDeath6** [comment]
Do not buff stupid meme instacrit
at least you can run from singloth

**Comment by X-TheDark** [comment]
Tesla loses energy and as it does so, it even loses the orbiting balls. The thing is, if you are struck by any single beam, you are dead, so a tesla without orbiting balls is as strong as one with many (except that the shocks are not as widespread, since there's only 1 ball that releases the shocks).
