### ISSUE TITLE
Add a way to order multiple items at once at cargo

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#1038]
### Expected Behaviour

You instantly order the 23 teslas.
### Actual Behaviour

It takes an eternity doing it one by one, give up and only order 18.

Yes, I was the one behind the _21 teslas_  meme engine.

**Comment by ghost** [comment]
yes this is being done by super by porting /tg/cargo and /tg/cargo UI

**Comment by Super3222** [comment]
aye
