### ISSUE TITLE
Forceghost cult-banned players upon conversion

### ISSUE THREAD

**Issue by Alblaka** [yogstation13/yogstation-classic#1039]
### Expected Behaviour

People get antagbanned from cult. They cant grief cult anymore
### Actual Behaviour

They get converted and then (subtly) grief cult.
### Suggested Change

If you convert a player who's antagbanned from cultist, forceghost them. Catatonic cultists are still of use to the cult, thus it's not a straight up loss, and avoids the issue of people griefing cult (i.e. by suiciding, forcing people to summon nar nar in no-narnar objectives, removing runes, etc)

**Comment by ghost** [comment]
True, converting an antagbanned player should either ghost them and put another ghost in control of the mob with an offering (Do you want to be a cultist?)

Or in the case of gang, just kill them outright if penned.

**Comment by FluffySurvivor** [comment]
:+1:

**Comment by Kmc2000** [comment]
:+1:

**Comment by oisin100** [comment]
:+1:

**Comment by ShadowDeath6** [comment]
Now just make this happen for rev too so I can just instantly die on being flashed

**Comment by ToGWtF** [comment]
inb4 we antag ban ourselves from rev
