### ISSUE TITLE
Foam dart bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#104]
Foam darts disappear if they hit Beepsky.

**Comment by Cruix** [comment]
It's not just Beepsky or secbots, it's all bots.

**Comment by Cruix** [comment]
It seems that bullets that hit bots like Beepsky only get their bullet_act() proc called if the bullet does brute or burn damage. Foam darts do 0 OXY damage on hit, so the proc that makes them fall to the ground is never called.

**Comment by george99g** [comment]
Fixed in #105
