### ISSUE TITLE
Nerf double-bladed energy sword, allow batons the ability to knock down.

### ISSUE THREAD

**Issue by RintheCynical** [yogstation13/yogstation-classic#1040]
### After one of our recent updates, double eswords now block literally everything. That means melee; stunbatons, telescopic batons, anything besides a bottle to the head, which doesn't really work on nukeops.

12 TC turns you into a walking tank. After witnessing a single near-dead nukeop below orange take down an entire squad of ERT by just holding a sword, I think this is an OBVIOUS problem.

There's literally no reason to buy anything other than a double esword as a nukeop, as one or even two people could steamroll the entire station, simply because they can't be touched. That is insane. There's no chance, at least before you could use a baton and bring them down, but now the only real choice is to counter with space lube. That's a joke.

Remove the blockage of energy swords from deflecting batons. Allow users of energy swords to be knocked down from their stuns, aka, revert eswords back to the way they were. I don't possible see how this can stay a thing.

**Comment by ShadowDeath6** [comment]
This was actually an oversight in @Super3222 's shield overhaul thing. Critical pls since this is abusable as fuck

**Comment by FluffySurvivor** [comment]
do they block bullets too now ?

**Comment by ShadowDeath6** [comment]
They have the same chance as a riot shield to block shit
They block bullets 50% of the time

**Comment by ParagonPrime** [comment]
Dual eswords should NOT have 100% chance to block batons. Batons were the one true counter to them, and so it should remain. In fact, they should have no chance at all to block batons or other melees.

Now, disarms, on the other hand- disarms should very much be blocked by dual eswords.

**Comment by ghost** [comment]
this is a BUG

**Comment by FluffySurvivor** [comment]
@AdamElTablawy
No it's not a bug. Neither it is intended... but you can rest your banhammer.

**Comment by ShadowDeath6** [comment]
Yes it is a bug

**Comment by ghost** [comment]
no it is a bug @FluffySurvivor

this is an error carryover from eswords having a block chance from riot shields

**Comment by Time-Green** [comment]
Ok.
Shields protect against all damage.
Not even bullets work
A guy with a riot shield got attacked by 3 juggernauts, and just stood still. Not even a scratch
The only way you're going to kill them is through slipping, surroundings or suicide bombing

**Comment by ShadowDeath6** [comment]
Simple mobs should ignore shields

**Comment by Groudonmaster** [comment]
Lets just make riot shields have the strength of an rwall. Once it passes that threshold it shatters into reinforced glass and metal.
