### ISSUE TITLE
Job Unlock Timer/Delay shift-based instead of time-based

### ISSUE THREAD

**Issue by glyphscribe** [yogstation13/yogstation-classic#1045]
### Expected Behaviour

Player demonstrates lack of grief by playing a substantial number of rounds, advanced jobs unlock earlier.
### Actual Behaviour

Player waits ages to play a role they may already be familiar with.
### Steps to reproduce the problem
1. Be player with less than required days of play.
2. Try to be advanced role.
3. Cry.

**Comment by Time-Green** [comment]
This might be a good idea.

It happens alot someone joins once.
Comes back months later, and just as inexperienced but then as cap.

I support this

**Comment by Super3222** [comment]
Imagine winding up a clock and starting it on January 1st, 2016. And never coming back to the server.

Come back to the server on April 26th, 2016, check the clock, and you have every job unlocked on the server.

That's how the system currently works. And it's bad.
