### ISSUE TITLE
Killing a mindwapping lich in your old body kills you when he casts RISE!

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#1046]
### Expected Behaviour

Kill the wizard who just mindswapped you in your old body, maybe he lich-revives somewhere else.
### Actual Behaviour

You instantly die..
### Steps to reproduce the problem
1. Be mindswapped by a lich.
2. Shoot him to death (I used captains laser)
3. Lich casts RISE!
4. Your body dissolves into dust, while he revives.

**Comment by ShadowDeath6** [comment]
It's realistic at least

**Comment by EMT321** [comment]
In order to more eloquently explain:

Let LW be lich wizard, and PL be player.

LW casts mind-swap on PL.
PL gets up before LW, now in swapped bodies, and kills LW (in what was PL's body a moment ago).

PL, in the lich body, instantly disintegrates and dies. LW in the PL body still respawns at their totem, but PL's body does NOT disintegrate.
