### ISSUE TITLE
Nanofrost launcher can't extinguish!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1047]
Nanofrost launcher was _seemingly_ empty, I refilled it (200u), and when I wanted to extinguish fire, it was still empty! It happened right after I refilled it..

"Server time: 2016-04-27 06:52

The extinguisher nozzle is empty!"

**Comment by Cruix** [comment]
What setting was the launcher on when you refilled it and when you tried to fire it?

**Comment by 00aquir** [comment]
I guess it was on initial "no water drop icon" extinguisher or "switched to" extinguisher setting when refueled and the same when it was empty (when I tried to use it). The metal foam worked and I didn't try nanofrost, but I might have switched across all before using extinguisher.. but that always worked before.
