### ISSUE TITLE
Allow constructs to interact with runes

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#1048]
### Expected Behaviour

Constructs are a useful part of cult and provide support and make construct cult a reality
### Actual Behaviour

"go kill AI"
### Steps to reproduce the problem
1. Be artificer
2. Try to activate a conversion rune to convert somebody since nobody knows how to click red circle
3. Doesn't work 
# HOW DO YOU FIX THIS?

Simple, let constructs click on runes to use them. 
Also, maybe let artificers write any runes as well, but not have a list of words so they can't just say all words over cultspeak.

**Comment by penguinfisher** [comment]
I likey. Maybe instead of giving them the ability to just write runes, what if we made it so the artificers could only write runes that the cult knows? you would smash your book into an artificers face-hole and that would be the words it can choose from to scribe runes. it cannot make any runes by default tho.

**Comment by Groudonmaster** [comment]
Eh I don't think the writing runes would make sense because the constructs don't have blood to write with

**Comment by ShadowDeath6** [comment]
They can just generate their own blood or something

**Comment by ghost** [comment]
Only constructs i'd say should be able to write runes are harvesters, otherwise jugg spam/artificer spam would be the new meta and you'd have tons of artificers spam using runes like blood boil and manifest ghost while taking no damage

**Comment by ShadowDeath6** [comment]
> construct cult would be the new meta

that's a good thing though

**Comment by FluffySurvivor** [comment]
the best cult is a removed cult

**Comment by ShadowDeath6** [comment]
The best cult is murderboner construct cult

**Comment by ShadowDeath6** [comment]
https://github.com/tgstation/-tg-station/pull/17345
Based Joan

**Comment by FluffySurvivor** [comment]
@ShadowDeath6 
Go play on tg then :^)

**Comment by ShadowDeath6** [comment]
@FluffySurvivor 
That's cool
But how about fuck yourself >:^)
