### ISSUE TITLE
Buff R&D

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#1056]
### Expected Behaviour

Experimentor is useful
### Actual Behaviour

Accidentally upgrade experimentor and it becomes useless
# how 2 fix :^)

Make experimentor have a higher chance of the blood succ event which upgrades the tech you put into it with less chance of other stuff like being blown up

**Comment by AsV9** [comment]
# how 2 fix :^) v2

change how R&D to not work off just stuffing a list of items into a machine idk about the experimentor, never seen it used

**Comment by ShadowDeath6** [comment]
experimentor is used to upgrade tech to shove into the R&D machine but is never used because it's unreliable as hell

**Comment by LesVegetables** [comment]
I don't know about unreliable, I'd say it fairly reliably emps the fucking toxins doors / fire alarms and traps you in there forever when someone actually uses it

**Comment by EMT321** [comment]
The fact that it is less likely to do its one benefit when upgraded is foolish.
