### ISSUE TITLE
Buff hulks

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#1059]
### Expected Behaviour

Hulks are a considerable threat. 
### Actual Behaviour

You are valid to literally everyone (security, sillicons and greytide alike), while at most you can do is use a stunbaton in combat if you somehow weren't already killed. 

"just laser him gg"

The last nerf destroyed hulks. 
### Steps to reproduce the problem
1. Be hulk
2. Try to do something. 
3. You can't because riot shield is the new meta which essentially nullifies a hulk. 
4. Die because your survival expectancy is proportional with your stunprod/stunbaton charge.

**Comment by oisin100** [comment]
Buff something Genetics can make in less than 10 minutes what can break into anywhere in seconds and cant be stunned? No thanks.

**Comment by FluffySurvivor** [comment]
so what if you can't be stunned
Security is 100% allowed to terminate you on sight. Non antag asimov AIs can space you without a second thought. 
Breaking is slow, obvious, and you globally state you're a hulk and hence the ai can instantly track you down and get you killed.

**Comment by oisin100** [comment]
> Breaking is slow, obvious, and you globally state you're a hulk and hence the ai can instantly track you down and get you killed.

Take your radio off.

> Security is 100% allowed to terminate you on sight.

They need a reason to terminate you.

> Non antag asimov AIs can space you without a second thought.

Silicon policy means they cant without reason.

**Comment by FluffySurvivor** [comment]
Not many people take their radios off

Non-Lethal Weapons Ineffective - certain targets are impervious to NLWs, such as Mechs, Xenomorphs, Borgs, and Hulks. Lethal force may be used against these targets if they prove hostile.

Hulks are not human and when you see a hulk breaking shit you can assume he is attempting human harm so valid.

**Comment by oisin100** [comment]
> Not many people take their radios off

Thats their fault.

> Non-Lethal Weapons Ineffective - certain targets are impervious to NLWs, such as Mechs, Xenomorphs, Borgs, and Hulks. Lethal force may be used against these targets if they prove hostile.

If they prove hostile. They need a reason to use lethal force.

> Hulks are not human and when you see a hulk breaking shit you can assume he is attempting human harm so valid.

Which is why you take your radio off.

**Comment by Nirnael** [comment]
Do you jest?

**Comment by ShadowDeath6** [comment]
Hahahahahahahaha
Hulks right now do an automatic 15 damage that bypasses all armor
Just slip someone and punch them a few times and they're dead

If you get killed because the sole reason you're hulk then it's breaking 0.0 
If you get killed as hulk because you're doing something to get killed it's valid and get fucking good

**Comment by Super3222** [comment]
Ive been planning on making more development with riot shields.

Hulks will bypass them, and deal their usual damage soon.

**Comment by ghost** [comment]
hulks penetrate armor, are unstunnable, unless you have lethals you're dead, hulks don't need a buff get good.

only necessary thing is passing riot shields.
