### ISSUE TITLE
Antag weighting system doesn't actually work.

### ISSUE THREAD

**Issue by MacHac** [yogstation13/yogstation-classic#1063]
When my antag weight viewing verb didn't actually work, I spent some time debugging it.  This revealed to me that it was not the only thing that didn't actually work.
### EXPECTED:

After you get an antagonist role, your antag weight is reset to the minimum of 25.
### REALITY:

It stays at the maxiumum of 400, which means that the only people that the weighting system effects are the new players.
# I was only joking when I said that it was a placebo.  Pls.

**Comment by ShadowDeath6** [comment]
I got an antag role and it went down to 215 or something during that round and it went up to 400 the next round

**Comment by AsV9** [comment]
@DavidEdwards
