### ISSUE TITLE
More Mime/Clown Slots at starting round

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation-classic#107]
With the recent migration of more rare mimals and cluwnes we desperately are suffering from overflowing of mimes and clowns, many new players are now playing mime and clown on a regular basis but the chance at grabbing clown/mime is now as rare as wizard, personally I spent 8 hours playing with clown set to high and did not get it once during medium pop.

Likewise the issue is much bigger for Mimes, with there being over a dozen veteran and new players wanted to play as a cute mime, while normally these are roles veteran players use to dick around the attention has shifted on new players and it would be nice to increase the beginning slots to allow more mimes and clowns into the round from start. I wouldn't mind seeing new players mixed with veterans when it comes to mime/clown.

I feel like this would also allow for more fun muckaround happenings and shenanigans to occur, I've never gotten any serious issues regarding clowns/mimes aside from the occassional shitcurity ticket.

Supplementary image
![2h5ctxm](https://cloud.githubusercontent.com/assets/16812748/12472891/e82bc82a-c060-11e5-9134-16d4e00677fa.png)

**Comment by doerakpoes** [comment]
No just no

**Comment by shrimptk** [comment]
Against. Many clowns and mimes don't even do their job right, veteran or newfriend. 1 Shitty Clown, and 1 Powergaming mime is enough until we have a consistent high pop.

**Comment by ghost** [comment]
No. 

HoP can open more clown/mime slots.

**Comment by Hydre** [comment]
1 is already too much, hey I can close stuff
