### ISSUE TITLE
Secborgs don't have an advanced sec hud.

### ISSUE THREAD

**Issue by Nirnael** [yogstation13/yogstation-classic#1070]
### Expected Behaviour

Should be able to set people to arrest and view their record when examining.
### Actual Behaviour

Doesn't happen.
### Steps to reproduce the problem

1.Examine as secborg.

**Comment by ShadowDeath6** [comment]
why do they need this, borgs do not need to be sec but better

**Comment by FluffySurvivor** [comment]
secborgs are only used for antaghunting anyway.

**Comment by Nirnael** [comment]
Because you are like a fucking robocop, theres literally no good reason to not have it except for "too OP" which it isnt, it obviously adds to setting people to arrest and not having to yell at a warden who is taking a shit in the chapel for unknown reason or the AI that is trying to roleplay, its also useful for discharging people, etc.

**Comment by ShadowDeath6** [comment]
secborgs can already do it by clicking a console
letting them do it whenever is "too OP"

**Comment by FluffySurvivor** [comment]
"too OP" 
:-1:  :-1:

**Comment by Nirnael** [comment]
...y u complicate dis, its no more OP than sec officers doing it

**Comment by ghost** [comment]
security cyborgs are not security, they're harm-stoppers

peacekeepers basically

they are intended not to have a security HUD

**Comment by ShadowDeath6** [comment]
Remove sechud from borgs entirely B^)

**Comment by FluffySurvivor** [comment]
Remove secborgs from game entirely B^)

**Comment by Nirnael** [comment]
Why go down the tg route when it's not half bad.

**Comment by X-TheDark** [comment]
Then, as many people on that particular PR have stated, cyborgs will effectively not have any way to stop harm, expect flashes.
