### ISSUE TITLE
Add clay to mining

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#1072]
Clay could be processed to make porcelain, which can be used to make new toilets and sinks. This means new bathroom can be built.

**Comment by ghost** [comment]
Let's implement defecation and urination as well.

**Comment by ShadowDeath6** [comment]
make sinks and showers constructable
also make mirrors constructable

**Comment by FluffySurvivor** [comment]
Why would you need sinks, showers and toilets?

**Comment by EMT321** [comment]
Sinks: Make a ramen factory.

Showers: Make a slip factory, or recreate that scene from Starship troopers

Toilets: So you can kill ascendents.

**Comment by ParagonPrime** [comment]
> inb4 miner named Polande Ball
> shouting "GIB CLAY" and autistically mining only clay

**Comment by ParagonPrime** [comment]
>inb4 miner named Polande Ball
>shouting "GIB CLAY" and autistically mining only clay
