### ISSUE TITLE
Radiation suits do not provide 100% radiation resistance

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#1073]
### Expected Behaviour

Raditation suits to wholly block radiation, as per their name.
### Actual Behaviour

Die while dragging around an SM shard.
### Steps to reproduce the problem
1. Don full radiation suit.
2. Activate SM shard.
3. Suffer hallucinations.

**Comment by ShadowDeath6** [comment]
radiation doesn't cause hallucionations, that's a thing with the SM. Were you taking damage from radiation?

**Comment by EMT321** [comment]
I believe so, I didn't realize they were different proc's.

**Comment by ToGWtF** [comment]
I think you need mesons to stop the hallucinations, but i seem to remember still getting the hallucinations

**Comment by X-TheDark** [comment]
Protects from radiation emitted by the SM, but hallucination is another effect that is applied to you that doesn't check for anything at all, it just applies to you based on your distance to the SM, nothing else. No fortitude throw.

**Comment by EMT321** [comment]
Poor understanding on my end, thus this is a non-issue.

**Comment by X-TheDark** [comment]
I don't think it is a non-issue. If people think suit/something should block the hallucinations, it is a matter that is worth being discussed, but I guess that'd be another issue, since this one is about the radiation thing.
