### ISSUE TITLE
Give magboots?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1079]
- Engineering/atmos departments do not have magboots (while they are the ones who need them)! There's one for CE, and for god knows why 2 in EVA (no access).
- fulmilant atmos event: even 4000kpa plasma in certain rooms
- Hardsuit makes it impossible to move around, get killed by pressure over time without hardsuit, you get sucked or pushed away from the Air alarm, lockers and objects move around, you cannot pull scrubbers/portable air pump, because the pressure constantly drags you and what you're pulling.
- = You need to give magboots to department. (eng and / or atmos)

**Comment by ToGWtF** [comment]
I could add a single pair to engineering storage with #972
