### ISSUE TITLE
Security belt stuck on golem

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#108]
Golem had security belt with sec ID, and could open all brig doors.. Security borg saw that but couldn't remove the belt because it was not shown on the item-removal list.

**Comment by Super3222** [comment]
The reason for this is because of the adamantine's shell which covers their entire body (one of the few things that restrains the golems from putting on external clothing).

**Comment by Hydre** [comment]
So this basically applies to shadowlings as well

**Comment by X-TheDark** [comment]
I'll see if I can do anything about this. Also, no, doesn't apply to shadowlings, they can be stripped as normal.
