### ISSUE TITLE
Pizza Bomb Replacement Suggestion

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1081]
Idea to replace the pizzabomb with a chameleon bomb.

For the same price as a pizza bomb, and the same explosion radius of a pizza bomb, you can purchase a chameleon bomb.

The chameleon bomb, before it is disguised, has a very obvious sprite.

However, you can scan it to look like a different object, in which it then assumes the object's form, like the chameleon projector does, to you.

Then, upon someone that is not the activator interacting with it, it ditches the holographic disguise in the same manner the projector does, and then a very short time later (could be one second to two seconds) explodes with the pizzabomb's radius.

The activator can freely interact and pick it up, but nobody else can.

This leads to such things as disguising the chameleon bomb as the communications console, having someone try to log in, and violently exploding, to leaving an 'emag' in the middle of the hallway that promptly explodes when someone tries to pick it up.

This replaces the pizzabomb, which is so meta'd that it is entirely useless for stealth or surprises and only use is an instant-gibbing if you set the timer to two seconds and toss it at whoever you want to kill.

**Comment by FluffySurvivor** [comment]
> leaving an 'emag' in the middle of the hallway that promptly explodes when someone tries to pick it up.

lmao yes please

**Comment by Cruix** [comment]
- Are you really sure you want it to be able to be disguised as objects you cannot hold? This would mean including things like walls, mobs, the singularity, energy fields, and all sorts of other things unless you make a blacklist.
- How is the activator identified by the bomb? By name? Fingerprints? What about wearing gloves? Does it just magically know (i.e., use the real_name or a reference to the user's mind datum)?

**Comment by Cruix** [comment]
- Should I make it so you can implant these during an organ manipulation.

**Comment by X-TheDark** [comment]
One of the alternative ideas that came up is to just make it a "bomb core" kind of thing, that you can plant into any container that, when opened up, explodes in your face.

**Comment by Super3222** [comment]
Chameleon everything right.

**Comment by ghost** [comment]
It can only disguise as objects you can hit or pick up, so yes, you can have chameleon bomb mechs.
