### ISSUE TITLE
new traitor objectives

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1082]
So I was considering that traitor objectives are fairly standard faire and don't do much.

Steal this. Kill that.

Let's get...creative.
# Sabotage objectives

-Cut power to 70% of the station's tiles.

-Cause significant damage to genetics/medbay/the brig/engineering/the bridge/cargo/science (calculated in X amount of tiles needed to be damaged.)

-Destroy all cloning machines on the station.

-Release the singularity/tesla.

-Destroy all power sources on the station.
# Murder/Destruction objectives

Eliminate all cyborgs on the station. If borged, you do not need to kill yourself to complete this objective.

Eliminate all medical staff.

Destroy all computers on the station.

Kill all pets on the station.

Destroy all plants on the station. (This one would be paired with any other one.)

Ensure no loyalty implanted crew escape on the shuttle alive.

Ensure 30% of all crew on the shuttle are on fire when it arrives at central command, excluding yourself.

Eliminate all syndicate agents, changelings, revenants, or wizards on the station.
# Theft Objectives

Steal X number of (generally high risk) items. This can be ID's with access to a specific department, or stunbatons, or guns, or helmets, or security radios, ect.

Steal X person's ID.

Steal X bars of (mineral).

Steal the (organ) of X.
# Gimmick Objectives (they're fluff ones that autocomplete, and come with another objective that doesn't autocomplete.)

-Fuck the police (not literally.)

-Convince (Head of department/clown) that they are X (antag name, so for example convince the HoS they are a wizard)

-Start a weapons trade.

-Steal back any syndicate gear confiscated by security.

-HONK.

**Comment by Nirnael** [comment]
> -Convince (Head of department/clown) that they are X (antag name, so for example convince the HoS they are a wizard)

What?

**Comment by ToGWtF** [comment]
I would say I wish we did the  civilian objectives thing we talked about months ago, but with no murder-bone rule that gives them the excuse to graytide to their hearts content and grief because "valid"

**Comment by X-TheDark** [comment]
> Eliminate all syndicate agents

As in all other traitors?

**Comment by FluffySurvivor** [comment]
> Ensure 30% of all crew on the shuttle are on fire when it arrives at central command, excluding yourself.

bad

> Steal X number of (generally high risk) items. This can be ID's with access to a specific department, or stunbatons, or guns, or helmets, or security radios, ect.
> Steal X person's ID.
> Steal X bars of (mineral).

bad

> Eliminate all syndicate agents, changelings, revenants, or wizards on the station.

the only way you can do this is murderboning the entire station

You don't even need objectives, traitor is the freestyle antag. You do your own objectives for your own round.

**Comment by ghost** [comment]
@ToGWtF no it doesn't since they're not antags they'd get banned for it

**Comment by ToGWtF** [comment]
Yeah but you would see the message in chat, or check notes tab and see it says something and it would be more work to explain to people that that it doesnt make them antag

**Comment by ShadowDeath6** [comment]
This is dumb. 
Yeah, I get that people aren't creative with their antag shit, but that's THEIR choice. Traitor definitely has the most freedom in their "fuck you and your station" stuff, but forcing them to be creative isn't going to make them like it. 

> release the engine

This happens every round anyway. 

> eliminate all other antags

Are you fucking high? Antag cooperation is already near nil. Leave ruining someone else's RNG role to double agents.

**Comment by Super3222** [comment]
> Eliminate all syndicate agents, changelings, revenants, or wizards on the station.

With how incredibly stupid our policy is on killing other antagonists who are affiliated with you outside of group antag rounds, I don't think we need this.

**Comment by FluffySurvivor** [comment]
> nuke station for tators obj when
