### ISSUE TITLE
Cult changes, eat shit fluffy

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1083]
Because Fluffysurvivor is shit.

also, a lot of these ideas came from Robustin and ChangelingRain, so thanks for that.
# Runes

-Runes should pulse red on failed invocation.

-Drawing a rune alerts cultists to where the rune was drawn, and rune type, just like when a golem rune is made.

-On mouseover, the rune's name is displayed, only to cultists.

-On examine, the rune name, it's effects, and number of required alocytes as well as words that go into the rune are listed.

-The convert rune automatically places an arcane tome with a random, not discovered runeword into the convertee's backpack.

-The imbue rune is removed. This will be explained why later.

-The stun rune is changed. Activating it will weaken (3) and disorient all non-cultists-The more cultists around the rune on activation, the larger the radius is, and the stronger the effects.

-Deafen rune is removed.

-Blind rune is removed.

-A new rune, Disorient, is added. The disorient rune is both of these runes effects condensed into one-again, the more cultists around the rune on activation, the bigger the radius and effects.

-Manifest ghost rune will send an alert to ghosts where it is drawn, just like a positronic brain/golem rune. Manifest ghost, while activated, also creates 1x1 barriers on top of the invoking cultist, that can be hit and destroyed instantly, but basically just exist so people don't move the guy making the ghosts and kill them all instantly. You can drag the guy off it and the barriers don't stop tazers, disablers, lasers, or attacks from hitting the guy and the barrier is instantly destroyable-it's just to stop assholes from moving you off the rune.

-Astral Journey now does the same.

-Summon Cultist will no longer list the cultists invoking in the summon list.

-The teleport rune will list runes to teleport to-For example, if there are three teleport runes drawn with the word 'blood', one in mining, one in EVA, and one in the old bar, you can choose 'Teleport rune (Old bar) from the list that pops up. It also teleports everything on the tile, so you can invoke it to warp captured prisoners away. Or items.

-Teleport Other is removed.

-Blood boil no longer instantly sends everyone in radius into crit-Instead, it scales on number of invokers. Five cultists is required to reach the maximum and send everyone into instant critical-One cultist will do twenty damage to one limb, two cultists will do thirty damage and incur some eye-nearsightedness for a couple seconds, three cultists will do sixty damage, weaken (3) and has a random chance to ignite non-cultists in radius, four cultists will do eighty damage, weaken (6), eye-nearsighted, and has a higher chance to ignite non-cultists.

Remove Reveal rune.

The Veil rune is now Veil and Reveal combined into one. On invocation, the veil rune will hide all runes except itself from cultist eyesight, and all runes including itself from noncultist eyesight. On invocation again, veil reveals all runes-basically just a toggleable filter of invisibility/visibility.

Blood Drain now is a toggle-on invocation, it glows bright red. Passing over it will sap health from anyone standing over-about ten per second, plus stamina. However, when turned on, it also does ten damage per two seconds to the cultist invoking unless a non-cultist is within four tiles of it. Meaning you can't have them always on-having six blood drain runes turned on when nobody's near will kill you almost instantly. But turning them on as sec rushes the hideout so they suddenly find oh shit we're dying, that'll work. Blood drain no longer causes bloodhunger-instead, it replenishes health to any cultist standing on the trigger rune. If no cultist is standing on the trigger rune, it won't drain health from anyone passing. It also turns off automatically after ten seconds of activation and has a 30S cooldown.

-EMP rune now scales with invocation. Nine cultists invoking it will EMP about the same as a 300u iron/uranium grenade-One cultist invoking it will barely fizzle his headset.

The Nar-Sie rune is now changed massively. It requires a 3x3 clear area. It takes the appearance of a large pentagram. When nine cultists activate it (this takes fourty seconds), it glows into activity. On becoming active, it immediately makes all walls and floors in a large radius into cult floors/walls. It also makes a massive, massive, massive message (along the lines of AI delta/Nuclear activation/dominator) that Nar'Sie is being summoned in X location. The rune then checks for number of cultists, and starts a countdown to nar'sie summoning, using the formula of 900 - (40 x X cultists). So say, if there are 16 cultists on station, it will give the crew about 340 seconds to stop the summoning. The summoning itself creates a very large shell that's sort of impossible to miss (being a giant nar'sie shell that's pulsing blood red) and has 500 health. Crew must destroy it to succeed-It's atmos proof, but vulnerable to the tesla or singularity. Bombs will not instantly destroy it-instead, being in the devastation range of a bomb will do a flat 250 damage, and anything less than total devastation will do no damage at all. 

Armor Rune-DEAD

Make Shell rune-Now accepts either inputs of 30 rglass, 30 metal, or 5 plasteel, or 5 runed metal (Will touch on shortly). 

Sacrifice rune-Puts the goddamn soulstone in the hand of the invoker so you don't have to wade through a motherfucking rightclick pile of death and shit to find the soulstone. Jesus.

Wall rune-No longer an invisible, impenetrable barrier-The wall rune now, on being active, creates a blood red barrier in front of it that allows cultists to pass through (albiet at a much slower moverate so it's a BAD IDEA to make 12 and leave them up) and has 150 health. The barrier will allow lasers and disablers to pass through, but not tazers. On the barrier's destruction, the rune is also destroyed. Null rods will, as usual, instantly destroy it, but to top it off also instantly destroy connected runes.

New runes added-

-Rune of Shackling. It just creates a pair of cultist handcuffs-They look like energy cuffs, but red, and are named 'arcane bindings', on invocation. Fairly useless normally-But you can imbue it into a talisman to cuff people once applied, but it takes two seconds to apply. You can't just bitchslap the HOS with cuff yourself papers and drag him off. Instant invocation time. Rune is destroyed after invoking. Requires five metal sheets or two cultmetal sheets.

Create Soulstone Shard, with a requirement of just one cultist, but requiring two cultglass or ten rglass. Does 15 damage to you on invocation and creates one unfilled soulstone. Instant invocation time. The rune is destroyed after invoking.

See Undetectable, which has an instant invocation time. Reveals ghosts, revenants, space ninjas, invisible geneticists, and removes dark tiles in a large (5x5) area around the rune for twenty seconds after invocation. The rune is not destroyed after invoking.

Corrupt Materials, which converts glass, rglass, or metal on it into cultglass and cultmetal when invoked, in a 5 to 2 ratio. So 50 sheets of metal will yield 20 sheets of cultmetal. Plasteel is a 1:1 conversion ratio. Other minerals can't be used, and trying to use plasma on it will just ignite the plasma. It also converts floor tiles and walls near it into cult floortiles and cult walls in a 4x4 radius-it's not for subtlety.  Not destroyed after invocation.
# Talismans

Talismans are now created by hitting a rune with a paper. The paper is no longer silent-It has a nice bloody pentagram drawn on it, except for the supply (roundstart) talisman. This takes two seconds and does the same barrier thing so that you don't get moved by an asshole. It's also not silent-You're chanting as you do it. I'll get into that in a moment.

Stun talismans stun for nine ticks, instead of ten. They also only mute for four, and for the rest make speech extremely slurred, as per Robustin's cult PR. They also do twenty damage to the invoker instead of ten.

EMP talismans are now less potent in range.

Teleport talismans now teleport whomever you hit with the talisman with a delay of four seconds, you chanting all the while. Unless self invoked, obviously.

Corrupt Materials is now a talisman that can be invoked to the same effect as the rune, but over what you're standing on. It also converts floor tiles and walls in a 3x3 area to you into cult floors and cult walls. 

Talismans of 'get the fuck around the fucking rune' are now automatically created if a rune is failed to be invoked ten times within thirty seconds. This talisman instantly warps the nearest cultist to you to the rune it was created by and locks them there for two seconds because jesus fuck get AROUND THE FUCKING RUNE. It fades out of existence when you get more than seven tiles away from the rune, so no using it to instantly free cultists.
# Cult Structures

To encourage basebuilding!

Runed Metal and Runed Glass can be used to make cult windows, cult walls, and cult floors. Cult windows look like dark grey/red windows with nar'sie symbols in glowing red sketched into them. Cult walls are fairly obvious, as are cult floors. Cult floors will reduce the damage of cultists invoking runes on them to nothing-so you can freely invoke without taking damage-with the exception of blood boil, blood drain, and stun talismans. Cult floors also constantly inject 1u epiphenerine into all carbon mobs with no epiphenerine in them, so a critted cultist is just that-stable-on a cult floor. Cult walls are just aesthetic. Cult windows will block disablers, but not lasers.

Runed metal can be used for other things, too.

Most of this is taken from Robustin-Runed metal can be used to construct specific things.

Cult Frameworks are the bog standard, in the same way machine frames are. They require 3 runed metal to construct.

From there, you can apply runed metal to a cult framework and get a dropdown list of-

Cult Pylons, which slowly and automatically heal all cultists in range-12 brute and 12 burn a minute, or 24 damage for constructs. They also spread cult floors in the same way alien weeds spread.

Cult Archives, akin to the librarian's one, which serve as storage devices for talismans to be placed in/drawn out of. 

Cult Forge, which can create a variety of objects just like the protolathe/autolathe depending on the amount of runed metal/glass inserted. It can make cultist goggles (flash resistant), cultist gloves (insulated but not heat proof or botany resistant), bottles of unholy water (dat speedboost), and cult armor, which is changed and I will detail below how. Can also manufacture talismans if talismans were previously inserted into it. Makes a fart noise if a non-cultist clicks it.

Cultist Generators, which basically just serve as super-capacity cell APC's for cultists, in case the power dies and they want stuff to work. It also powers exclusively and only cultist machinery-no regular machines. Feed blood or runemetal into it to power it.

Cultmetal Plasteel has an additional couple recipies.

Cultmetal plasteel now can make cult barricades, which are basically security barriers-but for cultists, and with less health. They also are instantly destroyed, as usual, by the null rod or application of holy water.

Cultmetal Cores-Basically, it makes a cultist machine, and then you use standard AI core assembly plus runemetal, and a cult themed AI (spooky sprite, looks nothing like a normal AI) is made, with a law zero of 'SERVE NAR'SIE.' The cult AI can see cultists as normal, but unlike a normal AI has no access to doors regularly-YOu know that irritating hacking thing? You'll have to hack the airlocks for every airlock. As usual you only need to bypass AI control once, but yeah. Once that's done, though, you always have access, even if the camera goes down or the AI control wire is snipped. The AI will recieve an alert you're hacking the door, however, and it can repair hacked doors by clicking on them and initiating a counter hack. Cult AI's hack much faster than regular AIs, though, so the hacking thing is mostly a small impedement. Cut wires are also no issue. It's also unable to be seen by the AI or tracked on camera, and requires a cult generator to still function-basically it's a risky length to go to but MASSIVELY useful since it's basically a subverted AI that can't be fixed and can't be stopped. It has no access to atmos cameras, though-Just to prevent shitty cult plasmafloods.
# Mechanics changes

Cult now starts with only four cultists. It has a thirty five pop requirement.

Instead of spawning with all sets of the same runeword, each cultist has only one runeword-Three are guaranteed to be part of the standard nar'sie set, and one is random.

On conversion, all cultists in eyesight of the invoking rune get the runeword automatically transcribed into their memory and into their tome.

Sacrificing a live body yields two runewords.

Sacrificing a monkey or a dead body yields nothing.

Rune research is dead-Don't try it. Seriously, don't. It'll do a ridiculous amount of damage to you if you flub a rune and draw one that makes no sense, and you'll die and everyone will laugh at you.

Runes now have a time to invocation and scale. Most runes can be activated with just one cultist-clicking on it starts the chanting, makes that 1x1 barrier below you so no asshole moves you, and you start chanting (in whispers first, and then as time ticks down towards 0 allcaps). However, they also scale-The more cultists around the rune, the faster the invocation, and the better the effect.

For reference-

A convert rune attempted with just one cultist has a 70% chance of failure and takes 16 seconds to invoke.

A convert rune attempted with two cultists has a 20% chance of failure and takes 8 seconds to invoke.

A convert rune attempted with three cultists has no chance of failure and takes 4 seconds to invoke.

A convert rune attempted with 5+ cultists has a 50% chance to convert even implanted personnel (but not the Captain or Chaplain) and takes 4 seconds to invoke.

Sacrifice takes 17 seconds with one cultist, 7 with two cultists, and 3 seconds with 3 cultists.

Wall-three second invocation, only one cultist required. No scaling effect.

Blood Boil-Fourty second invocation with one cultist. Thirty second invocation with two cultists. With three cultists, fifteen second invocation. With four, five second invocation. 

Blood Drain-ONly needs one cultist to activate the 'trigger' rune, networked the same way teleport runes are, and has a three second invocation time.

EMP rune scales, as does the stun talisman, as mentioned above. Fifteen second invoke time with one cultist, Seven second invoke time with two, Three second invoke time with three cultists. Anything above that is instant and the only thing scaling is the effect which I already went over.

Teleport rune is a seven second invocation, unless in a talisman, then it's instant. 

Summon cultist takes fourty seconds with one cultist, fifteen seconds with two cultists, and is instant with three cultists. Further than that, the only thing changing is amount of damage it does, evenly distributed among number of cultists invoking.

Invoking a rune and starting that chant will lock you in place until you click the rune again, unless you have fired a weapon/been hit in the last five seconds, at which point it will not lock you to stop accidentally clicking on a rune mid combat and being fucked over. 

Chanting is loud-you're going to be shouting things just like normal invocations.

Drawing runes is not silent when using a tome-you are painting the floor in blood, so people will see. However, it is not in red text, so it is overlookable.

Cult commune is changed-it no longer requires a tome. Cult commune is bog standard and you are capable of communing even without a tome. However, if cuffed or restrained in any way-even lying down in a bed-or stunned, or muzzled, you cannot commune. If holy water is in your system, you also cannot commune. Arcane tomes do not have the holy water restriction.

Drawing runes now has a one second delay rather than the massive delay before that made battle magic impossible.

I don't think i've forgotten anything, so i'll move on.
# Armor and Weapons

-Remove all the retarded cult spell armor things. No more cultists getting fucking wands of healing, wtf? 

-Also, armor values are no longer deathsquad tier, but instead ERT hardsuit tier. They are also pressureproof (but not temperature proof.) They are made by the cult forge. Manifested ghosts start in weaker versions of this.

-Cult swords now have the same blockchance as a single esword, making them to some level robust instead of a complete waste. Also made by cult forge.

-Cult armor and weapons speed up rune invocation by 1.2x each, so that being outfitted in full cult gear is going to lead to some speedy ass invocations. Battlechanting hooray.

On cultists-

Holy water will legitimately do damage to cultists if splashed on them, acting like old polyacid. Spraying it over cult tiles will revert it to normal floor tiles, and a cult floor tile reverting to normal will also convert adjacent walls to normal. A construct passing over blessed tiles will move slower and be more vulnerable to damage. Drawing a rune on a blessed tile takes more time, and reduces the effect, except for the corruption runes, which counteract blessed tiles automatically by making them cult floors again. Cultists who consume holy water will start gibbering and chanting constantly, until the holy water leaves their system or they deconvert. Having 50u holy water in you makes you immune to conversion.

The null rod does twenty damage to cultists, plus stamina. The more cult gear one is wearing, the damage is also amped up by 20%-wearing full cult armor and robes is going to lead to you taking some nasty beatings from the chaplain if you're not lucky. You're also completely immune to ALL cult magic, and thwacking cult floors and walls with the null rod will revert them to normal. Hitting a construct with the null rod rolls a 40% chance to freeze it in place, and does 20 damage, in addition to resetting all spell cooldowns.

The bible will do twenty stamina damage to cultists, disable their communing, and confuses them. 
This scales with cult armor-full cult armor will lead to taking about eighty fucking stamina per swing and rendering you more confused than grandma at a star trek convention. 

The Chaplain's robes will insulate heavily against damage from constructs and cult swords, rounding down ONLY for those items and ONLY those. 

The null rod will destroy ALL connected runes-if there are teleport runes linked everywhere under one runeword and the chaplain finds one of them, rip, the entire link is broken everywhere. 
# Constructs

Artificers can make cult metal and cultglass, attacking a floor tile will turn it into a cult floor, and can freely pass through cult walls or cult windows as if they weren't even there. Can also make pylons with a very very long cooldown.

**Comment by ShadowDeath6** [comment]
I don't want new narsie gang timer shit but I would love new rune effects, especially the teleport runes. Imbue is fine as is, just remove stun rune imbue. 

> giving artificers shadowwalk

WHAT A MADMAN

**Comment by ghost** [comment]
Narsie timer is both to make the summoning a big thing that isn't 'suddenly NARSIE' and to give cult the chance-and reason-to use all these fancy ass new runes.

Could add a couple more objectives to cult too-Convert X number of people, sacrifice  Y department, create X number of pylons.

So that a cult could get 'sacrifice the warden' and 'convert 50% of medbay to cultist territory', and as a final objective, ALWAYS narsie. Escape with x cultists is dead.

**Comment by ghost** [comment]
Also i removed artificer selfrepair so they needed that buff

**Comment by FluffySurvivor** [comment]
but i am cool

Even if this is essentially more or less tgcult lol. 
:+1: for cult buildings
:+1: for non-insta cheese narsie
Gotta love how people mistook my temporary solution nerf with an actual rework lol

**Comment by ShadowDeath6** [comment]
if you wanna remove artificer healing then give them a massive health boost and movement speed, they have shit heath

also- nevermind narsie timer is fine since we aren't porting the summon orb shit
