### ISSUE TITLE
Making R&D intresting.

### ISSUE THREAD

**Issue by Bekons** [yogstation13/yogstation-classic#1085]
Bare with me.

Right now, after checking, i can max out research within 9 minutes with little to no effort and no mining minerals.

The issue is, there is nothing intresting or difficult about it. Just spend some time, use your brains, take notes and boom, you know how to do it as good as you can.

---

How to fix it in my opinion?

Make it so when you research something, you gain levels but not the actual items that research gives.

You must then go into a menu and use your new gained research to unlock items.

For example.

You have everything at 1.

You research a manipulator and an analyzer, which gives you 
materials 2, 
engeneering 2, 
electronics 2 
data 2.

In the new menu, you look at what you got new, select new groups of research you want to combine. 

For example, from all the current research, you check materials and engeneering.

The system checks you having materials 2 and engeneering 2, and will unlock anything that is made with materials 2 and engeneering 2. It does not mean that the items you get will give you this research, it's needed to unlock making the item.

This would allow more exploration, hidden items and combinations.

**Comment by ShadowDeath6** [comment]
this is just making R&D less friendly to people who want to learn it and not changing the difficulty for people like you who know it inside and out

**Comment by Notamaniac** [comment]
R&D needs a rework which stops it from being a checklist. This just adds another checklist which involves knowing the combinations of tech levels for the items you want.

**Comment by Bekons** [comment]
Well it's an idea. 

It would make it more intresting.
