### ISSUE TITLE
Make lipstick not look like ass

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#1086]
### Expected Behaviour

You put on brightly colored lipstick, looking snazzy with colored lips on your sprite
### Actual Behaviour

HEIL HITLER
### Steps to reproduce the problem
1. Put on bright green lipstick
2. It's black and gives you a hitler stache
3. Kill millions of people in an act of xenophobia

**Comment by ShadowDeath6** [comment]
Should be an easy fix, just needs icons
