### ISSUE TITLE
Roundstart cultists commune verb

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#1087]
> 12:47:45 Avatera32 - Can the base cultists please can a commune without their books like converts
> 
> 12:48:45 Avatera32- It wouldn't make them OP, and I've lost my book in stupid ways before, not being able to commune sucks

**Comment by ShadowDeath6** [comment]
you have a paper with 3 free tomes though

**Comment by Bekons** [comment]
The commune verb makes you take tons of damage and start bleeding. Have fun with dealing that, seeing it's super obvious.

**Comment by ToGWtF** [comment]
yeah it basically cucks anyone but cabbages.  sure you can beg to be teleported out of perma but you'll be half dead so good luck running away
