### ISSUE TITLE
Add date to watchlist flags

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#1090]
### Expected Behaviour

Watch a problem player because the watchlist informs you of their behavior
### Actual Behaviour

The watchlist flag was added 6+ months ago and their behavior has changed but no one knows when the flag was added so no one removes it and they are forever marked

Also #824

**Comment by X-TheDark** [comment]
Also #707.

**Comment by ToGWtF** [comment]
wew, same person inspired me to ask this.

I would. But SQL is an alien language to me.

**Comment by X-TheDark** [comment]
We would need Kn0ss0s for this, as the watchlist table doesn't save (have columns for) date/ckey of admin who made the entry (I asked).
