### ISSUE TITLE
Hardsuit helmet sprite stuck to head

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1093]
### Expected Behaviour

When explosion damage knocks you over (removing helmet apparently), you won't have a helmet sprite stuck to your head (although you can engage helmet again or disengage it, with no visual effect).
### Actual Behaviour

You will, apparently.

**Comment by ShadowDeath6** [comment]
Do you mean like explosions obliterating the helmet, or the hardsuit?

**Comment by X-TheDark** [comment]
Any reproduction steps? Also, which Hardsuit?

Tried testing this with Engineering Hardsuit:
- Put on Suit, Toggled Helmet;
- Trigger Explosion with 0/0/1 range
- Get knocked down
- Helmet remained as it was

**Comment by 00aquir** [comment]
it was a syndicate bomb, knocked me over, removed my eng helmet (with the sprite stuck to head apparently, or maybe it was stuck after I activated it afterwards?) but the suit remained on body.

**Comment by ShadowDeath6** [comment]
It must have shredded your helmet via explosion
