### ISSUE TITLE
Give HoP a mini-comms console

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#1094]
### Expected Behaviour

HoP is the station's link to NanoTrasen, and can act as a bridge between not only the crew and command staff, but the crew and the command of the command staff to file complaints.
### Actual Behaviour

Only Captain can whine to NT about shitty this and shitty that via comms console
### Hao 2 fix

Give HoP's office a small, literal "comms console" with only one option- contact NanoTrasen.

You can access this with HoP Office access and relay a message to Central Command (badmins) who may or may not respond.

Why? Because HoP should have a little more administrative and mediation work to do to discourage SecHop!

**Comment by ToGWtF** [comment]
make it a fax machine because paperwork

**Comment by ParagonPrime** [comment]
yes
YES
APPROVED

**Comment by ShadowDeath6** [comment]
meh
HoP's loyalty is questionable, why would central take info from him?

**Comment by X-TheDark** [comment]
My personal opinion is that HoP is under authority of the Captain, it makes no sense for HoP to be allowed to contact NT. HoP is in charge of Personnel (in case it wasn't obvious from the role name), not in charge of informing NT of anything (emergency situations when Captain is dead notwithstanding).

The only person who would deserve this kind of mini-comms console would be the HoS, as if there's a breakdown in station's security, NT should probably be let known and the person responsible for the security is the HoS (obviously).

**Comment by utahclock** [comment]
Give to hos not hop...

**Comment by ghost** [comment]
remove the messaging functions from comms console and instead add the fax machine, which can fax a paper to centcomm/other fax machines, requiring fax machine access to use

heads of staff and the lawyer would have access to the fax machines. one fax machine would be in the law office, and one in each head's office.

**Comment by ParagonPrime** [comment]
adam fucking has it

**Comment by ShadowDeath6** [comment]
> 500 years in the future
> Using technology that was obsolete 500 years in the past

For what reason?

**Comment by ParagonPrime** [comment]
because 2d spessmans
it has a retrofuture air to it

i mean, have you seen the SIZE of our fucking computers

**Comment by ShadowDeath6** [comment]
They're big because they do a lot of stuff, like send messages through a huge amount of space instantly or view the power network of the entire station

**Comment by ParagonPrime** [comment]
man, you think we wouldn't be able to compact that shit by the 26th century?

not to mention that pAIs look like Gameboys, PDAs are HUGE for how little they do (and have a very antique-looking operating system), and the airlocks remind me of something straight out of Alien

don't get me wrong, i love it- i love the aesthetic of SS13
but it is in no ways hard-future, clean, sleek, whatever

**Comment by ShadowDeath6** [comment]
PDAs are tiny items.

**Comment by ParagonPrime** [comment]
...yeah, but they're still obviously bigger and bulkier than modern smartphones with far less functionality

**Comment by Super3222** [comment]
> For what reason?

Re-revolutionizing old technology to work in space.

Also centcomm is a far, far away from SS13. So it'd be a pretty powerful fax machine

**Comment by Cruix** [comment]
I'm just imagining a traitor destroying every piece of paper on the station so no one can contact CC.

**Comment by ghost** [comment]
it's a bluespace fax machine

centcomm is like in another solar system or something so it's fax technology but really powerful

it's still existing for the same reason we still use computers and flashlights 500 years into the future
