### ISSUE TITLE
Saline-glucose solution is broken

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#1095]
### Expected Behaviour

You administer saline-glucose solution to a patient via an IV and it acts as a blood substitute
### Actual Behaviour

It goes into their blood stream as a regular chemical and doesn't substitiute as blood
### Steps to reproduce the problem
1. Give low-blood patient saline-glucose solution through an IV
2. Check vitals
3. Blood amount has not gone up

**Comment by ShadowDeath6** [comment]
I have never heard of it ever being supposed to do that.

**Comment by Rocks4Free** [comment]
Am I just high or something because I distinctly remember it doing this. The chemists even put it in the IVs, so I'm pretty sure that's how it's supposed to work.

**Comment by X-TheDark** [comment]
I think this is on /tg/ right now, but not on our codebase. They are the ones who implemented the Saline-Glucose solution acting as Blood replacement.

**Comment by Super3222** [comment]
Saline-Glucose currently only has a 33% chance of healing brute and burn. Not like how you described it.

**Comment by Rocks4Free** [comment]
Huh. That's wierd, I could have sworn it did this, and I've never even played on /tg/.
