### ISSUE TITLE
Change the antag alert slightly

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1096]
On goon if you roll traitor or whatever you get a very big popup screen saying 'You are the traitor!' And going into the specifics of the role, how to use your uplink, what you can do, et cetera, and basically makes it impossible to forget you're an antag.

Adding something like that-the popup with information about the role and how to play-for rolling traitor, ling, wiz, blob, cultist, and headrev and gangleader, would be great.

Add an option to 'don't show this anymore' for people if they get sick of seeing it.

**Comment by EMT321** [comment]
Or you could just add a YOU ARE NOT AN ANTAG for the rest of the crew, while your at it
