### ISSUE TITLE
Let drones pass under doors

### ISSUE THREAD

**Issue by Hydre** [yogstation13/yogstation-classic#110]
This would fix drones unintentionally letting people into important places.

(Read as: Prevents dumbass drones from letting assistants into the armory because they don't give a shit)

**Comment by Xantam-13** [comment]
+1

**Comment by Groudonmaster** [comment]
Too be fair drones are supposed to fix. Not worry about the people they let in to places.

+1 though so I don't have to wait to go through a stupid door.

**Comment by shrimptk** [comment]
It makes sense, but to be able to phase through **airlocks** is kinda odd in my opinion

+1 If you make a _drone doggy door_

**Comment by X-TheDark** [comment]
I'm on the case.

EDIT : I do agree with David, drones making small drone doors for other drones would be really cool, but right now, I'll do the easier option.

**Comment by DavidEdwards** [comment]
Yes, I like this idea. we *could *make drone only passages that can be
built on a wall. With a special overlay for the wall.

That would be the more complicated option though.

**Comment by AsV9** [comment]
`+1`

**Comment by Hydre** [comment]
The idea was small drone doors yeah

Kinda standard on any door, but I don't really think a visual effect is needed. Just have door icons always above drone icons?

**Comment by DavidEdwards** [comment]
In this implementation, drones don't inhabit the doorway do they? Whilst it
is closed?

**Comment by X-TheDark** [comment]
Yes, they do, you can stay in the doorway as a drone if you want, but since drones have no collision with mobs, so they can't block the doorway.

**Comment by DavidEdwards** [comment]
My issue is that drones can in this sense hide unseen, and also not be
damaged.

Not a huge issue, I'll grant you, and likely not important for the
implementation of this code.

**Comment by Groudonmaster** [comment]
What's wrong with a drone being able to hide? People mess with drones constantly so a quick escape is always good

**Comment by AsV9** [comment]
Drones having to hide from humans are playing their role incorrectly.

**Comment by Hydre** [comment]
It's not really an issue for here, can't drones also ventcrawl?

**Comment by Groudonmaster** [comment]
Drones having to hide from humans are playing their role incorrectly.

Not when assholes keep picking them up

**Comment by DavidEdwards** [comment]
Alright, sounds like that was a non-issue then.

**Comment by AsV9** [comment]
> Not when assholes keep picking them up

Then they should scuttle off into maint and ignore the human.
If someone is trying to stop a drone from what it's doing, then the drone should leave.

**Comment by AsV9** [comment]
This has been merged, closing.
