### ISSUE TITLE
RPD: add transit tube dispenser

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1100]
It's the same principle as the pipe dispenser and disposal dispenser..  AND one more reason is that transit tubes are good for **space travel**, but the dispenser itself **has to be wrenched on a floor!** RPD should really handle this, too.

**Comment by ToGWtF** [comment]
theres no way to delete them either so the RPD would be good for that

**Comment by 00aquir** [comment]
and also, for CE's tool, too
