### ISSUE TITLE
ninjas are ass

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#1101]
### Expected Behaviour

Have fun.
### Actual Behaviour

You spawn after shuttle is 4 minutes from docking, the entire crew hunts you down despite your best attempts to roleplay or not attack anyone, you only get ~10% recharge per APC, your adrenaline gets you off the ground after a tase but then KNOCKS YOU BACK DOWN before you've even gotten away,  and your armor is balls for armor values, and die on your one and only time you will EVER get lucky enough to spawn as a ninja in 3 years of playing. ~~You can't even abuse and spawn one in without having it RNG one from available ghosts~~
### Steps to fix the problem
1. Give the suit a very minor health injector
2. Lower the cost of teleporting.
3. Give them a way to actually stun people so you can net them without critting them first (Give ninja suits a built-in martial arts that makes disarms have a higher chance of knockdown?)
4. **LOWER THE TIME REQUIRED FOR ONE TO SPAWN**
5. Make energy katana have a chance to deflect beam/energy type weapons like an esword
6. **Give them a power remaining % HuD so they don't have to dance between tabs while in combat just to see if they can use an ability without being left literally powerless**
7. **Give adrenaline a message upon use so you don't double-click and overdose, as well as a cooldown so you can't double-click on accident**

**Comment by ParagonPrime** [comment]
Doesn't the e-kat already deflect? I read somewhere that it did.

On the other hand, it really shouldn't, or have a low chance as such. If e-kat could deflect energy bolts, the only reliable way to stun one would be a stunbaton- getting into melee range is EXACTLY what the ninja wants you to do.

And assuming you get a hit in, with your suggestion, they'll just get right back up anyway.

Personally, I think ninjas should get a passive raised move speed and lower stun times, but not by much. Also, I like the disarm-jutsu (that's what it better fucking be called) idea. I want to encourage ninja to be a stealthy, high-power melee antag that gets cucked if it just blazes down a hallway at a guy with a laser gun.

Oh, also, e-kat should be able to ignore riot shields.

Also also, YES FUCKING GOD DECREASE THE TIME BEFORE NINJA CAN SPAWN THIS IS RIDICULOUS

**Comment by EMT321** [comment]
You are an invisible nukeop with a retrievable esword/emag and always-embedding infinite throw weaponry, plus blink and adrenals. You also have a hardsuit and armor, and a way to take anyone out of the round with a click+30 seconds.

They are almost impossible for a regular crew to match.

**Comment by ToGWtF** [comment]
Then why has there never been one that greentext'd?

**Comment by EMT321** [comment]
Mindlessly making the ninja the most powerful antag is short-sighted, especially for a mid round antag. Giving them passive health gen, shield penetration, stun resist, and what amounts to an eshield turns them unstoppable by anyone short of a nukeop.

**Comment by ToGWtF** [comment]
I'm not saying give them all those suggestions. I'm just putting out what I think could be possible to balance them

I also didn't mean 100% blocking lasers/tasers.  A single esword only blocks them some of the time, and the detectives revolver even less.

**Comment by EMT321** [comment]
And the likelihood is due to large/difficult objectives, and player inadequacy. It's not because my ninjas are woefully underpowered- a teleporting adrenals invisible melee nukeop can shit all over security in no time flat. I've seen it completely annihilate the station in the past, security, crew, and traitors/lings alike.

**Comment by ghost** [comment]
the only thing I agree to is reducing spawntime to 30 minutes max, since that's usually when the shuttle's called, and rounds never make it to 1hr

**Comment by ToGWtF** [comment]
Phase shift uses 20% of your power. Sure. You can gib people with it, but thats a HUGE energy cost.

Phase jaunt teleports you randomly in the direction you face, but costs 10% of your energy still

There is also no message displayed when you use adrenaline. You will easily overdose yourself. WHY THE FUCK DOES NINJA ADRENALINE USE RADIUM

You also cant take pills, drink from chem bottles, or use syringes with your suit on and if you take it off you can not put it back on. The only way you can heal your toxin damage from overdosing on your adrenaline is with a hypospray or find a medibot

**Comment by EMT321** [comment]
I've got no issues with making the spawntime shorter

**Comment by FluffySurvivor** [comment]
The ninja has a HUGE skillcap. You could literally go 1v20 and win if you're an expert at ninjaing. 

The problem? 

It's so damn rare nobody gets to learn the antag, and this is why they all suck. Ninjas don't need a buff. They need to be much more common so people can learn how to play as one.

**Comment by ToGWtF** [comment]
^   they need a small buff though. and some bugfixing for missing messages when using skills

**Comment by Time-Green** [comment]
Adrenaline will always overdose. It's a bug. I have been ninja 3 times, every time I was and used adrenaline, it boosted me, and critted me 2 minutes later.

**Comment by ShadowDeath6** [comment]
I always greentext as ninja.  The only thing that's bad is their low as fuck spawn rate, and you can stay invisible indefinitely by spamming super cap cells that you can crank out indefinitely at R&D, not to mention that throwing stars are instant and give no indication of your position other than the 'thunk' and crit in 3 stars regardless of armor. Ekatana is meh, but it's basically an emag with the retrieve spell on it. 

Also adrenaline just removes stuns and injects radium, so you will die if you spam it.

**Comment by ToGWtF** [comment]
theres no message that it worked so you end up spamming it

**Comment by ShadowDeath6** [comment]
Click it and git gud
