### ISSUE TITLE
rebuild labor station

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#1102]
Proposal : Rebuild labor station to add jail cells for prisoners who are truly dangerous and you want off station. Give a slightly more capable medic area of labor. Give labor mining scanners so they actually have a chance to notice that diamond block that's 2 tiles away from where they dug their path and make labor actually usefull to the station and have a chance to actually finish your points.

Labor should not be where you put the clown after he broke into medbay because you want him to log out/suicide.  Instead of having 100 points = 1 minute jail time,  make it 100 points = 2 minutes and a minimum of a 5 minute brig time (I have been sent to labor for 100 points. Unacceptable). 500 points is far more time than 5 minutes, especially if you have a !Fun! HoS that leaves you legcuffed

**Comment by ParagonPrime** [comment]
Yes. Perma cells on labour gets all my yes.

**Comment by ShadowDeath6** [comment]
Iirc labor literally cannot get anything other than metal

**Comment by Cruix** [comment]
They can get glass and I have found gold before.

**Comment by EMT321** [comment]
Just mine glass and get out in 5 minutes. Or escape to the east, if you are robust. Off-station perma sucks.
