### ISSUE TITLE
making an announcement as AI does not prioritize the chat box 

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#1112]
### Expected Behaviour

what happens to every single console and text box in the game...
### Actual Behaviour

It creates the chat box under the comms console menu and every other menu you have open
### Steps to reproduce the problem
1. See a wraith and announce "wraiths are totally not a sign of a magical and dangerous cult, absolutely not harmful, just a book club lol" from a comms console, as AI.
2. Text box is buried below 10 other menus, takes forever to announce meanwhile wraith is killing you.
3. Get killed by said wraith.

**Comment by Cruix** [comment]
This is caused by the comms console window updating itself every second or so. If you close the comms console window after clicking announce, you can type unimpeded.

Still a bug and I will see if I can fix it, but that works in the meantime.

**Comment by ShadowDeath6** [comment]
> not moving your core to mining immediately as soon as you detect danger

**Comment by FluffySurvivor** [comment]
@Cruix I am aware you can type just fine, but it takes unnecessarily longer and it's annoying
