### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#1115]
So recently, we've been adding in a lot of new features for you, as the players, to enjoy. However, a lot of interesting things are missed out on because not a whole lot of you guys read the change log. So, I'm asking for help from everyone to organize a giant list of new tips.

Remember that they can be no more than 1-2 sentences long.

You may know tips as the things that pop up like,
"As the Head of Security, you are expected to coordinate your security force to handle any threat that comes to the station. Sometimes it means making use of the armory to handle a blob, sometimes it means being ruthless during a revolution or cult."

That make most of us go "HOS ROUND CONFIRMED!!!".

So I'm not asking for every single feature to get a tip, but if you find a cool one, simply reply to this issue with it.

My example:
As the Warden, you can install security encryption keys into a security barrier so it can report whether or not they are attacked as well as how strong the attack was and how much health they have left.

**Comment by ShadowDeath6** [comment]
as the warden, always use riot shields because they are very fair and balanced

**Comment by ToGWtF** [comment]
Can we just add lines to config/tips.txt on each of our PR's as we go?  Or should the config file be left for kn0s to deal with?

**Comment by FluffySurvivor** [comment]
Tip of the round: cult is a garbage gamemode

**Comment by EMT321** [comment]
I have a plethora of security tips, if you would like. Science too.

**Comment by Super3222** [comment]
> I have a plethora of security tips, if you would like. Science too.

Sounds great, but don't let it stop you from making a robust guide on how-to play security over on our forums!

**Comment by Time-Green** [comment]
You can wear a slice of bread on your head.

**Comment by AsV9** [comment]
When faced with a double esword or an energy shield, fall back to melee weapons or a flashbang.

**Comment by Greatbigben** [comment]
Listen to admins or be banned

**Comment by Greatbigben** [comment]
Use pepper spray on those who don't respect your authority !

**Comment by Greatbigben** [comment]
Tear gas is your friend against the unruly masses

**Comment by Cruix** [comment]
To kill a rampaging cyborg, shoot it until it dies.

**Comment by Robertruler77** [comment]
If you want, I'll make non-sarcastic tips for you.

**Comment by EMT321** [comment]
The experimentor can raise research levels of items.

Most shotguns can be shortened.

Ghosts can inhabit drones and mining drones. Some already exist at round start!

Riot shields block melee damage, such as punches, pushed, and stunprod, but do nothing against some penetrating weapons and ranged weapons.

**Comment by EMT321** [comment]
The security and armored jumpsuits provide some defense against melee damage!

Sleepers, cryogenics tubes, and cloning pods can all be upgraded to be more effective, automatically clone dead bodies, or allow use of special chemicals!

**Comment by X-TheDark** [comment]
Odysseus can scan Sleepers to add their reagents to it's database (if it has a Syringe Gun).

Odysseus can rearm it's Syringe Gun. It takes 3 seconds per syringe and is done in bulk (all or nothing).
