### ISSUE TITLE
Toxins Lab Gas Bug

### ISSUE THREAD

**Issue by TheWhiteCrow** [yogstation13/yogstation-classic#1116]
### Expected Behaviour

The Gas just... Stays in the Mixing Room
### Actual Behaviour

All of the gas suddenly goes invisible as you contiously pump a tank with 0.01 pressure of any gas into it.
### Steps to reproduce the problem
1. Wrench the tank, turn the valve for input.
2. Watch the mixing room get filled with Plasma, for example.
3. Watch as the Plasma suddenly disappears into nothingness.

**Comment by Time-Green** [comment]
You should turn off the space-vent

**Comment by TheWhiteCrow** [comment]
There is a pressure from the tank still there, if you tried it out. Not to mention they're closed.
