### ISSUE TITLE
Hardsuit Jetpacks count for traitor objectives.

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#112]
Obnoxiously easy to obtain. Either remove Jetpacks from objectives or remove the jetpacks.

**Comment by Super3222** [comment]
Well shit. Didn't think that hardsuit jetpacks actually counted. I don't think it'd be too much trouble to remove jetpacks from traitor objectives.

**Comment by Hydre** [comment]
Doesn't make sense anyways, syndicate has way more advanced jetpacks

**Comment by ghost** [comment]
Feature, not a bug, has been this way for a while.

Buying your traitor hardsuit which somes with an inbuilt jetpack, kek.

Eh, frankly, just make the steal obj 'Steal the Captain's jetpack' since he has a unique one.

**Comment by shrimptk** [comment]
@Hydre Its to sabotage the station, by taking away a useful and uncommon tool.

**Comment by ghost** [comment]
can we just remove objectives entirely for traitors and leave it to them to be antaggy/sabotagey on their own 

who knows, maybe it'd cultivate some arrr peeee

**Comment by shrimptk** [comment]
@AdamElTablawy 

finally, I can cause chaos in peace.

**Comment by Groudonmaster** [comment]
Gods no.

Aren't you the one that was constantly complaining about people trying to RP on a lowrp server?

Anyways the solution to this was merged so closing this.
