### ISSUE TITLE
Cult's Armor Spells will replace each other

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#1121]
### Expected Behaviour

Be able to build up on spells by getting the necessary requirements for shit and using the armor rune.
### Actual Behaviour

It replaces the spell.
### Steps to reproduce the problem
1. For example. Steal captains suit and helmet. Put them on, use armor rune, get marauder build. it gives you space proof cult armor and a dangerous summon spell (which summons the abomination mobs)
2. Than try the same thing but wear the reactive armor, to get the trickster build which gives you a  door creation wand and a nerfed version of blink
3. Blink spell takes the place of dangerous summon spell.

**Comment by X-TheDark** [comment]
Not sure how I feel about the spells stacking. I'm pretty sure the whole idea of the build is to have only one thing that the build gives, not stack the builds and get everything.

**Comment by ToGWtF** [comment]
If you're going to get ALL the special armors for yourself just to stack spells you're a bad cultist.

**Comment by EMT321** [comment]
Also it clashes with previous "spells", such as the mime's shield and ability to renounce vows and talk.

**Comment by X-TheDark** [comment]
Now THAT'S a bug.
