### ISSUE TITLE
Holy Structural Enzyme

### ISSUE THREAD

**Issue by sagattyy** [yogstation13/yogstation-classic#1125]
### Expected Behaviour

You're George Melons, somehow you died and the CMO found and cloned your corpse. A greytider injected you with a monkey SE. You ventcrawl to Genetics and a blessed spaceman injects you with your boring human SE.
Your name is still George Melons.
### Actual Behaviour

Your name is Unknown, thanks to the clone damage renaming your character after cloning.
### Steps to reproduce the problem
1. Be cloned.
2. Get inside a DNA Scanner and ask someone to save your buffer
3. Become a monkey then inject yourself with your human SE

**Comment by ShadowDeath6** [comment]
secret monkey technique
