### ISSUE TITLE
traitor scaling is busted

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#1126]
### Expected Behaviour

you get a decent number of traitors 
### Actual Behaviour

1 traitor for 17 pop

![traitor ratio](https://cloud.githubusercontent.com/assets/16919472/15112153/ec0f1408-15f4-11e6-877e-81ec98953181.PNG)

**Comment by ghost** [comment]
this is intended so lowpop with 17 people doesn't get like 2 or 3 traitors, traitor scaling is fine except on higher populations because it'll just spawn 4 traitors

**Comment by FluffySurvivor** [comment]
yeah but that one traitor is often clueless and gets caught thus turning the round into extended

lowpop murderbone can be fixed in other ways

**Comment by ghost** [comment]
then it's up to admins to facilitate fun if antagonists get caught, hence the purpose of admins

**Comment by FluffySurvivor** [comment]
so admin complaints for everyone that doesn't facilitate fun ? because no admin messes around in low pop, not to mention low pop is often adminless

**Comment by ghost** [comment]
i mess around in lowpop

**Comment by ParagonPrime** [comment]
adam you're bestmin we can't use you to measure everyone else

but as for the issue at hand, ehhhhh

we COULD add a function where if a traitor is dead/catatonic/braindead for a certain amount of time new traitors get mulliganned in to replace them, but i dunno

**Comment by ShadowDeath6** [comment]
Having too many traitors on lowpop is a bad thing though.

**Comment by FluffySurvivor** [comment]
https://forums.yogstation.net/index.php?threads/6584/
It was supposed to have 1 tator per 5 crew
u wot
damn ninja nerfs or it's a bug

**Comment by ShadowDeath6** [comment]
It was probably never correctly changed from 1:7

**Comment by Axemeaquestion** [comment]
We need mulliganing
