### ISSUE TITLE
Allow handcuffed people to be buckled to conveyor belts

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1127]
traitor cargo tech twirling a fake mustache as they buckle the clown into a conveyor leading to an emagged grinder and laughing when

**Comment by ToGWtF** [comment]
just strap him to a rollerchair

**Comment by Rocks4Free** [comment]
AND/OR 
handcuff people to grilles, zapping them over and over if it's an electrified grille

**Comment by krgii** [comment]
Add double handcuffing so they have to resist twice.

**Comment by OurDreadFather** [comment]
If you can cuff to a pipe on the floor, I don't see why you shouldn't be able to cuff to a conveyor belt or a grille. Could be hard to code tho. Im no coder, but the conveyor belt doesn't move, it moves objects on it. So your cuffing to a stationary object but expecting the cuffed person to move.
