### ISSUE TITLE
Donor borg support

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation-classic#1131]
Fully implement a system that would allow Kmc2000's donor borg sprites to be used without busing.

**Comment by ParagonPrime** [comment]
_Disclaimer: not a coder_

Should be easy (_refer to disclaimer_); just add a check for donator status to the borg sprite selection screen and add the donorborg sprite

**Comment by Cruix** [comment]
Should all donators get all donator skins or just their exclusive skins?

**Comment by krgii** [comment]
Just exclusive I believe.

**Comment by ParagonPrime** [comment]
That's harder to do, though, innit?

**Comment by krgii** [comment]
It should be easy if you can title the .dmi with the ckey and icons with the borg type then make a proc that searches the folder for your ckey and borg choice.

**Comment by Kmc2000** [comment]
Ive titled mine things like:

Donor skin pack: Kmc2000

Would be nice to see this added after a YEAR OF NAGGING

**Comment by krgii** [comment]
Cruix can do it. We believe in him.
