### ISSUE TITLE
Display Cases (buildable ones)

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1142]
Captain's laser 100% requiring smashing is stupid.

As is it's irreplacability.

So.

Display cases!

Requires-5 wood for the display frame.

2 glass for the cover.

Any item can be put inside it as the Captain's laser can. Clicking it will open the case or close it accordingly.

Click the frame with wire and then an airlock circuit to access-lock it, so only members of that specific department in which the airlock circuit access was set to can open it without smashing it, by swiping the ID. Can be short circuited with a multitool or emag, like the atmos tech fireaxe case.

Attach a proximity sensor to the frame to make it sound an alarm to the AI if triggered through smashing. 

Attach a forensic scanner to the wired frame to fingerprint lock it, so that it requires that person or an item touched by that person to be applied to the frame to unlock it safely. Shorting this out with a multitool will alert the AI if a prox sensor is attached. Emagging it will trigger an alarm as well.

Attach a battery to the frame along with the wires to make it shock you if you fail the access requirement or beat it with something.

The captain's laser case is unique in bolting doors when broken, and has both an airlock circuit with Captain access and a forensic scanner attached, so that it requires both the Captain to touch it and then unlock it with his ID to remove the gun from the case safely.

**Comment by oisin100** [comment]
:+1:

**Comment by ParagonPrime** [comment]
protip:

to get cap laser, hurl floor tiles at display case while standing in a doorway
airlock won't close unless safety override is on
enjoy

but yes this is a good idea

**Comment by ghost** [comment]
> throw floortiles
> 
> ai sees due to unfixable bug that lets it hear emotes through walls
> 
> die

**Comment by Cruix** [comment]
protip:

just use the disposal bin to escape.

**Comment by krgii** [comment]
Tators should get a glass cutter in the uplink that can steal the gun without setting off the alarm.

**Comment by ghost** [comment]
> traitor specific item for one specific objective that you could steal just by rubbing the captain's condom and swiping an all access ID on the case

why krgii

**Comment by krgii** [comment]
Glass cutter could be used for other things too. Make them break windows into glass sheets instantly and maybe even give them a timer and allow them to break reinforced windows into glass sheets. The brig has glass windows so it would be very useful for breaking people out.

**Comment by ghost** [comment]
doesn't seem like a good traitor item either way, perhaps an item to add to engineering or atmos oh wait the fire axe does exactly that

**Comment by Time-Green** [comment]
Esword to cut it open?

**Comment by EMT321** [comment]
I always thought it was nice Comdom bait, to see who breaks their display immediately.

**Comment by Super3222** [comment]
This is nice.

**Comment by ParagonPrime** [comment]
EMT has it.

Whenever a cap breaks his laser out at roundstart I lock him into his office and turn off the power to the disposal bin due to "potentially harmful stupidity"

To this day, I've only been foiled by the Captains ahelping and being told they can swipe their ID on the APC to escape via disposals while I'm distracted.
