### ISSUE TITLE
Give soulstones a higher layer so they appear at the top of a sac rune gibstack

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1144]
being sacc'd more often leads to being ignored because nobody can find your stone in a right click pile of death so making the stone appear at top is gonna help

**Comment by ShadowDeath6** [comment]
sacc baby

:+1: this is a good idea

**Comment by krgii** [comment]
But then you can't hide soul stones under dropped items.

**Comment by ghost** [comment]
if sec walks in and sees the HOS's clothes on top of a pile of bloody robes and gibs they're going to kill you regardless of soulstone

**Comment by FluffySurvivor** [comment]
> sec walks in and sees the HOS's clothes on top of a pile of bloody robes and gibs 

but hey that's fine
thats perfectly fine

Ban them for not respecting the sacred metashield of cult
