### ISSUE TITLE
Remove limb damage caps

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1146]
It...doesn't make much sense to me, in all honesty, that for no reason in particular there is a maximum amount of damage you can take to one limb. Getting hit by a stunbaton 20 times in the left arm shouldn't keep you at the same health as though you were hit 8 times by a stunbaton.

Besides, I have  a medical rework i'm gonna suggest soon and this will definitely help.

I can't see many balance issues with this either-It's rather annoying cheese when you die just because your stunbaton hit an already max-damaged limb once more than it should have and the guy lasers you, but it won't actually affect game balance in any major, significant way due to the way weapons and the damage system works.

**Comment by FluffySurvivor** [comment]
It actually DOES have a purpose. 

If limbcap is removed, armor suddenly becomes useless because aiming for the unprotected limbs will be the meta, bypassing buletproof vests etc. Pretty huge, especially in nuke ops.

**Comment by ghost** [comment]
Aiming for unprotected limbs is already the meta with armor such as bulletproof vests.

**Comment by Time-Green** [comment]
At a certain damage point it should fall of or be made unusable. That way if your right arm is hurt to certain point, you can't use it.

**Comment by ParagonPrime** [comment]
> lose both arms
> shitler clown runs along
> slip, steal ID
> cri

**Comment by ghost** [comment]
Actually, /tg/ DOES have dismemberment, and i'm planning on porting it if nobody else does.

**Comment by Rocks4Free** [comment]
> Actually, /tg/ DOES have dismemberment, and i'm planning on porting it if nobody else does.

This, I love this. I remember the good old days of playing bay code where you could hack people limb from limb and then get banned for not emoting you butchering the corpse

**Comment by AsV9** [comment]
@AdamElTablawy 
port that pretty please
