### ISSUE TITLE
Add round history

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#1152]
It tracks all the rounds, stores important info like round number, duration, gamemode, outcome and crew manifest. Then all this info is accesible to everyone. Can calculate winrates and such. 

It can be accesed via the forum like the public ban list. 

Will help immensely in balance, so I can prove cult has a 100% winrate, while also being a really useful tool for everyone.

**Comment by oisin100** [comment]
Ive actually been working on this for the last few weeks...

**Comment by EMT321** [comment]
This would be amazing, similar to what TG has.

**Comment by Robertruler77** [comment]
We do need this, but fluffy I can categorically say cult is not a 100% win rate. 

Regardless, we do definitely need to see what needs the nerfs and buffs.

**Comment by oisin100** [comment]
The frontend of the statistics site has had a lot of work, see the site [Here](http://yogstats.oisin100.net/)

I still have to write the PHP backend, once that is done then hopefully Byond 511 will be out soon afterwards with Libcurl support.

Some feedback on design details and what exactly you want logged would be nice, The site isnt going to be developed to have mobile support.

**Comment by oisin100** [comment]
P.S: No DMCA pliz, Kthx.

**Comment by FluffySurvivor** [comment]
Amazing work, glorious Headcoder! 

but add mobile support pls

**Comment by FluffySurvivor** [comment]
-Damage dealt (helps immensely to determine murderbone/antag performance/traitor item combos) 
-Track traitor items purchases/winrates  (will help coders a lot on what is weak and what is op) 
-basically what other stuff tg has

**Comment by oisin100** [comment]
> -Track traitor items purchases/winrates (will help coders a lot on what is weak and what is op)

Good idea, Will do.

**Comment by EMT321** [comment]
Can we get a %survival rate as well?

**Comment by oisin100** [comment]
> Can we get a %survival rate as well?

Sure
