### ISSUE TITLE
Make war default in nuke ops

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#1156]
### Expected Behaviour

An all-out fight for survival between the nuke ops and the crew 
### Actual Behaviour

25 pop emag in caps steal the disk arm the nuke round ends LOLOLOL EZ GAME
-or-
comms get bombed nobody knows it's ops cap dicks around in maint gets killed round ends in 5 mins ayyy lmao 
### gimme le war

War is fun for both parties. Nukies get a shitton of cool gear they could never afford otherwise and every assistant can fulfill his wet dream. Basically, every department can finally feel useful and the whole station is collaborating for a common goal. 

In the end, a devastating war errupts and everyone is called to fight, thus **creating the only gamemode with 100% of players participation in the effort against antags**

Pls make it default it's too good compared to non-war.

**Comment by ShadowDeath6** [comment]
ops should have a choice

**Comment by Super3222** [comment]
I like both concepts of a nukeops round.

Stealth ops surprise the crew and go loud
War ops with an outstanding amount of gear go toe-to-toe with a crew given an amazing amount of time to prepare.

Rather than taking out an entire mode for another, why not make a variation of it like how double-agents is to traitors. Just make war automatically happen first, and possibly give the nuclear ops a little more TC than they'd receive on war. Maybe even give them more people, like 7 or 8.

**Comment by FluffySurvivor** [comment]
@Super3222

stealth ops can still happen
war just makes the crew aware of nuke ops, but they still won't recognize disguised ops from redsuit ops

**Comment by Super3222** [comment]
I mean completely invisible towards the round unless an engineer randomly encounters one.

So ideas like sending a trojan horse (locker full of nuclear operatives) through a teleporter can still exist.

And than when everyones calm and quie- BOOM! Five nuclear operatives shooting down everyone in sight and rushing through the station.

Stealthops leaving all of their gear in their backpack, dressing up as assistants, and than pulling guns on people is shitty. The only way to catch them is to realize how ridiculous their last name is and/or if they've named their ID job as something stupid like 'Not an Operative'.

**Comment by AsV9** [comment]
lol

**Comment by FluffySurvivor** [comment]
> lol

**Comment by ghost** [comment]
fuck off fluffy that's completely retarded

stealthops would NEVER happen because crew would immediately know when ops didn't show that it was stealthops

ops is fine as is and war being optional is fine

this is legitimately rocks4free tier suggestion here, screw off with that

**Comment by FluffySurvivor** [comment]
adam i made this issue for opinions and suggestions
No salt

**Comment by ShadowDeath6** [comment]
that was his opinion though

**Comment by Greatbigben** [comment]
Salt kind

**Comment by ParagonPrime** [comment]
fluffy i wuv u but this is shit as shit

aside from all the other reasons this is shit, such as removal of stealthops and any sort of sneaky strategy, it's also really unbalanced on lowpop

it's ridiculous- declaring war on lowpop gives the nukies free TC for loads of fun shit while the station simply cannot outgun them

war only works on highpop
forcing it in lowpop is retarded

**Comment by FluffySurvivor** [comment]
kek
