### ISSUE TITLE
Weird corner vision bug

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#1157]
### Expected Behaviour

Not to be able to see through walls
### Actual Behaviour

To see through corners of walls
### Steps to reproduce the problem

Go to a room with a corner in it

![capture](https://cloud.githubusercontent.com/assets/17688334/15270097/c1e7630e-1a0b-11e6-8abf-d18880d70d65.PNG)

**Comment by AsV9** [comment]
Can't reproduce, I cri.

This is latest dev branch:

![image](https://cloud.githubusercontent.com/assets/13056792/15270332/e5bac1a8-1a1b-11e6-83a2-d1194f9d0aa9.png)

**Comment by Time-Green** [comment]
It's caused by the sigs, Someone else reported it and again. SIGNS

**Comment by AsV9** [comment]
The signs are fine on the outside...?

Even then you shouldn't be able to see the signs from the inside.

**Comment by Super3222** [comment]
There's been a glitch going around even.

Papers (specifically the one inside of the gravity room) being able to be seen through walls.
Pinpointers seen through walls.
Captain's safe seen through walls.
