### ISSUE TITLE
Buff rev

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1162]
okay i never thought i'd see the day i'd say 'buff rev' but 

the revhead memorizer literally has a RNG failchance to not convert and the electronic hijacker takes 30 seconds to convert a flash into another one

remove RNG failchance and change electronic to take 20 seconds to convert a flash seeing as flashes are hard to come by without failing to convert the roboticist wearing welding goggles and an RNG fail

**Comment by ShadowDeath6** [comment]
I have literally not seen revs lose since the update, they're fine

**Comment by Super3222** [comment]
I'm not sure where the failchance is coming from, but yeah it has a chance to not do anything (this was tested with a revhead).

**Comment by FluffySurvivor** [comment]
I see no failchance in the revflash code.

**Comment by Super3222** [comment]
Adam was a revhead, I was a civilian.

He flashed me once, nothing happened. He flashed me again, and than I was converted.
