### ISSUE TITLE
Make surgery and medbay storage doors standard medbay access/all access

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1169]
Half the reason nobody does surgery is because nobody but the med doctors can get in, and usually there are bored medbay staff that are not doctors who want into surgery and have to yell at the doctors to let them in/the AI.

It'd be nice if it was actually available for people to enter.

Making medical storage also makes sense-So paramedics, chemists, and geneticists can get the medkits and supplies the doctors won't use or immediately need without having to break in.

**Comment by ShadowDeath6** [comment]
don't make them all access, but standard med would be good

**Comment by Time-Green** [comment]
Just make it all medicals, else it'd be looted empty on an instand

**Comment by ToGWtF** [comment]
ill add gen and chemist access to it, but syringe gun lockers are staying chemist-free

**Comment by Super3222** [comment]
Sounds reasonable. However, @TogWtF it's literally too easy to break open any locker with a simple water-potas nade. That doesn't even breach the floor

**Comment by ToGWtF** [comment]
if theres a will theres always a way. i'm just not going to GIVE them the way.  ill get to this when im feeling motivated again
