### ISSUE TITLE
Make shards more useful

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#1171]
What do you guys think of allowing shards to remove wires without getting shocked?

**Comment by oisin100** [comment]
So shards would work better then the actual tool(Wirecutters)?

**Comment by ParagonPrime** [comment]
Should take a long while and have a large chance of dropping the shard (causing brute and bleeding on the hand holding it)

**Comment by Axemeaquestion** [comment]
I like paragons idea for balance.
