### ISSUE TITLE
You can stack a soul shard with an item in a mining drones exosuit slot

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#1172]
### Expected Behaviour

To put one item and one item only in a mining drones exosuit slot
### Actual Behaviour

STACK ITEMS LIKE A BOSS
### Steps to reproduce the problem

Equip a mining scanner, and then a soul shard in any order

I've only made this work with a soul shard and scanner, I'm not sure what else would work.

![buuug](https://cloud.githubusercontent.com/assets/17688334/15287821/7f7efe16-1b5d-11e6-9b50-9973aff1d5de.PNG)

**Comment by ShadowDeath6** [comment]
I've done it with a lot of items, just use the quick equip hotkey with small items

**Comment by Notamaniac** [comment]
My guess is that the exosuit slot is working like a backpack rather than an equipment slot, so if the weight class is small enough for the items, you can stack them

**Comment by ShadowDeath6** [comment]
It also might be since the scanner STARTS in the storage that it doesn't count as having anything stored in there, so it can shove other items in there as well.
