### ISSUE TITLE
[Forum] Not Mobile Friendly

### ISSUE THREAD

**Issue by Robertruler77** [yogstation13/yogstation-classic#1173]
### Expected Behaviour
1. Doesn't crash randomly since the update and force me to use Safari rather then Google and only post on the forum at home on the PC
2. Can see what people are doing on steam and read ban appeals/complains related to me.
### Actual Behaviour
1. Crashes if you hang about on the same page every 2-5 minutes, making mobile posts a big no-no.
2. Anyone with a steam account gets the steam bit double posted in their id bio and actual post so they can't be read due to the squeezing to fit in the steam part.
### Steps to reproduce the problem
1. Go on browser on mobile (I used Iphone 4S)
2. Access any topic in any category
3. Crash and have to skip past battery draining text like this:

i
t
b
ro
k
e
pl
z
f
i
x

**Comment by AsV9** [comment]
please bitch to hardy.
