### ISSUE TITLE
revert the fucking forums

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1174]
### who the FUCK changed this

what were you THINKING
### I can't fucking see anything

it's as blue as a smurf's balls
### REVERT BACK TO OLD FORUMS PLEASE
1. I can't tell what the hell i'm looking at
2. The alert buttons are tiny
3. where the FUCK are the sections????

**Comment by OurDreadFather** [comment]
I concur. I dont like new things even by normal standards, but this is new AND bad.

**Comment by R3DGL4R3** [comment]
God almighty,please.

**Comment by sagattyy** [comment]
Good idea

**Comment by ghost** [comment]
add smurf balls tag please

**Comment by sehloiro** [comment]
"Adam is chubby" is also a suitable tag

**Comment by utahclock** [comment]
Yes revert please new theme sucks on my phone

**Comment by Rocks4Free** [comment]
why is it so big

( ͡° ͜ʖ ͡°)

**Comment by ShadowDeath6** [comment]
the only problem I have is steam integration making all posts I see look really bad and impossible to read

**Comment by Super3222** [comment]
The old theme was more atmospheric and space like.

This new form is a lot more blue and... it doesn't feel like a forum fit for 2d spessmen.

**Comment by Robertruler77** [comment]
My forum reoprt was basically asking for the same thing. Yeah, PLEASE change it back so I can actually use it.

**Comment by Notamaniac** [comment]
Wait when was github the go to place to complain about the forums

**Comment by Robertruler77** [comment]
Since Adam made it cool.

**Comment by Time-Green** [comment]
W
Hy
I
Do
Nt
Se
E
Th
E
P
R
Obl
Em

**Comment by Axemeaquestion** [comment]
Its so big too it makes it hard to navigate it old one was spacey

**Comment by ghost** [comment]
smurf balls tag NOW

**Comment by Kmc2000** [comment]
For once i actually agree with adam

Nerf forums

**Comment by AsV9** [comment]
bitch to hardy, not github.
