### ISSUE TITLE
Give the psychiatrist, lawyer, librarian and clerk some actual use.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1175]
They're four 'rp' jobs that unlike most other RP iobs, can't actually have fun. Lawyers are ignored or killed-I can count the number of trials i've seen on one hand. Clerk and librarian are either kleptomaniacs, traitors, or suicide at roundstart. The psych is a med doctor with less access and a robust briefcase, and a private murder office with a shut the fuck up jacket.

Proposed reworks-

Psychiatrist.

This one is the one I feel could go either way. He could have a special medvendor in his office with a few pills and bottles of synaptizine, morphine/chloral, mannitol, calomel/charcoal (for addiction or overdose) and space drugs, and when hacked a bottle or two of krokodil and mindbreaker toxin. With him specializing in the 'mind' chems, you'd see him helping out more around medbay-especially during ling hallucination outbreaks, which could lead to lines of patients showing up to get treatment. Put one of those nifty rubiks cube puzzle cubes on the table, perhaps expand the office slightly to take over the patient rooms to have the spare beds as part of his office for 'unstable patients' (murder victims), and he at least has SOME utility.

But adam, that won't change much at all, you might say.

To which my response is to throw more shit at the wall and see what sticks-incidentally also how I test my cooking to see if it's edible. 

We can go two options from here. For one, the psychiatrist specializes in treatment of the mind and mental afflictions. Naturally, the first thing that pops into mind is conversion antags-specifically, rev, gang. Cult already has the chaplain so we can ignore that.

The ideal here is to make implants, while important, less all-consuming than they are now. Someone specialized in mental treatment should be well versed in being able to break people out of whatever mental haze they're in.

Ideally, the psychiatrist would get some sort of item that spawns on them, similar to the chaplain, that allows for deconversion of revs and gangsters in a similar, but more reliable way than head-beating. Unlike implants, which are limited, the psych would get an of electroconvulsive therapy machine-it would, similar to head beatings, roll a 50 deconversion chance and a 50 failure chance. On that deconversion, it also rolls a 20-30% chance to render the subject implanted (iunno why, bluespace magic or something) to prevent further conversion without surgery. All it does on nonrev/nongangs is 20 burn-it does this to everyone. It also induces a seizure (a la genetics), so spamming it will probably kill the guy. It requires an empty head slot, and has the same delay application as a defib, so no psychs running through the halls deconverting everyone unless they're really good with a bottle of lube. On a gangboss or gangleader, it'll outright fail in it's deconversion attempt with a message stating as such. It can actually fry loyalty implants as well, with a 20% chance, and has a 25% chance to fry a mindslave implant (killing the guy but de-slaving and de-bombing him for easy cloning)

Why? Well, electroshock therapy is suitably barbaric to fit with the Nanotrasen theme. It also adds some actual counter to gang/rev beyond hide in cargo and wait for implants/kill everyone. It's a reliable source of deconversion, which will hopefully reduce the amount of mass death and salty ghosts on a long rev round. It still has a failure chance, so it's not perfect, and can actually kill the guy if you're not careful, just like head beatings, and will still piss off the AI. It belongs to one, rarely played role-a role also in a very vulnerable position (medbay) so chances are they'll end up in the gang/rev and spacing it. It adds some utility to a never touched role and fits with the general theme of things.

Obviously this is sort of touchey-feely and might be a bad idea, but at least the psychiatristvendor is an okay thought.

Clerk-

Instead of a useless toy vendor (and sometimes really overpowered gifts), give the clerk an all-in-one vendor that doesn't particularly specialize in anything, but can swap between a few sections.

It would contain-

Clothing
-4x colored jumpsuits (random)
-4x colored shoes (random)
-4x backpacks (random)
-4x colored gloves (random)
-2x jackets and 2x labcoats (random)
-1x psychedelic jumpsuit (when hacked)

Medical
-3x syringes
-2x brute patch
-2x burn patch
-1x antitoxin bottle
-1x epiphenerine pill
-2x large beaker
-1x Stimulant (mining stim) (when hacked)

Tools
-3x flashlight
-1x flare
-1x mechanical toolbox
-4x cable coil
-2x multitool (with coin)
-1x budget insulated gloves (when hacked)
-1x airlock painter (when hacked)

PDA
-2x all civillian PDA cartridges
-2x all medical and cargo and science cartridges
-8x PDA
-1x shiny centcomm PDA (with coin)
-2x all security/head cartridges (when hacked)
-1x valu-pak cartridge (when hacked)

Remove the camera in the clerk backroom so he has a place for murder.

The ideal here is to make people go to the clerk when they want something they generally can't find and want-and by coin locking some of the good stuff, people will actually bring money to the clerk for shit.

Lawyer-

The lawyer has the unique case of being in the right position to stop shit from going badly, but with no power to actually do anything if the HoS doesn't cooperate.

There are two ways to fix this, however.

Option A is to give the Lawyer a fax machine/one of those green announcer thingies, allowing them to make announcements, send messages, and message a centcomm official (whom is lower on the totem pole than the officials the Captain can contact, basically being a pencil pusher). This gives them a little more sway, since they can both make announcements and contact Centcomm in extreme cases if security's flubbing it badly. Giving them a set of sunglasses for looks and access to the cell timers would also help, so that they could correct incorrect sentences and enter/exit cells with unfairly/improperly brigged persons. 

From a roleplay standpoint, the lawyer's ranking in the security chain of command would go from Officer to Warden to HoS to Captain with lawyers excluded to lawyers being equal to or slightly lesser than an officer's ranking inside the brig in terms of sentencing, meaning that if a lawyer who saw the crime and an officer who saw the crime both have contrasting opinions, there is conflict in action rather than the officer punching the lawyer and walking away. The easiest way to do this is to change the 'you are subordinate to' message from HoP to 'warden and superiors' with an additional message that you're not a sec officer and shouldn't be brigging people.

The second option is to replace the lawyer entirely with Internal Affairs. Internal Affairs would basically try to ensure everything's going according to standard operating procedure (read as: everything should only be halfway tits up instead of the full bust)

IA would spawn under the supervision of Central Command and the HOP, and essentially act as the HOP's subordinates (though not under his direct command.) They would be to the HoP as an officer is to the Captain. 

IA would have the purpose of mediating interdepartmental conflicts and ensuring things aren't going crazy. What this boils down to is IA investigating all those obnoxious minor crimes like some dickshit making fun of you all shift or stealing your beakers or miners slacking off or the asshole who hijacks your job because he can do it faster or the HoS who brigs people during blob. All that stuff.

He isn't a member of security-he is to command as the lawyer is to security. External, but involved, with some sway. He'd have command and security access on his headset and start with basic access to most departments and bridge access. 

What the IA does is a short step process.

Step 1. Get a report from an angry crewman/see something happening. 
Step 2. Step in after the fact and look into what happened, whodunnit, why, and where.
Step 3. Inform security or the relevant head of staff(s) on what to do and whodunnit.
Step 4. Get ignored.
Step 5. Contact Centcomm via your announcer/fax machine.

The announcer slash fax machine in the IA's office would both allow them to make announcements and message Centcomm with theirs or another crewmember's complaint for a possible (and probable) response.

The IA wouldn't be arresting people for crimes like a sec officer. Nor fight for their release like a lawyer. But if someone called for IA while being brigged due to say, bucklecuffing, the IA would be responsible for writing up and lecturing the officer, and if they ignore them, going to the HoS, HoP or Captain, and if ignored there, going to Centcomm.

He'd also be authorized, similar to a head of staff, to schedule someone to be demoted for incompetence, or in the case of an idiot/rogue head of staff, have the authority to contradict them and order their arrest and demotion by security-this is the limit of their authority over sec, and just like the Captain, space law > them, and if they break the law they can get jailed too.

That's basically all my ideas for fixing some of those jobs. They're half baked and half assed but at least they're better than what we have now.

**Comment by Rocks4Free** [comment]
I like all of your suggestions since they would actually be useful, but you didn't even mention the librarian at all.

**Comment by Super3222** [comment]
I think I talked on our coder channel about a psychiatrist rework a long while ago.

But yeah, my main view is on psychiatrists and how their role on the station is currently useless. Since the server is centered around low rp with most people just wanting to become antag and bluntly murderbone, no one really plays it but newcomers.

I feel like implementing a basis for psychology, just like geneticists manipulate genes. The brain will become not just something that you shove into MMI's to make borgs, but a much more interesting/annoying force.

**Comment by ParagonPrime** [comment]
I like all of this, especially the psychiatrist's electroshock-therapy bit.

As for the lawyer, I approve of the fax machine, but as for how to solve the rest of the issue... neh...

**Comment by Robertruler77** [comment]
Though I'd rather not remove lawyer cause lawyer is the closest you can get to actual, meaningful cooperation with sec without being sec, IA sounds interesting. Just wish lawyer could actually get more to do cause the job is brilliant in the rare moments where a lawyer can do their job.

**Comment by Zostroll** [comment]
Electroshock should have a chance of brain damage

**Comment by Super3222** [comment]
> Electroshock should have a chance of brain damage

Definitely.

Also where's librarian??

**Comment by Super3222** [comment]
Hello, it's me 23 days later
