### ISSUE TITLE
Give biogen the ability to make clothes

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1176]
Some of the only nonreplacable shit on the station is clothes. 

Make biogen able to make jumpsuits, pants, ties, shoes, backpacks, hats, gloves and some exoslot items.

Generally in the 150-250 range, would be jumpsuits of all colors, backpacks, and some exosuit items that make sense (winter coats, labcoats). Certain jumpsuits, like head of staff or security jumpsuits, as well as clown and mime jumpsuits, would be unavailable. Tacticool turtlenecks, centcomm official jumpsuits and ian shirts and other gimmick jumpsuits would be allowed.

In the 100 range, backpacks of all types except clown and mime and Captain.

In the 250 range, duffelbags and work packs.

In the 75 range, all types of shoes.

In the 100 range, black and fingerless gloves.

For 400, can make bodybags.

For 250, can make potato batteries.

For 350, can make gasmasks.

When hacked, can print for 650 biomass, security/head of staff/clown/mime jumpsuits backpacks shoes and blindfolds, muzzles and straightjackets.

Can make saltpetre bottles for 85 biomass.

Can make psychedelic jumpsuits for 2000 biomass when hacked. Can also make the human flesh suits that lings wear, except removeable with no armor and no space protection-effectively a hilarious and creepy prank like the syndie replica suit

When EMP'd or emagged, can create for 2000 biomass, tactical turtlenecks, syndicate duffelbags. 

For 4000 biomass, when emp'd or emagged, can make the default military belt.

**Comment by Robertruler77** [comment]
All the yes. Botanist just makes leather shit in terms of clothes. Would love more fleshing out.

**Comment by Cruix** [comment]
Will the clothes come with suit sensors or will they need some addition from science for that?

**Comment by EMT321** [comment]
I feel like giving the people most likely to be slipping the station (after the clown) straightjackets could go wrong very fast.

Otherwise this is a great idea.
