### ISSUE TITLE
Re-add some chems + a few new chems

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1177]
re-add tricord, bicardine, dylovene, kelotane, dexalin, dexalin plus. The recipies are on the /tg/ wiki, old and new.

Tricktd is a general, slow acting cureall. Bicard and kelo are in sleepers, dexalin is a weaker salbu that purges lexorin and dex plus resets oxy damage to zero temporarily but overdoses really easily (5u).

Add dermaline, which is kelotane and plasma as a catalyst, which overdoses on fifteen units but heals twice as fast as kelotane.

Add to spaceallin the function of actually nullifying a disease's symptoms (no sneezing or bursting into flame) while preventing transmission. I have big plans for it in the future but this is just the start. Also add it to sleepers. Give it an OD at 20u>. 

Addictol (credit to keek) boosts addiction recovery chance 200%. Plasma (catalyst) calomel and copper. Becomes addictive itself at quantities over 15u, with heavy toxin penalties if not satisfied, and overdoses at 30u doing significant brain and toxin damage before knocking out 20 ticks later.

Hemofibrin-an anti-bleeding agent. Turns all Heparin in the body into water and iron, also reduces bleeding by 5 every 3 ticks. Made with Heparin and Carbon, also found in reishi.

Buff epiphenerine and atropine to restart the heart on injection if a heart attack is suffered, and to accelerate the purging of initropidil by 2x.

Add compensatin (shitty name). Converts brute damage to burn damage and clone damage to oxygen damage by 5 points a tick. Made with cyroxadone and epiphenerine. OD's at 20u, wherein it converts all damage into clone and toxin damage.

Vayterin, a stimulant, made with epedephrine and krokodil, resulting in  one units instead of two. Provides a significant speedboost (faster than meth, about 400%) while negating damage or stamina slowdowns, but doubles damage intake and stun time. If you're hit by a revolver shot on this welcome to crit city, if you get pegged by a couple lasers it's fourty damage. Also does steady stamina and toxin damage over time, and on wearing off deals 50 (non-multiplied, distributed) damage to both legs. On overdose (35u) you move so fast you kick yourself in the face every time you try to move, stunning you for four seconds and doing 18 brute.

**Comment by ShadowDeath6** [comment]
We have bicaridine, kelotane, dexalin, and dylovene already, not to mention charcoal. Dex plus is basically perflouro, and tricord was replaced with omnizine.

Also

> 50 damage to both legs

That literally will crit you

**Comment by ghost** [comment]
I said distributed 50 damage, not 50 damage each

**Comment by ShadowDeath6** [comment]
Also compensatin or whatever is stupidly powerful given that it's shit easy to make and is basically cryoxadone + rezadone but better than both combined

**Comment by ghost** [comment]
it also knocks you out due to the massive amount of oxygen damage it's doing, meaning that it'll knock you unconcious, and since you're unconcious due to oxy dep you will then suffocate and die without external treatment

**Comment by ShadowDeath6** [comment]
> inject with epineph or salbut or any chem that stops oxy damage, even cpr
> free cryo
