### ISSUE TITLE
Some simple_mobs attack twice

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation-classic#1186]
Thanks to @ShadowDeath6 for bringing this one to my attention.
### Expected Behaviour

Simple mobs attack once.
### Actual Behaviour

Some simple mobs (bears/carps/fearless/statues) attack twice per click.
### Steps to reproduce the problem
1. Spawn a simple_mob (bear/fearless/statue/etc)
2. Click on human being
3. Enjoy free double damage

Some simple_mobs do, indeed, attack only once (like constructs, slimes).

**Comment by ShadowDeath6** [comment]
pretty sure this has something to do with shields, since it started around the time that shields were made to block simple mobs. I can't see what's causing the problem, though.

**Comment by Super3222** [comment]
Quick questions.
1. Is this ONLY happening to humans?
2. Can you add more examples of mobs that attack twice?

**Comment by ShadowDeath6** [comment]
1. It happens with windows as well, probably other interactable objects. 
2. As far as I've seen, it's ANY simple mob that's not a construct or a slime.  Hudson, poles, carp, headslugs, faithless, statues, and so on.
