### ISSUE TITLE
Give the rev flasher a lower cooldown, and a cooldown timer 

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1187]
### Expected Behaviour

Revs can actually convert people
### Actual Behaviour

Most rev rounds take hours, and usually gets eight revs tops, in all the rounds i've seen (and i'm on most of the day). Give the flashers a timer so that you can shift-click on examine to see how long it is until you can flash again, or some indication like a gang pen, and reduce the goddamn cooldown.

**Comment by Groudonmaster** [comment]
Was in a rev round earlier. Like 30 revs because people know how to hijack flashes

**Comment by ghost** [comment]
nobody knows how to hijack flashes

**Comment by FluffySurvivor** [comment]
how do you hijack flashes

**Comment by Robertruler77** [comment]
You can hijack flashes?

**Comment by Super3222** [comment]
The point of lowering the cool down was to prevent most of the issues with rev.

So if the problem is no one knows how to hijack flashes, why doesn't someone just show it to them.... Like an admin.

Or some work can be done to the revs wikia page and I could just link them to it when they first join. Similar to how slings are linked to guides.

**Comment by EMT321** [comment]
I've had no issues as a rev with flashing people. I think people just dont know how to use the hijacker, so their starter flash burns out and they think they are S.O.L.

**Comment by X-TheDark** [comment]
Holy shit, rev is no longer a zerg rush? This must be fixed immediately! /s

**Comment by X-TheDark** [comment]
I don't any kind of problem, really. If players don't know how to hijack flashes then it's their problem (or maybe the hijacker needs some extra text in the description telling you to hit flashes with it).

The only problem I DO see is that now rev is basically a worse gang, but that's another issue entirely. I'm quite happy rev is no longer a zerg rush (unless you know how to hijack flashes and how to make them in robo).
