### ISSUE TITLE
Revert change to forced drone toolbox

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#1191]
Alright, so the drone was nerfed a lil' while ago, forcing them to keep their toolbox on them at all times (unlike the minedrone and his near-infinite bag). This was, presumably, a measure intended to prevent drone griff (?), and yet it seems to have gutted the fun of playing Drone.

Drone isn't just about pure maintenance (not to mention that it's a lot harder to do pure maintenance when you can't reliably carry around construction supplies like metal and glass); it's about dicking around a little without affecting the round too much, be that repairing station damage, fixing up the derilict, or building an autism fort out on the solars. Their laws prevent them from griefing anyways, and trust me, if a drone wants to grief, it'll find a way to do so without a bag.

This change just makes drone harder to play- for no real good reason.
# MakeDroneGreatAgain

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I agree, having to carry construction materials in your hands is really annoying. Plus there's nowhere to put your hat collection in.
