### ISSUE TITLE
cult objectives display twice

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#1199]
The staff managed to stop the cult!
The cultists' objectives were:
Objective #1: Make sure at least 10 acolytes escape on the shuttle. (3 escaped) Fail.
Objective #2: Sacrifice Curie Elise, the Captain. Success!

The cultists' objectives were:
Objective #1: Make sure at least 10 acolytes escape on the shuttle. (3 escaped) Fail.
Objective #2: Sacrifice Curie Elise, the Captain. Success!

@Cruix

**Comment by FluffySurvivor** [comment]
its cult who cares

**Comment by Robertruler77** [comment]
You should Fluffy, cult aren't 100% Winrate. :b

**Comment by FluffySurvivor** [comment]
doesn't really matter if it's 100% or not it's still cancer to play as or against

**Comment by Robertruler77** [comment]
Cause your plan A, B, C and D is to kill it. IMO cults brilliant fun and i don't see how you can hate it, but i guess that goes both ways, huh? Difference of opinion and the like.

**Comment by ShadowDeath6** [comment]
Le cult hate salt meemee

**Comment by Super3222** [comment]
Cult takes a lot of people to stand still, but as an antag you want to be mobile, fast, and always be advancing from place to place.

But besides, that not the point of this issue. This sounds like an easy fix.
