### ISSUE TITLE
Teleporter menu issue

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#120]
Occasionally when setting up the teleporter the destination menu will have special characters rendering you unable to set the teleporter to a certain place. Has also occurred with admin jump command.

**Comment by ghost** [comment]
Type in the name of the place in the command bar.

Teleport Derelict- And hit space, and you can choose the next part to fill in and it'll teleport you there.

It's the same shit as typing sa and then hitting space for say.

**Comment by Groudonmaster** [comment]
That's a pain in the ass though. Just fix the menu.
