### ISSUE TITLE
Suggestion: Welders refuelable from holdable containers

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#1203]
### Expected Behaviour

Click on glass of welding fuel with welder, refill
### Actual Behaviour

Nothing happens
### Steps to reproduce the problem
1. Fill glass with welding fuel for portable fueling
2. Run out of fuel
3. Try to refuel and fail

Portable refuels when

**Comment by FluffySurvivor** [comment]
welding tanks are everywhere

**Comment by ParagonPrime** [comment]
Napalm welders when

**Comment by Robertruler77** [comment]
Blob about?

UNLIMITED... AMMO!!!!

Make this a thing, make the blob be more involving around the clock for the warriors of yogs.

**Comment by FluffySurvivor** [comment]
Why don't you understand there are unlimited movable sources of fuel at every corner in maint and even more in maintey rooms. 

We don't need this.

**Comment by Robertruler77** [comment]
After seeing the blob rounds I've seen fluffy, we might as well get this. Makes sense game wise and outside of blob.
