### ISSUE TITLE
Insane asylum

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#1204]
### Expected Behaviour

Physciatrist is useful, wew lad
### Actual Behaviour

lol no
### what do i want to do?

Well, i suggest we add a seperate area, like labour camp, where you can throw insane people and subsequently forget about them.

WHY KMC?!, THIS IDEA IS SO INSANE THAT YOU NEED A TRIP TO A MENTAL ASYLUM!!!!
Well, instead of killing that physcho traitor, why not send them to an asylum where a physchiatrist can look after them, it'd give them, and assistants, who could apply for guards etc. something fun to do 

This would go hand in hand with @AdamElTablawy 's insanity idea he mentioned, where as you kill people, you go a bit crazy, i think it could really add to the round to have this, itd be giving people a chance to stay in the round and RP a bit more.

Im willing to sprite and map this, lets see what people have to say

**Comment by Kmc2000** [comment]
Pressed submit by accident,  please hold

**Comment by ghost** [comment]
go away

**Comment by FluffySurvivor** [comment]
kek

**Comment by oisin100** [comment]
...

**Comment by Robertruler77** [comment]
Done right be fun done wrong be shit.

Too much of a risk to give assistants disabling weapons and make them babysit tators and griefers. As a gimmick thing it'd be fun, but not as a permanent role. Greytide sec? Dear god it'd be shitcurity done wrong.

See what others say, on the fence really.

**Comment by Alek2ander** [comment]
> why not send them to an asylum where a physchiatrist can look after them, it'd give them, and assistants, who could apply for guards etc. something fun to do

This already exists. It's called "the station"
