### ISSUE TITLE
AtomProccal is not logged

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1209]
### Expected Behaviour

The deadliest tool available to admins is logged,or at least displays a message
### Actual Behaviour

I can open and bolt airlocks, dust people, gib people, kill people, and crash the server with impunity unless people check logs for the ONE line that indicates ANYTHING was done and cross-matches it with the server logs, time, and chat logs to figure out anything happened at all
### Steps to reproduce the problem
1. Be admin
2. Use atom proccal

**Comment by ParagonPrime** [comment]
What IS atom proccal

**Comment by X-TheDark** [comment]
Atom procedure call allows you to call any proc that whatever is being called on has defined. For example, you can call "gib" on any mob to...well, gib them.

**Comment by ParagonPrime** [comment]
So what, the server has a "crash" proc? :^)

In all srs, this is one of the few git issues of badam's I agree with

**Comment by ghost** [comment]
> few
> 
> not agreeing with everything I make
