### ISSUE TITLE
Add a delay to the Ion announcement

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1210]
Ion laws can be fun, but it doesn't help that the moment it triggers centcomm screams about aI getting a funky law and it gets reset.

I suggest adding a delay so AI gets some time to act weird and then gets outed by the announcement later.

**Comment by OurDreadFather** [comment]
I like the idea. Also, over half of the Ion laws are stupid shit like "You are now 99 raging screaming virologists". The Ion laws need some new ones that are more fun. Or at least more sensible.

**Comment by Robertruler77** [comment]
Add new fun laws and delay the announcment for between 5-10 minutes.

Have some really fun ones to shake up the gameplay too.

**Comment by ParagonPrime** [comment]
I think we should have some fun ones but also some more (quirkily) dangerous ones.

Something like:

"Every room on the station is actually [RANDOM HIGH-IMPORTANCE AREA]", or "Bright light strains human eyes to harmful levels"

The former causing wild confusion when the AI informs the entire security force stationed in the brig that the clown is being murdered in the brig, and the latter being a nightmare for Phytosians.

**Comment by FluffySurvivor** [comment]
:+1:

**Comment by Alek2ander** [comment]
I'd make the normal reset board not reset ion or hacked laws, just numbered ones. That way people would have to purge and asimov, which is always more !!FUN!!
