### ISSUE TITLE
Ling absorbing other ling, husked corpse alive.

### ISSUE THREAD

**Issue by Daman453** [yogstation13/yogstation-classic#1212]
### Expected Behaviour

Ling sucks all fluid out, killing the ling and husking her/he
### Actual Behaviour

Ling sucks all fluid out, then the ling i think revived at the same time
### Steps to reproduce the problem
1. Be ling
2. Kill other ling
3. try to suck all the fluids out
4. the other ling??? revives then they be a walking husked corpse

**Comment by Daman453** [comment]
Note, i know know this is a future, but why is it one?

**Comment by Daman453** [comment]
feature*

**Comment by Super3222** [comment]
It might just be luck that the other ling got up in time to avoid being absorbed. Or maybe they used a mixture of adrenals and fleshmend to get out of their trap.

I know for a fact that even if changelings manage to get up and heal while being absorbed, once the absorption delay expires they'll be husked and eaten no matter what.

**Comment by ghost** [comment]
Even if eaten lings can revive.

**Comment by ParagonPrime** [comment]
I say give husked lings a free "second chance" headslug without the explosion. Should make for some more fun shenanigans.

**Comment by ShadowDeath6** [comment]
Lings can revive if they start regenerating before they get absorbed. However, if they get absorbed BEFORE trying to regenerate, they can't.

**Comment by ghost** [comment]
Lings regen chems when dead so they can still revive even if absorbed

**Comment by ShadowDeath6** [comment]
It says " you have no DNA to regenerate with"
