### ISSUE TITLE
Combat Magboots

### ISSUE THREAD

**Issue by Flufkill** [yogstation13/yogstation-classic#1213]
### Expected Behaviour

Put on HoS combat magboots. Turn tracking function on and off. Still visible boots.
### Actual Behaviour

Put on HoS combat magboots. Turn tracking function on and off. Boots invisible, can be thrown and picked up though.
### Steps to reproduce the problem
1. Play HoS
2. Put on HoS spacesuit + combat magboots
3. Turn the tracking system of the boots on and off several times
4. Boots disappear in slot

**Comment by Super3222** [comment]
Easy fix. Something went wrong with the icon states.
