### ISSUE TITLE
Changelings with the steal nuke core objective might not spawn with a nuke box

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#1215]
I had a ticket today where someone claimed that in a previous round, they were a round-start changeling with the steal nuke core objective, and were unable to complete it because they did not spawn with a nuke box and there were no admins on to spawn one for him. I have not been able to reproduce this locally.

**Comment by faultlesselm16** [comment]
i think its a bug with the box since awhile ago when i was just a tratiorling and was given the box it just vanished when i pulled it out of my backpack
