### ISSUE TITLE
Microbomb implant not usable in crit?

### ISSUE THREAD

**Issue by avatera** [yogstation13/yogstation-classic#1217]
### Microbomb implant not usable in crit anymore

Been a while since I last played nuke ops, but I do recall microbomb implants being usable in crit to prevent the theft of equipment. I saw no change about it, and crew are beginning to get armed up on syndie gear.
### If crit, but not dead cannot activate microbomb

If you get crit (Unconcious, but still alive) by the crew as nukeops and I assume traitor you cannot activate your microbomb, instead it activates on death. I do not recall that always being the case and there was no documentation of the change.
### Steps to reproduce the problem
1. Get crit.
2. Microbomb is unusable.

**Comment by Rocks4Free** [comment]
Just ghost, you'll die automatically if you're in crit.

**Comment by Cruix** [comment]
You can also use *deathgasp while in crit.

That said this is an annoying thing that causes a lot of new nukeops to give up their equiptment because they don't know how to explode.

**Comment by ToGWtF** [comment]
Or type "succumb" as a verb,  or Last Whisper, to force yourself to die
