### ISSUE TITLE
Suggestion: Wizard Stamina

### ISSUE THREAD

**Issue by MacHac** [yogstation13/yogstation-classic#1220]
### Expected Behaviour

Wizards can be bested if you're truly skilled enough.
### Actual Behaviour

Magic missile + Timestop + Teleport makes sure that you are literally never in a position to hit the wizard if they know what they're doing.
### My proposal:

An across the board reduction in spellcasting cooldown times, with a twist:  All spells do stamina damage.  This means that spells can be cast in short bursts for emergency situations, but uncareful or spammy wizards would collapse from exhaustion.  It also makes disablers more effective against wizards, as they reduce the wizard's ability to cast spells.  

Additionally, spell effect would start to be reduced once a wizard passed a certain fatigue threshold.  The counter to this?  The wizard staff.  The staff must be held in two hands, but it A) reduces exhaustion from spellcasting and B) prevents spells from losing power regardless of current stamina.  This is a trade-off, as it prevents gunwiz and staffwiz, as well as makes certain spells (EI NATH) impossible while wielded.  It also means that, should the staff taze you, you lose much of your spellcasting ability.

When trying to cast a spell while exhausted and without a staff:
- EI NATH would stop disintegrating and have reduced brute damage, all the way down to leaving the victim in crit at maximum exhaustion.
- MAGIC MISSILE would have reduced stun duration.
- TIMESTOP bubbles wouldn't last as long.
- FIREBALL explosions would be smaller, and do less damage.
- REPULSE would have reduced fling radius and distance.
- BLIND would reduce blindness time.
- FLESH TO STONE gains a failure chance.
- LIGHTNING BOLT would have reduced damage.
- CURSE OF THE BARNYARD would have a failure chance.
- DISABLE TECH gains a failure chance for each tech item in range.
- SMOKE creates less smoke.
- MIND TRANSFER is unaffected.
- FORCEWALL reduces wall duration.
- BLINK reduces average teleport distance, and gains a bias for space tiles.
- TELEPORT gains a flat failure chance.
- MUTATE becomes impossible to cast.
- ETHEREAL JAUNT gains a chance to fizzle out and fail.
- KNOCK gains a chance to fail for each door in range.
- INSTANT SUMMONS gains a flat fail chance.

Artifacts and rituals are unaffected.
##### CURRENT WIZARD COMBAT:
- Wizard warps directly in front of three sec officers and HoS.
- MAGIC MISSILE
- All sec officers down, wizard EI NATHs one of them.
- Sec officers jump back up, about to grab weapons off the floor.
- TIMESTOP
- Wiz waits on his cooldowns in the magic bubble.  One security officer was caught, and he takes his weapon.
- Timestop bubble disappears, sec officers take aim once again.
- TELEPORTATION
- 10 seconds later, wizard reappears in same spot
- Sec officer is ready, tazes wizard the moment he pops in.
- MAGIC MISSILE
- Wizard gets back up, EI NATHs one of the downed officers.
- And so on.
##### PROPOSED WIZARD COMBAT:
- Wizard warps directly in front of three sec officers and HoS
- MAGIC MISSILE
- All sec officers down, wizard EI NATHS one of them
- TIMESTOP
- Wiz waits on his cooldowns in the magic bubble
- Timestop bubble disappears quicker due to fatigue, sec officers take aim once again
- Wiz catches disabler beams in the chest
- OH SHIT, MAGIC MISSILE
- Barely 1 second stun because of extreme fatigue
- Wiz tries to teleport out
- Passes out from exhaustion
- Wakes up 5 minutes later, stripped in the execution room
- Wizard dies because soloing four well-equipped people is fucking shitty

Any thoughts?  Comments?  Insults about my mother?

**Comment by MacHac** [comment]
Also, yes I made this because I was salty after getting killed by a wizard 4 minutes in because of the strategy outlined above.  My rage addled brain still thinks its a pretty good idea.

**Comment by FluffySurvivor** [comment]
Not stamina, add a mana resource.

**Comment by Kmc2000** [comment]
Mac, i've 1v1'd wizards with toolboxes and won before.

You just have to get good, mana will literally kill all noob wizards and hinder pros slightly

**Comment by Super3222** [comment]
Although I hate the idea of revamping Wizard Spells...

Maybe a certain amount of mana should get extracted into a spell, unless it's upgraded.
So normal spells would take like 30 mana, and than we keep splitting that amount each time you upgrade it.

**Comment by MacHac** [comment]
Mana is fine, but I don't know why you would want an entirely new resource when we can use the existing stamina damage system.

@Super3222 Wiz needs a change, desperately.  Nobody likes it the way it is now, except the guy playing the wizard.  If it was any more powerful than it is right now, I would put it next to oldrev in terms of ridiculous lack of balance and overall terribleness and unpopularity. 

@Kmc2000 I described in the post how a wizard can keep any number of people down indefinitely while he memes them one after the other.  Yeah, you can melee a wizard who doesn't have magicmissile OR jaunt OR lightning OR ei nath, but virtually every wizard takes at least some of (or all of) those spells because they can lock out everything but a golem with a maxcap in its backpack.

> > > > > > > > > > > > > WIZ IS SUPPOSED TO BE OP

no

**Comment by OurDreadFather** [comment]
Responding with git gud is casual tier trolling when refering to fighting wizards. Mac is right, its not balanced or fair in the slightest. And creating a whole other resource system instead of using stamina damage makes no sense.

**Comment by MacHac** [comment]
Any other thoughts?  I'm just trying to stem the torrent of assistants jumping out airlocks when wizard is announced.
