### ISSUE TITLE
Port the Peacekeeper borg module from TG when

### ISSUE THREAD

**Issue by Keekenox** [yogstation13/yogstation-classic#1223]
And replace secborg because secborgs NEVER follow laws properly. Their entire purpose is basicly to defy asimov

**Comment by ghost** [comment]
We don't have exactly the same issues tg does with silicons.

Secborgs pretending to be mall cops will be punished harshly. Adminhelp immediately if a secborg arrests someone for something like tresspass without orders and refuses to release them on a law two order if doing so would not cause harm.

**Comment by FluffySurvivor** [comment]
or we could just remove secborgs so people can't get banned and by extension others can't get fucked over by the grief

they are also literally antag validhunt police

**Comment by Keekenox** [comment]
They are also OP
