### ISSUE TITLE
Blue space battery quickly discharges in APC

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1224]
The bluespace battery (40000u) decreases 1% in 3 seconds in the cryo APC... do you think it's a bug?

The battery recharger cannot keep up with this...

**Comment by OurDreadFather** [comment]
I think that APC is a little special. I remember a round where the power load specifically for environment on that APC was 40 million.

**Comment by ShadowDeath6** [comment]
Cryo can reach over 10k drain if both are active

Also the battery may have been faulty and had a lower cap
