### ISSUE TITLE
Bootstrap.min.css opened in Notepad when clicked on R&D console

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1225]
We used the console together with someone and maybe we clicked together, but when I wanted to use the console and clicked on it I got a "bootstrap.min.css" opened in notepad, starting with

"/*!
- Bootstrap v3.2.0 (http://getbootstrap.com)
- Copyright 2011-2014 Twitter, Inc.
- Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)"

I mean.. yeah.. wow.

**Comment by Nirnael** [comment]
Yeah that's from the nanogui, something fucked it up and it opened the .css file, but it should be your client's cached one and it's harmless even if you modify it on the server side cause its just styles so you can't hack anything.

**Comment by 00aquir** [comment]
okay, I guess it's still a bug.
