### ISSUE TITLE
Allow latejoin AI by putting an empty AI core in the AI chamber and having the player load into the core when they join.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#123]
No AI? Empty inactive core in the core, same stuff as when AI is carded out of it's core.

AI latejoins.

AI is downloaded right into the core.

An inactive cyborg shell can also start there too if there's no roundstart cyborg, and when someone joins, they get blooped into the cyborg.

**Comment by Groudonmaster** [comment]
I always wondered why we couldn't have latejoin AI, I approve.

**Comment by Super3222** [comment]
Think of it this way. At the beginning of the shift, a big AI core is dropped off at the AI chamber. Whether it is or not depends on if the role has been assigned (presumably by centcom), however sometimes SS13 isn't monitored by an AI.

It wouldn't make sense if the AI was just automatically downloaded into the core at any point of the shift. Maybe that's just for IC sense at least, or maybe it's true that centcom can actually do anything... aside from BSA antags.

**Comment by Groudonmaster** [comment]
Centcomm sends reports constantly using blue space connections. Not that hard to send an AI would it?

**Comment by shrimptk** [comment]
Paradise uses this system, except instead of one maximum latejoin or roundstart AI, they have slots for one primary AI and a secondary one for being or doorknob or something.

**Comment by ghost** [comment]
Centcomm is capable of doing whatever the shit they feel like doing.

It's my personal headcanon they know who all the antags are and what's happening at all times, but just don't say anything just because it's funny.

So no, it makes sense because centcomm magic

**Comment by BadminBen** [comment]
Err against this. AI is suppose to be a privilege. if Research is too lazy to upload a AI then thats it

**Comment by DavidEdwards** [comment]
This was previously discussed on the old tracker. The crew can get a member of the crew into the AI if they really want an AI. Negating the need for an automatic system.
