### ISSUE TITLE
Locker locked while closing without correct ID?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1237]
Around server time 2016-05-28 21:30 I wanted to hide in a security locker (I had normal atmos ID in PDA and a named "captain ID" in the backpack box), I closed the locker on me with bare hands and it was also "red-light" locked. An admin had to get me out... no IDs I had worked on it.

Maybe the locker was alt+clicked when it was open? an open-locked locker which closes in a locked state?

**Comment by Cruix** [comment]
It is possible that the locker was EMPed while it was open. This has a chance of locking it, and there is no way to check without closing the locker.

**Comment by 00aquir** [comment]
Hm. I say because of this (gameplay standpoint) that the locker should only close in the "open" state since nobody can see even with examination that it's "locked".. while open... yeah.

**Comment by OurDreadFather** [comment]
Theres also a bug where you can open a container like a backpack, then put it in an ID locked locker, lock the locker, then put the ID in the bag you have open, which is inside the locked locker. So you can lock your ID in a locker you just locked with your ID. Its highly inconvenient.

**Comment by Cruix** [comment]
Its almost like the thing where you could put smuggler's satchels inside themselves.

**Comment by X-TheDark** [comment]
Or access the contents of a box inside your backpack without having to open your backpack each time.

**Comment by Cruix** [comment]
That is specifically intended, there is a comment about it in inventorycode.
https://github.com/yogstation13/yogstation/blob/6615b797373685febfdb546993e6f30378a238c1/code/_onclick/click.dm#L108
