### ISSUE TITLE
Nuke code error

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#124]
Nuke input registers as text instead of num which causes it to be unactivateable.

**Comment by Hydre** [comment]
Station nuke I guess?

**Comment by Cruix** [comment]
I believe it defaults to text as a failsafe so that people cannot possibly enter the proper code if an admin has not set it, since the nuke console menu only allows players to input numbers.

**Comment by Hydre** [comment]
Admin nuke (Read: 'station nuke') has to be manually set in vars by an admin for the reason Cruix gave

**Comment by Groudonmaster** [comment]
Fairly certain the zombie random event now automatically sets a nuke code but sets the code under a text type rather than numtype

**Comment by BadminBen** [comment]
kinda silly to automatically set the code without giving it

**Comment by DavidEdwards** [comment]
As you can see, the nuke is [not set at all by Zombies](https://github.com/yogstation13/yogstation/blob/dev/code/modules/events/zombies_outbreak.dm).

Text nuke is not a bug - as Cruix points out.
