### ISSUE TITLE
[Suggestion] Heads of Staff ID consoles

### ISSUE THREAD

**Issue by Robertruler77** [yogstation13/yogstation-classic#1242]
As it stands, the Head of Staff id consoles (barring the HoP, obviously) are missing some key features. A rework should be in order, i think.

Issues:
1. You cannot change a job name via the consoles, so Joe Greytider is still an assisstant with medical access, confusing Security and Medbay Staff alike.
2. Flat access to the department, meaning some jobs force a HoP, or cannot be played at all with no HoP (Service/Supply roles say hi)
3. The consoles are never being used outside of group antagging access, for those reasons.
4. Emagging?

What I'm suggesting:
1. All access for the department can still be given, but the console has some minor changes.

Firstly, a way to change jobs immediately. IE, a scientist can give his id to the CMO and get his job changed to medical doctor, no fuss. he gets any access from that department that the job requires, but access outside of that department (EG parmed requiring maint) is not given, so the person has to go to another head of staff who allows maint access, so the HoP and either the CE or HoS.
1. If that department console does not contain all of the accesses required for that job, then the person gets a prefix: Rookie. This is to signify they may not be fully able to access everything required to do their job. However, there are no Rookie Head of Staff roles, so the CMO cnat make an RMO, or a CE make an RE.

Most accesses are in one of the id consoles. The QM COULD also get a console with departmental access so mining and Cargo can progress smoothly. Maint could be HoS/CE, Genetics would be both RD and CMO, Tech could be RD/CE, tools would be CE, EVA could be CE etc.
1. Furthermore, all heads of staff should spawn with a box of ids in their locker, and are allowed to change the name of the id, but only unnamed ids and once and once only. They can freely manage their staff with the id box and the id console, rather then relying on a role that may never show up.
2. Emagging one of these consoles removes the requirement for a head of staff id to change access OR spits out an id with access to everything that console can allow. One or the other.

Thanks for listening, 
-R

**Comment by OurDreadFather** [comment]
Iv always wondered why you couldn't rename with Head of Staff ID consoles. I, at the very least, approve of fixing that bit.
