### ISSUE TITLE
Rival gang leaders in the same department.

### ISSUE THREAD

**Issue by OurDreadFather** [yogstation13/yogstation-classic#1243]
### Expected Behaviour

2 to 3 gang leaders spawn in random jobs at round start and allow the leaders to convert members of their department and actually grow a tiny bit.
### Actual Behaviour

Both chemists or roboticists are gang leaders and so 1 to 2 gangs are snuffed out right off the bat.
### Steps to reproduce the problem
1. Start round. Be gang leader.
2. Try to convert the crew member next to you in the same job.
3. Choose heads or tails and flip a coin to find out if he's a rival gang leader.
4. Realize that it didn't matter if you chose heads or tails, its a gang leader regardless.

I asked Time-Green to check and apparently there's no line of code that creates this problem, but its more than bad luck. It happens every gang round. I suggest a line of code that would force gang leaders to either have different jobs, or entirely different departments. Having one of the 2 or 3 gangs immediately eliminated because they spawned next to each other inst engaging gameplay and removes a lot of round complexity.

**Comment by Robertruler77** [comment]
I was recently viro and the CMO was another gang leader. I played for about 5 minutes. Try and start gang bosses in different departments, with similar levels of power (robotics, cargo, chemistry, chef for example)

**Comment by Time-Green** [comment]
Shouldn't be that hard. I'll go and do that

**Comment by ParagonPrime** [comment]
I'd actually recommend full removal of heads of staff from roundstart gang leader roster.

Like, HoP ganglead is INSANELY powerful. Free starting egun, all-access, cargo, zero suspicion from anybody but the most intelligent when you start egunning and cuffing random people... CE, RD, CMO, all of them, really, are pretty fucking insane.

So, while you should still be able to convert them, you shouldn't be able to spawn as them.

Much as I hate to say it, maybe QM ganglead too- QM ganglead is literally just a game of "poke the miners for free hardsuits, poke the HoP for access, gg ez"

**Comment by faultlesselm16** [comment]
prime he is complaining that you get 2 gangs leaders in the same department like both robos being gang leaders etc etc not about how op some heads as gang leaders are

**Comment by ParagonPrime** [comment]
two birds, one stone, honey

**Comment by FluffySurvivor** [comment]
@ParagonPrime heads are already restricted jobs concerning gang bosses

**Comment by Alblaka** [comment]
Actually I had my most memorable gang round as paramedic.
Spawn, be gangster. Walk up to other paramedic, pull pen, stab 'is already in a gang'. He'S holding a pen as well.
-"Akward"
-"Yup"
-"Gang truce?"
-"Sure, lets kill sec"

Don't remove random fun please! Maybe instead add a safety that killing a gang leader within 10 minutes spawns another gang.

**Comment by FluffySurvivor** [comment]
@Alblaka, unfortunately that is very rare. 

99% of times the gang bosses kill each other, and the winner's gang snowballs insanely hard with double pen and lack of opposition. Talking from experience.
