### ISSUE TITLE
Removal of the mini-hypospray.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation-classic#1244]
I personally had the mini-hypo added 2 years ago and it was all my idea. It wasn't a bad idea at the time but with the addition of goofchem and players learning how to abuse it, the mini-hypo has become beyond broken and the hypospray feature should once again remain limited to the CMO for obvious reason.

I don't need to go into details about how people can get crit and take 160~ toxin damage with only 5 units of some deadly mix. There is no counterplay against the mini-hypo, even if you catch the tiny prick message you'd be long gone and in crit in some corner of maint.

I'd even issue a challenge for someone to find a counterplay to a stimmed chemist running around hypospraying anyone in sight.

**Comment by FluffySurvivor** [comment]
I agree, it makes the real hypo obsolete.

**Comment by Cruix** [comment]
We could make it unrefillable instead. Then miners might actually use it for what it is for.

**Comment by Super3222** [comment]
Instead of removing it we could also make it a syringe that takes time to inject, notifies the person getting injected as well as the people around, instead of automatically doing it.

It'll still go through hardsuits. And added, what Cruix wrote.

I always wondered why it wasn't like that originally, because it made them stronger than the CMO's hypo up until it got buffed to go through hardsuits.

**Comment by GrayRachnid** [comment]
@Cruix It is refillable.. and that is the problem..

@Super3222 that doesn't fix the issue of the it not having a counter-play.

**Comment by Cruix** [comment]
I meant <I>un</I>refillable

**Comment by GrayRachnid** [comment]
But then you can only use it once, might as well replace it with a box of them similar to the ephedrine injectors.
Actually, why not make it so you can buy a box of healing injectors from the mining vendor? That could replace the mini-hypo. and have them start with a box.

**Comment by ghost** [comment]
Remove miner medic job, add a box of synthflesh patches to miner vendor

**Comment by GrayRachnid** [comment]
that too, could work.

**Comment by OurDreadFather** [comment]
Id love if mining medics were just removed. And Keek.

**Comment by SKR6DarkVoid** [comment]
Think I might've fixed it.. by adding recharged var to it, setting that to 0 so it cant be refilled.

Correct me if I'm wrong here.

**Comment by SKR6DarkVoid** [comment]
I can confirm, adding a refill var fixes the solution, once its empty you cannot put it back in a chem dispenser.

**Comment by GrayRachnid** [comment]
Mining medics were removed
