### ISSUE TITLE
Wire not spawning in 

### ISSUE THREAD

**Issue by missatessatessy** [yogstation13/yogstation-classic#1248]
### Expected Behaviour

A wire to spawn in that powers tcomms access and CE office.
### Actual Behaviour

The wire is no longer present (probably due to the moving of the solar stuff to secure storage)

![image](https://cloud.githubusercontent.com/assets/19648057/15647541/1bfb2df6-265c-11e6-9a2d-b1750a32a6df.png)

**Comment by oisin100** [comment]
@FluffySurvivor

**Comment by FluffySurvivor** [comment]
OOPS

**Comment by Super3222** [comment]
Wew lad.
