### ISSUE TITLE
Add the ability to cut holes in a bucket

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation-classic#1249]
What this accomplishes is that, using a surgical drill, or a screwdriver, you can cut eye holes in a bucket. This allows the player to wear it on their head and only give near-sightedness, and not complete blindness. Armour values remain the same, the bucket hat loses flash protection, and the bucket can no longer hold liquids.

**Comment by Rocks4Free** [comment]
Or it could hold half/some ther fraction of the liquid that it used to?

**Comment by ParagonPrime** [comment]
Maybe let it keep 10u of liquids but have a chance of some of it sloshing out with every step you take?

**Comment by Yackitori** [comment]
> Make it keep liquids

I'll let coders decide dis.
