### ISSUE TITLE
make it possible to bust down constructed disposals with brute damage

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation-classic#1252]
### Expected Behaviour

Break through the disposals
### Actual Behaviour

Lay down on the ground and cry because disposals are a sure-fire method to stop any attacking force aside from toxins bombs and excessive explosives.
### Steps to reproduce the problem
1. steal the rcd
2. place all high risk items in a room
3. fill the room with disposals outlets
   as an added bonus carry a bomb with you so if by some miracle someone manages to break through your autism fortress you can take them down with you.

nukeops round
http://puu.sh/palal/1d6b37cd6f.png

**Comment by Keekenox** [comment]
+1

**Comment by Rocks4Free** [comment]
Maybe make them like tables, so you can't move through them but you can shoot over them.

**Comment by Alblaka** [comment]
Toolbelt?
