### ISSUE TITLE
Debug>Spawn is not logged.

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#1253]
### Expected Behaviour

Debug>Spawn should show a message in the admin chat logs, like teleporting or gibbing would do.
### Actual Behaviour

It only logs in files, leaving the action unnoticed until someone checks the files.

**Comment by ToGWtF** [comment]
Atom ProcCall as well.

**Comment by Groudonmaster** [comment]
Man you guys are really cracking down on this stuff huh?

**Comment by ghost** [comment]
Spawning mobs is shown to admins, but not spawning items.

Make spawning items, spawning turfs, and adminghosting all display messages to admins, as well as check-antag. No more fucking abuse.

**Comment by george99g** [comment]
> Spawning mobs is shown to admins, but not spawning items.
> 
> Make spawning items, spawning turfs, and adminghosting all display messages to admins, as well as check-antag. No more fucking abuse.

This, pretty much.
Except that mob spawning is also not logged. If you use the spawn button from the debug tab, everything you spawn is just logged to file.
