### ISSUE TITLE
Initropidril is broken

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#1254]
### Expected Behaviour

Not to die from 5u of Initropidril.
### Actual Behaviour

5u of straight Initropidril will crit anyone in a few seconds, and stun them instantly. Imagine an insane chemical which is the baby of Neurotoxin (bar made) and CLF3. Not fun.

So after testing this I gave it some thought. My solution is to change how it works, instead of straight off stopping your heart from beating.

**Comment by ghost** [comment]
Just make heart-stop less lethal and make epiphenerine stabilize it and remove all initro from the body
