### ISSUE TITLE
Yogstation is Rebasing

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#1255]
### Expected Behaviour

Not have people throwing shit at the council about the council being un-democratic
### Actual Behaviour

Be up to date with /TG/ Code.

Once our copy of the /TG/ repo has been setup ill be doing a feature freeze(Atleast to the Yogstation branch), ill be expecting everybody to help port our features over to /TG/ code.

**Comment by Super3222** [comment]
:+1:

**Comment by Time-Green** [comment]
Welp

**Comment by Robertruler77** [comment]
The dam broke. Well, I don't know what to say cause I'm sure I'm already deep in the minefield, so good luck coders.

**Comment by Rocks4Free** [comment]
I'm not a coder, but maybe it would help to have a list of everything that needs porting beforehand?

**Comment by ShadowDeath6** [comment]
I have been and still am against rebasing. 
I won't be partaking in porting features over.

**Comment by X-TheDark** [comment]
![damn](https://cloud.githubusercontent.com/assets/2188139/15661635/131e0816-26f2-11e6-9553-f097ed3052ec.gif)

**Comment by Time-Green** [comment]
I don't want to rebase either, we'd just lose alot of our progress
But I will help porting

**Comment by Super3222** [comment]
> I have been and still am against rebasing. 
> I won't be partaking in porting features over.

@ShadowDeath6
This has to be a team effort. When you joined the coder team, you should have been prepared to work with it.

**Comment by ShadowDeath6** [comment]
I'm not going to work for something that I don't want on the server. Feel free to ask a head coder to remove my status if you think it's wrong for me to say so.

**Comment by imtakingabreakdontatme** [comment]
Lavaland soon

**Comment by oisin100** [comment]
> This has to be a team effort. When you joined the coder team, you should have been prepared to work with it.

Of course it would be greatly appreciated if he did help, but of course if its not something he likes he'll be more prone to make mistakes out of boredom.

All this is voluntary work, I wont be demoting anybody for not working on it.

**Comment by oisin100** [comment]
Also just to clarify, We are going to pulling the latest updates from /TG/ and adding(most) of our code ontop, we're only going to update once.

Once the update is done we'll continue on working as we work now, Keeping our code to yogs and not interfering with /TG/

**Comment by ghost** [comment]
May we clear the GitHub issues and have a list of what to port to the rebase branch and instructions on doing so?

**Comment by ToGWtF** [comment]
I think people should start with whatever projects they personally submitted and wish to bring over with this change, and leave a note in the merged PR that they have ported it over. We can go through whats left over and decide what else we want to keep.  Many small balancing changes can be left behind, as we will need a week or so on the new code to decide if they need to be re-buffed/nerfed
