### ISSUE TITLE
PDA icons missing

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1259]
PDA icons refuse to download(?) after installation on systems: Windows 7 and Windows 10 (past week experiences).
Only two icons missing from folder
Source:
[yogstation/icons/pda_icons/pda_exit.png](https://github.com/yogstation13/yogstation/blob/dev/icons/pda_icons/pda_exit.png)
[yogstation/icons/pda_icons/pda_chatroom.png](https://github.com/yogstation13/yogstation/blob/dev/icons/pda_icons/pda_chatroom.png)

![ss13-pda](https://cloud.githubusercontent.com/assets/16806055/15796362/ae486694-29fc-11e6-8fd2-f87d68fbfc13.PNG)

**Comment by Super3222** [comment]
Asset cache glitch.
