### ISSUE TITLE
Experimentation lab air issue

### ISSUE THREAD

**Issue by missatessatessy** [yogstation13/yogstation-classic#1261]
At every round start there's something wrong with the air in the experimentation lab that makes the temperature 0 degrees. If it's not the air it may have something to do with the air alarm.

![image](https://cloud.githubusercontent.com/assets/19648057/15805865/23ffb126-2b2e-11e6-9a15-ff40344eaaf8.png)

**Comment by Time-Green** [comment]
First few seconds of the round are weird. You got no name and your PDA is broken. 
Atmos hasn't been set yet, you can space yourself and have no damage

**Comment by missatessatessy** [comment]
It's like this for (from what i've seen) the rest of the round until someone goes in and turns on a heater etc,

**Comment by Time-Green** [comment]
That is very weird, I use it alot and that never happened.
Are you sure some idiot didn't blow it up?

**Comment by missatessatessy** [comment]
This happens every single round, as soon as round starts, i have sat there as an observer before round start and it's fine, but when it starts the alarm goes off, so.
