### ISSUE TITLE
Display robotics camera on science sec camera screen

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1263]
Science security can even watch genetics... but not robotics?

**Comment by ShadowDeath6** [comment]
Just walk like 5 tiles man

**Comment by 00aquir** [comment]
Yes and I should walk to R&D, Toxins, RD office etc. right (and they're on the camera screen)? Do you realize science sec has no access to  robotics and can't even see Mech bay in any way but via camera?
