### ISSUE TITLE
Abductor recalled out of cryo is stuck in a downed state

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#1265]
### Expected Behaviour

Be recalled out of cryogenics, stand up as if you were ejected.
### Actual Behaviour

Stuck in a downed state. Asleep/Unconscious. Cannot be shaken awake.
### Steps to reproduce the problem
1. Abductor agent sits in cryo, goes to sleep via cryo.
2. Abductor scientist recalls agent.
3. Agent is stuck in downed state.

**Comment by Super3222** [comment]
Can I ask, did you mark them from your camera view?

**Comment by Alblaka** [comment]
Did you try 'rest'?

**Comment by EMT321** [comment]
It was fully asleep. As in unconscious. The other abductor tried to shake me awake to no effect.

**Comment by Groudonmaster** [comment]
Did they try dragging the other abductor?

**Comment by EMT321** [comment]
No, though they were able to interact with my body via stripping.

**Comment by Groudonmaster** [comment]
Teleportation has always been an odd function. I believe the issue lies in that upon teleportation the game doesn't pick up that you've technically left cryo. Upon moving the mob should've had its stats reset to normal so if this occurs again that should fix it
