### ISSUE TITLE
Blob could use a more dramatic round end - From Dogar on forums

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#1266]
Blob is one of the best rounds imo, but the blob victory feels kinda anticlimatic, since the round just ends when the blob reaches some arbitrary size, without having achieved anything specifically. I think the mode might be improved a bit if the blob victory was similar to the nar'sie or shadowling endings, where the antags suddenly become super powerful and wreck shit up while everyone freaks out.

For example, maybe when the blob gains enough biomass for a victory, it evolves into some kinda suberblerb, doubling its point regeneration, or maybe all its factories start spitting out blobbernauts or god knows what else. The shuttle gets called automatically, people lose their shit, and the round finale turns into a desperate last ditch attempt to delay the blob by every means possible until the shuttle arrives. I've played blob rounds where the blob reaches the shuttle at the end, and it's usually been pretty fun on either side, and I think it would be cool if more blob rounds had that kinda finale.

**Comment by ghost** [comment]
I could implement this when we finish the rebase.

**Comment by Super3222** [comment]
Blob seeps into the space stations maintenance controls that keep it functioning, breaking every light, shutting down every source of power, and than the station begins falling into the orbit of one of the many nearby stars.

Everyone on the z level sees a bright light, even those in space get tangled up with the station, and a sharp sound of sizzling plays.

And if the clown is still alive you hear a honk.

**Comment by MacHac** [comment]
> station begins falling into orbit of one of the many nearby stars

From the temperature outside the station, it's probably in a jupiter-like orbit.  Jupiter is 40 light minutes away from the sun.  That's an impressive fucking burn there, Wernher Von Braun.

**Comment by Axemeaquestion** [comment]
The reentry would be enough to burn it.
