### ISSUE TITLE
Brass knuckles/ knuckledusters

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation-classic#1269]
I think that adding brass knuckles would be neat. They would be a gang item that would be small enough to fit in your pocket and would add a increase to knock out chance and brute damage.

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1089

@ToGWtF lmao

**Comment by FluffySurvivor** [comment]
you crushed his dreams
