### ISSUE TITLE
(regular) Satchel of holding

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#1270]
### Expected Behaviour

Look stylish while using your fancy bluespace pocket for storing items
### Actual Behaviour

Look ugly as shit with a giant fucking backpack on your back ugh-
### Hao 2 fix

Dead simple.
Sprite and add a Satchel of Holding.

Satchels of Holding function _exactly_ the same as Bags of Holding with _exactly_ the same cost. They just look far, far better because they're slung by your leg and not just some fugly box on your back.

**Comment by Cruix** [comment]
> not dragging all your stuff behind you in a personal locker and wearing a bedsheet cape

**Comment by ShadowDeath6** [comment]
Honestly I always thought satchels looked ugly, bluespace backpack for life
