### ISSUE TITLE
45,000 kpa caused by event.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1274]
Fulminant plasma event was unmanageable. Admin intervention was successful. SMES access: the door opening for just 1 second threw all lockers into the other side of engineering and almost killed engineer, even in the Eng access. Syphons: worthless

**Comment by oisin100** [comment]
Duplicate issue. I still stand by my stance of calling it a feature.

**Comment by 00aquir** [comment]
Why? It is simply not manageable. The pressure spreads through many rooms and even kill people who get pressed against walls, and you cannot even solve the problem by normal means, an admin was needed. Serves no reasonable purpose in gameplay.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
You could probably drain it by punching a hole into space... But I agree, this "feature" needs to be removed.

**Comment by Time-Green** [comment]
It's hilarious

> opens chapel door
> congratz you're now in south-america
