### ISSUE TITLE
Lings cannot regenerate inside of lockers

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#1275]
### Expected Behaviour

Be able to regen inside a locker.
### Actual Behaviour

Identical problem to: https://github.com/HippieStationCode/HippieStation13/issues/2307

**Comment by Cruix** [comment]
Hippie's regenerate code is different from ours. We do not have the isobj() check.

I cannot reproduce this locally. Were you killed or did you use statis to fake your death? Did it give you a fail message? Did the regenerate verb just not appear? Did you have a lot of genetic damage at the time? Could you possibly have had some zombie powder in you? Did you respec while dead?

**Comment by EMT321** [comment]
I was killed, and entered stasis. I was then placed in a locker and welded. It then said "you are ready to regenerate" , but I was unable to do so, and was unable to re-attempt regeneration as it said "you are already regenerating". I had to be admin-healed.
