### ISSUE TITLE
Horrorform Changelings can be stunned while in horrorform, if they were stunned before transforming.

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#1276]
### Expected Behaviour

Use Horrorform as a panic button when stunned.
### Actual Behaviour

Continue to be vulnerable to stuns in horrorform. Unknown if it extends to stamina damage as well.
### Steps to reproduce the problem
1. Be stunned in humanform (in my case, a taser)
2. Go horrorform.
3. Continue to be vulnerable to stuns in horrorform.

**Comment by ShadowDeath6** [comment]
Do you mean that you're able to be tased again after horrorforming or you're still stunned after? It gives hulk so if there was anything obstructing the mutation it won't give stun resist.

**Comment by EMT321** [comment]
I meant upon entering horrorform in stun, I was vulnerable to stunbatons for apparently the entirety.
