### ISSUE TITLE
New Drunk Effects

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#1279]
We could add an effect to being drunk where all turfs and mobs spin

**Comment by Time-Green** [comment]
![schermopname 245](https://cloud.githubusercontent.com/assets/7501474/16053402/ed1610d2-3268-11e6-9b50-5292d1ed7a8b.png)

**Comment by FluffySurvivor** [comment]
no

**Comment by Robertruler77** [comment]
No. No No no no.

No

No
No

No
                                                                     No

No.

Absolutely not.

**Comment by Super3222** [comment]
For a hell of a strong drink? Yes. It'd probably have to be a secret mix of different drinks for the bartender though.

This isn't a yes to making a PR of it though.
