### ISSUE TITLE
Cargo Circuit Board Broad Spectrum

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#1282]
### Expected Behaviour

Build a functional cargo computer.
### Actual Behaviour

Cargo computer disapears and leaves the circuit board behind.
### Steps to reproduce the problem
1. Grab cargo circuitboard
2. Use multitool to set circuit board spectrum to broad
3. Build computer

Reported by PitKid

**Comment by Super3222** [comment]
I'm currently fixing it, heh.
