### ISSUE TITLE
Remove racist Space Ninja accent

### ISSUE THREAD

**Issue by matskuman5** [yogstation13/yogstation-classic#1284]
Normal: The quick brown fox jumped over the lazy dog.

Ninja: Ze quicku buraun hu-huox jumped obe-ober ze razy-zy dog.

Stereotypical Asian accent, should be removed since

```
0.1: Do not be a bigot. We have players of different races, nationalities, religions, and lifestyles. We expect our players to be tolerant to people who are different from them in some way, and respect their choices. Do not use terminology that is considered bigoted or racist, or is offensive to a large group of people.
```

And yes I am a SJW shill :^)

**Comment by FluffySurvivor** [comment]
how is this racist ?

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I hate it and it makes it nearly impossible to understand what the ninja is saying. It should stay.

**Comment by Super3222** [comment]
I don't feel this is going to happen.

**Comment by Super3222** [comment]
I don't think this is going to happen.

**Comment by Robertruler77** [comment]
Make it randomly pick from like 10 languages and enjoy the tally ho ninja.

All roasted, equality.

**Comment by Groudonmaster** [comment]
Tally ho ninja please

**Comment by Robertruler77** [comment]
> Literally every sentence turns into a top hatted chip butty with a monocle and tea.

Come on, various accents would make it less bigoted if we share it around a bit.

**Comment by Groudonmaster** [comment]
Its not really bigoted but I'd love an English ninja. That'd be one hell of a time

**Comment by ToGWtF** [comment]
Turn on your mask and it both gives you the option to disguise your name  as well as remove the stupid language filter.
