### ISSUE TITLE
Request: Add in a Export Scanner for Cargo Techs

### ISSUE THREAD

**Issue by SKR6DarkVoid** [yogstation13/yogstation-classic#1285]
Did the code myself, would like to request that Cargo Techs spawn in with this tool.

`/datum/job/cargo_tech/equip_items(mob/living/carbon/human/H)
    H.equip_to_slot_or_del(new /obj/item/clothing/under/rank/cargotech(H), slot_w_uniform)
    H.equip_to_slot_or_del(new /obj/item/clothing/shoes/sneakers/black(H), slot_shoes)`

^ Old Code

New Code

> /datum/job/cargo_tech/equip_items(mob/living/carbon/human/H)
>   H.equip_to_slot_or_del(new /obj/item/clothing/under/rank/cargotech(H), slot_w_uniform)
>   H.equip_to_slot_or_del(new /obj/item/clothing/shoes/sneakers/black(H), slot_shoes)
>   H.equip_to_slot_or_del(new /obj/item/device/export_scanner(H), slot_l_hand)
> /*

The Export Scanner, tells techs the value of items, so its quite useful.

**Comment by Super3222** [comment]
They were initially suppose to start in the Cargo Tech's lockers, but I did make a lot of reversions in that PR.

**Comment by oisin100** [comment]
So why dont you PR it  @SKR6DarkVoid ;^)

**Comment by SKR6DarkVoid** [comment]
Would like some guidance so I'm not messing this up,

Which branch would it go under for a PR? @oisin100
