### ISSUE TITLE
AI camera view movement crashes

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1289]
As AI on the server with 24 players... It is one thing that AI movement is always laggier than human movement. but when I was supposed to track a single person... the game crashed and had to restart game 3 times in succession.. it doesn't matter if I have 6 gb of ram or whatever.. can't this thing be optimized in some way?

**Comment by Rocks4Free** [comment]
I've had the same issue before, admin bwoinks and too much radio chatter would also crash my game. Maybe try updating BYOND?

**Comment by 00aquir** [comment]
It doesn't matter if it's a completely reinstalled Win 7 , Win 10, old or new BYOND... The only thing I know is that 3-5 years ago there was no lag and crashes like this with the AI. That's why I'm asking.
