### ISSUE TITLE
Make singuloth actually lethal again.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#129]
Tiny baby singulo that goes loose, at worst eats the bottom half of engineering and leaves. It's so sad.

Singularity used to actually be round-endingly dangerous when it got loose. It ate most of the station. It still does do that, on TG.

Instead we have this stunted abortion of a singularity that inches slowly and at worst eats part of engineering. 

Make it lethal again so that it can actually path beyond engineering and eat more of the station. Loose sing should actually be dangerous, not some wimpy thing that farts off into space and dies

**Comment by X-TheDark** [comment]
I'm pretty sure the round-ending danger and the grief associated with it is the reason it has been nerfed into oblivion.

That being said, I DO think singularity needs some sort of a buff, at least increase the movement speed or something.

**Comment by Cruix** [comment]
Pull Request #131
If there is no singularity beacon on the map, the singularity will follow anyone named John Sweeps. Upon the singularity being released, there will be an automated Centcom announcement explaining this and authorizing the spacing of the aforementioned character.

**Comment by Super3222** [comment]
Yeaah. I'm with Adam on this one, our singulo is really nerfed. I can understand if it was nerfed on purpsoe due to grief or maybe it's because it was one of TG's many updates which we didn't integrate into our code.

We could easily balance this by changing the probability of singulo's collapsing when clowns interact with them to 100%.

**Comment by ghost** [comment]
Sacrificing the clown to the singularity becoming a common occurance would be great.

**Comment by BadminBen** [comment]
I have no problem making sing lethal again. But we have to give AI the ability to contact Centcomm in order to ask for BSA. Caps usually dont know/ too bothered to contact Centcomm about anything. so let the AI do it

**Comment by ghost** [comment]
AI can just make an announcement.

**Comment by Kmc2000** [comment]
Want

Make it big
Make it fast

MAKE IT LETHAL

Because atm if gets loose it just kinda flops around helplessly until engi decide to abandon ship

**Comment by DavidEdwards** [comment]
@X-TheDark Would you take this on? Sing could be programmed that, at each time it attempts to move, 33% of the time it will move towards the nearest undisturbed tile. That way, it will _always_ edge slowly towards some part of the station. Whilst also giving the appearance of randomness.

**Comment by X-TheDark** [comment]
Yes, I could try to see what I can do. I am worried about the runtime expenses of checking range/orange/view/oview stuff, though.

**Comment by Alek2ander** [comment]
Changing singulo behavior to /tg/ is a one line change

**Comment by X-TheDark** [comment]
How does /tg/ singularity's behavior differ from Yogs?

**Comment by Alek2ander** [comment]
/tg/ singulo is affected by space gliding, so it moves about 4 times as fast.
