### ISSUE TITLE
The Bluespace shelters don't work.

### ISSUE THREAD

**Issue by Wiebman** [yogstation13/yogstation-classic#1297]
### Expected Behaviour

You activate them, they make a shelter
### Actual Behaviour

You activate them, there's some smoke, then nothing.
### Steps to reproduce the problem

Click on shelter in hand, either throw on ground, or keep in hand. Nothing.

**Comment by ChangelingRain** [comment]
There's message feedback; they need a clear 5x5 area to open.

**Comment by X-TheDark** [comment]
Nah, we just didn't have the template, that's all.
