### ISSUE TITLE
Map Rotation or Map Change

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#130]
Honestly, I get tired of every server having a Boxstation style map. It's boring and not very fun to play every single round all the time. I would honestly like to have a Metastation type map be thrown in for the normal map to rotate with or even permanently replace because **fuck boxstation.**

**Comment by Hydre** [comment]
Box is too small for our high pop times and meta is too large for our low pop times

We really need a balance between the 2.

I've been taking notes of stuff that needs to be included in a map and gonna try making one myself at some point.

**Comment by shrimptk** [comment]
Thats the point of a rotation, meta on highpop, box for lowpop

**Comment by ghost** [comment]
map rotation reee

ministation for super lowpop
box for medpop
meta for highpop
ass station for if we're bored

**Comment by shrimptk** [comment]
I like it, but adaptations of said maps would have to be made for yog specifically because I don't want us to be just straight copying /tg/. Also, instead of just having the straight templates, making an actual **yogstation** would be pretty cool.

**Comment by McShooterJr** [comment]
Whats wrong with copying TG, we did it before and we were fine. Honestly the quality of the server has gone down since we seperated.

But yes, A map rotation would be nice.

**Comment by ghost** [comment]
Because if we're a carbon copy of TG with harsher rules, everyone will go play on TG.

**Comment by shrimptk** [comment]
Adam is right, we need to stay independent from /tg/ as much as possible. Given there are things that they have that would be great here, we can become just another /tg/ server or we'll end up like Bagil.

**Comment by Hydre** [comment]
> Because if we're a carbon copy of TG with harsher rules, everyone will go play on TG.

We used to be for a long time, uwot

**Comment by Hydre** [comment]
> Thats the point of a rotation

I'm a dumbass I thought you meant rotating box around, like literally rotating it

**Comment by shrimptk** [comment]
come on dude @Hydre

**Comment by shrimptk** [comment]
Something pretty cool that I didn't know until recently. On the /tg/ build of Metastation, the derelict is replaced with a bombed out and beat up version of Boxstation

**Comment by BadminBen** [comment]
Hmm you mean to say you want to build a whole new map!?!?! OH MUH IMMERSIONS!!! @shrimptk

**Comment by shrimptk** [comment]
@BadminBen fuck the system
