### ISSUE TITLE
Explosive Holoparasite Glitches

### ISSUE THREAD

**Issue by SirCodey** [yogstation13/yogstation-classic#1302]
### Expected Behaviour
1) When I click on an item to turn it into a bomb as a holoparasite, when undoing the bomb and picking it up it should turn back into the single normal item.

2) When turning a locker that someone is inside into a bomb, attempting to open the locker from inside should either cause it to explode, or open the locker.

### Actual Behaviour
1) When an item is turned into a bomb, if it is picked up as the holoparasite undoes the bomb effect it duplicates into one item that is the actual item, and another which is the bomb copy.

2) When turning a locker into a bomb, if someone is inside it they will be unable to open it at all, regardless of whether it has a lock or is welded. The second someone outside attempts to open it, it will explode as normal.

### Steps to reproduce the problem
1a) Become an explosive type holoparasite
b) Turn an item (such as an e-sword) into a bomb
c) As it is being picked up (by your master, presumably) undo the bomb, this part requires precise timing.

2a) Become an explosive type holoparasite
b) Have someone stand inside a locker and close it
c) Turn the locker into a bomb and watch as they're unable to escape.

**Comment by enailz** [comment]
https://github.com/yogstation13/yogstation/issues

**Comment by Time-Green** [comment]
HAHAHAHAHAHHAHAHH GOOD JOB CODEY YOU NOOB
