### ISSUE TITLE
Consolidated thread of issues, problems and plans.

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation-classic#131]
I think we need a place where current issues with balance/features that you think should be discussed in general and broad terms, rather than concentrating on a specific issue.
There might be a "General plans for the future" thread on the coder forum, but, hell, I'm not a coder yet and still would like to know the general direction Yogstation wants to go and the current issues people see with jobs/whatever on the server.

**Comment by BadminBen** [comment]
General section on forums

**Comment by X-TheDark** [comment]
Fair enough.
