### ISSUE TITLE
Donor PDA

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation-classic#134]
It would be pretty cool if donors got the limited edition transparent PDA either instead of their regular PDA or in their backpack with the hat.
![pda-transp](https://cloud.githubusercontent.com/assets/16780533/12536598/e41920de-c277-11e5-9c99-133587f0dbc7.png)

**Comment by shrimptk** [comment]
I agree with this, the sprite for the transparent PDA has been around for a long time, adding more sprites so donors can spawn with a transparent version of their own PDA would be a really nice feature that would go a long way.

+1 because its practical

**Comment by McShooterJr** [comment]
More donor items please. This looks cool and brings back that nostalgic feel of having a Gameboy Color or a  Gameboy Advance that was transparent.

**Comment by ghost** [comment]
+1.

I love the transparent PDA. It's fancy, and a harmless cosmetic that has no impact on the game aside from looking cool.

**Comment by X-TheDark** [comment]
Should it replace the one you have or be added to the backpack, though? I guess it makes sense to replace it rather than add, since, you know, 2 PDAs and stuff. PDA is a bit more important than some hat.

Also, should it be a preference or something that is done always?

**Comment by Xantam-13** [comment]
Transparent? That tiny image looks awfully botany-like. And I'd disagree with transparent?

**Comment by McShooterJr** [comment]
Hardy its transparent like the old gameboys, where the plastic is see through and you see the circuits and stuff.
