### ISSUE TITLE
Make lings zombie-immune

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#135]
Because it dicks with transforms, lings can't resist out with pancea or transform to avoid it and a random event that can instantly shit on everything is bad.

Please make lings zombie-immune, and naturally secrete the antibodies for zombie virus.

**Comment by Cruix** [comment]
Should Shadowlings and thralls and such also be immune?

**Comment by BadminBen** [comment]
Nah Zombies is suppose to be a end all. leave it so. would be weird to seen a guy just runniing around still human and when he gets swarmed Out comes the armblade

**Comment by ghost** [comment]
Lings are supposed to be immune as such.

Shadowlings are already immune, as they have their chitin coating, which blocks them being bit.

**Comment by Groudonmaster** [comment]
So if lings use their chitin armor they're immune. This doesn't need done.

**Comment by BadminBen** [comment]
Can this be closed?
