### ISSUE TITLE
Get the admin DB working

### ISSUE THREAD

**Issue by Xantam-13** [yogstation13/yogstation-classic#144]
If we can get the Admin DB working, we can integrate that into the website or even forum to manage the admins. It'd also be neater.

**Comment by Groudonmaster** [comment]
What's wrong with it right now?

**Comment by george99g** [comment]
It doesn't work with the database. We edit a text file with the ranks on the host.
We want it to be able to integrate with the forums.

**Comment by DavidEdwards** [comment]
Honk.
