### ISSUE TITLE
New Telescience Suggestion

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#145]
Note: Telescience does currently have many useful abilities, but for the purpose of this issue I am going to pretend that its only use is teleporting things around on the station z-level. 

The way telescience currently is has some problems. The fact that telescience uses polar coordinates rather than grid coordinates and elevation/power rather than distance means you have to use trigonometry, which is virtually impossible for most people to do without a calculator. Add in the random offsets, and it's almost required to have a specially made telescience calculator. Of course, using a telescience calculator is against the rules, but telescience is so damn useless without one that no one seems to care. In addition, there is the issue of a metagaming telescientist being able to teleport their steal objective out with perfect accuracy using a telescience calculator and a table of high-risk item spawn locations.

Telescience, as I understand it, should operate by the following rules:
-The range of the teleporter should be limited by some rare resource (currently bluespace crystals).
-To use the teleporter accurately, you should have to perform some sort of mathematical calculation based on the result of using the teleporter multiple times. This should be simple enough to easily do with, at worst, a standard four-function calculator.
-Telescientists should not be able teleport to or from exact coordinates without one of the following:
    -seeing exactly where an object is in character, with a device (such as a gps) in their hand.
    -trial and error in a general area with the teleporter.
    -exact coordinates from something, such as suit sensors.

Here is a suggestion for a new telescience system.

The teleporter's coordinate system will be changed from polar to grid coordinates, making calculations much simpler. The maximum range will remain very similar to what it is now, and can be upgraded by using items created with telescience research (more on that later). At round start, the z-level will spawn "warp nodes". These nodes will have a type, a radius of effect, and a "frequency". Most tiles on the map will be in the area of at least one node. Some space-bending effects, such as anomalies and the singularity, act as nodes as well.

There are several types of nodes. Each translates the coordinates of a teleportation in its area of effect. Some types will translate the coordinates in a particular direction, some towards the center of the node, others away from the center of the node, etc. Depending on the node, it can translate the coordinates anywhere from one to six tiles away. If admins are worried about telescience abuse in a particular area (i.e., the armory), they can spawn a node that changes the coordinates randomly, and differently each time, making it nearly impossible to accurately drop bombs or steal items from that area. For simplicity, a single teleport will only be affected by one node at a time, usually the most disruptive one it is in the area of effect of.

This would, in some cases, make certain tiles unreachable by the teleporter. To counter this, there will be an additional "frequency" setting, with a large number (perhaps 50 or so) settings. If the frequency of the teleporter is exactly that of the node, the distance that  a node alters teleportation coordinates is reduced. Naturally, the randomness nodes that protect valuable areas are immune to this. The job of a telescientist is to map out the nodes on the z-level, discovering their type, radius, and frequency.

The nodes will also provide a research opportunity, probably bluespace, but possibly its own category. The protolathe will be able to print "space-curvature analyzers", which can measure the curve of space in their tile and tell you exactly how far and in what direction teleporter coordinates will be altered. By using the analyzer on the center tile of a node, it will produce an item for the destructive analyzer or fill a research disk. Nodes created by effects such as anomalies or the singularity cannot be analyzed. At a high research level, the protolathe can print a device that, on a timer, makes a small node that stabilizes the area around it and allows for perfectly accurate teleports there for a short time.

Perhaps with an advanced enough teleporter, you could even teleport the singularity. Once. Into maint near the escape shuttle, where it would promptly eat the teleporter and everyone waiting patiently to get on the shuttle. Or you could go the boring route with two bags of holding and an autocloner.

Please discuss. Better names and numbers are welcome.

**Comment by BadminBen** [comment]
Hmm seems extremely complex and the current T science system will have to be scraped. the thing about this new system is that it makes T science much more random (which i like) but also it borders on the same complex set up (which i also like). Science should be about exploring and observing which the game doesnt really project too well in terms of discovery to my liking. If you can figure up a rough draft of this system and present something please do.

**Comment by X-TheDark** [comment]
What will this even change? I mean, look at EXPERImentor thing, noone ever uses it, why would they use your new Telescience for research? I just don't see the function of it.

**Comment by krgii** [comment]
There's several tools to make this simple. I'm able to use it as it is so I'm biased against changing it, but I don't think it needs changed.

**Comment by DavidEdwards** [comment]
Alek is currently doing an overhaul on Telescience.

@Alek2ander : Linking you, incase you find any of this suggestion useful.
