### ISSUE TITLE
Bug with Ian (Possibly all critters?)

### ISSUE THREAD

**Issue by CactiCactus** [yogstation13/yogstation-classic#147]
I play the Head of Personnel a lot, and I've noticed the last day or two that Ian can walk into my airlocks. I first noticed it when I got a message in chat saying someone was petting him, but I was alone in my office. He had walked into the south airlock and other people could apparently see him. I've also seen him walk into the north airlock. I haven't been around other critters to see if this is an Ian-only issue or not, however.

**Comment by Groudonmaster** [comment]
Intentional. See PR #115

**Comment by CactiCactus** [comment]
I see. Thanks!
