### ISSUE TITLE
Traitor Chem Bundle

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation-classic#151]
We should rename Venom in the traitor chem bundle to McShooter. Because he's too toxic.

**Comment by Stealthkibbler** [comment]
yes

**Comment by ghost** [comment]
I'm going to step in here and say no.

Funny meme PR's are one thing.

Don't deliberately code an insult into the game. It's not funny or original, unless the player themselves agrees to it.

**Comment by McShooterJr** [comment]
Its not an insult, I agree with it. Its funny. My name is Venom in teamspeak and I have a Toxic Icon. Its pretty 10/10

And it is pretty Funny and its pretty Original.

**Comment by BadminBen** [comment]
Closing this
