### ISSUE TITLE
Space vine event doesn't trigger.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#152]
Vines no spawn. 

RIP vines.

Step 1. Trigger vine events.

Step 2. No vines.

Step 3. Drink self unconcious and bitch about your ex leaving you.

**Comment by shrimptk** [comment]
fuck your vines, and your ex

**Comment by BadminBen** [comment]
Vines were disabled. because of the memes

**Comment by ghost** [comment]
nooooooooooooooooooooo!!!!

whyyyyyy

New issue-Re enable vines

**Comment by BadminBen** [comment]
make the New issue so i can close this one

**Comment by george99g** [comment]
Closing this.
Make an issue for re-enabling when you want to.
