### ISSUE TITLE
REMOVE REVOLUTION.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#153]
IT's SHIT.

NOBODY LIKES IT.

NOT SEC.

NOT THE HEADS.

NOBODY.

IT'S A SUPER SHORT SHITTY ROUND OR A LONG DRAGGED OUT GRIEF FEST, IT'S CULT WITH NO INTERESTING MECHANICS, AND IT'S A HIGHPOP CREW AUTOVICTORY OR A LONG DRAWN OUT 'CE HIDES IN HIS AUTISM FORT IN SPACE.'

EVERYONE PLAYS IT LIKE IT'S GODDAMN COUNTERSTRIKE.

ALMOST NO SERVER HAS IT ANYMORE.

REEEEEE REMOVE REV REEEEEEEEE

**Comment by shrimptk** [comment]
calm down

**Comment by Groudonmaster** [comment]
Holy shit what. I like Rev thank you. It's fun and relatively easy especially when you can open fire as a head.

**Comment by ghost** [comment]
let's just go over it, shall we

it's a long, drawn out snorefest
or it ends in 10 minutes

it's always a nightmare and barely fun for sec to play at all

nobody likes being CMO/RD for fear of rev

it turns into a giant grieffest fairly soon

it's hardly balanced at all with easy conversion mechanics but very very slow deconversion mechanics

gang is basically rev, fleshed out

cult is basically a slower rev

this is just,

heads can turtle/hide somewhere and stretch it out

or it ends in 10 minutes

it shouldn't even be out of concept stage, tbh

i've seen admins outright log off because it's rev

**Comment by ghost** [comment]
just held a vote

'Remove revolution' won 

Following behind it 'It needs changing'

Finally 'keep it' was at the low minority

evidently, playerbase dislikes it

**Comment by Hydre** [comment]
Instead of removing it which is a bad idea, we could just remove any kind of metashield there is against revs

**Comment by B1gb3ast** [comment]
Or leave it as it is because heads of staff win as often as revs.

It's fast paced, so is nuke ops.

It can also be slow paced, so is blob.

What's the problem?

**Comment by Hydre** [comment]
The problem is that on high pop rounds (as in 60-70-80 people) there's about 30-40 revs within the first 10 minutes of the round assuming the revheads know their shit.
That's a guaranteed win for the revs

**Comment by Groudonmaster** [comment]
If we remove the metashield though we'll have shitlers running around flashing random people just for the luls and seeing people scream rev.

**Comment by X-TheDark** [comment]
Would reducing the cooldown of the flash be an option? But that would basically make the game be shittier gangs (since you only get 1 gang (revs) and can't buy your revs converter flashes).

**Comment by ghost** [comment]
It's already shittier gangs.

On highpop it's a storm of 70 assistants and an instant win for heads.

The amount of prayers and people screaming 'it's rev fuck i hate it' is insane.

Seriously, the vote against rev won 9/8/5 for Remove it, Change it, Keep it

It's not fast paced like nukeops-It's either a ten minute victory with no counter against the tide wheras you can fight nukeops, or it's a one hour thirty minute round of hunting for the fucking CE hiding in space with his dick up his ass.

**Comment by BadminBen** [comment]
I suggest just putting in a timer on flash. Like gang pen, easy fix to give sec and heads a fighting chance. If heads are hiding out Revs if they have the caps ID can ask for "locator services"

**Comment by Kmc2000** [comment]
Replace this shitfest with predators when?

**Comment by ghost** [comment]
Held another vote.

Remove rev won 20/5. 

NOBODY LIKES REV

**Comment by DavidEdwards** [comment]
I am extremely against removing content, especially when that content is
workable. I was against removing gangs, and I am against removing rev.

If there truely is a problem with rev (as indicated by your poll), then we
need to brainstorm what the problem IS then devise a solution to fix it.

Unless there is a council vote to the contrary.

**Comment by george99g** [comment]
> Unless there is a council vote to the contrary.

There have not been any council votes regarding this.

**Comment by DavidEdwards** [comment]
I meant unless there -will be- a vote. Not if there had already been one.

**Comment by Super3222** [comment]
A council vote (or maybe a community vote?) would make it final on whether or not to remove this mode. Honestly it'd be sad to see it go, but give me more relief whenever I play as a head role.

Though the days as HoP gunning down revs with combat shotguns will never be forgotten.

**Comment by Groudonmaster** [comment]
I think we should just add a delay to the revhead flash.  It'd balance it out and we wouldn't have to remove an entire gamemode because Adam is a saltmine.

**Comment by DavidEdwards** [comment]
OK - council vote clearly indicates Rev stays. We are open to suggestions for improvement however. Small improvements. I will be closing this issue. Please move any improvement related suggestions from this issue into this forum thread: http://forums.yogstation.net/index.php?threads/vote-removal-of-rev-gamemode.9092/ or happily create a new issue for improving Rev.
