### ISSUE TITLE
Gateway Destinations collab.

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#154]
Sup my dudes, this post separate from #76 so we can organize collaborations for gateway locations unique to yogstation. So to start, I have myself and @BadminBen currently working out some things on the mapping side, with a few other people not officially taking part. What we need are people to give ideas, balancing, and **spriters.** So far we have a few general directions to take this, and if you want to hop on in go for it my dude.

Meme list:

> Underwater Nanotrasen Base after a syndicate raid, complete with Hostile syndie NPCs, dead staff, and moderate loot, with the potential to be revamped and recolonized.
> 
> Some Prison/Station post riot/revolution full of dead guards and Hostile prisoners (Courtesy of Father)
> 
> Nice beach with a minibar for the peace lovers, and a jungle dungeon just to the north full of man-eating plants and the sweetest of loots
> 
> Another Station, with NPCs that are friendly and have dialouge

**Comment by Cruix** [comment]
For the underwater base, we could make water behave like a fast-spreading gas that suffocates and deals pressure damage. We would also need some way to remove the water once it floods in. We would also need some way to deal with people dicking off into the depths of underwater. Maybe just have a special z-level that is just infinite water, with all the sides connected to each other, and only a very small chance to send you to the underwater base z-level whenever you hit a seam.

Luckily there is absolutely no way that messing with atmos code could horribly break the whole server.

**Comment by shrimptk** [comment]
@Cruix I like the gas concept, and portable pumps that act like scrubbers could be used to get rid of it

The mission is designed to be super deep sea, so high pressure and of course not being able to fucking breath. I want someone to sprite a bioshock style suit for going into the depths and getting that sweet loot.

**Comment by X-TheDark** [comment]
I mean, we could just replicate the atmos thing by literally filling the entire map (except the areas) with extremely high pressure tiles, although that would probably bring atmos system to it's knees, unless there's very little space between station/z-wall.

**Comment by Hydre** [comment]
> Luckily there is absolutely no way that messing with atmos code could horribly break the whole server.

Yeah.........

**Comment by B1gb3ast** [comment]
_steven universe memes intensify_

**Comment by ParagonPrime** [comment]
Maybe make it so regular space suits don't work underwater, so you basically need a HARDSUIT to go down. Yet, even so, you'd be slowed by all the pressure- so perhaps spriting and coding a submersible that works kinda like goon's pods?

**Comment by shrimptk** [comment]
@ParagonPrime  wew, ask cruix and the lads if you want this stuff

**Comment by BadminBen** [comment]
the thing is we need help, Ideas are amazing but if no support then this will be just a pipe dream

**Comment by shrimptk** [comment]
@Kmc2000  WHERE YOU AT BOY

**Comment by shrimptk** [comment]
the dream is dead because Cruix wont code water physics

**Comment by Cruix** [comment]
I did not say I wouldn't. I just won't right now.

**Comment by shrimptk** [comment]
EUGH

**Comment by Kmc2000** [comment]
Poke me for sprites, I can do some smexy enememes and tilesets
@shrimptk 

AND A GIANT ASS MOTHERFUCKING SUBMARINE FOR GOOD MEASURE

**Comment by shrimptk** [comment]
@Kmc2000 Final area in caves dungeon will be a abandoned naval submarine with all the loot your heart desires

**Comment by shrimptk** [comment]
I plan on having the monsters be your typical sea monster type fishman, and space sharks, and of course Syndicate Commandos with their own pressure suits

**Comment by DavidEdwards** [comment]
Overall, I am behind the concept.

I was a big fan of BioShock ;-)

Care needs to be taken in implementation. It might be possible to reuse the atmos subsystem.

Something to bear in mind, is that the mechanics for space and water in the event of a breach will be different. Water will push in, whereas for space, air will be sucked out. That will immediately cause issues when attempting to imitate the function of atmos.

I find the concept intriguing through. I think the players would enjoy the change.

**Comment by Kmc2000** [comment]
@shrimptk 

So do you want a giant ass subramine sprite that you put rooms in then?

And fishpeople and syndicate commandos?

Just to clarify

**Comment by Greatbigben** [comment]
@DavidEdwards could we possibly make it so the outside pressure is higher then the inside?  That way it will flood into whatever breach is made. Only thing im concerned about is the push back that will happen from such a breach.

**Comment by shrimptk** [comment]
@Greatbigben Yep, that was the intention. I don't want water flooding this thing completely the second a breach happens, so I might set it to where air alarms activate blast doors on the exterior of a room when a breach happens

**Comment by Cruix** [comment]
I've got water to work as an add-on to the atmos system. I've also made a new turf for ocean tiles that constantly gives off water. Now I need to figure out how to do pressure calculations with it, since PV=nRT won't work for liquids.

**Comment by Greatbigben** [comment]
Excellent thanks for the support

**Comment by shrimptk** [comment]
@Cruix Pressure outside the station should be constantly high, and the windows on the interior when broken aren't floor to ceiling, so the water won't fill up enough to do any pressure damage or suffocation, but will slow people down dramatically. I also plan on mapping in automatic blast-doors to close soon after a breach, with a minor delay

**Comment by Super3222** [comment]
@shrimptk @Cruix 

Thought of something interesting. On the map that's basically all sea, make a mob called Cthulhu that attacks anyone they see within an 8 tile range and can't leave the z level (similar to the nukedisk, will be re spawned somewhere)

**Comment by shrimptk** [comment]
@Super3222 Alright, calm down there Satan
