### ISSUE TITLE
Add "Welcome to Lunar Industries" as a new lobby theme

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#155]
(https://youtu.be/_lAfMT5FIZE)

So, the theme song of Moon is hauntingly appropriate for an SS13 theme song- it just sounds fitting, never mind the fitting plot of it. The length is relatively good (I even tested it out) for the pre-game sequence as well, and it just creates some nice haunting atmosphere.

Also, we kinda need a bit more variety in our lobby music, so there you go.

Implement pl0x!

**Comment by george99g** [comment]
Do keep in mind that the size of the resources everyone needs to download increases with every song we add in.

**Comment by ParagonPrime** [comment]
Then perhaps we could remove that third lobby theme that almost never plays with this one? And in any case, as the community voted in favour of adding new music... why not this one?

**Comment by X-TheDark** [comment]
This may need to be edited to be shorter before being added.

**Comment by george99g** [comment]
> Then perhaps we could remove that third lobby theme that almost never plays with this one?

Regarding that, it actually never ever played. #157

**Comment by george99g** [comment]
A council vote regarding this is now underway.

**Comment by george99g** [comment]
Council vote passed.
A trimmed version was added to #157 and merged.
Closing this.
