### ISSUE TITLE
Station's random name not displayed in window (for cargo papers)

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#156]
Cargo crate papers require checking the randomized name of the station, which is not visible after a certain update.

**Comment by Axemeaquestion** [comment]
I'm an avid cargonian and I support this

**Comment by DavidEdwards** [comment]
@Groxic Perhaps you could take a look at this one?

**Comment by ghost** [comment]
Where is the randomized name supposed to appear? When did this start happening?

**Comment by 00aquir** [comment]
It appeared in the very top bar of the window next to the icon. It's just displaying "Space Station 13" for one-three months now instead.
