### ISSUE TITLE
Defibrillator paddles stuck to hand

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#159]
Details: People were on the floor after an explosion, one of them had defib belt. Double paddles were on the floor, two of them. I examined them and prepared for the worst. I picked up one "double paddles" then tried to remove it with the defib belt on, then off me. Nothing worked, so I picked up the other one for fun and became the paddle-man.

![ss13-paddles](https://cloud.githubusercontent.com/assets/16806055/12596808/06bc62de-c482-11e5-8008-6c2df8e2484d.png)

**Comment by BadminBen** [comment]
A issue was made about this before. to solve this you have to pick up a defib and attach the paddles back or have a admin intervene and make you drop all

**Comment by DavidEdwards** [comment]
@Super3222 Could you investigate this bug?

**Comment by AsV9** [comment]
I've tested this and I can confirm this bug. I'm a bit too tired to look into it now, but I'll see if I can make a solution.
