### ISSUE TITLE
Ai turret settings cannot function

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#16]
opened by David Edwards · 3 months ago
http://forums.yogstation.net/index.php?threads/ai-turret-settings-cannot-function.7331/
Normally you could set the turret to target only non-security or non-command people, or people with weapons, etc. non of these settings are functioning for AI since forever. Would be great if it worked.

**Comment by TehFlaminTaco** [comment]
Why is this in the bug tag? Isn't this technically a feature request?

**Comment by george99g** [comment]
Added it as it was on the issue tracker on gitlab.
