### ISSUE TITLE
Nuke Ops item port from tg as well as modifications

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation-classic#160]
1. Proposal to port "Reinforcement" item that spawns an additional nuclear operative without items (Cost = 25TC or more/less)
2. Port the "Announce Attack" item from /tg/ that sends a global announcement about an attack that delays shuttle by 15 minutes (or more/less) but gives additional TC (to be debated).
3. Reduce cost of Syndicate Cyborg to 60 TC as noone ever uses that thing.
4. Cyborg LMG - currently you get 1 bullet every 5 seconds. Should this be buffed?

**Comment by Hydre** [comment]
> Reduce cost of Syndicate Cyborg to 60 TC as noone ever uses that thing.

That thing is rather OP, I even think we have it removed if I'm not mistaken

**Comment by X-TheDark** [comment]
Negative, Syndiborg is a buyable item that never gets bought normally (I mean it's like what, 60-80% of what syndicate start with (fluctuates with player count)).

I rather feel the LMG takes way too long to reload. 1 bullet per 5 seconds is harsh...although I guess it has so much other stuff (e-sword and a non-working grenade launcher that I just fixed). That being said, I totally can see how a competent syndiborg can be a devastating asset.

Wonder why people don't buy them...maybe it's the "we don't need another flukeops" attitude, you got plenty of failure potential with 5 operatives already, perhaps people are afraid their investment will be for naught?

**Comment by ghost** [comment]
Syndieborg is fairly weak, to be frank.

It has all the weaknesses of a normal cyborg except easily identifiable. An AI can cuck it by killing APC environment and locking it in, it can be flashbanged/ion rifled/flashed, ect.

It has an LMG that recharges slowly and cannot be used in anything more than 1v1 reliably, an energy sword that can't be used in close range combat without getting flashed, a grenade launcher that doesn't work (this is being fixed) and that's it, combat wise.

Once the LMG and grenades run out, you're dicked, due to low recharge time for LMG.

It's also 80 TC, which is wayyyy too high for something of that level-ops can buy complete stun immunity/laser/disabler immunity and a stamina-stunlocking 3 round burst easy-to-reload gun that also fires grenades for a combination of 30 TC.

**Comment by X-TheDark** [comment]
I guess I could make it flash-proof, as well as decrease damage from ion weapons and/or decrease/remove the stun effect so you can't stun it.

Your opinion matters guys! I will not start implementing this until we have at least a consensus on some of the features (if the announcement/reinforcement can be ported, please say so, perhaps I can port points 1 and 2 first and then implement features 3 and 4 at a later date).

**Comment by ghost** [comment]
'I guess I could make it flash-proof, as well as decrease damage from ion weapons and/or decrease/remove the stun effect so you can't stun it.'

UNSTUNNABLE BORGS

GOOD FUCKING IDEA

THAT WON'T END IN PAIN 

i'm saying because syndiborg is wimpy as shit it's cost should be 60TC

**Comment by X-TheDark** [comment]
Fair enough. I'll just port the 2 items in question first and then, perhaps at a later date, everything else can be balanced.

The one thing I do plan on changing is to **make challenge mode always available** (instead of needing 50 players minimum). To balance this, I plan to implement scaling TC given. Right now I plan on using the /tg/'s baseline 5.6 TC per player (280 for 50 players - which is the minimum you need on tg) on the server up to the nominal 280 bonus TC (maximum bonus TC I plan on giving right now).

**Comment by Super3222** [comment]
This is one of the features from TG that I'd enjoy seeing the most on Yog. Thank you for introducing it, @X-TheDark 

One other thing about the changes, I think that making the challenge mode avaliable **always** would create a few problems. Imagine a low pop round where a few civilian roles are taken, maybe a CMO or so. Everything is going fine, and a few people go braindead and than WHAM. The announcement pops up and everyone begins running around screaming. They will run around shitting them self while a dangerously armed nukeops team gets ready to raid the station.

My point is, the challenge mode is only great when there is an efficient / fair population of crew members. It'd be fine if you could lower the amount of participants (of the round) needed in order for them to activate the declaration of war, possibly 25~? That's just my input.

**Comment by X-TheDark** [comment]
Yeah, that does sound fair, but you have to keep in mind you still need 20 players for the gamemode to be considered for the rotation. I'll probably make it as you suggest, 25-30 players for now.

**Comment by X-TheDark** [comment]
A SYNDICATE BORG CURRENTLY COSTS 120 TC! WHAT? (Found out during challenge port test)

The 3.point was based on my assumption that the Syndicate Borg costs 80 TC...but damn. Like, seriously, that's only 20 TC less than a Mauler mech...what?

**Comment by george99g** [comment]
Implemented in #177
