### ISSUE TITLE
Make Chef's Fridge Nuke Resistant

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#163]
It wouldn't hurt balance, and seeing 20 people try to cram into a fridge would be pretty funny.

**Comment by shrimptk** [comment]
> wouldn't hurt balance

funy meme!!1!

**Comment by Kmc2000** [comment]
Kek, as much as I would love an indiana deathmatch, MUH FUKKEN BALANCE

**Comment by ghost** [comment]
Round ends when nuke goes off.

I don't see an issue with this.

**Comment by DavidEdwards** [comment]
Wouldn't this mess with round end green text for some people? Would the
fridge people count towards survivors?

**Comment by ghost** [comment]
If nuke goes off, it's 1 of 3 antag types w/o admin intervention atm-

malf, which wins regardless of nuke going off if timer wins
nukies, which win if nuke goes off and blows up station and they ren't on it regardless of survivors
blob, which if exceeds 1hr something minutes goes plooie

there's nothing else to green BY, unless an admin gives a wizard or traitor or something destroy the station, wherein they'll either make it to mining or die anyway

**Comment by krgii** [comment]
What about die a glorious death?

**Comment by Super3222** [comment]
> What about die a glorious death?

I don't recall admins freely handing traitors the nukecodes so they can ruin everyone's round from a nuclear blast instead of pizzabombing them self with the clown under them.
I also don't recall glorious death meaning you have to kill everyone on the station..

**Comment by Groudonmaster** [comment]
I occasionally do it because what's more glorious than killing everyone with you?
