### ISSUE TITLE
Janitor PDA

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation-classic#164]
It would be cool if the janitor's PDA worked like a bar of soap in being able to clean up messes. No need to slip people, just clean.

**Comment by shrimptk** [comment]
+1

nice

**Comment by Cruix** [comment]
While we're at it, could we make the botanist's PDA have a cartridge that makes it a plant analyzer? That's one less item they need in their inventory while working, and they still need a lot of stuff.

**Comment by Super3222** [comment]
Wait... what? A PDA that cleans up messes... what.

> could we make the botanist's PDA have a cartridge that makes it a plant analyzer

I believe that this can be done, like how medical doctors PDA's have built in health analyzers which can be toggled.

**Comment by krgii** [comment]
> Wait... what? A PDA that cleans up messes... what.

It's the future. And on tg chem they have drying agent that can be poured on galoshes to make them absorb water. Maybe the janitor's PDA just has a layer of soap around it.

**Comment by Greatbigben** [comment]
New clown Pda?
