### ISSUE TITLE
You're gonna love this one

### ISSUE THREAD

**Issue by Hydre** [yogstation13/yogstation-classic#165]
New chemical item: suppositories

Max amount of units: 75u

Keks had when shoving 75u of salt up a prisoner's ass: millions

**Comment by X-TheDark** [comment]
What happens if you overdose?

**Comment by george99g** [comment]
So, basically a giant hypospray that only works on naked people?

**Comment by Hydre** [comment]
A pill that only works on naked people, not instant

**Comment by X-TheDark** [comment]
Basically a pill for the butt for literal ASSBLAST USA.

**Comment by Kmc2000** [comment]
Just fucking add it now already, jesus

**Comment by shrimptk** [comment]
+1 Actually used irl, and pretty funny for chatlogs

**Comment by krgii** [comment]
Better idea. Bluespace suppository. Put anything in the pill and it doesn't react until "ingested" by the person. Literal ASS BLAST USA.

**Comment by Kmc2000** [comment]
Oh god, I love it @krgii

**Comment by Greatbigben** [comment]
im not even gonna support this

**Comment by shrimptk** [comment]
+1 to Kurugii because this gave me a few ideas

**Comment by ToGWtF** [comment]
Oh god its happening
