### ISSUE TITLE
Add a tooltip to sleepers.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#167]
Mousing over the sleeper buttons should provide a description of what they do, treat, and their overdose levels.

To prevent shitty med from pressing every button and killing a clown with morphine OD.

**Comment by X-TheDark** [comment]
Sounds like something that's pretty useful.
Perhaps we could also add some sort of limiter that prevents people from OD'ing patients on drugs using the sleeper (unless emag'ed?).

**Comment by ghost** [comment]
No, because forcing antags to not be able to OD people in sleepers unless they have a traitor-only item is shit.

Emagging a sleeper should make it automatically inject the maximum amount of chemicals into whoever's in it, until screwdrivered.
