### ISSUE TITLE
CentCom space has moving stars (teleport) around shuttle at end of round.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#168]
At the end I was moving toward the CentCom doors and windows right from the shuttle but a breach pulled me a bit, and boom, I teleported from an enclosed space.. into empty space.

**Comment by ghost** [comment]
whoever mapped centcomm added moving space because it looked swag
what they forgot
is that

it teleports you into space

**Comment by Xantam-13** [comment]
I did it.
I didn't forget it teleports you. 
Stay in the shuttle, or drift away into space. It's more realistic :)

**Comment by 00aquir** [comment]
The "moving stars" section is always linked to pods / shuttle  that are moving.. represents only that. And it teleports you even from a closed space, it doesn't really make sense.

**Comment by Xantam-13** [comment]
I don't believe for a single second you want this reverted because "it should only be for pods or shuttles". What is the real reason?

**Comment by 00aquir** [comment]
The previous one was my main argument for why it doesn't even fit into the usage of this type of area in the game. The reason I disliked it was that I was right at the door of CentCom, and boom, this area which doesn't fit there logically teleported me into empty space, and couldn't finish the process.

**Comment by ghost** [comment]
It's somewhat illogical that at centcomm it spaces you.

**Comment by shrimptk** [comment]
He has a point, I feel CC should maintain -some- realism. For the central NT operating base it shouldn't be loaded up the ass with memes and other random garbage just because it looks cool.

+1 Because its logical

**Comment by Greatbigben** [comment]
I support the revert

**Comment by AsV9** [comment]
:ok:

**Comment by ghost** [comment]
Shrimp is mapping this to revert it.

**Comment by 00aquir** [comment]
um.. any reference?

**Comment by Groudonmaster** [comment]
I don't think Shrimp is doing any more mapping. Reopening for comment.

**Comment by oisin100** [comment]
Please revert or make the tiles not teleport objects. I want to be able to summon Lord Singuloth without it disappearing into space.
