### ISSUE TITLE
Poster transformation bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#170]
The most terrible bug ever for any spessman.. Once you abort (or someone (like security) makes you abort) putting a Nanotrasen poster onto a wall (you walk away while applying it, etc.), it changes and looks like a contraband item both in its color and description.

![ss13-posterbug](https://cloud.githubusercontent.com/assets/16806055/12641613/bd9b706a-c5b0-11e5-84de-ae9d7016a6bf.png)

**Comment by george99g** [comment]
While someone's at it, could they also fix the "it's" to "its" on the Nanotrasen one?

**Comment by 00aquir** [comment]
This bug has changed now. After the fix, the Nanotrasen poster only turns into a red one after someone removes it from the wall with a wirecutter.
