### ISSUE TITLE
Less eyebleedingly atrocious sith gear

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#171]
IF SOMEONE HASN'T ALREADY ADDED THIS

DO IT

I wanna be able to use the sith stuff again

https://drive.google.com/file/d/0B9VUbibptgF2VmI2TkxmVllYMjA/view?usp=sharing

**Comment by DavidEdwards** [comment]
Did you make sure to double-triple-quadr... that the DMIs correctly match up on the body when worn?

**Comment by Kmc2000** [comment]
That's the whole point of the thing, so yeah

**Comment by DavidEdwards** [comment]
You say that, but remember the donator hats :grinning:

**Comment by krgii** [comment]
#161 

Like this?

**Comment by DavidEdwards** [comment]
That was partially my fault there. I OKed the final DMI.

**Comment by Kmc2000** [comment]
Yis, yis it is

And yeah the donator hats were my first attempt at making clothing, DON'T JUDGE ME
