### ISSUE TITLE
Rework ling.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#172]
Ling, as it is.

Is fairly terrible.

It's a stealth-based transformation antagonist with no reason to transform and hilariously overpowered abilities.

It's not even supposed to absorb people seeing as it has DNA sting.

Let's rework it.

Firstly, remove DNA sting entirely. Make absorption the only way to gain DNA, as it was prior, and as is proper. Or, alternately, make absorption the only thing that counts toward DNA objective.

Secondly, rework abilities. Ling has almost no stealth abilities that aren't grossly overpowered or scream 'I AM LING.'

Make abilities function and get stronger based on absorbing. The more absorptions, the stronger a ling gets. Fleshmend lvl1 might be weak, but fleshmend lvl4 will heal you right back up from -99 health to 100. 

Keep armblade, but remove shitty chitin armor/chitin shield because that shit is overpowered.

Render a ling completely naturally immune to space, or disease.

Lings should be exceptionally weak to fire, a la the thing. They should take double damage from it, and changeling abilities like fleshmend should be disabled.

Ling abilities should also be unlockable the more DNA you have. Make mutesting loud at lower levels-You get the tiny prick message-And with enough DNA absorbed, becomes entirely silent.

The flesh-transform abilities we have right now are good.

Hallucinogenic virus sting is already acceptable as is. The enfeebling sting should be made non-subtle in it's entirety- A message like 'X's hand grows a dripping needle and they jam it into Y's neck!' . It becomes less of a 'STING IN PUBLIC I'M TAKING HIM TO MEDBAY LOL' thing.

Make transforming non-subtle. It should display a fairly obvious message to anyone in 3 tiles.

Remove dissonant shriek, but keep resonant shriek, and remove the downside to using it that scrambles genomes-make it cost the DNA system I'm going to mention up ahead.

Ling abilities, rather than being powered by chemicals, should be powered by DNA.

Some, like transforming, should cost no DNA at all.

Others should cost between 4-20 DNA to use.

Absorbing a human should yield 40 DNA if they were alive.

Absorbing a human that was already dead should yield 20 DNA, as a way to encourage actual agressive hunting.

As to how to detect a changeling-

Their body temperature should be about 60 degrees on a medical analyzer.

Putting their blood in the pan-demic should reveal xenobiological pathogens are in the blood.

Heating the blood should force it to react to heat, a la the thing, literally leaping out of the beaker and scurrying away.

Changelings should have a variety of different organs-Organs for healing, organs for better sight, stingers, et cetera, all of which should be surgically removable and implantable into humans for actual abilities. Depending on what abilities a changeling has chosen to buy with their DNA, those new organs grow.

For example, a default babbyling who just got caught would just have one organ-It would allow whoever's implanted with it to do an imperfect transformation that would shudder and fail in a few minutes.

A ling with around 9-10 people absorbed, however, would have a variety of organs-Organs that increase innate healing in humans, organs that provide humans a strength boost or stronger eyesight...ling 'harvesting' could become a real thing, providing a reason for xenobiologists to actually keep changelings in custody, feed them monkeymen, and harvest their organs.

A debrained changeling should have a red-colored brain, just like alien brains are green. No reason, just because cool red.

Thoughts?

Alternately we can just fucking take goonling because jesus christ they got it right and /tg/ really really really did not.

**Comment by Time-Green** [comment]
Please fucking yes

Lings are stupid the way it is now

And looking at adams beautifull hate creation

I am totally for this

Not with no DNA regen tho

**Comment by ghost** [comment]
DNA isn't available unless you absorb a human, albiet lings start off with a stockpile of 40 DNA.

It's to prevent ability spam, ect.

For example, you have 40 DNA.

You see someone you want to absorb, so you draw your mutesting.

This draws 4 DNA from your stockpile, using it up.

You sting them, stunprod them, and drag them off to eat them.

You now have 75 DNA to use.

Rather than spamming stings/abilities, ect, it actually becomes 'when do I use this ability, do I have the DNA to do so, will the return be good?'

It completely changes the 'chem' system lings have now from current 'I have 70 chems let's grow an armblade and run around with it willy nilly and there's no chem issue there i can also spam fleshmend infinitely.'

By quite simply making it that it costs a changeling to use the ability by using up some DNA, like a traitor can spend telecrystals for their stuff, but absorbing a human offers them a way to get their DNA back for their abilities.

Certain abilities wouldn't be very costly, like mutesting. 

Others, like fleshmend, would have a cost dependent on how much damage you've taken-if you have  150 brute damage, it will take 9 DNA to heal yourself back up very rapidly.

Still more, like the armblade ability that I am still uncertain I want in at all, would cost around 8-9 DNA to extend, none to retract, but burn 2 DNA per second to prevent lings from going on a murderbone rampage with the armblade with ease.

It prevents ability spam, adds resource management, and balances every ability AT ONCE by making it cost DNA rather than giving it cooldowns/ridiculous chem costs that can be played off.

**Comment by ghost** [comment]
Comprehensive list of abilities and costs-

Mutesting, 6 DNA for one absorption, 5 DNA on 3 absorptions, 4 DNA on 5+ Absorbings. 5 DNA to buy ability.
Exhaust sting-8 DNA on one absorption, 7 DNA on 3 absorptions, 6 DNA on 5+ absorbings. 6 DNA to buy ability.
Augumented Eyesight-Nerfed to purely low light/nightvision, costs 5 DNA to buy ability, freely toggleable.
Adrenalin Sacs-9 DNA on one absorbing, 7 DNA on 3 absorbings, 6 DNA on 5+ absorbings. Unlike current sac's, rapidly heals all stamina damage and instantly removes all stuns, plus adds stun resistance for a good bit after that. Reveals changeling as changeling through a 'X recovers with unnatural speed!' 10 DNA to purchase.
Fleshmend-Ranges from 1-10 DNA to heal, damage dependent. Unchanged from current fleshmend except heals with greater speed. Messages are displayed in loud text, just like as though you were hit. Innate ability. Also flushes body of current chemicals. Becomes weaker with successive use.
Last chance-REMOVED because it's ass
Lesser form-5 DNA to activate, unchanged. Innate ability.
Mimic Voice-3 DNA to unlock, freely toggleable.
Armblade-11 DNA on one absorption, 10 on three absorptions, 9 on five+ absorbings. Costs 2 DNA per tick to use for one or 3 absorbings, 1 DNA per tick for 5+ absorbings.
Organic Shield-REMOVED
Organic Spacesuit-REMOVED, lings with the new suggestion would be naturally spaceproof and immune to no-pressure but still need oxygen
Chitin armor thing-FUCK THAT IT'S GONE
Anatomic Pancea-REMOVED, since lings are now disease-resistant with the new suggestion and fleshmend purges the body of chemicals already
Dissonant (EMP) Shriek-FUCK THAT SHIT IT'S GONE
Resonant Shriek-6 DNA on one absorbing, 4 DNA on 3 absorbings, 2 DNA on 5+ absorbings
Spread Infestation-15 DNA to purchase, 10 DNA on one absorbing, 8 DNA on 3 absorbings, 6 DNA on 5+ absorbings. Nerfs the spiders, finally. Alternately, 10 DNA to purchase, and 9/7/5 DNA accordingly, but displays a very obvious message that 'X hunches over as spiders crawl out of their mouth!'
Strained Muscles-6 DNA to buy, freely toggleable, still has same drawbacks and issues-with more absorbings, longer stamina before you pass out to it.
Transform sting-5 DNA to buy, costs 3 DNA flat to inject someone with a genome you've eaten, same stuff as usual.
Blind sting-GONE
Hallucination virus sting-20 DNA to buy, and use, flat. It's basically an endgame ability anyway, you sting one guy with it and everyone hallucinates until AI calls the shuttle.

Any suggestions for abilities, nerfing costs, ect? Remember, with 40 DNA per living human and 20 DNA per corpse, there's a lot of DNA to go around.

I should mention that i'd also suggest reducing lings to 1-2 lings on a traitorling round, and 2-3 lings on a changeling round if forced since they're not in rotation. Lings since they could only get DNA through eating actual humans would be an active threat instead of a boring round.

Alternately, you could make them appear in any roundtype where their existence wouldn't completely ruin things-Unless, of course, you made them conversion resistant, so you didn't get rev lings/cultist changelings.

**Comment by Time-Green** [comment]
Ahh

I see no reason to not do so now

Changeling is looking more like the real thing now

I love the idea of the organs and such

And actually having them mixed in all gamemodes is the best thing ever

**Comment by Cruix** [comment]
Adam, stop coming up with good ideas so fast and learn how to code.

If the changeling's evolutions are all organs, we could make it so that being cloned does not clone the organs, and the changeling has to find its own corpse and absorb it to get its powers back. It would also make lings more motivated to kill each other for the powers of the other lings, and prevent clone-spam abuse to harvest dozens of organs from one changeling.

**Comment by shrimptk** [comment]
FINALLY, ADAM CAN'T BAN ME FOR ABSORBING EVERYONE

**Comment by ghost** [comment]
'FINALLY, ADAM CAN'T BAN ME FOR ABSORBING EVERYONE'

THIS
LING'S A FUCKING PREDATOR NOT A BUBBLEWRAPPED DILDO YOU SHOVE UP YOUR ASS AND PRETEND YOU'RE NORMAL CREW FOR THE REST OF THE ROUND

**Comment by Super3222** [comment]
And than there's the dick that doesn't read the team objective and absorbs his fellow lings for organs.

**Comment by ghost** [comment]
team objectives don't exist 

because ling is not a gamemode

and will never be a gamemode in rotation again

it's all traitorling now baby

**Comment by X-TheDark** [comment]
If I understand correctly, the organ-thing is something like the Slaughter Demon kill thing, where you get "loot" for killing (and harvesting) a changeling, not actual organs that correspond 1:1 to changeling powers?

**Comment by ghost** [comment]
'If I understand correctly, the organ-thing is something like the Slaughter Demon kill thing, where you get "loot" for killing (and harvesting) a changeling, not actual organs that correspond 1:1 to changeling powers?'
Not quite.

They'd be actual organs that appear in the ling, surgically removable, depending on purchased abilities.

Lings would have innate organs-One for transforming/genome storage, and a healing organ, and one for ling hivemind.

Certain abilities would grant lings organs-Shrieks would develop an organ in the mouth that you could do surgery to remove, as would mimic voice.  Augumented eyesight would develop organs in the eyes. Adrenalin sacs would develop organs in the chest. Ling hivemind organ would be in the head. Ling healing organ and genome storage would be in the chest.

Stings would also be surgically removable, albiet i'm not sure from where...

Lings would naturally regrow those organs when in stasis-Even with the healing organ removed, stasis is still possible, but slower. The only thing they can't regrow is the brain.

Changeling organs would yield high levels of bio and illegal research.

You could also surgically implant them into humans to provide them with nerfed versions of those abilities that drain directly from human health to use or are just imperfect-Implanting a healing organ into a human, say, would increase natural healing rates, at the cost of the human becoming lethally allergic to certain chemicals.

Implanting the changeling hivemind organ into a human head could result in the human being able to listen in on ling hivemind, but not communicate, a la syndie key, if at all possible-And perhaps garbling locations and specific names.

Augumented eyesight organ could be implanted into human eyes to yield increased low-light vision, along the lines of preternis or further, at the cost of extreme weakness to flashes.

Et cetera, et cetera.

You could kill a ling, drag it to xenobio, dump it on a surgery table, and systematically rip out organ after organ for dank research and start an augumented human farm.

Changelings could eat each other, too, to increase their natural organ strength by consuming the DNA of other lings and their storage...but you're going to have a very angry husk shambling at you very quickly if you do, so there's some sufficient risk there.

**Comment by ghost** [comment]
BUMP

**Comment by ShadowDeath6** [comment]
Eh... Not really a fan of encouraging powergamers, it's irritating. 

Also giving lings a finite chem pool is fucking dumb IMO. 

Abilites scaling is a cool idea, though.

**Comment by Super3222** [comment]
BUMP.
