### ISSUE TITLE
Light system bugs

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#173]
No.1: A lit emergency flare paints the light of PDA/portable flashlights dark red (see below) (even when you separate them after that and turn them off and on separately after picking them up again, and even after the flare runs out of fuel), but it only remains painted when you hold them or you wear them (so it's tied to your character somehow).

No. 2: When you put the red-painted flashlight (or any other light source) into the box or the backpack, the light (which now has good color) remains in the place where you put it inside after you walk away, and after some seconds, disappears.

![ss13-light](https://cloud.githubusercontent.com/assets/16806055/12651076/71da8938-c5e5-11e5-9c8d-5d5ea8185202.png)

**Comment by ghost** [comment]
i believe taco said he was reverting lights

**Comment by DavidEdwards** [comment]
He is, that is waiting a push to live. I hope to get that done tonight.
