### ISSUE TITLE
Major ling bug

### ISSUE THREAD

**Issue by Greatbigben** [yogstation13/yogstation-classic#174]
Got this in a ticket.

12:37:30 - Silvaplex256 - I think ling is bugged.

12:37:30 - Silvaplex256 - Ticket created by Silvaplex256

12:37:37 - GreatBigBen - explain

12:37:47 - Silvaplex256 - When you transform, you transform into whatever the guy is wearing.

12:38:01 - Silvaplex256 - This engineer´s clothes just duped.

12:38:24 - Silvaplex256 - But they´re glitched. I can´t take them off, nor can I use them.

12:38:34 - GreatBigBen - hmm so the clothes cant be used?

12:38:37 - Silvaplex256 - Nope.

12:38:40 - Silvaplex256 - Just for show.

12:38:46 - GreatBigBen - wow ill make a bug report

12:41:01 - Silvaplex256 - whoa, I bugged it even more

12:41:06 - Silvaplex256 - holy shit

12:41:10 - GreatBigBen - hmm?

12:41:11 - Silvaplex256 - KEK

12:41:17 - Silvaplex256 - I'm wearing a headset for my ID

12:41:27 - GreatBigBen - i cant even.....

12:41:28 - Silvaplex256 - And a toolbelt for a jumpsuit

12:41:34 - Silvaplex256 - This is so bugged...

12:41:54 - Silvaplex256 - KEK I HAVE A PDA FOR A JACKET

12:42:33 - Silvaplex256 - Oh man

12:42:40 - Silvaplex256 - Vision is horrendously bugged now

12:43:11 - Silvaplex256 - the sprites are fucked up lol

12:45:25 - Silvaplex256 - Can you edit this headset out of my inventory or something?

12:45:33 - Silvaplex256 - It's stuck in my backpack slot now.

12:45:36 - GreatBigBen - i can make you drop everything

12:45:41 - Silvaplex256 - okay

12:45:45 - Silvaplex256 - I´m fine with that

12:45:59 - Silvaplex256 - sweet, thanks

12:46:04 - GreatBigBen - np

12:46:08 - Silvaplex256 - oh FUCK

12:46:13 - GreatBigBen - hmm?

12:46:20 - Silvaplex256 - almost all of the items disappeared

12:46:30 - GreatBigBen - thats a horrible bug

12:46:45 - Silvaplex256 - my inventory is so, so bugged right now

12:46:46 - GreatBigBen - i need all the things you did from beginning to end to make a full report

12:47:07 - Silvaplex256 - well, I dnastung someone

12:47:16 - Silvaplex256 - changed from human to monkey

12:47:25 - Silvaplex256 - ventcrawled to a dead engineer in dorms

12:47:28 - Silvaplex256 - switched to human

12:47:33 - Silvaplex256 - fuck det at the door

12:47:39 - Silvaplex256 - hold on

12:47:52 - Silvaplex256 - nevermind

12:48:00 - Silvaplex256 - so, I was human with my target in bed

12:48:08 - Silvaplex256 - and I absorbed him

12:48:12 - Silvaplex256 - transformed

12:48:17 - Silvaplex256 - All of his items appeared on me

12:48:25 - Silvaplex256 - so I switch from target to monkey

12:48:27 - Silvaplex256 - and back

12:48:37 - Silvaplex256 - Items all reappear again, except in weird places

12:48:51 - Silvaplex256 - Change back to monkey, and to human

12:48:56 - Silvaplex256 - Items get fucked even more

12:49:06 - Silvaplex256 - Ask you to instastrip me

12:49:25 - Silvaplex256 - All items dissappear, then I change from monkey to human and notice that the ground items are gone.

12:49:25 - GreatBigBen - alright is that everything you did?

12:49:28 - Silvaplex256 - Yep.

12:49:58 - Silvaplex256 - There were two sets of ground items, original and duped set. /Most/ of the dupe set disappeared.

12:50:12 - GreatBigBen - hmm probably the monkey thing bugged it

12:50:12 - Silvaplex256 - A bedsheet that I had from monkey kinda duped.

12:54:03 - GreatBigBen - alright thanks for the report

12:54:19 - Silvaplex256 - anytime

**Comment by X-TheDark** [comment]
Sigh, so much for making Transformation String work... Monkey is still my greatest nemesis, it fucks with the Transformation String if you sting a monkey and now it fucks even when you don't sting a monkey.

**Comment by X-TheDark** [comment]
So, how do you propose to fix this? I mean, I could try to make ling string only copy appearance and not even touch the items, so you'd still be wearing what you have (or nothing, as the case may be).

**Comment by DavidEdwards** [comment]
_KEK I HAVE A PDA FOR A JACKET_

That doesn't seem possible? There are a thousand checks to make sure things
like that don't happen. I would have been interested to see that happen!

**Comment by X-TheDark** [comment]
The problem is that the "phantom items" you get when transforming are dropped when you become a monkey, I think I need to see what can be done about that so it doesn't happen, as anyone pick up the "phantom items" and even equip them (in places they are not supposed to go), but the only way to remove them from yourself is to become a monkey again.

**Comment by Hydre** [comment]
Why is copying someone's outfit even a thing

**Comment by ghost** [comment]
'Why is copying someone's outfit even a thing'

To encourage lings to transform.

You grow their clothes in flesh form so you can actually impersonate them on the fly without having to kill them.

**Comment by X-TheDark** [comment]
One thing to note, though, you only get their item as a "phantom" if that slot is empty. If you have something equipped, it doesn't give you the victims clothes or backback or whatever for that slot.

**Comment by Cruix** [comment]
I have an idea. I'll see if I can make a new "flesh clothing" item that has the same wearing-sprite and name as whatever it is mimicking, but the in-inventory sprite will have a special symbol on it and the description will say that it is a non-functional flesh item, and that unequipping it will destroy it. I will also fix the proc that makes these items because holy crap it's ugly right now. (Either it's shit code or brilliant code, but it's so crazy I can't even tell.)

**Comment by Cruix** [comment]
Also perhaps I will add a separate transform ability for clothing.

**Comment by FluffySurvivor** [comment]
It's not actually a bug.
You can remove the clothes by using "transform" then clicking "drop flesh disguise". The last time I used this it worked at least.

**Comment by X-TheDark** [comment]
Problem is, OTHER people can pick up these items and even equip them by accident. But since they don't have either the lesser form or drop flesh disguise, they are stuck with the items permanently until Genetics turns them into a monkey.

**Comment by X-TheDark** [comment]
Done and closed. Reopen if any more bugs happen.
