### ISSUE TITLE
Waste disposal recycler is out of order?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#180]
After 15 pieces of light tubes, several other trash.. the recycler seemingly doesn't produce any glass or metal.

**Comment by Cruix** [comment]
The recycler was nerfed to prevent science from getting infinite materials by recycling foam-force darts. It now produces exactly nothing.

**Comment by DavidEdwards** [comment]
Precisely. I think I made that change myself. If you have any thoughts about balancing it, you are welcome to post them. However, since this issue is about it being out of order, I will close this issue.

**Comment by 00aquir** [comment]
Well if something does not do anything, why is it on the station (wouldn't be better solution to remove from game)? This confuses people who's waiting for the recycler to do something. I guess the only other way to solve this is to make the recycler recycle "smaller" materials slower (it would count toward a certain trash unit type in a more balanced way).
