### ISSUE TITLE
Waste disposal recycler rework

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#181]
I guess the only way to solve the past abuse of the recycler (which was tied to R&D) is to make it recycle "certain" or "smaller" materials slower (counting toward certain trash unit types in a more balanced way), or make it produce mainly (or only) metal and glass (since it is normally tied to cargo's trash material management).

But until then, when the recycler does not do anything (like now), why is it on the station (wouldn't be better solution to remove from game)? This confuses people who are waiting for the recycler to do something.

**Comment by DavidEdwards** [comment]
It was intended to rework it, but that never happened. I would be happy with returning a percentage of the original items value. Upgrades bringing the percentage closer to 100%.

**Comment by ghost** [comment]
RETURN BROKEN RECYCLER

FUCK YOU, PHYSICS
