### ISSUE TITLE
Colored lighting is still causing issues

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#183]
Apparently even after the soft revert, the colored lighting is still white to people with specific hardware.
@TehFlaminTaco

**Comment by TehFlaminTaco** [comment]
It's still not been reverted.

We need a pull to live.

**Comment by DavidEdwards** [comment]
Yep, I tried a couple of days ago, but there was a silly long round running so I didnt have the opportunity. I'll be attempting to do so this afternoon.
