### ISSUE TITLE
Remove Glowshrooms

### ISSUE THREAD

**Issue by Cephalopoet** [yogstation13/yogstation-classic#185]
They're laggy, they multiply and add nothing to the game.

**Comment by Time-Green** [comment]
They add pretty lights!

**Comment by shrimptk** [comment]
+1 Either optimize them, or drop 'em

**Comment by Xantam-13** [comment]
Drop 'em. They are useless.

**Comment by Cruix** [comment]
But how is botany supposed to keep running when the lights go out? Glowshrooms are far more thematic than flashlights.

And as the only source of radium that can be grown, they are the only sustainable way botany can get extra-species mutations without the help of chemistry.

**Comment by shrimptk** [comment]
@05rhardy The king has spoken, these powergamey shits need to get the fuck out

**Comment by X-TheDark** [comment]
One word - Shadowlings. Other than that, they do more harm than good due to causing some mad lag.

**Comment by Cruix** [comment]
Are we removing flares too?

Shadowlings can kill glowshrooms, they just slow them down. They can't do shit to flares.

**Comment by Cruix** [comment]
Is this resolved by #187, or are we still thinking about removing glowshrooms?

**Comment by DavidEdwards** [comment]
For the time being, this issue will be closed.

Cruix made some nerfs to Glowshrooms. If there is another uproar we can create a new issue.
