### ISSUE TITLE
Timer for cloning pod occupant to see duration until cloning completed

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#186]
Simple convenience thing. Add a little counter in the Status tab to show the occupant of a cloner how long they have until they pop out, just so you know when you can tab out safely.

**Comment by ghost** [comment]
Done.

**Comment by Cruix** [comment]
Wait this was done? When?

**Comment by oisin100** [comment]
LIES ADAM LIES
