### ISSUE TITLE
Lightning issues.

### ISSUE THREAD

**Issue by Toskin** [yogstation13/yogstation-classic#190]
Lots of areas in station (mainly maintenance) ignores cyborg lamp light levels. Also, right-click menu is detecting light and light levels. I provide pictures.
![picture 1](https://cloud.githubusercontent.com/assets/8083413/12698453/e701329e-c79c-11e5-96ef-590b4aa57b50.png)
![picture 2](https://cloud.githubusercontent.com/assets/8083413/12698460/1cd9f8a6-c79d-11e5-80b3-9ea7c7b6108d.png)

**Comment by AsV9** [comment]
Paging @TehFlaminTaco for this.

**Comment by george99g** [comment]
I don't think non-admins are supposed to see light stuff when they right-click.

**Comment by TehFlaminTaco** [comment]
Going to do a bigger revert, atleast then people can stop asking me about the damn lighting.

**Comment by DavidEdwards** [comment]
Lots of changes to lighting lately. Report again if there are still issues.
