### ISSUE TITLE
Noslip shoes or Operation : Cancel Lubrication

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation-classic#195]
So, I'm sure we can all agree that Space Lube is kind of ridiculous, but...how do we fix it?
Current proposals:
1. Make syndicate no-slip shoes not slip on lube;
2. New super-stik shoes that are more expensive but don't slip on lube;

Both of these options will further need to be discussed in context of their availability - Traitor and/or Nuke Ops.

Perhaps you have other ideas on how to make lube a bit less ridiculous? Or maybe it's perfectly balanced? Thoughts?

EDIT : Or maybe just change the operative Chem Sprayer to spray lube or something.

**Comment by krgii** [comment]
Make magboots noslip too while active.

**Comment by X-TheDark** [comment]
Done and merged.
