### ISSUE TITLE
Remove confirmation window from destructive analyzer.

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation-classic#197]
Yes, I'm sure I want to destroy this item. I wouldn't have pressed destroy if I didn't want to.

**Comment by Super3222** [comment]
I think the confirmation is there so people don't deconstruct something that's pointless towards research levels and can actually use. Considering deconstruction is permanent and you can't get it back unless it's re producible.

Maybe there could be a safety lock that you can toggle using the RD console with the destructive analyzer which goes ahead and deconstructs what's in it without asking you to confirm.

**Comment by oisin100** [comment]
Maybe it should only prompt you when the item your deconstructing wont give you any research levels at all...

**Comment by george99g** [comment]
> Maybe it should only prompt you when the item your deconstructing wont give you any research levels at all...

This would be an immense help to speed up R&D. The main part of it is checking if the item you're deconstructing will be any useful or not. With it prompting you and telling you when it's not, it'll take a lot of the work out.

**Comment by oisin100** [comment]
Ill see what i can do about it then.

**Comment by X-TheDark** [comment]
Done and closed.
