### ISSUE TITLE
R&D Idea

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#198]
So you know how antags can pretty much lube up some common place's door and get free kills? Well, to counteract antags using space lube, what if we added the no slip shoes that traitors can get to the protolathe? It would probably cost quite a bit of materials to balance it out, but it would be good to give to sec so they don't get rekt by unarmed librarians in maint. 

Inb4 "lol ur just salty you got killed by lube git gud"

**Comment by Super3222** [comment]
Noslip shoes are not suppose to be common & RnD doesn't really need to create a re-engineered version of every traitor item.

It just sounds like a bad idea to make noslip shoes an actual producible thing by normal crew members. Maybe a T4 bio generator could produce them with exceptionally high biomass requirements.

**Comment by Rocks4Free** [comment]
> Noslip shoes are not suppose to be common & RnD doesn't really need to create a re-engineered version of every traitor item.

They'd be hard to obtain, requiring a lot of research, and some decent materials would be needed too.

**Comment by Super3222** [comment]
> They'd be hard to obtain, requiring a lot of research, and some decent materials would be needed too.

Wait, what am I thinking? We DO have noslip shoes in RnD. They are called magboots.

**Comment by ghost** [comment]
no
magboots for 1 aren't noslips

two no

R&D doesn't need a copy of every damn antag item for themselves

noslips are traitor only, that's it

it'd be good if noslips were cham'd though, so that you could click them to turn them into any type of shoe but being hit with an EMP turns them into clown shoes that flash every color of the rainbow

**Comment by ghost** [comment]
Magboots no longer slip on lube and are printable from R&D. Boosh.
