### ISSUE TITLE
Lighting issue with hand-held lights (PDA, Torch etc)

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#20]
opened by Xantam · 3 months ago
I don't know if discussed already, but many times when you have two light sources on you, and for example you pick up a gun attached to a flashlight, then put it away, you often realize you can't see yourself in maintenance.. (no light at all). I don't know if it happens every time but it's really annoying that you have to Turn Everything Off (PDA, seclight, gunlight, hardsuit light), then On again. When I was doctor, same thing was with light source plus medical light pen.
Somehow any or just some things that glows changed more light sources by dropping it/putting it away, or equipping a new one that you put it into backpack before, I don't even know... If you manage to handle more lights, one can affect all of them in a bad way, and you will have to turn some of them off and on again more than one time in a round.
SOURCE: http://forums.yogstation.net/index.php?threads/light-system-is-broken.7472/

**Comment by TehFlaminTaco** [comment]
Can someone confirm if this works with my current code?

**Comment by DavidEdwards** [comment]
With so many changes to lighting, I am going to close this. If there is an issue still, a new issue should be made.
