### ISSUE TITLE
Drones cannot set access level on Airlock electronics

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#203]
So much for airlock repair...

**Comment by Time-Green** [comment]
Well, drones have no ID

Ehh. Im not a fan of needing an ID to set the level.

Even an assistant can set it to captain level. Kinda pointless

**Comment by Cruix** [comment]
Drones also cannot access settings on bots without stealing an ID. Perhaps they should be given silicon privileges.

**Comment by Super3222** [comment]
I'll get onto this.

**Comment by Super3222** [comment]
I figured it out.

Drones get all access naturally, being able to open any airlock at will.
Airlock electronics require you to use your ID card (which has it's access) ON it, in order to unlock it's functions.

Drones can't accomplish this, considering they have no ID.

**Comment by 00aquir** [comment]
well obviously it would take some change in the code for them to be able to do it without ID (which would be the normal way)

**Comment by Cruix** [comment]
Cyborgs don't have IDs, and they can change the access levels on airlocks from their RCDs.

**Comment by 00aquir** [comment]
Cyborgs can only change access level on doors they make (only once), but not on airlock electronics. I guess drones would need different access method by simply clicking the board.
