### ISSUE TITLE
Chatlogs and others not being recorded

### ISSUE THREAD

**Issue by Xantam-13** [yogstation13/yogstation-classic#204]
Shadowling chatlogs possibly are not recorded in the logs themselves. 

In addition, the new cybermen game mode does not log much either. Primarily chatlogs, among other things like their actions.

**Comment by DavidEdwards** [comment]
@Cruix Could you check this out?

**Comment by Cruix** [comment]
I'm on it.

**Comment by Cruix** [comment]
I thought it was just abilities that use input() to get text were not being logged, but looks like binary chat and changeling chat are not logged either. Am I just missing something?
