### ISSUE TITLE
Crayon/graffiti logs

### ISSUE THREAD

**Issue by Xantam-13** [yogstation13/yogstation-classic#205]
When people graffiti on the walls or floor, it isn't logged for the admins to see who did it. We tend to get a lot of "gay" or "faggot" graffiti and we have usually no way to tell who did it (unless this was fixed and I am unaware). 

I think the simplest way to fix this is, whoever draws a rune or letter/graffiti, they touched it last.

**Comment by shrimptk** [comment]
+1 Good idea, helps handle a lot of unoriginal griefers. I myself had have to hunt down and find the names of people drawing swastikas all over the station

**Comment by Groudonmaster** [comment]
Just remove crayons  problem solved
