### ISSUE TITLE
Syndicate Syringe Gun

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#206]
I had seen this _elsewhere_ and for the longest time we I thought we had it on yog but I was upset to find that it wasn't quite here. This little baby of a syringe gun is for the inconspicuous bastard who likes to turn his lethal toxin mixes (Im looking at you, b1g) into long ranged instakills. The traitor toxin kit already costs a hefty 6 TC, but requires you to steal one of two very big and not-so-stealthy syringe guns in order to use, or have immediate, and uninterrupted access to chemistry in order to use effectively. So for maybe another 3-7 (Debatable) you can get a nice little syndie box loaded with:

> 1: A Small Syringe gun with a black & red paint job that not only fits in your pocket, but also gives no indication as to who fired it when fired, and the hit message isn't in massive text
> 2: A Box of syringes
> 3: A Large Beaker for mixing
> 4: A Friendly letter from the syndicate telling you to buy the fucking toxin kit.

**Comment by ghost** [comment]
eh

just add the mini syringe gun to the toxin kit

albiet i don't even like that because the whole point of the toxin kit is you have to steal clunky syringe gun

and you can get large beakers from chem and syringe guns from medivendors

we aren't handing out free bjs to traitors, work for your damn green

**Comment by shrimptk** [comment]
@AdamElTablawy That was my initial Idea, but it was kinda lame and ehghg

**Comment by ghost** [comment]
yeah but a 3-7 syringe gun box that comes with like all the other shit to make it easy peasy is literally just an inbuilt combo cafe

**Comment by X-TheDark** [comment]
What about a "loud" hypospray that can contain 5-10 units of chems?
