### ISSUE TITLE
Lighting issues

### ISSUE THREAD

**Issue by forhiti** [yogstation13/yogstation-classic#207]
![lighting](https://cloud.githubusercontent.com/assets/16998210/12708518/e1c39b40-c865-11e5-9917-4eea50f65759.png)
![lighting2](https://cloud.githubusercontent.com/assets/16998210/12708517/e1c134e0-c865-11e5-9d4a-ac7072101492.png)

**Comment by forhiti** [comment]
Flashlights only work in some circumstances, and in maint sometimes the light won't change at all.

**Comment by george99g** [comment]
@TehFlaminTaco

**Comment by TehFlaminTaco** [comment]
Fuck me... The Light and Dim view-ability was left completely untouched by me. Why flashlights just aren't working is far beyond my comprehension, but I'm probably to blame. I'll look into it.

**Comment by AdamElTablawy** [comment]
>makes good feature
>it shits on things
>removes good feature
>keeps the shitting

??????????????????

**Comment by DavidEdwards** [comment]
Lots of changes to lighting lately. Report again if there are still issues.
