### ISSUE TITLE
Bug opening backpack

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#21]
opened by Xantam · 3 months ago
Aquir: so in this round right now.. I could open every backpack, just not the one where we put syndicate items. The backpack was in the middle of a breach.
Admin answer: "Might want to file it as a bug then. Aka, a backpack blown up from inside with a pizza bomb, whilst being worn, glitches the backpack?"
Kn0ss: Could you explain what exactly you mean? Including steps to reproduce the error, if you can.
Aquir: Could you explain what exactly you mean? Including steps to reproduce the error, if you can.
SOURCE: http://forums.yogstation.net/index.php?threads/couldnt-open-backpack-on-the-ground-just-placed-syndicate-items-into-it.7397/

**Comment by BadminBen** [comment]
testing needed on this bug

**Comment by X-TheDark** [comment]
Cannot be reproduced with the information provided.

Testing methodology:
1. Arm pizza bomb to 10 seconds;
2. Trigger pizza bomb;
3. Put pizza bomb inside of backpack located on the ground (tested with industrial backpack and regular backpack)
4. Pizza bomb explodes, deleting backpack;

Step 3 was also repeated with backpack located on persons back. Resulted in gibbing of person along with all items on them.
