### ISSUE TITLE
Bans not lifting properly

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#211]
Jobbans continue even after being lifted and I've had a few reports of bans continuing despite them not supposed to be active.

**Comment by Cruix** [comment]
Looking at the code it looks like the ban has to be manually lifted AND expired for the ban to stop being in effect, is this what happens?

**Comment by Groudonmaster** [comment]
Unsure.  All that's obvious is that certain permanent bans aren't being lifted even after manual removal despite it working previously ~3 months ago.
