### ISSUE TITLE
Add Cortical Borers

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#216]
## Adds the bay simple animal, Cortical Borers.

I think tg tried to do this but they gave up, maybe we can do it.

There are a lot of different codebases which change the ways borers work, the closest ones are paradise and current bay, both which use language systems so I'm not totally sure how it'll work there. 

Major parts needed:
-Porting the actual borer and all its abilities.
-Remove borers being able to speak different race languages, since we don't have those.
-Change chemical list since it has chemicals from trek chem, which we don't have, like alkysine, hyperzine, and dylovene.

Minor parts / suggestions:
-Add nulvoscine (silence chem) to the borer injection list so borer can mute its host for small periods of time.
-Add borers to xenobio blacklist or make it adminspawnable only since random borer events will make people cry tears of 100% pure crystallized salt.
-Add borers to the list of things you can extract from the head 
-(anything else people suggest)

**Comment by Super3222** [comment]
nice meme.

Can you describe what cortical borers are exactly for people who may not know, please?

**Comment by ShadowDeath6** [comment]
Basically, borers are slugs that can burrow into a person's head. They're pretty weak outside a host, but they're space immune.

Once they're inside a host, they can do a lot more things, like inject chemicals (bicaridine, kelotane, alkysine, antitox, hyperzine) into their host.

Their main ability is being able to take control of the host, basically turning them into the person for as long as they can before the host resists out of it. They can also reproduce, which basically makes the host cough up a new borer along with a decent amount of vomit.

They can get knocked out by sugar, and can be cut out by doing brain surgery on the host. Brain surgery won't kill the host.
![borer](https://cloud.githubusercontent.com/assets/17034893/12767540/590974e4-c9cf-11e5-9ada-60a0e69a6c0f.gif)

**Comment by shrimptk** [comment]
+1 Good antag/random 
-1 Not memetic anomaly

**Comment by ShadowDeath6** [comment]
They removed meme because whenever someone found out they had it they would immediately suicide, which killed it.

If we had any chance of reviving meme, I would be super happy.

**Comment by shrimptk** [comment]
@ShadowDeath6 #218

**Comment by ghost** [comment]
> infect host
> hijack host
> he resists, eats 40 twinkies and karate jumps into space

**Comment by X-TheDark** [comment]
It would be nice to know what these things are supposed to do in the first place.
Do they have objectives?
Do people infected with them become antags?
Etc.

**Comment by Super3222** [comment]
> Do people infected with them become antags?

I'd believe so, I'd enjoy one crawling into my ear and giving me antag status. Maybe that's just me, but Shadow clarified that the cortical borer takes control of their body.

**Comment by ShadowDeath6** [comment]
They don't have objectives, no. I think the text that pops up when you spawn in is that you need to do whatever you can to ensure your race survives and reproduces.

**Comment by oisin100** [comment]
Sounds pretty cool! The borers from Bay appear to have objectives... I dont think they give the host objectives/antag status though... I think it would probably be pretty fun as a rare round event(Not a gamemode)

**Comment by ShadowDeath6** [comment]
> I think it would probably be pretty fun as a rare round event

They were always events mobs, although I'd prefer if they were adminspawn or xenobio due to the salt that's generally created whenever they happen.

**Comment by oisin100** [comment]
Hmm, I mean if its only one of them and they dont seem all that powerfull that if you didnt want one it wouldent be hard to get it out of your head... If its adminspawn somehow i think it will end up worse than ninja and just never occur..

**Comment by ShadowDeath6** [comment]
> only one of them

They can reproduce.

**Comment by Stealthkibbler** [comment]
My question is how does a borer stealthily get into someone? Because it has a sprite so people can see it.

**Comment by ShadowDeath6** [comment]
They have an ability, Dominate Host, that stuns a person which gives them enough time to get in.

**Comment by george99g** [comment]
Implemented in #434
