### ISSUE TITLE
What the fuck is wrong with me? ~a novel

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#217]
When @krgii mentioned bluespace suppositories in #165, my mind got ticking. For a solid 20 minutes I just had the vivid image rolling in my head of someone jamming a pill full of banana peels, cramming it up some poor Officer's chute, and having him gib in a shower of bloody banana peels. Obviously, my disgusting humor thought'd it'd be funny to add a super hard to make chem based upon this principle; Simply titled **HINK!**

Here's a lil' recipe:

> 1 part Initropidril 
> 2 parts Mint toxin
> 1 part Bananium
> 1 part Space lube
> 2 parts Black Powder
> 2 parts Polonium
> 1 part Krokodil 

A Shitty little chem that can only be used effectively via patch, any other form will cause the Subject to randomly say **Honk** in place of words in their speech patterns until it metabolizes out. If it is used on a crit or dead body however in patch form, the janitor is going to have a _real fun time._

**Comment by Cruix** [comment]
Careful with chems that gib people, those can be OP.

**Comment by shrimptk** [comment]
You have to not only be a traitor, but also find bananium

**Comment by shrimptk** [comment]
Pretty fair for gibbles on only crit and dead people

**Comment by ShadowDeath6** [comment]
2 parts mint toxin...
you can only ever get 1u of mint toxin ever without adminbus.

**Comment by ghost** [comment]
> grind mint toxin
> load in oddy
> delicious mint poison farm

**Comment by X-TheDark** [comment]
At that point, you might as well just scan nutrient with Oddy, inject shitton of it into people and then gib them with the scanned mint.

**Comment by Super3222** [comment]
Gibbing corpses with a chemical which is nearly impossible to make...

Maybe spawn 1u of it in a bottle on a gateway mission in the clown planet?

**Comment by shrimptk** [comment]
@Super3222 **gg**

**Comment by DavidEdwards** [comment]
Doesnt seem to be much activity on this one. Closing. That said, I'm open to a chem that inserts honk in text. More harmless fun for the Clown can't be bad.
