### ISSUE TITLE
Meme

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#218]
http://nanotrasen.se/wiki/index.php/Meme

Retired Gamemode
Time to get portin'

**Comment by ShadowDeath6** [comment]
The only problem with this is that codermemepeople have to root through shitty old bay files to find this, since any current code doesn't have it.

**Comment by oisin100** [comment]
The code for the meme gamemode is still in the latest there by the looks of it(Or atleast the gamemode is so im assuming the mob is too)... Shouldn't take too much effort to port it _Famous last words_

EDIT: If you saw what i edited in here earlier just ignore it.
