### ISSUE TITLE
Mechs Unable to Use their Special Ability

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#219]
More HUD stuff not working, why did someone even make it so that mechs have an HUD?
1. Get in mech.
2. Go to view stats.
3. Try to click special ability like defense or phasing.
4. Not work.
5. Check HUD where breath mask toggle and stuff is.
6. No mech HUD button.
7. Wonder if I'm doing something wrong.

Am I just stupid or is this actually a problem? I want meth speed on gygaxes.

**Comment by X-TheDark** [comment]
The correct answer is : both (/s). Press F12 a couple of times until the HUD buttons on the top left appear. And this HUD thing being switched when entering a mech should probably be fixed as well.

**Comment by shrimptk** [comment]
Don't worry baby I got you.

**Comment by ShadowDeath6** [comment]
I mean, the HUDs on the top left are there, but there's no button for a mech ability. F12ing will fix the button not being there, or it'll just re-add stuff like breath mask?

**Comment by X-TheDark** [comment]
Currently, there's a huge problem of it taking ages to readd icons to the mech abilities HUD thing after exiting/reentering the mech (at least when done quickly) and I can't quite pin down why searching through the code.
