### ISSUE TITLE
Sec don't start with sec sunglasses

### ISSUE THREAD

**Issue by harry2680** [yogstation13/yogstation-classic#224]
Can we make it so they do please?

**Comment by Super3222** [comment]
I think this was meant to be a thing on purpose, so security can suit up entirely from their locker.

**Comment by oisin100** [comment]
An attempt to introduce RP... Security has to put on their glasses...

**Comment by ghost** [comment]
who puts fucking glasses in a locker

tazers, body armor, yeah

glasses?

in a fucking locker?

make them start with stunbaton in locker and glasses on their face/bag

**Comment by FluffySurvivor** [comment]
Yes please make them start with the hud glasses. It would help in rev cause there will be spares for the loyalists.
