### ISSUE TITLE
Able to use Cyberman verbs while a ghost

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#225]
For some reason I was able to use Cyberman Broadcast while dead.

This happened when I had been converted into a cyberman while being nonimplanted, than got into crit, and emp'd while in crit. After dying I was still able to use cyberman broadcast (and had my cyberman tab), which gives ghosts the power to abuse it. ((which I did not do if you are wondering))

I could not only cyberman broadcast, but I was able to deconvert my self. By pressing 'cancel hack' (or any other cyber verb that's not broadcast I'm guessing) I had deconverted myself back into a civilian status.

steps version:
1. get converted
2. get put on surgery table
3. enter crit
4. get emp'd
5. eventually die from bleeding out
6. be able to use cyber broadcast normally as ghost. using other verbs makes your body deconvert

**Comment by Cruix** [comment]
Fixed by #235
