### ISSUE TITLE
Give Swarmers the ability go to through doors like drones

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#228]
They're, like, anti-drones. Would be cool and it give swarmers more mobility.

**Comment by oisin100** [comment]
I thought that was just a bug that drones could go through doors...

**Comment by Super3222** [comment]
> I thought that was just a bug that drones could go through doors...

You gotta try examining airlocks nowadays, they provide some interesting information. Basically centcomm has equip airlocks with drone doggydoors.

Anyway swarmer's being able to zip in and out of rooms would make them more difficult to deal with... though that's their entire purpose. :+1:

**Comment by oisin100** [comment]
Ah right. It doesent take much for a drone to zip through walls anyway... I cant see this causing any serious balance problems...

**Comment by Time-Green** [comment]
Swarmers are already way to annoying. If this went through they could walk in everywhere with zero problem

**Comment by ghost** [comment]
The default thing about swarmers is that they have access restrictions so welding vents 'n shit does something.

Otherwise you just have swarmers who walk right the fuck into the AI core and warp the AI into space.

They should still have their access restrictions otherwise they're op af

**Comment by DavidEdwards** [comment]
The reason that drones have no access restrictions is that their only
purpose is to build and repair things. Swarmers are an antag and should not
have the same all access that the non-offensive drones have.

**Comment by oisin100** [comment]
Yea. True that. Ill be against giving them the ability to walk through doors..
