### ISSUE TITLE
NTSL cancels AI Tracking

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#23]
opened by Nicholas Weber · 3 months ago
Adding NTSL Scripts bugs out AI tracking, and will not allow you to track people at all.
Source:http://forums.yogstation.net/index.php?threads/ntsl-scripts-ai-camera-tracking.6663/
Additional Sources: I've done it myself to test its theory, Adding anything even a job indicator usually bugs it's tracking and will not allow you to track at all.

**Comment by Groudonmaster** [comment]
That's because it tracks by searching for the name defined but if you add a job title to the name the script can't locate it because instead of searching for "John Sweeps" it searches for "[Sci]John Sweeps"

**Comment by oisin100** [comment]
Fixed in PR
