### ISSUE TITLE
Ghetto armoury

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#232]
Basically, as the name suggests, more craftable weapons and clothing items.

Sprites will follow when they're made

Duct tape: Because everything is made of ducktape, only exists for crafting, would be vendable by the tool vendor in arrivals, starting with 5 in stock, also findable in maint with a medium chance
Weapons:
Pneumatic spear: A self propelled spear that hits for 20 throw damage at a stupidly high throwspeed and an embed chance, and the usual amount for spears on normal force, made with 1x spear, 1x air tank 2x pipes 1x cable cuffs 1x pipe manifold, like the pnuematic cannon, it would use the air tank as propellant

Glass shank (stick 'im bruv) : 1x glass shard, 1x duct tape/Or cloth strip for muhpermashank, 5 brute and doesn't cut you like a real shard does

Glass sword: Very sharp sword made of glass, hits for 15 brute , made with 1x metal rod, 2x glass sheets, 1x glass shard  1x duct tape 

Black glass sword: Literally the same as above, but looks a bit less shitty,  1x glass sword, 1x black 
crayon (this is only there so that the cool sword is really hard to make)

Refined glass sword: A baddass looking sword, costs more to make but looks epic (can be worn on your back) and hits slightly harder, 17 brute , 1x black glass sword, 2x metal ,  3x reinforced glass , 2x metal rods

Clothes:
Robust coat: A sleek black coat that gives medium brute resist and makes you look badass, 1x leather coat, 2x metal sheets, 2x duct tape, 2x cloth strip

Cool black undershirt+trousers: Low brute resist, equal to the sec jumpsuit. 1x black jumpsuit, 1x duct tape, 1x cloth strip, 1x metal

Thoughts?

Lemme know if any of this sounds OP, and i can change it, sprites coming soon

An example of the coat, refined sword, and jumpsuit in action:
https://gyazo.com/7bc85d5da1f70392b42d6c77b60c0e45

The shitty sword: https://gyazo.com/ad374d5ce8316bef07bf24d10a059243

The black glass sword: https://gyazo.com/8c89c24d91d91a46a575f1486fd4ec42

The refined sword: https://gyazo.com/10b37bf8a87de84f572420eb1f6a1224

**Comment by oisin100** [comment]
Sounds pretty cool.. More choice when it comes to how you want to kill someone whilst greytiding sounds fun as well!

**Comment by Time-Green** [comment]
Lets give assistans more weapons. Good idea (no sarcasm)

But uhm, pretty sure black crayon doesnt exist

**Comment by george99g** [comment]
> But uhm, pretty sure black crayon doesnt exist

Mime crayon.

**Comment by Kmc2000** [comment]
I have a DMI ready to go for the first coder (nerd) who wants to take it

**Comment by Kmc2000** [comment]
Oisin is working on this

**Comment by Super3222** [comment]
Sounds like powergamers will have a greater arsenal now. Great.

Also what's the point of the glass sword. A craftable weapon that does as much damage as a pickaxe or butcher knife? I'd only be okay with this if it broke after a certain amount of attacks and weight class was bulky (allowing you to put it on your back as well).

I like the concept of the glass shank though, if we could make it so you need 1 glass shard and ductape or piece of clothing that'd be great. (Allowing people to make PRISON SHANKS in perma)

> Low brute resist, lower than the sec jumpsuit

Sec jumpsuit only protects 10% of brute damage... anything lower would be... not much.

**Comment by Kmc2000** [comment]
@Super3222 

Added in balance based on your points, as for being limited use , not sure if that's even possible, but I can see your point

**Comment by Super3222** [comment]
> Added in balance based on your points, as for being limited use , not sure if that's even possible, but I can see your point

@Kmc2000 
Well Death Nettles deteriorate each hit (lose brute damage, get smallah), and I don't think a sword made out of glass shards would hold for so long unless it's welded together.

**Comment by ghost** [comment]
hm

how about we also port /tg's/ exploding spears 

those are fun

**Comment by X-TheDark** [comment]
Exploding spears? What could possibly go wrong?

**Comment by ghost** [comment]
it's a traitor only item so

literally, you get c4

you tablecraft it with a spear

exploding spear

you can also do it with a grenade

WITNESS ME

**Comment by X-TheDark** [comment]
Might as well return being able to plant C4 on people then.

**Comment by ghost** [comment]
c4ing people is different to running at someone with a spear and jabbing them, killing you and them at the same time

**Comment by X-TheDark** [comment]
Oh, right, I forgot it killed both, silly me.

**Comment by Kmc2000** [comment]
@adameltablawy

I love it

Pnematic spears with c4 tipped rounds, want

@Super3222

Oisin said he has this covered, 10 hits and then it has a chance to shatter on each hit

**Comment by ShadowDeath6** [comment]
c4 + spear will do 600 damage as long as the spear embeds

**Comment by Kmc2000** [comment]
@ShadowDeath6
AHAHAHAHAHAHAHAHAHHAHAHAHAHAHA

Imagine, 

> Make pneumatic spear
> its DA
> Target walks up
> throw spear, KABOOOM
> Get thrown in perma and get shanked by a different DA

**Comment by shrimptk** [comment]
@oisin100 @Kmc2000 When glass weapons shatter when hitting a target, the shards from the broken sword (Or if it is refined, rods as well) should have a super high chance to embed.

**Comment by oisin100** [comment]
Alright. Sounds like a good idea! It might turn out to be quite OP if it embed though..

**Comment by shrimptk** [comment]
@oisin100 Glass swords should drop 2-3 shards on shatter, with a maximum of 2 shards being able to embed with a >40% chance of embedding at all.

**Comment by ghost** [comment]
embedding is way too fucking strong

10% chance of embed, 2 shards can embed max

there, balanced

remember that embedding does  a fuckload of dmg + does bleed +does dmg to take out +Does damage over time if not taken out

you could kill wizards with embedded pens

and a tablecraft weapon should not be stronger than a fucking security stunbaton, because something that has a 40% chance of lodging 'FUCK YOUR ENTIRE FAMILY' in your leg and can roll this chance 2-3 times

bad

**Comment by shrimptk** [comment]
> balance embedding

Realistically, getting a wee lil' bit o' glass stuck in your hand wouldn't hurt that bad, no more than a splinter. Getting a metal rod to impale your leg however, different story.

Nerf glass embedding, Nerf rod embedding chance, fuck spear embedding

**Comment by ParagonPrime** [comment]
Glass sword sounds OP as shit for how easy it is to make. Maybe make it so it breaks if you whack it against something hard (ie, armour)? Like, you know, glass DOES

Armoured coats sound cool, though

**Comment by PineappleWolf** [comment]
Hi hi, KMC wanted me to shove CHAINSWORDS AND FISTS UP IN HERE

http://www.bitzbox.co.uk/images/chaos_terminator_lord_chain_fist_2007_large.jpg

http://vignette3.wikia.nocookie.net/warhammer40k/images/c/c8/Astartes_Chainsword_2.jpg/revision/latest?cb=20120103063947

as the examples, no sprites yet.

**Comment by Kmc2000** [comment]
@ParagonPrime 

Mate, the toolbox does 15 as well, this one does 15 and has a chance to shatter.

Also, chainsaws could be fun as high tier craftables

**Comment by PineappleWolf** [comment]
First model chain sword, complete with animation, more or less.

http://imgur.com/vEE4G1C

**Comment by Super3222** [comment]
> Mate, the toolbox does 15 as well, this one does 15 and has a chance to shatter.

@Kmc2000 
Toolboxes and kitchen knives do 10 brute damage, hatchets do 12 brute damage, pickaxes and butcher knives do 15 brute damage. I think these factors should be taken into account somewhere.

> 10% chance of embed, 2 shards can embed max

I think this would make their chances at embedding almost equal to agent ID cards. Which never happens.

**Comment by DavidEdwards** [comment]
Closing, since the PR was merged.
