### ISSUE TITLE
Admin Tickets

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#24]
opened by Nicholas Weber · 2 months ago
I've noticed that when I have multiple tickets open, some players replies go into another already closed ticket, which is odd and bizarre, as it makes me think that they are being ignorant.
Thought I'd add this in since it just happened to me recently.
Source: http://forums.yogstation.net/index.php?threads/tickets.6664/

**Comment by X-TheDark** [comment]
Any reproduction steps? I've tried testing this with 2 tickets, resolving one then opening it again.
The reply went to whichever unresolved ticket is at the top of the list and I couldn't get the reply from player to go into a ticket that's already resolved, it always goes to a unresolved ticket.
