### ISSUE TITLE
Add /tg/'s admin powers similar to AI

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#241]
I was told a while ago that /tg/ apparently has the power for admins to interact with electronics similar as to how an AI would.  It'd be useful to just port this over to fix say fucking atmos without having to either spawn in or delete the piping.  Or to close doors to space that a griefer AI has decided to open, or hell turn down the bloody PA because engineering is comprised of idiots that don't know how to do that.

**Comment by Cruix** [comment]
/mob/dead/observer/canUseTopic() already returns true for admins, so this should be a 1 or 2-line thing of making /mob/dead/observer/ClickOn call attack_ai for admins. It SHOULD be. I'll see if I can get it out before I leave my computer for the weekend.

EDIT: canUseTopic does not work the way I just said, but it will with a small change

**Comment by Cruix** [comment]
More complicated than I thought, mostly because there are about two dozen special cases that must be added. I won't have time to make and test this until after this weekend, but anyone else could just copy https://github.com/tgstation/-tg-station/pull/13474/files.

**Comment by Groudonmaster** [comment]
I'll look into it later. I want able to find the pull from tg was my issue

**Comment by Groudonmaster** [comment]
I'm gonna go through and add all of these tonight hopefully.
