### ISSUE TITLE
Health analyzers are completely useless

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#242]
![capture](https://cloud.githubusercontent.com/assets/12787230/12860903/41bd1a70-cc68-11e5-9ce0-a86d91df2f09.PNG)
^Three clicks on self.

**Comment by Super3222** [comment]
Tried it in game. I can't seem to reproduce the same bug, It worked correctly on myself and other people.

Any more details?

**Comment by Cruix** [comment]
Could it have been a rad laser? Did he collapse soon after for no apparent reason? (Even if he didn't, it might have been recharging)

**Comment by ShadowDeath6** [comment]
Radlasers do that. Examine the health analyzer or use it in your hand to check if it's a radlaser before scanning yourself, that usually helps.

**Comment by Super3222** [comment]
If it turns out he used a radlaser on himself 3 times and didn't realize, I'm gunna cry.

**Comment by Time-Green** [comment]
Nope

I tried it aswell and it does exactly that

I cant scan myself. I was a pirate in that round

**Comment by Cruix** [comment]
Found the bug, it was my fault. Need to add a conditional between lines 128 and 129 in scanners.dm. For now, you can make them work by opening the cybermen panel and initializing the cyberman network every round.

**Comment by Groudonmaster** [comment]
Solved in #257 awaiting merge.
