### ISSUE TITLE
Lethal darts bug

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#243]
12:22:11 - Time-Green - I discovered a bug with lethal darts. Once they leave your gun by shooting, they turn to normal baby darts
12:22:11 - Time-Green - Ticket created by Time-Green
12:24:24 - George99/(Nathan Fields) - Lethal darts?
12:24:49 - Time-Green - Yeah, when you remove the safety cap with a screwdriver, they should hurt people. But once you shoot them they are magically normal again

**Comment by Cruix** [comment]
In code/modules/projectiles/ammunition/ammo_casings.dm replace line 257 (A.loc = BB) with "A.loc = src".
In code/modules/projectiles/firing.dm add starting on line 29:
If(istype(BB, /obj/item/projectile/bullet/reusable))
src.loc = BB

(I couldn't add tabs but I know any coders could figure the indenting out)
That should work and not break anything. Someone do this and make a PR, I can't right now.

EDIT: You'll also need to add some stuff to on_range and on_hit in code/modules/projectile/projectile/reusable.dm to make the projectile set itself as the BB of the first thing of it's ammo_type in it's conents. While you're at it you can make some of the copy-pasted code into a single new proc. And you'd have to find a way to make the dart not qdelete itself...just forget I said anything. As usual, refactoring old code gets complicated fast...

**Comment by X-TheDark** [comment]
As a note, just removing the cap is not enough to make the dart hurt people, as it does 0 damage, you need to insert a pen into it. But I guess the issue is them turning into normal darts.

**Comment by ShadowDeath6** [comment]
I don't think penned darts will work, sadly, and I'd like to have this fixed for dank ranged gang converts and 20u sleepypen darts.

**Comment by george99g** [comment]
@Cruix / @X-TheDark any update on this?

**Comment by Cruix** [comment]
I have a halfway done solution, I'll work in it.
