### ISSUE TITLE
Donor Races - Simple to implement features/Cosmetic eyegrabbers

### ISSUE THREAD

**Issue by R3DGL4R3** [yogstation13/yogstation-classic#244]
Obviously this is just a suggestion,and opinions will vary.I'll organize it by simplicity and include a small lore entry below each.

Grays - Reskinned humans with telepathy/Speech augmentations
Agents of the mothership employed by NT after first contact,these stereotypical aliens have been altered via their radically strange science  to be capable of human speech.NT currently is in discussion with the creatures leaders and is exchanging [REDACTED] for their services as anything from science officers,to lowly janitors.

Possible gameplay mechanics:Telepathy allowing them to deliver messages to outside species over long distances silently,takes more brute damage due to being a frail,technological species.

Plasmamen - Reskinned humans encased in biosuits
The unfortunate victims of plasma research,these beings are humans infused with plasma to the point that they leak plasma from their very pores.Encased in advanced biosuits,these rare few are effectively held prisoner by NT with loyalty implants,greased palms,and luxury accommodations.They're typically found in powerful postions,or with larger than average paychecks.What's a life of torment and living in secrecy to ensure your family is well kept.

Possible gameplay mechanics:Removal of a Plasmamans biosuit will cause them to leak plasma at a low rate,poisoning those around them and potentially being ignited.If set on fire without their biosuits,they burn until dead.Biosuits are modified for different jobs,more armor for sec,radiation protection for engineering,fire for atmospherics etc.

More to come.

**Comment by krgii** [comment]
Ghouls - Heal when exposed to radiation

**Comment by Time-Green** [comment]
Fishmen. Highly resistent to cold
But need watur
