### ISSUE TITLE
LIGHTS ARE STILL FUCKED

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#246]
BLACK TILES EVERYWHERE

RIP SHADOWLING

**Comment by ShadowDeath6** [comment]
Shadowlings actually aren't affected by it, they only get hurt by the lights that are actually on. 
It looks super fucking awful though and people can see them spookying around.

**Comment by george99g** [comment]
@TehFlaminTaco

**Comment by TehFlaminTaco** [comment]
Can I just delete issues like this? I am aware it's fucked, the fix has been sent to master, and we are waiting for a pull to live.

And remember, I AM AWARE THAT IT'S FUCKED.

**Comment by DavidEdwards** [comment]
Yes, you can just close anything you think is not relevant. Just make sure that you specify why.
