### ISSUE TITLE
Add a surgery equipment to security

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#248]
Ussually when you catch a Cyberman or thrall, you can either kill him or deconvert.

ussually kill since security has no way of deconverting, only to give them to medbay. 

Wich is kinda stupid because in those rounds you dont want to trust others.

I discovered security had a defibrillator. Why not add a surgery table and tools?

This way people will be deconverted and it keeps them in the game.

**Comment by shrimptk** [comment]
my dude

http://forums.yogstation.net/index.php?threads/revamping-brig-area-including-labor-camp.8482/page-4

**Comment by Time-Green** [comment]
My god, why is that not added yet?

**Comment by shrimptk** [comment]
ask the coders >>>
