### ISSUE TITLE
Brig Revamp, Again

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#251]
http://forums.yogstation.net/index.php?threads/revamping-brig-area-including-labor-camp.8482/page-4

Gimme good feedback and I'll push for finalization and merging. kthnx

**Comment by Time-Green** [comment]
Its amazing. He showed it to me and this solves so much problems. 

Perhaps also a mini-cargo bay for in those edgy rev/gang rounds?

I fully support this

10/10

**Comment by shrimptk** [comment]
@timkoster1 minicargo would be 2op, raiding cargo on rev rounds is the best part too.

**Comment by DavidEdwards** [comment]
It looks interesting. This has been waiting for quite some time on the forum, and I think we need some proper feedback now here on Github. 

There are some things missing. Like for example, the soap from perma. Antags might find that useful in a scrape.

**Comment by shrimptk** [comment]
@DavidEdwards Didn't sweat too much on the details, the map build pictured on the forums is off of the /tg/ build, and was done prior to yog going opensource.

**Comment by shrimptk** [comment]
Once I get enough good feedback, and approval from coders, admins, etc. I'll get to work on merging it to yog.
