### ISSUE TITLE
Chameleon Belt

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#254]
Adds a chameleon military belt that you can use in-hand to change its appearance to any belt, which basically gives you 6 extra pockets that can be disguised. 

This is important because military belt is a great item but it's an immediate permabrig so nobody buys it ever. 

Disguise options- 

Toolbelt
Medical Belt
Security Belt
Fannypack
Janibelt
Military Belt for those badass traitors

**Comment by Cruix** [comment]
Will this replace the military belt or be an different item? Will it be more expensive?

**Comment by ShadowDeath6** [comment]
It would replace the military belt on the traitor uplink, but the regular belt would still exist for newcops and the like. 

Price is debateable, I'd say 5 tc would be good.

**Comment by Super3222** [comment]
:+1:
This would be great and a bonus we finally get rid of the military belt that no one buys.

Just think of the situations where an officer takes off your tool belt and finds a nuke disk, hand tele, hyprospray, and an esword.

**Comment by ghost** [comment]
5 TC sounds a bit much.

You can buy veritable all access and inconspicuousness for 5.

Belt should be 2-3 TC. Liek cham jumpsuit.

When EMP'd should flash R A I N B O W

**Comment by X-TheDark** [comment]
I'm terribly sorry for being retarded, but what's the difference between military belts and other ones? Couldn't find a definitive answer by quick-searching the code. Does it hold anything that can fit into the pocket slot or something (Judging by the code, it's can_hold is not set, so it can hold anything)?

**Comment by ghost** [comment]
It can hold anything that fits into the pocket slot. You can't put in shotguns, for example, but pistols, crowbars, emags, nuke disks...

**Comment by Super3222** [comment]
What sucks about it is if you attach a silencer to a pistol, it won't fit in the belt. Revolvers also don't fit.

**Comment by shrimptk** [comment]
@Super3222 That should be added, what good is it if you can't have a revolver anywhere but your backpack or exosuit

**Comment by ghost** [comment]
I can try to add it.
