### ISSUE TITLE
Cable cuffs + wirecutter = cable coil ?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#255]
I suggest that we make it possible to make coils out of cable cuffs with a wirecutter. There is no other way to recycle it.

**Comment by ghost** [comment]
Idea: allow cable cuffed people to cut their cablecuffs in ~10 seconds if they click on a wire cutter.
I think this your idea is good, aquir.

**Comment by Super3222** [comment]
I think that if you are holding the cable cuffs in your hand, you should be able to untie it through activation.

Now if you use wire cutters on it while it's in your hand, I think that should just produce cable pieces.

**Comment by ShadowDeath6** [comment]
Secret robust tipperino- You can attack someone who is cabecuffed or ziptied to instantly free them. 
Zipties turn into the cut form, while cabecuffs just vanish.

**Comment by Super3222** [comment]
@00aquir How do you feel about people untying cable restraints by simply pressing Z (or double clicking it)?

**Comment by 00aquir** [comment]
I'm ok with using them in hand to make coils.

**Comment by DavidEdwards** [comment]
Seems good in principle. I like Groxics idea too. If there is a cable cutter laying around, and you click on it when you are cuffed. You should be able to fiddle around until you get it in the right position to cut it.

Longer than 10 seconds though.
