### ISSUE TITLE
Adminforced revheads don't display resist message on implantation

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#259]
step 1: viva keek

step 2: keek gets implanted

step 3: no resist msg to the living but resist shows to deds

**Comment by Time-Green** [comment]
http://imgur.com/5ZuP1a5 As ghost

**Comment by X-TheDark** [comment]
Is this done via the Traitor Panel things?

**Comment by X-TheDark** [comment]
From local testing, you still get the "X seems to resist the implant.". Will see if I can test this on the server with someone.

**Comment by ghost** [comment]
Seems fixed now.
