### ISSUE TITLE
Make varedits log to admin_log.txt file.

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#26]
opened by Andreas (AsV9) · 2 months ago
ADMIN LOG: [timestamp], [username] edited [object]'s [variable] to [value].
Like that^

**Comment by Cruix** [comment]
Doesn't it already do this to [date]/Admin.log?

**Comment by Groudonmaster** [comment]
Doesn't it already do this to [date]/Admin.log?

I thought it did this already too.
