### ISSUE TITLE
Random Blind Players (BL1ND L3G1ON)

### ISSUE THREAD

**Issue by TehFlaminTaco** [yogstation13/yogstation-classic#264]
Randomly, seemingly only one player per round will be completely blind, with no way to resolve this.

Although fun for me, an issue for many people.

Unknown cause, cannot be replicated, client based, not mob based.

**Comment by TehFlaminTaco** [comment]
Definitely not one person at a time, and those suffering will keep suffering, even between rounds.

**Comment by shrimptk** [comment]
**DISCLAIMER:** This issue was found _prior_ to myself blinding @TehFlaminTaco with a screwdriver.

**Comment by TehFlaminTaco** [comment]
The fact that it's every round kind of suggests that, yes.

**Comment by Groudonmaster** [comment]
This appears to be an issue with byond 510.  Probably something to do with our updating regex and I don't know enough about that so if someone who does look into that that'd be great

**Comment by X-TheDark** [comment]
Merged and done.
