### ISSUE TITLE
Make the hijack objective more common

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#265]
We need more of them explosive tator rounds. Currently hijack is very, very rare.

**Comment by Time-Green** [comment]
ik denk dat het grote probleem hier is dat je 2 opdrachten krijgt

Als je alleen de Hijack krijgt dan is het nog wel te doen

Maar als je eerst de capitein bijvoorbeeld moet dode, lastig om ook nog te Hijacken

**Comment by Time-Green** [comment]
What the hell did I just do?

Just remove the first objective

hijack is already hard enough

**Comment by DavidEdwards** [comment]
I would prefer to keep Hijack at its probability that it already has. I don't want to create even more situations where murderboning is switched on. In my opinion, the server has a good balance. I would close this, but I would like to get more feedback before I do.

@ Everyone else: thoughts?

**Comment by FluffySurvivor** [comment]
Imo high pop tator rounds should make at least one traitor have hijack. This way we can involve everyone in the gamemode, not just the antags or their victims. Murderbone is not a bad thing in itself, it's pretty much what antags are supposed to do. Anyway, when someone gets hijack he generally fails hard. Hijacking brings new strategies and gameplay to the table.

**Comment by ghost** [comment]
mmmm yea i sure love that tasty murderbone

you don't want new strategies you want to beat off your murderboner to the sound of eswords fluffy

as usual

**Comment by Cruix** [comment]
I personally am not a fan of increasing the chance of hijack. However, if it were increased, it is likely that more people would buy the damn encryption key and be encouraged to work together for that tasty murderbone, and getting people to work together is always good.

**Comment by oisin100** [comment]
I personally dont like the sound of increasing the Hijack objective... We have enough murderbone as it is right now. _cough_rev_cough_

Even in high-pop round having just one hijack traitor in a lot of positions causes havoc EG(Atmos plasma loops, Scientists bombings, Chemist mass lube, Virologist just no please.)

**Comment by DavidEdwards** [comment]
Closing the issue, the concensus is clear.
