### ISSUE TITLE
Mo blobby mo problems

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#267]
Okay so, blob rounds tend to become a little boring for, well... the people who die.

So, how does one get people back into the round during bleb? Simple!

Make all the currently NPC-controlled blob mobs (spores, blob zombies, blobbernauts) able to be controlled by ghosts. This would also very slightly buff their stats just to make it so you can play them for more than ten seconds.

Just a neat way to get people back into the round.

**Comment by Time-Green** [comment]
Pretty good idea, do make them slower, since it would be too OP otherwise

**Comment by oisin100** [comment]
Did you just say make a already pretty powerfull mob player controlled AND Buff the stats?

Paragon... Your a madman...

Other than that i like the idea!

**Comment by Cruix** [comment]
I believe tg does this. There are constant complaints on their forums about how OP blobernaughts are, and asking that they make them mindless again.

**Comment by ghost** [comment]
NO FUCK NO

IMAGINE FUCKING SETINENT BLOB ZOMBIES

YOU SEE THAT SHIT?

YOU WANT A FUCKING MELEE MOB THAT JUKES AND DODGES ALL YOUR SHIT AND AMBUSHES OYU AROUND CORNERS?

YOU WANT THAT? NOPE.

There's a fucking reason xenobiology setinence is so fucking hard to get and if you have setinent spores and setinent blobbernaught spam you end up WORSE than /tg/ especially because our current bullshit blob chems are more likely to kill you on the first fucking two hits!

No!

**Comment by DavidEdwards** [comment]
I like the idea. I would be OK with controlling all blob mobs, if they were also NERFED when you inhabit them. It is a buff to the creature to be able to know when to retreat and regroup, so basic stat debuffs would be necessary for balance.

The blob should be able to control that with a sentience preference. If they don't want players to control the mobs (default to allowed).

**Comment by ShadowDeath6** [comment]
Should make the person that a blob spore attaches to able to play as a zombie. Also the bullshit blob chems don't affect blobbernauts as of now, only smoke which doesn't pose much problems due to its low injection.

**Comment by ghost** [comment]
blobbernauts apply their reagents onhit

lexorin jelly blobbernauts are likely to one or two hit kill you

**Comment by FluffySurvivor** [comment]
Dem microing spores? 
Please no

**Comment by Stealthkibbler** [comment]
lexorin jelly blobbernaut :^)
