### ISSUE TITLE
Buff Mediborgs

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#269]
Mediborgs are decently powerful, but in some cases they could need fixing. 
1. The module they get from being hacked is literally awful, it doesn't do anything anymore due to the way spraybottles work. 
   I propose they get a toxins/lethal chemical hypospray upon hacking, similar to medibots. 
2. Add an upgrade to robotics that gives mediborgs defib paddles so they don't need to clone or bug medical for not using defib.

**Comment by Time-Green** [comment]
Something like Neurotoxin or Toxin could work. If thats not too OP

And defibs? YES
This is so needed, medbay is ussually bizzy fucking the genetics window to clone someone that is critted.

Not necceseraly an upgrade. Just make it take alot of power. Like 2000?
And place a cute cuborg recharger in medbay storage

**Comment by Kmc2000** [comment]
+1

**Comment by Super3222** [comment]
> Something like Neurotoxin
> not too OP
> not too OP
> too OP
> O
> P

No, and only no if you are talking about the bar-made version. For one, it wouldn't be of any use unless their inbuilt hyprospray had some of it in them. Considering the other option of adding it to a spraybottle, would literally do nothing.

I definitely agree with the defib upgrade though. That would definitely be useful.

**Comment by ghost** [comment]
Emagging a mediborg should provide it with an emagged defib.

Or instead of a bottle of acid, a hypospray of some random traitor chem, or perhaps the chem in the bioterror sprayer/bioterror syringe gun.

**Comment by ShadowDeath6** [comment]
> chem in the bioterror sprayer

What does that even do? I've literally never seen it used. 
Also maybe an emagged medborg could GET a bioterror sprayer, which would make it great for crowd control.

**Comment by ghost** [comment]
Bioterror sprayer is spore toxin, unstable mutagen, neuvulscine and some other thing.

Basically it stuns you, mutates you, mutes you, and then does a tap dance on your gonads while singing about eswords.

**Comment by DavidEdwards** [comment]
Looks good. Generally I am open to this. Request 1 needs to be finely tuned.

**Comment by ShadowDeath6** [comment]
I'd just say to give them a new, seperate hypospray upon emag with some medium-deadly chemicals. 
Toxin, neurotoxin (chem kind not bar kind), and maybe lexorin if that wasn't nerfed too hard.

**Comment by ghost** [comment]
Serviceborgs get a murder instastun oldchloral.

Secborgs get a laser gun.

Janiborgs get lube.

engiborgs get an instant stun.

Mediborgs need to be as OP as the others-Seeing as their hypo would have to be in melee (flashing) range, yes, they should have neurotoxin bar kind in the hypo.

**Comment by ShadowDeath6** [comment]
Other than bar neuro, I can't think of a chem that would be strong but not stupidly powerful like stuff in the poison kit. Unstable mutagen could be good.

**Comment by ghost** [comment]
This is done.
