### ISSUE TITLE
Make Silenced Pistol a small item. 

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#270]
I know, realism and mass or whatever, but I'd like to see this be used more as a stealthy item that can fit in pockets and other places.  Also it can't fit in military belts due to its size which makes me !angery!

**Comment by Time-Green** [comment]
A stealth item that cant be placed in pockets etc?
Thats bloody retarted. 

Good idea

**Comment by ghost** [comment]
no

this is the downside to the silenced stetchkin

you trade it being a fucking bullet ebow with no chance for reaction for shitty inventory manaagement issues

get a fannypack fucker

**Comment by DavidEdwards** [comment]
The thing is, a pistol might fit in a pocket. If it was deep enough. A pistol with a massive extra barrel surely won't.

I wouldn't have a problem with it fitting onto a military belt though.

I will close this issue, as I think that when it has a silencer attached, it really isn't small any more.
