### ISSUE TITLE
Interacting with materials

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#275]
When there's no gravity, you can move next to a lattice (or wall), but not the floor tiles that you put onto them! We should change that.

**Comment by Time-Green** [comment]
This is unclear. But i'm assuming you mean you should be able to walk on the floor with no graffiti?

Or do you build floors on walls? 

Please explain this. I really cant understand it.

What you're saying is that you cant move on floors you place on walls. 

._.

**Comment by DavidEdwards** [comment]
Hold on - "when there's no gravity". You can't hold onto floors when there is no gravity. Is that what you mean? If so - that is entirely intended.

**Comment by 00aquir** [comment]
If you can hold on to lattice and a simple wall, why is it not intended to do it with the thing structurally halfway between them? (It's basically the same solid material, you should be able to grab them just like you do it with a simple wall, it's not like walking on them)

**Comment by DavidEdwards** [comment]
It makes working in no-gravity environments more difficult. Otherwise, why bother disabling gravity at all as an antag.

For now, I will close this issue. If anyone else chimes in, thinking this needs to be changed we can reopen it.

**Comment by 00aquir** [comment]
Ah, gameplay balance.. okay then.
