### ISSUE TITLE
Moar botany

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#279]
More botany plants!

EMPeaches, a mutated variant of Peach, which would also be a new plant.

An ambrosia variant that contains strange reagent instead of omnizine.

Alien weeds, a mutated variant of normal grass.

Zapples, an electrically charged mutant variant of apple. Literally just shocks the idiot stupid enough to eat it, also stuns when thrown, stuns for longer on higher potency.

Lemonade Trees, a mutated variant of lemons, that literally just harvest into cups of lemonade.

Pears, a separate plant.

Bears, a mutated variant of pairs, which harvests into small, edible teddy bears with a high sugar content.

Mangos, a tropical fruit that heal burn damage via kelotane in them.

Golden Mangos, a tropical fruit (for dwarves) that heal burn damage and provide minor stun resistance through epedephrine!

Fig trees, which grow figs, used in pastries or just sweet to eat.

Fib trees, which grow bright red, veiny figs that contain neuvulscine.

Cannabis-Weed! WEED! WHY DO WE NOT HAVE WEED FOR BOTANISTS YET?

Radabis-Weed with unstable mutagen in it!

**Comment by Cruix** [comment]
Strange reagent can already be produced by botany, provided they are supplied enough unstable mutagen.

Why make lemonade trees when you can just juice lemons in a grinder?

Ambrosia already is weed.

Plant that makes unstable mutagen will lessen departmental interaction (i.e., will lessen botanists breaking into chemistry because the chemists are AFK, non-existent, or just plain suck). You can already grow glowshrooms for ghetto unstable mutagen.

All that being said more for botany is always good. Also organ plants.

**Comment by ghost** [comment]
Ambrosia isn't weed enough, doesn't have mindbreaker toxin in it.

Lemonade trees for the same reason there are Egg Plants while chickens are mobs-it's fucking funny.

Omnizine can also be produced by botany w/o deus, ect-doesn't mean there shouldnt' be a plant specific to it.

Organ plants might be nice-Synthbrain, synthlimb, ect, to allow surgical replacement of organs or even limbs with plant parts, so that body part heals on it's own/brain/heart replacement

**Comment by oisin100** [comment]
Organ plants would be an awesome way for dead players to come back into the game! They would literally be a Vegetable!

I agree with Cruix though we shouldn't have Unstable Mutagen plants or lemonade trees... Other than that i love all the other plants...

**Comment by Time-Green** [comment]
Holy fuck yes.
You can make a Vegetable puzzle to make new players.

**Comment by ToGWtF** [comment]
Throwable taser plants seem a bit too greytidey. Even a half-second instant stun is incredibly easy to overpower someone with. Maybe have them do stamina damage. 91+ potency instant stun.

Mutate bear plants into Gummy Bear plants that have some healing chem in them as well kek

Changling enfeeble sting plants seem overpowered as well. You can easily grow them 90 potency with a little help from research and mass produce enough to perma-stun someone

**Comment by ghost** [comment]
Daily reminder that botany can grow toxin-spewing flesh eating vines, killer tomatoes, 45 damage instant stun eswords that also melt your clothes, maxcap grenades, 50 dmg burn plants, two of the most lethal toxins in the game, and the most potent anti-shadowling tool in the game.

**Comment by oisin100** [comment]
Peaches, EMpeaches, Pears, bears, Mangos And Figs are done.
How should people be able to attain the Organ plants?

Still looking for sprites for all the Veggies.

**Comment by ghost** [comment]
As Oisin's doing this, closing.

**Comment by oisin100** [comment]
Should probably keep this open for feedback until the PR is open.

**Comment by oisin100** [comment]
This is still being worked on,

**Comment by Silvaplex256** [comment]
Can someone make a list of sprites for me to make?

I'll [probably not, fuck DM] be able to sprite some veggies, but first I'd like everyone to agree on what should be sprited.
