### ISSUE TITLE
Ore redemption machine bugs when depowered and crowbar'd

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#28]
opened by Nicholas Weber · 2 months ago
Quoted from user because I have nerve damage in my hands.. "The power was out and a shaft miner was stuck with his ID in the machine so I just went up to crowbar it out which I've known from experience works with the computers that require ID insertion.
BUGS BUGS BUGS!
The first bug I noticed was that the ore machine became noclip and anything could pass through it. The second bug that happened was that when the power returned I hit eject ID and the ID that had previously been removed by crowbar was duplicated. Then there was a third bug where it started making 0 sheet stacks. And not to be out done- there was a stupendous fourth bug an admin and I discovered when he got fed up with the mess and decided to admin replace the machine. He asked me to start removing metal until I realized it was infinite for a finale bug!"
Source: http://forums.yogstation.net/index.php?threads/ore-redemption-machine-bugs-when-depowered-and-crowbard.7557/#post-76941

**Comment by Super3222** [comment]
Does this bug still happen?

**Comment by X-TheDark** [comment]
No. The only bug I did find is the ID related one that was fixed in the linked PR. Everything else cannot be reproduced.

**Comment by AsV9** [comment]
That's weird. I tested this 10 days ago when I self assigned this and I was able to reproduce the bug perfectly.
