### ISSUE TITLE
Make picking up a drone take 2 seconds

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#280]
'HURR DURR I LOVE TO FUCKING PICK DRONES UP AND SPACE THEM BECAUSE VALID'

**Comment by ShadowDeath6** [comment]
+1 fuck the butthurts who grab drones

**Comment by X-TheDark** [comment]
I am not going to lie, what will 2 seconds change?

**Comment by Time-Green** [comment]
+drones best hat 2016

And please, remove drones from the valid list.
I dont like assistants killing me on sight for keks

**Comment by DavidEdwards** [comment]
I think this is a good idea. +1

**Comment by FluffySurvivor** [comment]
-1 i hate metagaming drones and this would make them very hard to kill

**Comment by Time-Green** [comment]
+1 Why would you kill them?

**Comment by X-TheDark** [comment]
In all fairness, right now they are basically that beastrace from hippie. You can kill them at your will, but they cannot respond to you.

**Comment by ToGWtF** [comment]
If you put a drone on as a hat and die, he can't ever escape.

**Comment by ghost** [comment]
I can try to add this.

**Comment by krgii** [comment]
Drone laws don't allow you to get mad people space you.
