### ISSUE TITLE
Port Holoparasites

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#283]
Ports holoparasites/guardian spirit/STANDO from tg, pretty self explanatory. 
Also need to add the injector kit to the traitor item list so traitors can buy them. 

https://tgstation13.org/wiki/Holoparasite

Fun item, gives dead players a chance to be back in the game and gives traitors backup/a different way to use their items. 

We need more JJBA memes on our server anyway.

**Comment by Time-Green** [comment]
Already exist in the code.
But admin spawned, once got one by sacrificng the Cap as revchaplain

I am not sure about this yet

**Comment by ShadowDeath6** [comment]
> Already exists in code

It was in a while ago, but I think it was fully removed or something because every admin I've asked can't spawn it.

**Comment by ghost** [comment]
No

It's shit

No

**Comment by X-TheDark** [comment]
It's basically like revenant, only you have some really good direct attack options and you almost never die and you are automatically combo-cafe. So yeah...it's pretty unbalanced.

**Comment by ShadowDeath6** [comment]
Except they're super weak to ranged things and all damage done to them is transfered to their host, which if they die, they'll both be gibbed.

**Comment by ghost** [comment]
except they're the #1 murderboning tool on /tg/ and regularly depopulate the whole station, can heal their master, do a shitload of chaotic shit, and you can literally just camp in medbay surrounded by 8 medibots and spam applying brute and burn patches and drinking bicard to shrug off any damage done to them.
- there's a ranged holo.

**Comment by Stealthkibbler** [comment]
I remember watching a holoparasite on TG, its master got critted by a valve bomb and it just jumped out and healed him back to full health in a few seconds.

The only downside is that when the holoparsite takes damage the master does, but from what I saw it took a hos with a double esword to even combat one on fair grounds and the Parasites ability to jump out of its host without warning makes it a stronger gank tool than any of the changelings abilities combined.

**Comment by ghost** [comment]
Never forget 20 firestack chaos parasite that bursts out of someone you just cuffed and fucking flails you to death.

Never forget healing holoparasite that teleports you to a tiny rwall box in space that you can never escape from.
