### ISSUE TITLE
Nerf to shotgun darts and remove grinder

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#29]
opened by Alex West · 2 months ago
People are making instakill shotgun darts by having a fuckload of reagents in them in 3u doses. 10 in total.
So, my proposition to nerf this is to make it so it can only contain 3 different reagents. 30u limit can remain the same though, that's fine. But having 10 lethal reagents proccing at the same time is just death instantly.
Also remove the grinder. >_ Durands and phazons every round is not how shit should be.

**Comment by Super3222** [comment]
This was already done, wasn't it?
And I think the shotgun dart nerf is unnecessary, only professional chemists (like b1g) would know what would go good in them.

**Comment by DavidEdwards** [comment]
Grinder was disabled.
