### ISSUE TITLE
Bandage duplication

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#294]
This is only a graphical glitch, as you don't end up with two useable bandages

> Begin to apply bandage
> Switch hands
> You switched hands, so you drop bandage because you failed to put it on
> But you drop bandage from a hand that was empty, leaving the real bandage in your other hand
> Pick up bandage on ground, bandage switches hands
> The hand the bandage was in now has an invisible bandage
> Use bandage from either hand, it uses both up

Also, you can use a bandage from an empty hand if you have it in the opposite hand. Not sure if this behavior was intentional.

**Comment by Cruix** [comment]
> Also, you can use a bandage from an empty hand if you have it in the opposite hand. Not sure if this behavior was intentional.

I am unable to reproduce this, can you give more details?

**Comment by ToGWtF** [comment]
Uh. If you hold a bandage in one hand, duped or not, you can switch to your empty hand to apply it to yourself
