### ISSUE TITLE
more clown slots

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation-classic#298]
please its been 2 months since i got clown with a high preference.

**Comment by AsV9** [comment]
good meme

**Comment by krgii** [comment]
donor clown slot

**Comment by Stealthkibbler** [comment]
suffering

**Comment by FluffySurvivor** [comment]
shhhh
mapaku is kill

**Comment by ShadowDeath6** [comment]
Meme tag when

**Comment by DavidEdwards** [comment]
That couldnt possibly have any bad consequences......... That said. I would consider it. Any serious thoughts?

**Comment by Stealthkibbler** [comment]
people said no last time, but the people who said no are the people who never play clown/mime, it would be nice having extra mime or clown slots at round start since it's so hard to get it now.

**Comment by ShadowDeath6** [comment]
Make more mime slots, not clown. People love silent people that don't slip you.
