### ISSUE TITLE
Shadowling - Bugged vision and ascend ability

### ISSUE THREAD

**Issue by Silvaplex256** [yogstation13/yogstation-classic#305]
Every time I play shadowling, I cannot ascend nor can I hatch when the time comes because of some horrible bug.

Also, when shadowlings spawn, they do not have any ability to see in the dark (which I believe is really retarded, may or may not be a bug).

**Comment by ghost** [comment]
shadowlings can't see in the dark in human form

they CAN when hatched

not  abug

**Comment by DavidEdwards** [comment]
Thanks Silva, if you think this really is a bug. Just reply again here.

**Comment by Silvaplex256** [comment]
When I opened this issue, I mentioned two things.

One of them being the possible bug involving shadowling darksight (which was proven to be in fact not a bug).

The other was the **bugged ascend ability**. Every time I play as a shadowling, I lose the ability to hatch/ascend near end-round. More testing is needed, but I view this as a fairly serious bug.

**Comment by DavidEdwards** [comment]
Ah ha, I misread that. Thank you for the clarification.

**Comment by Cruix** [comment]
Possibly fixed by #537? Were you unable to ascend even after you had hatched?
