### ISSUE TITLE
Mech grav catapult insanely op

### ISSUE THREAD

**Issue by Paroclomas** [yogstation13/yogstation-classic#307]
For something that can be acquired fairy easily by a competent science team, and that can be mounted even on a ripley, the grav catapult is much too powerful.

a traitor with one, without even being in my LOS just bounced me around and in 2 seconds i was dead, then there was an open window to space and instantly i got lol killed...

it sould be nerfed

**Comment by ToGWtF** [comment]
Does it not cost Silver/Gold/Diamond?

**Comment by Paroclomas** [comment]
I don't think thats enough

**Comment by ghost** [comment]
it costs nothing

it's also adminthrow for mechs.

There's no cooldown to tossing-you can wall people to death near instantly and it's not logged at ALL

**Comment by Super3222** [comment]
Maybe it should cost as much as the mech RCD, since it appears to be in it's tier.
