### ISSUE TITLE
Ghost teleport buttons missing brig and other areas.

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#31]
opened by Alex West · 2 months ago
Missing bridge and most brig areas.
Also, it did show brig control at one point and this is what happened when I tried to click it:
Sorry, the following is not valid: Brig-Control8û1 usage: [ parameter]
http://puu.sh/leXtE/bd93a732e6.png

**Comment by X-TheDark** [comment]
Is this still relevant?

While there aren't any areas like "Captain's Quarters" or "Brig Cell 1", I have to wonder if these are even necessary.

Also, Brig Control works properly on the latest dev.
