### ISSUE TITLE
Make crematorium emaggable

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#311]
It doesn't make sense for it to be resistant to emags.

**Comment by ShadowDeath6** [comment]
I assume you mean the button to activate it? Would it just allow anyone to cremate?

**Comment by ToGWtF** [comment]
what exactly would an emagged cremator do?

**Comment by Time-Green** [comment]
Grow feet and leg and go on a killing spree?

**Comment by DavidEdwards** [comment]
I think everything should have an emag function. Open to suggestions.

**Comment by oisin100** [comment]
Suppose its new meta to emag crematorium... Instead of just throwing people out of airlocks..

**Comment by ghost** [comment]
Not everything needs to be emaggable, for fuck's sake.

Let's buff some of the other weapons in the traitor arsenal instead, so that the god damn only item purchased isn't the damn emag over and over.

**Comment by DavidEdwards** [comment]
I would be very happy if every object had an emag function. It doesn't necessarily need to be something that allows you to easily get rid of bodies. It could infact simply be used to cause a distraction.

**Comment by shrimptk** [comment]
I bet he means the button.

**Comment by Cruix** [comment]
New feature: you can emag an emag. This will make the emag capable of emagging everything, including other emags.

**Comment by ShadowDeath6** [comment]
Emag the crematorium to make it not leave ashes

**Comment by AsV9** [comment]
@Cruix pls

> New feature: you can emag an emag.
> This will make the emag capable of emagging everything, including other emags.
> 
> including other emags.
> 
> other emags.

**Comment by doerakpoes** [comment]
Im with the suggestion above this one that actully isnt a suggestion as in mine isnt
