### ISSUE TITLE
Shuttle window placement bug?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#312]
I put the glass onto the grille from inside, this happened..
When shuttle was launched, I was able to make window normally.

![shuttle-window](https://cloud.githubusercontent.com/assets/16806055/13050404/751796ce-d3f3-11e5-8f8d-6d3eedc966e0.png)

**Comment by oisin100** [comment]
Not a bug. Glass isnt secured when its place on a grill. Thus the space wind pushes the window out of the frame.

**Comment by DavidEdwards** [comment]
Thank you for taking the time to report though!

**Comment by 00aquir** [comment]
well as I remember I didn't see the window move ( at all ), was immediately in space, I hope it wasn't lag but (but cannot entirely confirm), will check again if I can.
