### ISSUE TITLE
Emag pAI's 

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#316]
Gives them access to special abilities and Hologram forms such as:

> Toxin Synthesizer: Allows a pAI to print out a bottle of Venom every minute or so, and they must stand still for half a minute to complete the process. (80 CPU or whatever)
> Holographic Banana Launcher: Allows them to launch out one (1) holographic Banana that will disappear after 5 seconds, and requires a 20 second cool down. Good for that fatal slip. (60)
> Frequency Interceptor: Lets them tap into every radio channel, including the Syndicate one, and transmit vital information to their master, should they choose. (30)
> Digital Auditory Mutilator: Fuck it, lets give the little ventcrawling shit a bike horn. (90)
> Syndicat Sprite: Allows pAI to choose a red and black themed cat for their holographic form.

**P.S: FUCK YOU ADAM WE'RE EMAGGING EVERYTHING**

kthx

**Comment by ghost** [comment]
Retarded no.

'hurr durr traitor gets an already stupid useful free buff item that's another player that lets them scout for their target and talk their way out of their issues'

'hurr durr let's encourage purchasing of the same fucking item'

'hurr durr let's give it the one ability that pAI's were created not to have-the ability to actually interact with humans via slips and poison lol'

'Hurr durr let's let the pAI replace the traitor syndicate encryption key for fucking reasons lol'

The only decent one is the syndicat sprite and the digital auditory mulitator. Can't wait until this thing gets buried and forgotten like every other suggestion.

**Comment by ShadowDeath6** [comment]
Fuck off with buffing pAIs, they're fine as-is. Also you can emag one, it makes you its master.

**Comment by DavidEdwards** [comment]
For pAIs I am very happy to have additional functions, but only if they don't create an advantage.

> Frequency Interceptor: Lets them tap into every radio channel, including the Syndicate one, and transmit vital information to their master, should they choose. (30)

I am behind this only in sofar as it gives Syndicate radio access. Not access to other radio channels. That said, I think the head of the department / captain should be able to grant that to a pAI.

> Digital Auditory Mutilator: Fuck it, lets give the little ventcrawling shit a bike horn. (90)

Why the hell not. 

> Syndicat Sprite: Allows pAI to choose a red and black themed cat for their holographic form.

Fine with that.

**Comment by Kmc2000** [comment]
Did somebody say sprite ?

**Comment by doerakpoes** [comment]
Yas do emag pais it only makes sans ;)

**Comment by doerakpoes** [comment]
That shoud be a thing when you emag an pai it makes a sans

**Comment by ghost** [comment]
This is already existing and feedback is negative. Close it.

**Comment by DavidEdwards** [comment]
pAIs can be emagged? Did that get an in a recent PR? I didn't see that.

**Comment by ghost** [comment]
PAI's can be emagged to unbind them.

**Comment by DavidEdwards** [comment]
I would enjoy seeing some harmless functionality in an emag. Nothing that will actually buff them. I don't consider this a problem. Lets keep this issue open.
