### ISSUE TITLE
SHADOW GETS SALTY- EI NATH

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#318]
Ei nath is basically the 'fuck you' spell. Not only does it instakill, it deletes ALL items on you, deletes your body, and drops you as a brain who will probably never get back into the round as a human unless med has any free time outside of getting memed on by ei nath. 

People have probably said this before, since this is a widely talked about spell. 
I propose for the spell to work like a melee-range wand of death, instantly doing 200-400 (I can't remember how much lethal damage is) oxygen damage and killing the target. 

Might also need to change the spell's name to something that isn't disintegrate, and change the description of the spell in the spellbook. 

What this accomplishes-
People can be defibbed/cloned after death, meaning ei nath wizard who takes out robotics is no longer invincible. 
(Hopefully) Prevents salt in deadchat

Inb4 worst idea please go die

**Comment by FluffySurvivor** [comment]
Because the swarm of angry secborgs coming after you is surely fun. 
Ei math is the only reliable murder spell for wiznerds

**Comment by DavidEdwards** [comment]
I am hesitant to change the wizard. I think that this spell is fine how it is.

If more people complain, we can consider a change in policy. Perhaps, a serum could be researched that reduces the effect of El Nath to your suggestion.

**Comment by B1gb3ast** [comment]
I got an idea.

Why not make it so Ei'nath turns whatever you touch into an explosive?
Hold a pen. Click Ei'nath. There's now a glowing rune on top of it, pen explodes.
Wanna blow up a person? Grab them by their neck, click EI'nath, you blow their head off.

Possibly make it so the first level of EI'nath lets you blow up items on a short fuse, the second makes the explosion bigger, and the third would let you blow up people. That way, you'd have to invest to use it's full potential, sacrificing potential defenses.

**Comment by X-TheDark** [comment]
Problem is, EI NATH is kind of the only reliable offensive option wizards have. Now, obviously stun+EI NATH is a bastard to go against, but really, there's no other options except Fireball that can literally blow up in your face (other than that, I think Fireball is better than EI NATH since it downs people very often and has short cooldown)

**Comment by ShadowDeath6** [comment]
Other options for offensive spells-

Fireball
Lightning Bolt- Which will literally crit multiple people if you charge it
Wand Belt
Guns
Timestop+Ritual Knife

None of which turn you into a brain.

**Comment by ToGWtF** [comment]
I think its fine as it is. it kinda is the only reliable way of making sure your target doesn't come back/there is no sec to catch you in maint because a paramedic tracked their suit sensors

**Comment by B1gb3ast** [comment]
None of you think my suggestion to make Ei'nath blow shit up is a good idea.

YEAH NO OKAY DAS FIEN MATE KEEP BITCHIN' BOUT IT ANDYWAYS YOU NORMIES

**Comment by Super3222** [comment]
Wizard mode isn't suppose to be fair. It's suppose to make you rage so hard that you spam ALT + F4 and than shut down your computer.

That's why EVERYONE is allowed to hunt the wiz. Ei Nath has no reason to be balanced, it's suppose to be the way it is.

**Comment by DavidEdwards** [comment]
I will close this. I think it has run to its conclusion.

**Comment by ShadowDeath6** [comment]
Keep in mind that this would in no way nerf the spell, it would just prevent your round being completely ruined because somebody wanted the most "fair and balanced" spell.
