### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#321]
Revise the server rules. For example, what you can and can not do as an antagonist.

**Comment by ghost** [comment]
It's already there.

We don't need to add even more bulky rules.

It's very clear on what you can and cannot do and if you don't get it ahelp and ask admins. It's never been a problem for anyone.

**Comment by Time-Green** [comment]
Wouldn't mind a closer look on the rules.

Like, you're security. Am I allowed to torture prisoners? (no obviously, without caps perm)

But some closer look on the rules can be really usefull

**Comment by Super3222** [comment]
Don't forget that don't be a dick is a rule.

We are also suppose to use common sense, especially when playing Security.

**Comment by oisin100** [comment]
I've never seen anyone banned for being a dick.
