### ISSUE TITLE
Let borgs and AIs choose their own name when constructed

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#322]
Title, seeing way too many "Default Cyborg-122" and those shitty default AI names that you can NEVER CHANGE AT ALL EVER. 

Just, like, make a popup appear that prompts the borg/AI to pick a name. Didn't we have this a long time ago?

Also give syndieborgs the popup so we can see MemeLord dicing people with an esword

**Comment by oisin100** [comment]
We did i think... But /TG/ coders dont believe in fun so...

**Comment by Time-Green** [comment]
Please do so.

I am pissed being called standard-security borg 640

**Comment by Yackitori** [comment]
You can change your borg and ai names in your character setup...

**Comment by X-TheDark** [comment]
But not when you get borged by a Roboticist, unless he uses a multitool. And why make someone else pick a name for you if you can do it perfectly fine yourself

Functionally, this would be identical to Wizard, where upon borging/spawning as a borg/AI (?), you get to enter your name.

**Comment by DavidEdwards** [comment]
Sounds like a good little mini project! ++

**Comment by ghost** [comment]
This is being done by Pineapple.

**Comment by ghost** [comment]
Closing as Pine's doing it.

**Comment by X-TheDark** [comment]
Please do NOT close the issue until it is actually done and merged on the server.
