### ISSUE TITLE
Make cyberman broadcast display names

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#323]
Title. Closest antag to this is cult, and it displays names. 

Would help with coordination.

**Comment by Cruix** [comment]
The specification specifically said that names should not be shown in the broadcast. It can easily be made to if necessary.

**Comment by ghost** [comment]
no

either put a name in the broadcast when you announce or be stuck with anonymity until you subvert ai

**Comment by DavidEdwards** [comment]
> The specification specifically said that names should not be shown in the broadcast

I'll close this.
