### ISSUE TITLE
Make rezadone easier to mix

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#324]
Current recipe-
1 part Carpotoxin- Grinded from space carp fillet
1 part Cryptobiolin
1 part Copper

Due to the annoying amount of work it takes to get carpotoxin, nobody ever uses this chem. Would be nice to have chemistry give out cloning patches to genetics so patients can get cellular healing without cryo. Also would make being sucked by a slime less irritating since you could just stop off at chem instead of sitting in cryo for like 5 minutes.

**Comment by B1gb3ast** [comment]
Why not give xeno a box of these patches to start with?

**Comment by Yackitori** [comment]
Why not just buff cyro?

**Comment by Groudonmaster** [comment]
> Why not give xeno a box of these patches to start with?

:+1:

> Why not just buff cyro?

Because it used to be the standard for powergamers to just heal themselves using cryo and completely ignoring doctors

**Comment by ghost** [comment]
Cyro will not be buffed.

However, adding a box of rezadone patches would be quite useful for xenobiology to prevent slime cellular damage AND in a pinch when cyro is no longer working help medbay out.

**Comment by ToGWtF** [comment]
any competant scientist can build his own cryo in science, and a chem machine to make cryox

**Comment by ghost** [comment]
This is done. Close it.
