### ISSUE TITLE
Changeling Augmented Eyesight

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#328]
It sometimes bugs where you have thermal vision but not darkvision, even without glasses. Could be related to shadowling stuff.

**Comment by Super3222** [comment]
I'll be on it.

**Comment by ShadowDeath6** [comment]
Liar >:^)

**Comment by ShadowDeath6** [comment]
This doesn't seem to be happening anymore

**Comment by Cruix** [comment]
Probably fixed by #928
