### ISSUE TITLE
Mentoring system.

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#33]
opened by Xantam · 2 months ago
Can we have a mentoring system implemented?
Mentors would not be mods or admins, just players who have a title of mentor who can answer mentorhelps, instead of adminhelps.
Perhaps when you click the ahelp button, it gives you 2 options; Button 1: Admin help. Button 2: Mentor help
then it'll send tickets to the relevant people. Admins should get all tickets, including mentor ones. Mentors should only get mentor tickets.
Mentors should perhaps have their own chat. MSAY. They do not have any buttons, only access to mentor tickets.
Could we steal bay's code for moderator ranks and adapt it to fit this?

**Comment by Time-Green** [comment]
why the fuck is this sending me messages?

**Comment by george99g** [comment]
I have no idea. I'm closing these because, well, they're _old_.

**Comment by Time-Green** [comment]
It's on the old codebase, what does it matter?

**Comment by george99g** [comment]
It still shows up in my list of open issues.
