### ISSUE TITLE
Port /tg/'s newer blob chems

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#331]
Just because we aren't copying their blobbernauts doesn't mean more chems aren't good.

We currently have GG if you're hit (lexorin jelly) three of the same shit (oil, ripper, melter), meme chems (drugs, omnizine), get the fuck out (sorium), senpai notice me (dark matter), and Triple GG if hit (exploding gelatin)

Replace these with /tg/'s newer blob chems. Which are available in detail to look at on the tg wiki for blob.

Some highlights- 
Sporing pods, where killing a blob tile has a random chance to generate a weaker blob spore mob
Regenerative Materia, which uses miners salve to convince the hit that they are at full health until they finally end up in crit still convinced they're healed
Energized Fibers, which emp's but is far weaker in exchange
Cyrogenic Liquid, which injects you with frost oil and does stam damage

And far more.

Additionally, allow strong blobs to be used as advertised-buff them to cost 7 resource points over five to encourage their use, and allow them to actually block atmos as they are advertised.

Finally, copy over /tg'/'s addition of bomb resistance to blobs-5 minute gg round is amusing the first few times but gets old. Don't make them IMMUNE, but increase their resistance to bombs, so that bombing it in a room full of crew isnt just autogg.

**Comment by ShadowDeath6** [comment]
Oil does burn and firestack
Ripper does straight brute
Melter does brute and firestack

Blob buff when, also sentient blobbernauts when?

**Comment by ghost** [comment]
Never setinent blobbernauts
