### ISSUE TITLE
Adams Mining Rework

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#332]
Anyway ignore the title that was just some RL issues.

Anyway, mining atm is pretty dull for miners, hence why nobody does it and science is just a bunch of resourceless virgins.

So, let's rework it.

Firstly, let's add a few more minerals to it.

There are already some minerals available in code-adamantine, enriched uranium, and mythril-which already exist.

Let's put them to work.

Firstly, adamantine is the shit used to make golems, right? But why keep golems locked to xeno? There's already a golem race in the game that's rock-based as well as adamantine- put it to use.

Adamantine ore can serve two purposes. Firstly, akin to goliath plates, it can reinforce the mining hardsuit-or any other hardsuit-it is applied to. However, it would insulate against burn, not brute damage. 

Secondly, Adamantine would serve a much rarer purpose-filling in a golem shell. I have three ideas for golem shells- either make them artifacts, findable randomly om mining, make them craftable out of adamantine, or simply make adamantine slimes produce golem shells, making golems resource reliant on mining. 

Adamantine would be as rare as diamond. Adamantine floor tiles would not break when burned and adamantine walls would take two applications of a welder to cut through.

Secondly, enriched uranium would simply be smeltable from the ore refiner from 5 sheets of uranium. It would emit radiation at a higher rate, recieve cargo points if shipped off akin to plasma, and otherwise just act like it had the value of 5 uranium sheets. The downside, of course, is that enriched uranium would emit radiation even in sheet form.

Mythril is the next ore.
Mythril I was curious in. It's often a miracle substance used for armor or weapons. So, mythril would serve two purposes mainly. Applying it to any item increases the brute force of that item by 5, up to three times. Yes that means a miner with a katana is going to have a 55 dmg brute weapon and if that bothers you you are lying and you want a twohit murderkill katana. Secondly, mythril would be the only mineral, ground up, to actually serve a healing effect- it rapidly refills the hunger bar a la weight even from viro, and would heal toxin and brute damage at 0.7 a tick. It would be about again as rare as diamond.

A new smeltable material would be plasma glass, creatable by smelting plasma and glass in the ore refiner. It would be much more resistant to damage, making it the glass equivelant of plasteel-not as strong or difficult to break as an rwall, but compared to a window, pretty nice. It'd also be tinted purple for that extra look.

Copper would be another mineral, one engineering would like. Copper would be used as a shock guard, for the reason fuck you. Applying it to a tool makes it not shock you if the wrong wire is cut/you clip a live wire, ect, again because eat my shorts this is an unrealistic spaceman game. Roughly as common as iron or perhaps plasma, it also can be used to ship off for cargo points, and create copper crates, which can be shipped off for more points and look fancy. Finally, for copper, it would be a component of mining charges-essentially, eeny beeny mining bombs, useable for blasting holes in rocks to mine faster. I'll touch on mining charges later.

Coal would also be an option. As much as I want to suggest coal be useable in some sort of super shitty pacman, that won't happen. Instead, make plasteel making require coal, iron, and plasma. It can also be shipped off to centcomm for points, and is used in the creation of plastics, which I will touch on later. Coal is also flammable, but unlike plasma, it does not spread-igniting coal simply lights it on fire, and anyone else who touches it also bakes. It would be as common as iron. 

Platinum would be the first purely decorative mineral, simply for looking nice or shipping off to centcomm.

Clarenkite would essentially be space magic-used in the mining vendors-also will discuss-to produce the better mining gear that science can't make. Pretty sweet. Also, HORRIBLY radioactive. As in stunlock with rads unless you're kitted for it. Also probably going to give you fucking aids or something. 

Electricite, which is basically a troll mineral-mine it without some higher tier equipment, a mining charge, insulated gloves, ect? Bzzzzzap, shocked. Assuming it is mined, however, sheets of the stuff can be applied to electrical equipment or power cells to charge it slowly. Plating a mech with it means the mech drains it for power too- wear fucking a hardsuit or insu gloves in the mech or suddenly you're fishsticks.

Plastics are the final new addition mineralwise-because i'm an unoriginal little whore, you get them with silicon and oil. This produces sheets of rough silicate, take the lumps to an ore refiner, put in coal, smelt, it shits out plastic, which would serve loads of purposes.
Plastic can craft most of plastic shit like janibags. It can make inflatable plastic barriers, craft balloons, plate windows, walls and floors to make them blast resistant and stronger, used to make tape-duct tape or police tape- make plastic barricades, reinfoce cyborgs against heat, insulate gloves, wires, tools, make bodybags, blood bags, crates. It has it's nice uses and is going to be wanted for a lot.

Moving on from minerals, we reach gems.

Gems are quite simple. Just like bluespace crystals, the mining scanner detects them.

Gems can be encrusted into your hardsuit to make you look like a pretty princess, encrusted into any blade weapon or a pickaxe to make you look like a flamboyant psychopath, or simply sold off for a nice bunch of points at cargo and are purely cosmetic.

However, there are two gems that are not. Telecrystals are one-while you sadly can't use these to buy more eswords to stroke your throbbing murderboner, you can use them to-
Sell to cargo-
Slot into a cyborg to increase it's movement speed-
Power anything that requires a power cell-
Slot into the telescience console just like bs crystals to increase range-

The second gem is Nightstone, which-
Disables lights around it when clicked inhand in a short radius akin to sling veil
Can be used as fuel for the RCD
Sells well
Suprisingly, can actually be eaten, unsuprisingly is composed of tons of lethal toxins and wizard bullshit and as such kills you stone dead on eating.

But adam, mining is 2godly now! You cry, probably fuck I don't know your thoughts. I hope that's what you cried, if it wasn't meh not my fault.

First off, rebuff goliaths. Give them back their hilarious tripping tentacles-specifically, if a tentacle came up under you or you walked into a tentacle, you got tripped, requiring actual caution to beat them.

Add hivebots and faithless to mining. Hivebots you have all seen from xeno-bucket of fun, weak solo, strong in groups, fires projectiles slowlt. Make hivebots occur in groups of three- deeper into the asteroid, groups of four with a strong hivebot 'leader.' Faithless would occur in pairs. into the deepest asteroid-they do stam damage and hit like a fucking truck.

Space clown-clown mobs, but in the clown hardsuit, usually occuring deeper in mining because honk.

Simple-mob xenomorphs such as drones, setinels, hunters or even the queen. Simple mob xenos cannot infect and are fairly weak, but hey, they add SOME theme.

Simple mob animated skeletons-they already exist and already hit like a truck, shouldn't be too hard to add.

Golem-found inside wiz artifact rooms. Hits for 25 brute w/o any armor plus stamina, but very slow. Mining mob level resistance to lasers-guide to beating it is just to kite it and blast it with the KA, don't let it pin you.

Space Worm-this i' proud of. Hostile, multi segmented worms thay burrow through rock, leap out when the rock they are hiding in is mined and attack the player. Hit for 15 brute, plus stamina-also in possession of a lash body attack, knocking down the person they are attacking. Burrows into rock after attacking to continue ambushing the miner until killed. Failing to beat the body further after 'death' results in the worm splitting into two more, smaller, weaker worms-this process continues until either the worms are too small to fit or too dead to split.

Bam, new more dangerous mobs for mining.

To do tomorrow-suggest rework for mining vendor, mining gear, suggest and balance new artifact rooms and add in-and actually map cus im not too lazy-exploration options for miners to explore hidden buildings ect on the asteroid, expand the mining base, add more details/balance minerals further.

**Comment by X-TheDark** [comment]
Are you alright, Adam?

**Comment by ghost** [comment]
NO

**Comment by ghost** [comment]
I like it, but the mining asteroid must be enlarged if it's added.

**Comment by Groudonmaster** [comment]
Adam It'll be okay. BUT HOLY SHIT YES.

I'll try working on an asteroid rework if someone wants to work on the other stuff.

**Comment by Super3222** [comment]
I support the idea of reworking mining, I've always thought of it myself. There's not a whole lot 'adventure' towards mining currently, which it should definitely have so you don't feel like a complete slave when mining.

And the goliaths, oh man, are far too easy to beat if you play smart. I like the tripping idea, it'd be a reasonable buff to goliaths.

**Comment by darkwahn** [comment]
Almost all of this sounds pretty great, not a fan of adding faithless but otherwise like it all.

**Comment by ShadowDeath6** [comment]
Hivebots are shit, even in groups. They suck. A lot. 

Adamantine would just make xeno rely on mining for golems and that's bad. 

Making mining more difficult will make people stay away from it more and that's also bad. 

How to solve- give scientists some way of mining, most likely through access. Then you'll get materials 190% of the time.

**Comment by Kmc2000** [comment]
I have the clowns covered

I made a space clown icon for just this sort of thing

**Comment by ghost** [comment]
I'm not done yet. 

Certainly mining will be a good deal deadlier.

However, the miner will get a new array of tools and gear, including different types of pickaxes, resonators, actual mining charge mining explosives, hammers, ect.

Not only will late game miners have an array of powerful-extremely powerful-mining tools that mine faster and hit like a truck that are available from the mining vendor that I will also rework and improve to no longer be point based, they'll also have assorted minebots that work alongside them, breachers and explosives, et cetera et cetera to balance out the now lethal asteroid.

Prepare for adamantine pickaxes, sonic blasters, mythril mining charges, mob decoys, auto-minebots that don't suck oceans of dick, and even an advanced mining pod equipped with a plasma blaster and plasma thrusters that can be piloted around the asteroid and used to mine-if you've ever been on goon or paradise, you'll know what I mean by pods.

**Comment by ghost** [comment]
I'll give specifics and stats later

**Comment by X-TheDark** [comment]
I suppose you want to rework mining item acquisition to be similar to Goon, where you smelt them yourself, yes?

**Comment by ghost** [comment]
Basically, yeah-You'd input minerals rather than the point vendor into the ore reedemer, wherein not only would pure minerals be claimed by science, but the miner could use it to print specific equipment.

**Comment by shrimptk** [comment]
Here's an idea: Make the asteroid have caves entrances (Or ladders, or stairs, whatever.) complete with bump-teleporters that let you go _inside_ the asteroid. Going deeper will be more dangerous, darker, but provide more loot.

**Comment by X-TheDark** [comment]
We Dungeon Crawler Station now.

**Comment by Super3222** [comment]
> Make the asteroid have caves entrances (Or ladders, or stairs, whatever.) complete with bump-teleporters that let you go inside the asteroid. Going deeper will be more dangerous, darker, but provide more loot.

I thought about something like this before. A gate only openable with a sort of keycard worth 1000+ mining points from the mining vendor, that led to a more challenging, fun, and interactive place to mine.

**Comment by Wardog390** [comment]
> Adamantine would just make xeno rely on mining for golems and that's bad.

Science relys on mining anyway you egg
double the size of the asteroid or enlargen it as far as possible and these changes will be amazing.
goddamn i love that fucking title.

**Comment by ghost** [comment]
still working on the tool and pod specifications

**Comment by ghost** [comment]
WHY DID YOU CHANGE THE NAME
