### ISSUE TITLE
Dead Blobs being able to respawn?

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#334]
Today I was playing as a Blob, and I got bombed and died. My game disconnected for whatever reason, and when I reconnected, I was able to join the game again, even though I had already bursted and died as blob. Not sure if this is intentional or what, but just in case it isn't I'm reporting it here.

**Comment by Cruix** [comment]
Repeat of #36 and possibly #32. Can we fix this by making blobs be ghosts when they die?

**Comment by Groudonmaster** [comment]
Again. The issue is that when the blob core is destroyed it deletes the overmind mob. Find where that proc is and change it to gib the overmind instead. Random gibs out of nowhere but it should cause a ghost.

**Comment by Time-Green** [comment]
It never does. I have been blob 4 times, including sub conscious.
I died 2 times and both of them I got kicked and respawned

**Comment by DavidEdwards** [comment]
This issue should be fixed by the recent blob changes. However, if issues persist. Please make a new issue (you can reference this one).
