### ISSUE TITLE
10 tiles of lava+one timato+one xray gun with prayer_chaplain.ogg as firesound = Crash

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#335]
As the title implies, I made tim a personal hell with a few blocks of lava and shot at him with an xray laser with a custom sound and it managed to crash the server (somehow)

[20:43:39](AsV9): #585# [21:38:16]ADMIN: kmc2000/(Aidan Eliza) created a /obj/item/device/firing_pin
[20:43:41](AsV9): last line
[20:43:44](AsV9): in the thing

Apparently, this is what happens to the host when you do:
http://prnt.sc/a50v8u

I have absolutely no idea WHY it crashed, i've done that kind of thing plenty of times before but may want to take a look at that one

Also placed tinted windows around the lava

**Comment by ShadowDeath6** [comment]
Keksray lasers

Lava has a history of doing performance shit, tg has talked about it a few times.

**Comment by Kmc2000** [comment]
@succ baby

Probably best to remove THE FLOOR IS LAVA buttons then, because if TEN tiles kill the server... oh god... imagine 1000's

**Comment by X-TheDark** [comment]
Cannot be reproduced locally with pray_chaplain.ogg and 10 lava tiles, so this probably is a server lag issue.
