### ISSUE TITLE
Miner drones (not that shitty one you buy)

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#336]
New kind of drones since science never gets materials ever. 

Basically a drone with a cute little miner helmet that can ONLY mine stuff and kill the mobs on the asteroid. 
They work the same way as maintanence drones, controlled by ghosts, blah blah. 

Laws- (requests if you think they suck)
1. Do not interact with anything other than xenomorphic life on the mining asteroid. 
2. Do not actively work against the station. 
3. Retrieve ore from the mining asteroid and bring it to ore redemption machines. 

Maybe give it a bit more health than regular drone, and obviously basic mining tools like a scanner and pickaxe.

**Comment by Super3222** [comment]
> 1. Do not interact with anything other than hivelords, basilisks, or goliaths.

Maybe instead of specific xeno's, we could have "Do not interact with anything other than xenomorphic aliens on the asteroid".

Drones are also basically 2-3 hit kills, are made to be expendable, and are generally weak. How much more health would a mining drone have?

**Comment by oisin100** [comment]
Would be cool if they worked a bit like swarmers where they can eat the metal they mine to create more miner drones

**Comment by Kmc2000** [comment]
+1 to oisin

I reckon 5 hits, or let em wear mining hardsuit helmets, like the syndrones with their syndi helmets to armour them up a bit

**Comment by oisin100** [comment]
Where would they get the mining suit helmets? Theres no such thing...

**Comment by ShadowDeath6** [comment]
There are unremovable mining helmets in code, the only problem being that it would fall off when they died and somebody was dumb enough to pick it up

**Comment by X-TheDark** [comment]
Don't Mining Cyborgs already sort of cover this or not good enough?

If not, we could try giving them an upgraded capacity mining satchel, maybe in internal furnace for smelting ore.

**Comment by oisin100** [comment]
Nope, Miner drones are like drones. When people die they can become a miner drone if they wish to continue the game. Whilst a borg is just someone who decided they wanted to play borg.

**Comment by ShadowDeath6** [comment]
A borg needs to dedicate a module out of the kindness of its heart, while a miner drone can do it to get back in the game.

**Comment by X-TheDark** [comment]
I see, just add a volunteer mining job for drones. Cool. What equipment would they get?

**Comment by ghost** [comment]
I'll try to add it, but it might take a while since I'm new to Yog coding still.

**Comment by ghost** [comment]
Need more discussion on what the drones actually get.

**Comment by ShadowDeath6** [comment]
Equipment... I mean, all any miner needs is an advanced scanner, kinetic accelerator, and a miner satchel. Obviously this would work like a drone, so you could just get upgraded equipment from R&D.

**Comment by ShadowDeath6** [comment]
I actually just had an idea. Maybe make them similar to a borg, where they have a module and type thing but don't sync to the AI? Maybe they could be hacked similar to a borg as well.

**Comment by ghost** [comment]
Instead of making it a normal drone.

You know those shitty buyable mining drones? Add like 10 of them to a mining bay and instead of being AI controlled, make them ghost-inhabitable like drone shells. They'd have an inbuilt ore satchel, KA, mining drill and meson vision and advanced mining scanner inbuilt and be able to communicate with other mining drones and regular drones. But just like drones, they cannot communicate with humans.  

Their laws would be as follows.
1. You may not in any way shape or form interact with any non-hostile non-xenobiological life on the asteroid, even in self defense.
2. You may not harm or impede any non-xenobiological asteroid creatures, regardless of intent or circumstance.
3. Your goals are to mine, harvest, explore and refine materials to the best of your ability. You must never work against these goals.

They would  also get a health buff to 100 health-half that of a human's total health- and the ability to self repair, like swarmers, if standing still for ten seconds.

**Comment by Time-Green** [comment]
You forgot the law where they may commune with other drones
:p

**Comment by shrimptk** [comment]
We might as well remove mining borg all together with this shit.

**Comment by ToGWtF** [comment]
Yeah. think rather than be build-able, the shells have to be purchased for like 1000 mining points at the vending machines

**Comment by ghost** [comment]
Why not remove minerborg anyway?

It's a shitty module with no original emag types, is the only cyborg that does it's job worse than a human can, and is altogether dull as fuck to play.

**Comment by ShadowDeath6** [comment]
I'd prefer there to be one already existing on mining. Literally the entire reason I made this request is that too many miners either do nothing or get robusted by a hivelord and R&D suffers forever.

**Comment by Time-Green** [comment]
Just a minerborg that starts at mining and can be accesed by ghosts?
Not a bad, maybe give him an extra law stating to mine.
