### ISSUE TITLE
Syndicate spy drones

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#340]
So, for the low cost of  7TC, you can buy yourself this little guy (if you think this is unbalanced, comment)
[https://i.gyazo.com/db35f4dd276d8782060671702c39c366.png](url)

He would function as a scout, with your 7TC you'd also get a neat little drone phone, which you'd use to control it: 
https://gyazo.com/ca04c60245d7d6a35dfe67979615b443

The drone would be able to slip under doors, and have the hide verb that alien larvae have, so you could deploy it under a table and spy on people. He'd have 35 HP, so it would take a few hits to knock it down.

It would also have the ability to tag specific people, and this would go to the drone phone, when you examined it, it would say, for example: Phazon [mime] Last seen: Bridge, and would go away after you tag someone else, to clear all tags you would have to use a special verb on the drone whilst in use.

It'd look like this when tagging:
https://gyazo.com/635740bdb560894cf44ec246f650683b

So you'd be able to hide in a locker, and deploy this little guy to scout ahead for you, you would get the drone and phone TP'd in for your TC and to control the drone, it'd be one click

To stop controlling the drone, a verb in a drone tab next to his hide verb, saying terminate link.

So, why?

Well there aren't an awful lot of USEFUL scouting items, there's the camera bug but that's pretty crappy, having your own drone which you can tag your target with would be pretty cool IMO.

So tl;dr You get a drone which you can control and see through it's vision to tag your target(s)

**Comment by ghost** [comment]
Duplicate issue. Closing.
