### ISSUE TITLE
Mice: Mini Antags

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#342]
A while back, I had an idea for a new type of mini-antag sort of thing. The idea was that dead players could join the game as mice and just be given complete freedom. However, a better idea would be to give them objectives. A few objectives I have in mind are:
-Steal x pieces of food
-Steal x pieces of trash
-Steal x item
-Chew through x wires (Maybe not, would be too annoying)
-Kill x other mice
Mice would have the ability to bite people giving minimal brute damage, as well as biting wires to sever them. Attempting to chew wires currently conducting electricity would shock mice almost to death, but they would heal over time. For the stealing objective, instead of having the items on them, they would have a designated place or just maintenance to pull/bring all the stolen stuff to. Mice would also be able to hide like xeno hatchlings, and be given the ability to ventcrawl as well. They would also possibly be able to crawl under doors like drones, through a hatch on the botto.
This would give dead players something to do, and it would also make the janitor's mouse traps useful for something other than pranks. Mouse traps would just appear as food to mice, and kill them if interacted with. Mice probably wouldn't be available to play every round though, every 2 or 3 rounds would be good. Alternatively, there could be a set limit on the number of mice that could spawn every round.

Thoughts? I'm open to suggestions for objectives, abilities, etc. and criticism.

**Comment by ghost** [comment]
No, not as antagonists, giving people the ability to join as midround antags is stupid as fuck.

What I do suggest, however, is that mice be an option to inhabit-With two rules-Do not reveal you are sapient to any humans, and you do not remember your past lives.

Then dead people can play as mice if they're particularly bored and just walk around.

Giving bored ghosts the ability to sabotage the powernet-and by extension release the singularity-is the stupidest thing I have ever heard.

**Comment by Rocks4Free** [comment]
> Giving bored ghosts the ability to sabotage the powernet-and by extension release the singularity-is the stupidest thing I have ever heard.

You're right, I didn't think of that before. The chewing wires thing was a suggestion from someone else on the old forum post. Maybe only give them the ability to chew wires that aren't conducting any electricity? 

> No, not as antagonists, giving people the ability to join as midround antags is stupid as fuck.

The mice wouldn't be important antags like traitors or cultists, just tiny things that would affect the round minimally, and maybe annoy the chef and janitor a bit. They would be valid for the crew to kill, too. If you're really opposed to it, then maybe make it very rare, like every 5-10 rounds.

**Comment by ShadowDeath6** [comment]
Mice can chew wires on tg and get shocked. 

Also the singulo can't have its wires cut unless you pull up tiles.

**Comment by 00aquir** [comment]
hm.. the idea that dead players could be mice (friendly ones) with the mission to eat as many trash food on the floor as they can (dropped food, cigarette butt.. scrubber-emitted milk puddles) and the game would display the fattest mouse at the end of the round could be fun.. automatic hiding would be on for them (under tables, etc.), they could have fun by tailgating into rooms if somebody opens the door, and if they're trapped, maybe it would take them 1:30 minutes to make a mouse hole so they (and only they) could move beneath it... that could be something..
And if they want out, they could just ghost at no cost, with they or the other dead players being able to take control of it again.. more mice in maint areas from the start could work for something like this..

**Comment by Rocks4Free** [comment]
>  mission to eat as many trash food on the floor as they can (dropped food, cigarette butt.. scrubber-emitted milk puddles) and the game would display the fattest mouse at the end of the round

That's a good idea! Added it to the OP.

> they could have fun by tailgating into rooms if somebody opens the door, and if they're trapped, maybe it would take them 1:30 minutes to make a mouse hole so they (and only they) could move beneath it

I don't think mice would be able to chew through a metal wall. Maybe it could work like drones and they would be able to move under airlocks through hatches? They would also be able to ventcrawl, considering monkeys already can.

> more mice in maint areas from the start could work for something like this..

I think a set limit on mice would be a good idea, so everyone isn't just playing as mice.

**Comment by 00aquir** [comment]
yes they could use the vents then, and mice would be for dead players.. not that they could do more than any other character..

**Comment by ghost** [comment]
Aurora or paradise already has this implemented and balanced.

Mice are just required not to remember their previous lives, or reveal their sapience by speaking or doing any revealing actions, or intrude in the round in any way-Like a drone.

They can also ventcrawl, hide to hide under objects or tables or whatever like a larva, and can eat food by clicking it. They also cannot bite or nibble in any way humans to cause them damage.

They're also available every round, consistently-you just have to be dead for 10 minutes to play a mouse.

That way, mice don't have any actual appeal to playing them, but they're some way for bored ghosts to inhabit mice and do something like eat cheese or scurry around and get killed eventually or eavesdrop on conversations.

Midround ghost inhabitations should be like drones-Non round intrusive in any way, shape, or form. Drones do their repairing shtick, mice do their scurrying and eating cheese shtick.

It's going to be boring, and that's the intent.

**Comment by ToGWtF** [comment]
I'm yes and no on this.

Other servers used to have them, and they could ventcrawl. People used it to spam Malf AI's chat since it has a universal translator and distract its turrets while people broke in. Or ventcrawling to the same location and mass suiciding to stack 100+ bodies on the same tile to cause lag issues. I think something like respawning as an animal should be done through a staff member. Its harder to police what a player does when no one recognizes its even a player

However

Same conditions as Revenant spawning only more common. 5+ dead mobs, gives a chance for Cat and Mouse event.  Between 3-5 people are chosen out of those who click yes on the prompt,  3-4 of them are chosen to be mice with the job of eating the most trash (Good way to clean up. Slave labor ftw kek). One player either gets spawned as a cat or takes over either Runtime or Mimekitty. The mice have to stay alive and not interact with the crew so they don't get caught for being sentient, and the cat has to catch the mice while also pretending not to be sentient lest it be worshiped as a God. Good for a few keks, before an assistant/clown/sec officer/basically fucking anyone toolboxes the cat to death in a hallway and the mice get trapped in a maintenance tunnel for the entire round.

**Comment by Stealthkibbler** [comment]
So after discussing in TS with keek and taco we have come up with an amazing set of abilities and the very skeleton of implementing Mice as a semi-antagonist role.

An observer or ghost would have the verb to possess a mouse on the map, there would be a limited amount of mice on the map (current default is 12), they would become one of the 12 NPC mice on the station with the objective to simply consume and reproduce. Mice consume food, acting as their resources it converts to Nutriment which they stockpile inside themselves and use for abilities.

**## -Mice Abilities.**
**Micetosis**\- Costs X amount of Nutriment, The Mouse temporarily inflates then shortly thereafter a new mouse erupts from the head, splitting off from the original organisms body thus resulting in two mice. (Most Important Ability)
**Consume**\- The Mouse latches onto a piece of food and begins to leech all reagents out of it until there is nothing left but crumbs, only nutriment is of use to the mouse however rat poison kills the mouse if a lethal amount is consumed.
**Infiltrate**\- The Mouse crawls into a vending machine and begins to consume all the food inside it, this action is a safe method of nutriment but sugary food is less nutritious and the mouse can be ejected if someone uses the vending machine.
**Dig** - The mouse carves out a hole into the designated wall in which it can then enter and exit using CTRL+Click and expand using tunnel. Once a hole is dug on either side of a wall, the mouse can travel freely between the two, the holes cost nutriment to make and can be patched up using metal sheets.
**Thin Form**\- Naturally the mouse can squeeze under and between airlocks like a drone can as-well as crawl into the ventilation of the station. Mice cannot use Dig or Tunnel while in the ventilation pipes.
**Hide** - COPYPASTA LARVA CODE ECH!
_~Suggestions Welcome~_

Weaknesses
- Mouse traps, instakills them and can be placed under food.
- Cats like Runtime and Mimekitty, they have inbuilt code where they kill mice on sight.
- New Chem: Rat Poison, Put 5 units of it on food using a dropper, instantly kills a mouse, if a human consumes it causes excessive vomiting and overdose kills extremely fast with toxin damage, requires 30 units to overdose. 
  4 carbon, 2 hydrogen, 1 oxygen, heated at 400k, produces half of what the normal output would be. Chemical name is Indandione, AKA Rat Poison.

`
