### ISSUE TITLE
Add shadowperson to green slime radium toxin list

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#343]
Literally least available race, please add it. 
If you don't know, injecting a green slime extract fills it with race toxin that randomly mutates you into any race other than shadowling, shadowperson, skeleton, or plasmaman. 

;_;

**Comment by Super3222** [comment]
Why do you love shadowpeople so much

**Comment by ShadowDeath6** [comment]
BECAUSE THEY'RE COOL

**Comment by Super3222** [comment]
Have fun getting lynched instantly!

**Comment by ShadowDeath6** [comment]
> Have fun getting lynched instantly

I WILL

**Comment by Time-Green** [comment]
You can already become plasmamen through this

**Comment by Super3222** [comment]
> You can already become plasmamen through this

No, no you can't. Shadow specified that it's one of the races mutation toxin doesn't transform you into & it's under mutation toxin's blacklist

**Comment by ShadowDeath6** [comment]
Merged. Thanks coders!
