### ISSUE TITLE
Alien P.A.I skin invisible while resting in holographic form

### ISSUE THREAD

**Issue by bunny232** [yogstation13/yogstation-classic#344]
Hey look a title

**Comment by Time-Green** [comment]
Oh this one?
I thought it was a feature, I use it alot

**Comment by Kmc2000** [comment]
Yeah that's me being lazy

Easy fix, set resting icon state to the right hand state for the alien, chicken, carp etc.

**Comment by bunny232** [comment]
also don't fix please i need to have my snake pai be able to hide and steal the soviet info
space station metal gear pai 13 confirmed?

**Comment by Time-Green** [comment]
You were solid snake? That pAI that kept himself invisible and constantly ratted me out?
