### ISSUE TITLE
Make wands of nothing recharge.

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation-classic#350]
Small thing, but hey, who doesn't like getting hit with absolutely nothing?

**Comment by oisin100** [comment]
![fun police](http://fridayafterwork.fm/wp-content/uploads/sites/3/2013/05/Fun-Police.jpg)

**Comment by Time-Green** [comment]
We should make it recharge.
Its not going to do ANYTHING

**Comment by ShadowDeath6** [comment]
Staff of nothing when
Wands too op pls nerf

**Comment by FluffySurvivor** [comment]
:+1:
Kay

**Comment by PineappleWolf** [comment]
Adding in recharge ability with clown borg update to facilitate easier Wand of Nothing usage for Borgs.

https://github.com/yogstation13/yogstation/pull/402
