### ISSUE TITLE
Mech Jetpack

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation-classic#351]
We should make an exosuit equipment that lets mechs fly around in space.

**Comment by ghost** [comment]
> be floating around in space as traitor
> _vrrrrm_
> look around
> see nothing
> continue floating, slightly worried
> gusts of hot air blow past you
> glass shards fly by you suddenly
> you turn around
> GIANT DURAND WITH A SOLARIS FLYING OFF THE STATION DIRECTLY AT YOU WITH GIANT ION JETS BEHIND IT
> SLAMS YOU IN THE FACE WITH A GIANT METAL FIST AND DESTROYS YOUR ENTIRE LOWER BODY WITH A SOLARIS CANNON

FUND IT

**Comment by X-TheDark** [comment]
Already present in code and used (Syndicate Mauler/Gygax), but not as a buildable module for Robotics.

**Comment by ShadowDeath6** [comment]
Thruster module when

It's already a thing inbuilt on certain mechs, as X said.

**Comment by ToGWtF** [comment]
spacepods when

**Comment by X-TheDark** [comment]
No need to close this as it's still a valid suggestion to add Jetpack Module as something buildable by Roboticists.

**Comment by Super3222** [comment]
I like it. It will also help miners out a bit, so their ripley can actually get out of an infinite space loop with no end.

**Comment by X-TheDark** [comment]
Thing is, all mechs have 3 slots, so you can't have a Clamp/Drill/Scanner Ripley with a Jetpack.

**Comment by ghost** [comment]
ripleys have more than 3 slots

ya dingus

some deathsquad and combat mechs have 4 too

**Comment by X-TheDark** [comment]
What the hell? Ripley has 6 damned slots? Holy crap.

**Comment by Super3222** [comment]
> What the hell? Ripley has 6 damned slots? Holy crap.

Ripley just can't get combat based weapons (that aren't work based like rcd, drill, cramp), but they can get up to 6.
