### ISSUE TITLE
Can't use (O2) canister from vehicle

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#358]
Release valve won't open, just keeps refreshing. Only possible on foot.

**Comment by Cruix** [comment]
It's the same reason you can't open one from inside a locker, or a mech. I would say that this is intended behavior, even though the sprite on most vehicles doesn't have an enclosed cockpit.

**Comment by 00aquir** [comment]
Hm. Although you can put your Oxygen tank into the Canister while on the vehicle and interact with it to that point.
