### ISSUE TITLE
Players able to respawn after being killed as blob

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#36]
opened by Ben · 2 months ago
What is the nature of the issue: Just had a blob round and the person controlling the blob. Stated that they were still alive then they saw a emitter and "imploded". they were still alive but without a core they DC'ed then reconnected and was able to join the round
What steps must be taken to reproduce this error:
Become blob
Get rekt and DC
Come back and see if you can join
Any additional information? : stated he was fire blob and a Bomb went off thats what made him imploded after he imploded he was "kicked" so please test

**Comment by TehFlaminTaco** [comment]
Not blob related, when you're force DC'd like that, that means your client was deleted, meaning you don't have any mob you are currently in, this includes ghosts. Blob cores being deleted commonly do this.

**Comment by Groudonmaster** [comment]
We just need to make it so blob cores aren't deleted by stuff like that. Or make it so that a ghost is generated instead.

**Comment by DavidEdwards** [comment]
This issue should be fixed by the recent blob changes. However, if issues persist. Please make a new issue (you can reference this one).
