### ISSUE TITLE
the not unbaning job bans and the not loading up bug i think some people dont know about

### ISSUE THREAD

**Issue by awseomenathan987** [yogstation13/yogstation-classic#360]
so i had a job ban on captain and all sec roles and hop when i was unbaned it only unbaned the sec roles including hos so i cant be captain and im now sad i have windows 10

onto the 2nd one there is a bug were you cant acsess anything with a eye and a loading screen ir loads the loading screen but stops at the last bit and witch means i cant use APCs or air alarms or canisters or if im a AI can edit the doors cant use cem dispensers can use SMEs and a whole bunch more i also run on windows 10 dont know how to get a screen shot or anything i dont go deep into computer stuff so if you ask me stuff please please be very lets just say to the point were i can understand it so please fix both of theses bugs it would help a lot if you do fix em and you have to implant em or somthing my OOC name on byond is the same name on my github acount and same goes for the forums

**Comment by oisin100** [comment]
1st bug. There's a on going bug whats been around for a few months which for some reason is stopping some perma job bans from being lifted. We are working on this.

2nd bug. Can you make sure you have the latest version byond installed?

**Comment by ghost** [comment]
YEah no this is already known and both are being fixd-the second bug however is just unfixable clientside, relog to fix it.

**Comment by awseomenathan987** [comment]
the 2nd one has ben going on ever sence i first played the game so yah reloging dont work

**Comment by awseomenathan987** [comment]
and i dowloaded it like 2 or 1 month ago i think i have the lateist virsion

**Comment by awseomenathan987** [comment]
just redowloaded it still dosnt work

**Comment by awseomenathan987** [comment]
i cant use cryo cells ether

**Comment by oisin100** [comment]
What does it look like when it loads? Does it load part way then loads the rest white? Do some buttons not load but the background is still there? It sounds more like a BYOND bug than a SS13 Bug.Some screenshots would be REALLY REALLY helpfull you should be able to find out how to screenshot with just a quick google search!

You might also want to try to ask on the BYOND forums about it if its a BYOND Bug.

**Comment by awseomenathan987** [comment]
![image](https://cloud.githubusercontent.com/assets/17034396/13230423/4ba3977c-d973-11e5-9a94-b78353575ab3.png)
i think this is how i do da image

**Comment by awseomenathan987** [comment]
there we go that is what happens when i click on somthing
i finnaly found out how to do da image

**Comment by Groudonmaster** [comment]
The banning thing is a repeat of #211

**Comment by awseomenathan987** [comment]
well sorry if it was a repeat

**Comment by oisin100** [comment]
Alright, Have you always had the loading bug or is it a recent thing?

**Comment by awseomenathan987** [comment]
i have always had the bug ever sence i first started playing the game
it sucks

**Comment by awseomenathan987** [comment]
are ya gona fix it?

**Comment by Cruix** [comment]
This may be solved by https://github.com/tgstation/-tg-station/pull/13507. Porting that would be a significant style change to everything that uses nanoui, but I doubt too many people would be opposed to it.

But holy crap that's a huge update, I don't even know where to start on porting it. It will probably take some Git magic well above my tier.

**Comment by ShadowDeath6** [comment]
It bugs out if you move while the screen is loading, just for the record.

**Comment by oisin100** [comment]
What operating system do you have? It sounds like some other people are encountering the same problem. https://github.com/tgstation/-tg-station/issues/13460

**Comment by awseomenathan987** [comment]
what do you mean bye operating system im sorry im a computer noob with this stuff

**Comment by oisin100** [comment]
Like windows 7,8,10...

**Comment by awseomenathan987** [comment]
i said that i had windows 10 2 time in the writing box well i have windows 10 and thank you for helping me with this :)

**Comment by awseomenathan987** [comment]
and sorry if im not that active on this websight

**Comment by oisin100** [comment]
Oh right sorry! I might know why its not working but ill need to test it first... Ill get back to you once i have,

**Comment by awseomenathan987** [comment]
ok thank you a lot and its ok :D

**Comment by awseomenathan987** [comment]
i havnt heard from anyone in a while

**Comment by oisin100** [comment]
Sorry, Havent got around to testing your problems with loading yet...
Your job bans should be lifted now!

**Comment by awseomenathan987** [comment]
there were lifted but then they whent back baned the next morning what is going on?
i was so happy then i was sad :(

**Comment by awseomenathan987** [comment]
so please unban captain please

**Comment by oisin100** [comment]
Are you sure you arent unbanned already? It should really be working now....

**Comment by awseomenathan987** [comment]
ok well it was but it stoped im checking right now
thank you for your troble

**Comment by awseomenathan987** [comment]
no im still baned from captain

**Comment by DavidEdwards** [comment]
As for you being banned from Captain. It seems like you were banned from all heads (6 different bans).

4 of those bans have been overturned, and 2 still remain. That means you are still banned from Captain and HoP. That is not bug related.

The public ban system didn't show those 2 bans, because it grouped them with the unbanned list. The public ban system will now also show mismatches:

https://www.yogstation.net/index.php?do=publicbans&search=awseomenathan987

**Comment by awseomenathan987** [comment]
well is the active ban a bug since its 6 seconds before the real ban?

**Comment by awseomenathan987** [comment]
or did he just be a shit tard and make 2 bans?

**Comment by DavidEdwards** [comment]
Those 6 bans are created automatically as part of banning someone from all critical jobs.

It just means that you were not freed to play those 2 roles.

Do you have a ban appeal for this? If not, you can't reasonably expect to be unbanned at all.

**Comment by awseomenathan987** [comment]
i was unbaned from a ban with the same reson soo i think thats pretty valid for the same reson but that ban was for the sec roles

**Comment by DavidEdwards** [comment]
As far as I see it, the current bans are entirely legit. Unless there is a ban appeal to revert them.

Go ahead and make an appeal on the forum. I'll close this, because we are sliding away from the intended purpose of Github.

**Comment by awseomenathan987** [comment]
ok i just made a appeal for the ban there working it out thank you
