### ISSUE TITLE
(blank)Station

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#362]
This is it boys, the grand _**certain project**_ I've been hinting at for some time now. We all love our classic box station, but as yog grows the cramped maint hallways and limited number of supplies can only be crammed into so much space. As of now, with our 50-70 peak player count, box is just way to small, and with meta being the next biggest one up, we're just not at the point to be on such a massive map consistently. So about a month ago I whipped out the ol' sketchpad and started doodling concepts for a completely new station unique to Yog and designed to fit the bill of our player count and community for a more efficient, balanced, and thoroughly enjoyable spessman experience. 

I'll get with anyone who wants to take part in this clusterfuck sometime this week and start organizing this blasphemy. It's not going to come quick, but it'll be worth it. As for the issue title, I'm still working on a name for it, all suggestions are welcome. I'll post rough layout pictures sometime this week as well, god willing with school and all. Any and all contributors are going to be mentioned somewhere in the code for the .dmm or even in some hidden z-level of the map so I encourage all forms of participation whether it be here on the git or merging on dream maker. 

thanks lads.

**Comment by ShadowDeath6** [comment]
Box is big enough imo, but I'm interested to see what you have planned. 

Just no AI satellite, damn.

**Comment by shrimptk** [comment]
> Central AI is too easy
> Satellite AI is too hard
> I want to die
> get rid of malf

**Comment by 00aquir** [comment]
> Box is big enough imo, but I'm interested to see what you have planned.

Yea, sec still needs reasonable amount of time to search things in maint areas at all, I think the station is big enough, especially when the bigger player count often means Less security per players, but other station blueprints could have some potential..

**Comment by ghost** [comment]
We could just use /tg/'s box with it's huge maint.

Also, meta really is not that big, i've played on it with 50 people on /tg/, it fits pretty damn well.

**Comment by awseomenathan987** [comment]
the staiton work fine with this player count but im intrested of what you made

**Comment by ghost** [comment]
groxic please stop tagging things as critical 

when they are not critical

just because you'd like something to be in there doesn't mean it's critical

critical is like 'HOYL SHIT EVERYONE GOT UNBANNEd'

or 'HELP ALL THE FLOOR TILES ARE NAR'SIE'

not 'man i'd like to rub my murderboner in a larger maint'

**Comment by shrimptk** [comment]
Replace **critical** with _**fuck**_

**Comment by shrimptk** [comment]
Its also a matter of _'settling for functional'_ or wanting better so we have a map that adapts to our community versus the inverse.

**Comment by shrimptk** [comment]
> We could just use /tg/'s box with it's huge maint.

But we also get the handful of massive changes that /tg/'s box has to offer such as an AI Satellite, awkward brig setup, totally broken toxins, and on-station tcomms.

**Comment by ShadowDeath6** [comment]
Maybe just make maint bigger, fucking blobs get found in like 3 seconds nowadays.

**Comment by ghost** [comment]
okay then let's have the AI satellite, their nicer brig, their not-fucked toxins, and their on-station tcomms.

**Comment by shrimptk** [comment]
Fuck off adam the whole point of this is to get rid of box.

**Comment by ShadowDeath6** [comment]
> AI satellite

NO

**Comment by shrimptk** [comment]
One of my bigger ideas was to have the station centralized around the sing/tesla and have engineering be in the middle, with the bridge at the north end. So that would make it next to impossible to have a central AI, both of which I hate.

**Comment by AsV9** [comment]
am I the only one here who thinks asteroid station is a cool concept

**Comment by Stealthkibbler** [comment]
MAKE IT SO 70% OF THE LABOR IS MINING AND R&D, YES, YES YES, ASTEROID STATION YES, WORKING HARD ALL DAY EVERYDAY AS MINERS SWARM THE HELPLESS GOLIATHS FOR THEIR PLATED SKIN.
