### ISSUE TITLE
make the shuttle able to leave on rev with a delay

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#364]
shuttle comes in 15 minutes rather than 10

shuttle docks

shuttle leaves 10 minutes after it docks

pros: prevents long boring shitfest when revheads are mostly dead or in hiding and sec has to wait 4 minutes each time for 3 more implants

prevents long boring shitfest when CE is turtled up in engineering with 23 emitters and the only option is to wait until the PacMan runs out

cons: none

revs will have access to head of staff ID's by fucking default, so recalling should be easy for them

also means that there are viable options beyond laser-implant everyone or spend 50 minutes looking for the CMO 

shuttle docking with loyalists and revs on the shuttle is draw

shuttle docking with no revs on shuttle is head of staff minor victory (Revolution still exists but heads escaped to central command)

shuttle docking with no heads on shuttle is revolution minor victory (command staff still exists but revolution has spread to other stations)

nice long time for revs to recall, nice long time for both parties to beat each other off the shuttle or kill all respective revheads/heads

**Comment by ShadowDeath6** [comment]
> rev victory by traveling to a station of heavily armed loyalists with flash protection

**Comment by Super3222** [comment]
Remember that this will remove the 'if a head jumps off the z level, they have abandoned ship and no longer a goal for the revs to kill'.

but anyway, i like the idea. fixing rev one step at a time

**Comment by shrimptk** [comment]
me likey :^)

**Comment by ghost** [comment]
> rev victory by traveling to a station of heavily armed loyalists with flash protection

centcomm employees are not implanted tho

for some reason inspectors and such aren't implanted, just the ERT and deathsquad

**Comment by Alblaka** [comment]
Technically if rev rounds drag out the normal procedure is to send ERTs. But since those are admin-only, having this as an alternative for no-admin rounds sounds fine.

**Comment by ParagonPrime** [comment]
Gotta figure out a way to keep around exiling as a valid way of winning rev, then.

Otherwise support.
