### ISSUE TITLE
AI's lethals able to hit (and kill) a revenant hiding in the wall.

### ISSUE THREAD

**Issue by nazitra** [yogstation13/yogstation-classic#365]
It happened to me and it made me grumpy. My annoying the AI funtimes was ruined, I tell ya, ruined.

**Comment by nazitra** [comment]
Oh yeah I meant to label this as a bug. I suppose.

**Comment by shrimptk** [comment]
If you're gonna be a scumbag revenant and dick with the AI, you deserve to be shot.

**Comment by ghost** [comment]
hide on top of the core you shit

not a bug, this is intentional, as lasers-and tazers-have always been able to impact inside of walls

**Comment by ShadowDeath6** [comment]
Can we just make it so revenants work like slaughter demons instead of whatever weird code they run on now?

**Comment by shrimptk** [comment]
Remove them all together @ShadowDeath6

**Comment by ShadowDeath6** [comment]
This was fixed, pls close
