### ISSUE TITLE
Make Mediborg hyposprays work through hardsuits. 

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#367]
They're supposed to be super advanced, why not make their main form of healing more effective?
Also it's annoying to remove hardsuits from crit people as medborg

**Comment by ShadowDeath6** [comment]
MEDIBOTS CAN DO IT SO IT'S NOT UNBALANCED ALSO

**Comment by X-TheDark** [comment]
As a reference, regular Hypospray (CMO) doesn't go through hardsuits, but the Minihypo (Mining Medic) does.

**Comment by ghost** [comment]
CMO's hypo goes through hardsuits, if it doesn't that's a bug.

**Comment by ShadowDeath6** [comment]
Pretty sure CMO's hypospray is intended not to go through hardsuits because giving someone with chem access the ability to jab peoole with hardsuits full of cyanide is probably bad.

**Comment by X-TheDark** [comment]
Nope, CMO Hypospray does not go through hardsuits. Just tested this on the server.

**Comment by Super3222** [comment]
CMO's hypo was intended to not go through hardsuits, a sort of balancing thing.

Mini hypos weren't originally planned when CMO got their hypo, but once the mining medic idea got installed they were created to help miners ONLY. That's why they are able to go through hardsuits... so miners don't die as easily.

**Comment by ShadowDeath6** [comment]
Main reason I made this is that mediborgs lose a huge amount of functionality during rounds like blob, where people wear full-body exosuits like space suits or firesuits and the borg needs to drag them off and strip them to heal, by which time they die.

**Comment by X-TheDark** [comment]
Honestly, with Mediborgs, I don't think adding this would break balance or anything, since they don't have any lethal chemicals (yet).

**Comment by doerakpoes** [comment]
So medi borgs need a mini hypo

**Comment by doerakpoes** [comment]
Mabey only miner borgs

**Comment by B1gb3ast** [comment]
I thought that the CMO's hypo was also capable of going through hardsuits, that's odd.

I usually steal one of the minihypo's from mining, seeing as they're always there at roundstart and will go through a 3 meter barbed wall made out of energy shields as long as you can click on the mob.

**Comment by ghost** [comment]
Being done.

**Comment by ghost** [comment]
This is done. Close it.
