### ISSUE TITLE
Items from exploded/burnt backpacks take up the entire tile they're on. 

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#368]
Basically if a backpack is forced to drop its contents from something not player-controlled, it bugs out, making every item in the backpack take up the entire tile, even areas the icon isn't covering. 

Probably caused by the game thinking the item is still in a destroyed backpack, and since items in backpacks have expanded icons to allow easier grabbing...

Kind of annoying since you have to alt+click the tile a person who got blown up is on since you can't just reach around the items they dropped.

**Comment by doerakpoes** [comment]
Bug comfirmed
