### ISSUE TITLE
Changlings

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#37]
opened by Ben · 2 months ago
What is the nature of the issue:Transformation Sting not working or working very rarely
What steps must be taken to reproduce this error:
Become changling get transformation sting
Attempt to sting someone
Fail
Any additional information? :

**Comment by X-TheDark** [comment]
So far, seems that changing [tiny_prick.dm](https://github.com/yogstation13/yogstation/blob/c8b5bf85b54c7c0adb059925829a6246fd115999/code/game/gamemodes/changeling/powers/tiny_prick.dm) makes the Transformation Sting work.
Line 68 from:

```
var/datum/dna/selected_dna = null
```

To:

```
var/datum/changelingprofile/selected_dna = null
```

as well as line 90 to:

```
add_logs(user, target, "stung", "transformation sting", " new identity is [selected_dna.dna.real_name]")
```

and line 91:

```
var/datum/dna/NewDNA = selected_dna.dna
```

**Comment by Xantam-13** [comment]
@X-TheDark - Perhaps open a pull request with this fix? :)

**Comment by X-TheDark** [comment]
As soon as I figure out why Dream Daemon keeps crashing after 3 minutes of starting the game (right at the moment of the "Communications intercepted" thing), I'll get right on that.

**Comment by X-TheDark** [comment]
Ok, so far I was able to make it work, it changes DNA data and doesn't break the game or anything, but it doesn't update the appearence of the target correctly (gender/skin color/eye color/hair/etc, it uses some default settings, such as Bald, Caucasian1 skin color, etc).

I'm going to see if I can make the sting also change the appearence of the target to the correct one in the nearest few hours.
