### ISSUE TITLE
Add customizeable Job ICONs

### ISSUE THREAD

**Issue by Alblaka** [yogstation13/yogstation-classic#370]
Would be nice if HoP's console would have a function where you could assign job titles (by name) to certain icons (maybe represented in some simple text string as well). And add new custom jobs and give them already existing image icons.

Edit: Adding example because people being... people.
[Captain] [captainicon]
[Security Officer] [officericon]
[Random New Job] [blank]
HoP uses new feature, clicks [blank] and enters 'captainicon], and now whoever has the job title 'Random New Job' will have the captain's job icon displayed to sechuds/AI.

I think the reason should be obvious: For any custom job title, Sechuds and AI sec scanner will show up Grey Blanks as job icons. This can lead to confusion and 'better safe then sorry' tazers if a 'Security Paramedic' simply walks into brig (example).

Of course it's just a QoL improvement and I'm not sure how feasible it is to implement...

**Comment by ghost** [comment]
You're just going to end up with someone making their job icon a penis if i'm understanding this right.

**Comment by Alblaka** [comment]
You are not.

I only meant that you can assign any of the existing job icons to new custom titles (or for rogue HoPs, change all job icons to clown symbos).

Aka, make a Security Paramedic, give him the sec officer icon. Or that of a paramedic. Or whatever.

**Comment by B1gb3ast** [comment]
You're just going to end up with someone making their job icon a penis if i'm understanding this right.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<<<<<<<<<<Can someone please tell me why that isn't a thing already?!?>>>>>>>>>>>>>>>>>>
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

**Comment by Alblaka** [comment]
Edited for needless clarification

**Comment by ghost** [comment]
Good news, this might be getting worked on.
