### ISSUE TITLE
Double Click / Drag Issue

### ISSUE THREAD

**Issue by Roppe1** [yogstation13/yogstation-classic#371]
So, I played few years SS13, and I kept pause of 2 month of SS13. Well, I came back to Yogstation! AHH, the relaxing feeling. Yes, I needed to double click to pick up something, and I could not drag my sprite to chair or remove cuffs or strip anything cause of that bug! That has been happening a week or longer. One or few times this bug hasn't been happening on my game's, and it were back again on next time...
I have windows 10, have reinstalled game and I have custom cursors, I tried to remove custom cursor too, didn't help.
Byond: Roppe1
EDIT:
Seems to be the application called "Overwolf", try closing it while playing if you had the same problem I have. Thank you shrimptk for this

**Comment by ShadowDeath6** [comment]
Windows 10 hates byond confirmed

**Comment by FluffySurvivor** [comment]
I have the same issue when league is open. 
Try closing any other games when you are playing spessmen.

**Comment by Rocks4Free** [comment]
I've had the same issue, but I haven't found a way to fix it other than wait and hope. If you double-click something but hold your mouse button on the second click, you can drag whatever onto whatever and it will work.

**Comment by Roppe1** [comment]
Rocks4Free thanks for that tip! Im glad to see im not only one who has this problem.
I hope it gets fixed

**Comment by shrimptk** [comment]
I had the same problem consistently for the longest time, I eventually found out it had to do with Overwolf. Check if you have that installed and if you do, remove it. Byond doesn't like it.

**Comment by X-TheDark** [comment]
This is a BYOND problem, not Yogstation code problem.

**Comment by Roppe1** [comment]
shrimptk! I have overwolf, I'll try that, thanks for hint!
