### ISSUE TITLE
Changeling: Last Resort

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#372]
Well I was changeling and accidently took Last resort instead of lesser form.

I hoped it was fixed but it wasnt

Being a headslug, then laying eggs in a dead body and wait for the eggs to hatch turns you into a monkey.
But if you turn back into a human then you get parmanently kicked out of your body, and your antag status is removed.

Either fix it or remove it entirely.

**Comment by ShadowDeath6** [comment]
Who even uses it, honestly? It's a useless ability and resonant + lesser form is eons more useful.

**Comment by Time-Green** [comment]
I accidently took last resort instead of lesser. It happened before ya know.
But still, an ability that basicly makes the changeling insta lose. GG
Sorry, but either remove or fix it.
I would be fine with both.

A power that instantly fucks you over 100%
Just remove it

**Comment by ghost** [comment]
This has been removed. Close it.
