### ISSUE TITLE
Make removing an apc battery kill a shunted AI

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation-classic#373]
Well, currently, to kill a shunted ai, you have to unweld the entire apc from the wall. Shunting in a malf round is supposed to be a, "oh shit they got in so lets get out and hopefully buy myself a few extra minutes" tactic. It's there so that you can buy yourself a bit of extra time, and once you're found, it's gee gee. 

It could be cool to see this feature re-implemented as a upgrade during malf rounds, where you can spend some CPU and make apcs super robust or something.

**Comment by ShadowDeath6** [comment]
but the AI isn't in the battery, it's in the APC's electronics. Maybe make it so that once the electronics are removed the AI's ded.

**Comment by ghost** [comment]
just welderbomb it you nerd

**Comment by AsV9** [comment]
you only need some extra steps with standard tools to remove it from the wall, so adding this feature would shorten shunted AI lives by like 20 seconds tops.

**Comment by ghost** [comment]
Removing the battery depowers the AI anyway, killing it.
