### ISSUE TITLE
Slime Person Changes

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#374]
I like xenobio.

https://github.com/tgstation/-tg-station/pull/12476

Ports this thing, basically. Makes slime people weaker to coldness and resistant to heat like fire and lasers.
Main thing it adds is that slime people perpetually generate slime jelly if well-fed, and if they hit 200u of it they can split, which lets them freely swap between the two (or more if they split more).

Not really sure how code stuff works, you might need to look for whatever things they referenced it in since there've been bug fixes.

**Comment by ToGWtF** [comment]
Only thing I don't like is it sounds like theres no cooldown/delay between switching bodies. The second sec comes after you/someone sleepy-pens you, you just switch bodies and snitch on them/find them to kill them.

I think there should be some sort of minimum range that both bodies have to be before they can swap minds, or some cooldown+delay between using the mindswap.

**Comment by ShadowDeath6** [comment]
It's a pretty hard to get thing, considering it takes quite a long time to generate that much slime.

Autocloner can do just as well. Also, if you die in one of the bodies you can't swap.

**Comment by Alblaka** [comment]
Sounds like a fun new gimmick for xenobio.
Albeit I feel like that ability kinda implies the slimepeople would need another disadvantage. Especially if they gain heat resistance (especially one as absurd as 50%). Maybe make them twice as long stunned when hit by anything? Because slimey and hard to keep shape?

**Comment by X-TheDark** [comment]
They would have the same weakness as regular slimes, I assume, spray them with fire extinguisher and laugh.

**Comment by ShadowDeath6** [comment]
They're really weak to cold, so stuff like space will wreck them. Not sure if fire extinguishers actually make you cold, though.

**Comment by X-TheDark** [comment]
**I'm makin' this.**

Also, this probably really should...you know what, no, let's not do that what I wanted to do. All I can say is this is going to be **!FUN!** when you understand what I was going to tell you.

**Comment by ShadowDeath6** [comment]
> This is going to be **!FUN!**

Hyped but also nervous to what may come. Sounds pretty good to me.

**Comment by B1gb3ast** [comment]
So when can you vomit 200 globs of slime toxin into someone's mouth and [assume direct control](https://www.youtube.com/watch?v=4ElbUx6lFtY)

**Comment by ShadowDeath6** [comment]
Now that it's merged I'm RIPing the issue. Thanks coders!
