### ISSUE TITLE
Make CE blueprint naming and plasma-pump turning on display logs in adminlog, not just on investigate. Also make CE blueprint naming log in the first place.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#376]
CE's can run around naming places of the station 'DICKVAG' and the AI has to open doors in 'DICKVAG' and if the dominator goes down it alerts the station to a domination attempt in 'DICKVAG.

And we can't tell who named it that. And it's tiring to see places named YOU MOMMAS ASSHOLE LOL and not deal with the guy who did it.

Also, plasma pumps being turned on, and N2O and CO2, should log the same way emitters log-loudly, so we know if someone's flooding ahead of time.

**Comment by doerakpoes** [comment]
Well im not am admin but this seems kinda crucial (go my spelling!)
