### ISSUE TITLE
Make the magnetic speargun's projectile embed

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#378]
Literally worst weapon. It sucks so bad that it just bounces off your skin. 
It could actually become useful during wiz rounds that you get it, woah.

**Comment by ToGWtF** [comment]
Shoot it at assistant
Bounces off assistant and lands at his feet
He picks it up and runs off with your only ammunition
Then ToG lynches you for your gun even though he already has 8 in his backpack and on his belt

**Comment by shrimptk** [comment]
Buff for more practical purposes, like hunting those pesky greyshirts with a high power projectile launcher.
