### ISSUE TITLE
[admin tools] change the worn icon state of clothes

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#379]
As title says, i'd love a var to do that, purely for events and the like.

If it's not possible then just say so

**Comment by ghost** [comment]
It's possible and likely simple, but I don't know how to work with admin stuff.

**Comment by AsV9** [comment]
Can't you just use varedit and set the icon state?

**Comment by Kmc2000** [comment]
Nope, icon state defines the item's icon for when it's on the floor etc. I need worn_state

**Comment by ghost** [comment]
Doesn't item_state determine the icon when worn or held?
