### ISSUE TITLE
Edible Cabbages

### ISSUE THREAD

**Issue by Alblaka** [yogstation13/yogstation-classic#380]
Cabbage people are OP and everyone knows it. Thus, I propose the ultimate nerf: Make them edible.

In detail: Targeting a Cabbage's head, will initiate a short 'x starts plucking leaves from y's head' message. Upon completion, the cabbage takes 5 brute damage (aka neglectible because healing) and the plucker gains some edible valid salad.

This will nerf cabbages by making everyone and the world constantly insist on plucking valid salad.

**Comment by Time-Green** [comment]
This is really not neccessary.
Cabbage people already have the ultimate weakness. 2x fire damage

To put that into perspective. You take 30 damage from a welding tool as cabbage.
Thats the same as an esword.

**Comment by B1gb3ast** [comment]
Goddamnit alblaka.
god.damn.it.

**Comment by Kmc2000** [comment]
WANT

NOM NOM NOM CABBBBAAAAAAAGE

**Comment by ShadowDeath6** [comment]
You can get special plant meat from gibbing them though, how about it just drops cabbage WITH the meat?

**Comment by X-TheDark** [comment]
It's not double fire damage, only 50% extra damage from burn/fire.

**Comment by ghost** [comment]
ADD.

ADD.

ADD.

Also it should be double burn damage, change that.

> This is really not neccessary.
> Cabbage people already have the ultimate weakness. 2x fire damage

To put that into perspective. You take 30 damage from a welding tool as cabbage.
Thats the same as an esword.

are you serious

**Comment by Time-Green** [comment]
Fucking hell its not????
People specificly told me it was.

errr, forget everything then.

**Comment by ToGWtF** [comment]
If we add this, we need to add the ability to remove Lizards tails in surgery so they can't ever walk straight again

**Comment by X-TheDark** [comment]
> If we add this, we need to add the ability to remove Lizards tails in surgery so they can't ever walk straight again

If we add THAT, we need to give Lizards more agility when they have their tail, because they should be able to use it for balancing/stabilizing themselves, meaning they should be capable of turning/maneuvering better.

**Comment by ShadowDeath6** [comment]
> Buff lizards

No please don't do it

**Comment by B1gb3ast** [comment]
> If we add THAT, we need to give Lizards more agility when they have their tail, because they should be able to use it for balancing/stabilizing themselves, meaning they should be capable of turning/maneuvering better.<

Yeah, no. Just make them permanently drunkwalk if their tail gets surgically removed. Also, to the issue at hand. Why not add a chance for a cabage to drop leaves if you hit them.

**BWOINK**
Admin PM >> Why did you kill them?
player reply >> I was hungry

**Comment by krgii** [comment]
Plant people sacrificing themselves to save starving crew.
https://www.youtube.com/watch?v=Mc6vU6fQcnE
