### ISSUE TITLE
Make the syndicate nuke start anchored

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#386]
Title.
Removes shitty meta of securing the disk AND the nuke.
Requires the disk to be inserted for the nuke to be unanchorable.
No more shitty borgs or space suit assistants stealing my high tech fission weaponry >:^)

**Comment by ToGWtF** [comment]
iirc you can cut the bolts off the nuke to unanchor it?

This makes nuke ops way too easy though. Its REALLY not hard to drag the nuke out with you as you first leave and stash it somewhere

**Comment by ShadowDeath6** [comment]
> stash it somewhere

yeah, then it gets stolen and spaced from there. Ops are supposed to be offensive, not defensive. They're assaulting the station.
Also cutting off the bolts is still more work than welding and wrenching some walls.

**Comment by ToGWtF** [comment]
If its true you can cut the bolts then sure let it start anchored. The best it will do is give you a few extra minutes if someone competant finds your shuttle. If a random baldie finds it, well,  you're pretty safe then

**Comment by ghost** [comment]
stupid and bad 

ops shuttle is getting turrets anyway

**Comment by shrimptk** [comment]
> turrets

The targeting fucking blows and everyone knows it.

**Comment by ghost** [comment]
good luck welding in when being shot

**Comment by ghost** [comment]
eh, give the nuke some walls and a door to hack through as well i guess maybe
