### ISSUE TITLE
Power alerts for Derelict bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#387]
Received alerts on PDA:

"Power Alerts:

The Derelict Computer Core
The Derelict Primary Hallway
The Abandoned Satellite"

Whether related or not, at that moment the power monitoring showed no APCs (common problem that occurs rarely for some reason).

**Comment by Cruix** [comment]
That's my bad, I'll make it only work for alerts on the same z-level.

**Comment by 00aquir** [comment]
thanks
