### ISSUE TITLE
Agent ID's can change appearance too. (suggestion.)

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#388]
Can't disguise as Head of Personnel even if you have the jumpsuit, voice changer, ect, to pull it off due to agent ID not looking like HoP's shiny ID card.

So allow the ability for agent ID cards to change their appearance on command, too. Captain's gold, Head of staff silver, prisoner orangish-red, Centcomm color ID for the gimmick traitors who pretend to be a centcomm inspector.

**Comment by FluffySurvivor** [comment]
have all my yes
:+1: :+1: :+1: :+1:

**Comment by Time-Green** [comment]
This is so fucking shit. Dont they already have enough?
Now every single traitor fuck can make a captains spare ID.
Are you fucking kidding? This is so retarted.

(someone had to do it)
Good idea

**Comment by ParagonPrime** [comment]
Don't see why not, !BUT!

Make it so you can only set your ID to the appearance of an ID you've already scanned. So you actually have to scan the Cap's ID to get the gold into your forgery database.

**Comment by ghost** [comment]
True, but prisoner and Centcomm ID's should come inbuilt.

EMPing the agent card should make it lose all it's stored accesses and start changing ID colors randomly.

**Comment by ParagonPrime** [comment]
^yes, yes that shall work.

Not seeing much use for the prisoner ID, though, except for super-gimmicking...

**Comment by ShadowDeath6** [comment]
Emping won't make much of a difference unless the person examines you rapidly.

**Comment by ghost** [comment]
it'll still fuck over the lost accesses.

maybe it should scramble names too, so it goes from 'Vide Rein' to '!$@#^THSARWQRBFG@!%I*^#!WTFBBQ'

**Comment by ShadowDeath6** [comment]
Do EMPs actually remove access from agent cards? That would be a pretty big nerf if it were true.

**Comment by ghost** [comment]
I'M SAYING ADD THAT AS A FUNCTION OF EMP'S YOU CUCK

**Comment by Super3222** [comment]
Agent cards don't GET access. They have access to maintenance airlocks though.

**Comment by ShadowDeath6** [comment]
> they don't GET access

You can scan access from other cards, an EMP could reset that.

**Comment by ghost** [comment]
> Agent cards don't GET access. They have access to maintenance airlocks though.

^bad traitor

**Comment by DavidEdwards** [comment]
I can get behind this one. Should be s imple change for someone to make too.

**Comment by ghost** [comment]
Is done.
