### ISSUE TITLE
Penlight doesn't provide messages. 

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#391]
Step 1. Direct penlight to eyes.
Step 2. Nothing happens other than the penlight message saying you did it.
Step 3. Get blinded by injecting yourself with a bad SE.

**Comment by ParagonPrime** [comment]
Can confirm, really detrimental as Geneticist.

**Comment by ShadowDeath6** [comment]
Honestly it isn't that detrimental due to how blindness works, just an extra injector syringe.
