### ISSUE TITLE
Clown Cars (Suggestion)

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#393]
May or may not be a joke suggestion, but it would be fun to have a clown car orderable by cargo for a high amount of points. Alternatively, it could be made by robotics with bananium. It would be able to fit 8 people inside, but only someone with a clown/mime ID would be able to drive it. Optionally, if emagged, it would work like mulebots and be able to run over people lying down. 

Inb4 "go kill urself skrub"

**Comment by ghost** [comment]
go kill urself skrub

Goon does have this sort of thing for a clown car that's buyable by traitor clowns.

Adding it to a traitor clown's PDA would be pretty hilarious. Drag people to the car to lock them inside, ram into them to knock them over, once you have like 15 people drive into the singularity.

**Comment by ShadowDeath6** [comment]
> go kill urself scrub

Sounds honky, probably should be worth 20 tc if it's as good as goon's.

**Comment by PineappleWolf** [comment]
Oh god Goon's car.

**Comment by Kmc2000** [comment]
I actually suggested this

I'll sprite this if adam doesnt shit all over it and get this idea relegated

But definately traitor clown thing, HONK

**Comment by PineappleWolf** [comment]
Considering goon's leaked we at least have a basis to **learn** how to do it based on theirs.

**Comment by Kmc2000** [comment]
>LEARN

what is there to learn? it's literally just a janicart reskin
