### ISSUE TITLE
Gamebreaking bug concerning botany

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation-classic#398]
Vanilla seedlings cannot be acquired at all leading to not being able to acquire vanilla leading to ME NOT BEING ABLE TO MAKE MY VANILLA PUDDINGS

WORST
CODING
TEAM
EVER

**Comment by ShadowDeath6** [comment]
Chocolate > vanilla

**Comment by Cruix** [comment]
You can get them by mutating generic seeds. I'm pretty sure this is a coder joke, because generic seeds appear to be abstract and should never exist in-game.
