### ISSUE TITLE
Rev

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#40]
opened by Alex West · about a month ago
What is the nature of the issue: Revheads not being able to flash to convert.
What steps must be taken to reproduce this error:
Be revhead
Flash guy.
!!No profit!!
Any additional information? :
[16:44:39] Adam El-Tablawy: I've seen revs, normal revs, flash people to convert them and I've seen revheads be unable to convert even when revheaded and derevheaded

**Comment by BadminBen** [comment]
Please provide a update on this

**Comment by george99g** [comment]
> Please provide a update on this

You might want to tag the person who made the original issue.
I just copied it here when we moved so I can't add anything.

**Comment by george99g** [comment]
Closing this since it doesn't seem to be a bug anymore.
