### ISSUE TITLE
Buff earmuffs

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#403]
Usless item, reee.

Basically consists of 2 main parts-

Let people hear talking but still blocks the sound part of flashbangs. See: bowman headsets

Make earmuffs creatable in an autolathe as tools or something OR found in maint like sunglasses are. 

INB4 ">LETTING CREW GET SHITTY EAR PROTECTION"

Still worse than a bowman, since it doesn't have radio functionalities. Combine with regular sunglasses and you have some moderate amount of protection from flashbangs.

**Comment by X-TheDark** [comment]
No. Flashbangs at the moment are pretty much the only AoE control security have. If you give random assistants ability to get ear protection, suddenly, lynch mob is even stronger. Against.

**Comment by B1gb3ast** [comment]
Against as well.
