### ISSUE TITLE
Hackable Chem Dispensers

### ISSUE THREAD

**Issue by Maxiemo** [yogstation13/yogstation-classic#408]
Alright, since Adam is going to tell me I'm a moron for suggestion this, I want to get this out of the way quickly. I think that chem dispensers should be hackable in order to more directly configure the quantity of chems released into the beaker. For example, if you want to make Atropine, you currently have to waste an entire beaker to create the minimum amount of Acetone possible:
[45 Acetone]
    [15 Oil]
        5 Welding Fuel
        5 Carbon
        5 Hydrogen
    15 Welding Fuel
    15 Oxygen
And then constantly juggle that back and forth through beakers with Diathylamine and Phenol, Ethanol and Sulphuric Acid.

What I propose is this: After a 'ChemMaster' is hacked, it then gives the ability to dispense 1u or 100u of a chemical at a time, making it much more  convenient for chemists to make complex drugs.

Edit: Also I'm an idiot who doesn't know how to add labels to requests.

**Comment by ToGWtF** [comment]
Dump 5u into a small beaker, then use the convinently provided dropper that can select anywhere between 1-5u to add chemicals to the correct level

**Comment by Maxiemo** [comment]
So, your saying I should clutter the table with beakers full of each individual chemical? That seems like it would be quite the hassle.

**Comment by Maxiemo** [comment]
Or are you saying, every time I need 1u of a chemical I insert a beaker, dispense 5u, take it out, get the dropper, click on one beaker, click on the other, and then empty the temporary beaker. Cause that's even more hassle.

**Comment by ShadowDeath6** [comment]
Depends how much chems you want in each one. Syringes and droppers are generally the go-to thing, though.

**Comment by ghost** [comment]
So basically meaning the chemmaster gets to choose 1 to 100u instead of being limited to 5, 10, 15, 20, 30, 50, 100?

I can see that, yeah.

But instead of hacking, make that unlocked by R&D tiers-Hilariously enough the chemmaster isn't even a buildable machine, only the porta chemmaster, so making the chemmaster a machine with more chems unlocked when upgraded and greater selective range?

That'd be pretty swell.

It could just use 2x the parts the portamaster does.

**Comment by ShadowDeath6** [comment]
> 2 console screens

for what reason

also, making chem-masters R&D'able will turn science into even more of a bomb factory, but ten times quicker.

**Comment by ghost** [comment]
not R&Dable

no boards for them

only upgradable

**Comment by ToGWtF** [comment]
You could also just add more chems then you need, pop them in the chemmaster, and remove specific amounts of reagents.

I like where your head is at with this, but theres already ways to do this take don't take more than an extra few seconds.

**Comment by Maxiemo** [comment]
I think my browser is messing up... Adam didn't call my idea retarded? What is this?!

All jokes aside, I imagined it would be something like using a screwdriver on the machine to open its port, then putting a manipulator in it. Using a micro manipulator allows 2u, a nano manipulator allows 1u, and a pico manipulator allows custom amounts. Each manipulator would also have the abilities of the previous tiers. Then you use the screwdriver again to close the machine's port. Clicking on the machine with an empty hand when the port is open will remove the manipulator currently inside it.
