### ISSUE TITLE
Research Overhaul

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#41]
opened by Alex West · about a month ago
Pretty simple, but I think it will be effective and make science more !!FUN!!. Make it so that research levels have to be gained via the Experimentor instead of destructive analyzer. Item goes in, they spam buttons until item is gone, normal levels they would get. With potential bonuses sometimes because rng is nice guy.
Makes science less dull as a whole, via the RNG nature.
Also I'm sure we need the meteor showers which it can cause back. ;)

**Comment by ghost** [comment]
NO

WHO THE FUCK IS THIS GUY?

'HURR DURR LET'S TAKE A NON-RNG JOB AND MAKE IT COMPLETELY RNG'

THAT'LL WORK

Against against against against against. If this gets merged I will set myself on fire in protest.

**Comment by george99g** [comment]
> If this gets merged I will set myself on fire in protest.

Don't wanna merge it but also wanna see this happen.
The choices!

**Comment by Groudonmaster** [comment]
Let's make it so there's a chance you have to use the experimentor instead because let's be honest science knowing exactly what they're doing every round is really boring.  Like I get people enjoy doing RnD sometimes because of the predictability but it's just really annoying when someone runs around with xrays 20 minutes in because they know what they're doing.

**Comment by Hydre** [comment]
Making research random (sort of) would be a great idea

Fuck powergamers

I was thinking about changing it to something where you actually would have to think..Something in the sense of how goon goes about genetics.

**Comment by Super3222** [comment]
> science knowing exactly what they're doing every round is really boring

I can say, as a person who use to play as the Research Director each and every round maxing research, science gets REALLY boring. Unlike the other jobs, there's no surprise or anything popping out at ya at random. Unless there's an anamoly, which barely happens anymore, you could get it's core and make a Phazon. RnD becomes a chore to do.
