### ISSUE TITLE
Centcomm drone'spenser

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#412]
An infinite factory of drone shells that only comes online when the escape shuttle docks at CC.

Because why the fuck not? Let ghosts dick around on CC after the round is already over. Maybe even have an automatic syndrone arena set up once a certain amount of time has passed.

**Comment by ShadowDeath6** [comment]
too op, cue 400 energyshield drones with thompson SMGs and pulse destroyers

**Comment by ghost** [comment]
No.

**Comment by Super3222** [comment]
At round end, admins are suppose to enjoy bussing the players for being so shitty during the round.

**Comment by ghost** [comment]
It can spawn or activate when shuttle docks at CC. Would be fun instead of getting instant death and waiting for ticket-heavy rounds to end.

**Comment by ghost** [comment]
No.

**Comment by FluffySurvivor** [comment]
I agree with this. 
ADAM SHUT UP

**Comment by Time-Green** [comment]
Fuck no
When round ends, I can beat the crap out of every singe person for ahelping.

I dont want drones in my way

**Comment by ghost** [comment]
No.

I don't want more requests about ADMINS TURN ON THE DRONE DISPENSER LOL ADMINS SPAWN ALIENS AT CENTCOMM LOL.

It has enough and coders have more shit to deal with than this...useless thing.

**Comment by ParagonPrime** [comment]
okay how about you reread the suggestion again

it is a DEAD-EASY SCRIPT that spawns SOMETHING THAT ALREADY EXISTS into centcomm AUTOMATICALLY at a time when PEOPLE AHELP TO END THE ROUND BECAUSE THEY HAVE NOTHING TO DO- this suggestion's sole existance is to AMUSE PEOPLE AT THAT TIME WHEN THEY AHELP because ADMIN INVOLVEMENT IN THE PROCESS OF SPAWNING THESE DRONES WOULD BE NIL

reread that a few times
there is literally zero reason not to implement this

**Comment by lanhikarimega** [comment]
It would give you something to do, until Centcomm was completely destroyed because no one even tries to hold back, they just run after the guns and pick up the first they find (often the Gyrojet pistol) and blast the crap out of the whole place, and if they survive, they will hunt whoever is alive.

It may be a good idea, but in that case, it would be best if we once again restricted the access to the AB-USE room, since i already seen drones wreck everyone in there, and an army of them would only make things worse, and on the Meta side, there could be people suiciding or jumping off the shuttle just so they could get the drone (Obviously, this doesn't apply to Traitors)

**Comment by ParagonPrime** [comment]
But...

What's the problem with people suiciding to get drone or the drones destroying CC?

**THE WHOLE POINT IS THAT IT'S AFTER ROUNDEND. NOTHING MATTERS AFTER ROUNDEND. LET THE DRONES ANNIHILATE EVERYTHING, HIJACK THE CARGO SHUTTLE, AND RIDE BACK TO CONQUER ALL OF KNOWN SPACE WHILE ADMINS HANDLE TICKETS.**

**Comment by Yackitori** [comment]
Why not just put drones into the Centcomm th-th-th-THUNDERDOME and let them duke it out with eachother. Just wall it off so nobody can get in or out.

There. Drones don't get in the way of you end round griffers and the dead get a nice little thing to do before the round starts.

**Comment by Groudonmaster** [comment]
Thunderdome is already separated. It was separated when we made the CentComm changes.

**Comment by DavidEdwards** [comment]
We have long wanted to add things to give players something to do during tickets.

**So long as no time is required from admins**.

**Comment by ghost** [comment]
No.

I don't want to waste my time listening to prayer after prayer of 'ADMINS ACTIVATE THE DRONE DISPENSER' during the round.

And if a round is exceptionally shitty I'm not going to reward anyone for being shitty by letting them do anything other than die at round end.

**Comment by Groudonmaster** [comment]
We have a mute button for a reason Adam.

**Comment by Alek2ander** [comment]
Admins can spawn drone shells if they thing it would be a good idea. And if they don't have the perms, then it isn't a good idea anyway.

**Comment by Groxic** [comment]
Someone doesn't get the issue request. It was to add a drone dispenser that automatically starts dispensing when the shuttle docks at CC, not to have admins spawn crap at the end of the round.

**Comment by ghost** [comment]
It is just a drone dispenser that turns on when the shuttle arrives at CC, which doesn't require admins and can be ignored.
