### ISSUE TITLE
Give wizards charge

### ISSUE THREAD

**Issue by abdbla** [yogstation13/yogstation-classic#417]
give wizards the ability to choose charge in the utility spells tab

**Comment by Super3222** [comment]
i think the reason this isn't a thing is because the wand assortment belt is a THING. we also don't wanna give wizards the option of manifesting 6 staffs for 2 points.

**Comment by abdbla** [comment]
You can still do that by getting a wizard apprentice: healing. they get charge and you get a healing staff too.

**Comment by Alek2ander** [comment]
Wands lose maxcharges when charged, so it's not like they become infinite or anything.

**Comment by ShadowDeath6** [comment]
Wand of death would become a 55 use item and I don't know if the server is ready for that
