### ISSUE TITLE
Shadowlings can drag people with them through closed airlocks after using that phase shift ability

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation-classic#418]
Sounds a tad bit silly to me that they can drag people along with them through closed airlocks.

**Comment by ghost** [comment]
Not a bug.

They can pull people through walls, doors, ect. 

Intended feature.

**Comment by GrayRachnid** [comment]
Then make this a suggestion, nerf shadowlings.

**Comment by ghost** [comment]
Get good.

**Comment by ShadowDeath6** [comment]
As much as I advocate shadowlings, they are literally unbeatable if they know how to use their abilities.

**Comment by PineappleWolf** [comment]
Iunno Shadow, I have had the fortune of murdering a few with dragon breath combat shotgun spam and general teamwork.

**Comment by ghost** [comment]
> light shadowling on fire
> 
> it is now it's own light
> 
> can't veil to extinguish
> 
> shadowling dies because it can't jaunt away
> 
> two people working in groups = GG
> 
> one torch = GG
> 
> opening a hole to space in maint = GG
> 
> even random luck with taze 'n laze = GG

**Comment by ShadowDeath6** [comment]
> light shadowling on fire
> it extinguishes itself with a fire extinguisher
> it phases through 15 walls
> it comes back and eye rapes your best friend
> drags him through the wall
> tase it
> it immediately gets back up because darkness
> you suffer

only bombs can save us from meme hell, don't nerf shadowlings

also, space doesn't emit light, it just has light on that existing tile, so even if you wanna expose all of maint to space, they can still kek through the darkened walls.

**Comment by DavidEdwards** [comment]
Intended.
