### ISSUE TITLE
New skin/race

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#42]
opened by Xantam · about a month ago
Nature:
Race/skin
Thread linked:
http://forums.yogstation.net/index.php?threads/cosmetic-kmc2000.7614/
Base content:
What is your idea type?:
Cosmetic

Give us a short description of your idea?:
cylons

Give us a full description of your idea?: Cylon race for donors, purely cosmetic but they would have an animated eye.
By your command

**Comment by DavidEdwards** [comment]
We have an Android race now. I don't think it is necessary to also have a Cylon race. We can reopen this if there is still a desire.
