### ISSUE TITLE
Buff Biosuits

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation-classic#421]
Biosuits currently serve zero purpose, unless you're the viro and don't want to spread brainrot everywhere and get bant.

Make biosuits more robust when fighting a blob (After all, they are a biohazard). It'd also be cool if biosuits make you uninfectable by zombies, (Unless they already do that).

(Bracing for Adam salt)

**Comment by PineappleWolf** [comment]
Zombies cannot bite through biosuits/Hard suits the last time I checked forever ago.

If that helps, unless it was changed.

**Comment by ShadowDeath6** [comment]
Biosuits DO protect against blobs. The splashing of chems when the blob attacks you countd as touch, so it protects a bit, same with chem and sci labcoats. 
Also biosuits block zombie bites completely.

**Comment by ghost** [comment]
Biosuits also protect against blobs.

And prevent zombie infections.

They also tank facehuggers like nothing else.

I can't think of any way to make them more robust. That being said, a syndicate biosuit that has no slowdown would be pretty cool. Maybe if biosuits also came with an inbuilt emergency oxygen tank?

**Comment by ShadowDeath6** [comment]
> tank facehuggers like nothing else
> hardsuits not being infinitely better

**Comment by ShadowDeath6** [comment]
Newcops hardsuit exists so nobody would buy biosuits

**Comment by ToGWtF** [comment]
I think biosuits need a nerf. They should obscure your vision, cut off your view range by a little bit but less than a welding helmet does

**Comment by ShadowDeath6** [comment]
Biosuits aren't even op, there are like a quadrillion better options. No changes pls.

**Comment by DavidEdwards** [comment]
I think this needs no change at all.
