### ISSUE TITLE
Add parallax to space

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#422]
Demonstration: https://gfycat.com/ThoughtfulDenseAnophelesmosquito
It's just adding a client underlay and removing the icon from space turfs so the underlay shows through. Simple and effective.

**Comment by ShadowDeath6** [comment]
My brain hurts :+1:

**Comment by oisin100** [comment]
What server is that on? As i have no idea how they managed to do that with DM...

**Comment by ToGWtF** [comment]
@oisin100 
Paradise. Unlinking because I guess links show up on their PR >.>

**Comment by X-TheDark** [comment]
Ah, nice, good to see latest DM features used.

**Comment by 00aquir** [comment]
There is a major problem with this. You won't see if you're moving or not, or what direction you're moving to when there's no solid object in space but you were hit by flying things out there. You won't necessarily face the same direction you're flying to in space.

**Comment by Alek2ander** [comment]
You **won't** see if you're moving or not. And that is realistic.
Space exploration is too easy, if this makes it a bit more tricky I'm all for it.

**Comment by DavidEdwards** [comment]
I'm entirely for this. A momentum indicator _could _be added to the HUD to indicate what direction someone is currently heading.

**Comment by 00aquir** [comment]
> Space exploration is too easy, if this makes it a bit more tricky I'm all for it.

Well if it's intended then ok..

**Comment by oisin100** [comment]
On paradise its a optional feature. You can turn it on and off in your character preferences if you dont like it.

**Comment by Spacemanspark** [comment]
Paradise nerd here. Sadly, removing a link from a PR won't remove it from the PR you linked to.
But oh well, it's interesting to see many other codebases want this.

**Comment by monster860** [comment]
> Sadly, removing a link from a PR won't remove it from the PR you linked to.
> But oh well, it's interesting to see many other codebases enjoy this.

Yup. I'm the guy that made the original PR here. It's nice that other servers are starting to do this.

> As i have no idea how they managed to do that with DM...

The basic idea is simple: Space tiles are made white, and areas where you can't see anything are already black, so that's taken care of. Simply have a /obj/screen layer for space, and BLEND_MULTIPLY it by the white space tiles. However, where you can't see anything, it's BLEND_MULTIPLY'ed by black, and stays black.

**Comment by oisin100** [comment]
> /obj/screen layer for space

Yea, I did not think Byond could do something like that... Good to know however!

**Comment by Super3222** [comment]
This would be pretty cool, honestly. :+1:

**Comment by Axemeaquestion** [comment]
Is this abandoned?

**Comment by Spacemanspark** [comment]
On Paradise? Eh, it's kinda delayed at the moment.

**Comment by FluffySurvivor** [comment]
On para it can be toggled on/off. 
So yes let's bring it home.

**Comment by monster860** [comment]
Tigercat has given it his "Okay, merge it now".

> myeh this is mildly better now and the planes n' shit seem okay for their purpose so this is okay i guess :neutral_face:
