### ISSUE TITLE
Triple vent output does not work.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#425]
Triple vent output environmental setting on air alarms should boost the repressurization for a short amount of time normally. After it was set on the air alarm, with 9000 kpa outgoing in Atmos (after somebody changed the pump), pressure still increased about 0.1 kpa/sec...

**Comment by ToGWtF** [comment]
Generally, you can set the vent pressure manually to over 5000kpa. More usefull for malf AI's, as it will keep spreading plasma even if a fire sets the ambient pressure of a room past what the vent it set to output

**Comment by ShadowDeath6** [comment]
You gotta set the air alarm to allow pressure over 100kpa for it to go fast iirc

**Comment by 00aquir** [comment]
There is no other option. The only other way to change the pressure on air alarm is in "Vent control", which is automatically set to 303 kpa anyways when you turn on "Triple vent output". Right now it seemed to raise pressure somewhat (Atmos 1300kpa, air alarm 303kpa), but it's still around 0.2-0.5 kpa/ sec.. that should be faster.
