### ISSUE TITLE
Make preternis suffer more from EMPs

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#427]
Have a super low 5% chance of making their heart stop upon EMP, basically making it work like their organs are augmented too. Can be cured by shocking yourself on something or defibbing.

**Comment by ghost** [comment]
They already suffer enough. Four EMP's can fuck a preternis's round.

**Comment by ShadowDeath6** [comment]
It just drops their nutriment level and does damage, getting shot in the circuitry should probably fuck you up more than that.

**Comment by ghost** [comment]
dropping their nutriment level blinds them

they also get stunned by it for a long time, around 9 seconds, and does heavy damage

**Comment by PineappleWolf** [comment]
Yes, as a Preternis player, FUCK EMPs at the moment.

I can verify what Adam says, it's not a fun time right now, and thats only from one. Pretty sure if you wanted to an Ion RIfle full clip could probably decently damage if not crit/kill a Preternis.

**Comment by ShadowDeath6** [comment]
I didn't realize it blinded and did all that, oh well. Thread seems to have run its course.
