### ISSUE TITLE
Recruitments pens dont recharge in PDA's

### ISSUE THREAD

**Issue by abdbla** [yogstation13/yogstation-classic#428]
If you put a gang recruitment pen in your PDA, it doesnt recharge.

**Comment by ShadowDeath6** [comment]
Last I checked they do, they might recharge more slowly though.

**Comment by abdbla** [comment]
How long is the recharge timer for a pen?
it seems like about 2 seconds

i had it in the pda for about 30 seconds, no recharge.

**Comment by Alek2ander** [comment]
The pen generates a charge every 2 minutes (+1 minute for every lieutenant), and has a 5 second delay between uses. 30 seconds isn't enough time for it to recharge if it runs out.

**Comment by ToGWtF** [comment]
If you don't use it while its charged, it can keep gaining charges saved up. You may have been using your pen just seconds before its next charge cycle

**Comment by ghost** [comment]
On testing, it takes the same in PDA as out.
