### ISSUE TITLE
Infinite meat?

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#429]
> be xenobio
> gib monkey
> Inject monkey meat with monkey blood
> Bite meat like 80 times
> Meat not gone
> Scan chemical contents of myself
> 1.5 units of nutriment
> 45 units of blood

What

**Comment by Alek2ander** [comment]
When you bite a piece of food you actually consume a fixed amount of reagents inside, and the snack is completely eaten when the reagents run out. By adding more reagents you make the snack take longer to eat, but you don't get any more nutrition .

**Comment by ShadowDeath6** [comment]
But it was replicating nutrients. I injected 15u of monkey blood and I ended with 45u in myself with meat to spare.

**Comment by AsV9** [comment]
"""intended""" behavior

**Comment by ShadowDeath6** [comment]
indented

**Comment by X-TheDark** [comment]
Doesn't seem to be the case anymore:
1. Spawn monkey meat slab;
2. Inject with 15u of blood;
3. Eat the meat completely;
4. Scan self to find your blood increased by about 15, sometimes less, but definitely not 45;

Am I missing something?
