### ISSUE TITLE
New HUD's as optional

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#43]
opened by Xantam · about a month ago
Nature:
New HUD's and possibly GUI to select one
Thread linked:
http://forums.yogstation.net/index.php?threads/cosmetic-crazy_drakkon.7660/
Base content:
What is your idea type?:
Cosmetic

Give us a short description of your idea?:
Additional HUD styles.

Give us a full description of your idea?:
Other than a little spriting, I don't see the harm in additional HUD styles, and they're pretty cool. :P I'd recommend a Pipboy-esque and Syndicate style one? You say.

**Comment by DavidEdwards** [comment]
New huds have been added.
