### ISSUE TITLE
Goonstation

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#432]
Making this an issue, so that all coders see it.

Guys. Just found out about this Goon shit. **Do not copy paste their code into our code base**. 

This might be 2d spessmens, but we are still in the real world. It is very much **ILLEGAL**. Not to mention immoral.

We have no right to the code in that code base. I will close this issue later in the week.

**Comment by Stealthkibbler** [comment]
They do not have a license on their code, you cannot 'steal' their code and it is definitely not illegal. Why they are so upset about this I cannot fathom.

**Comment by DavidEdwards** [comment]
Of course it is illegal, and taking their code _is_ theft. Simply because it is on Github, does not mean that it is open source and open season. Please do some research on the subject.

**Comment by Stealthkibbler** [comment]
Unless they got actual legal paperwork to represent a legitimate copyright or trademark on their codesource it is not illegal to take it from them.

**Comment by DavidEdwards** [comment]
1. No license does not imply free / open source.
2. What makes you think their actual code base has no license?

**Comment by Stealthkibbler** [comment]
Everyone says their code only has a license on the GPL and nothing else. The post hasnt even been taken down on reddit yet the people responsible were banned, so no, it's not illegal because they cannot remove the content.

**Comment by DavidEdwards** [comment]
"Everyone says" is not a legally binding agreement.

"it's not illegal because they cannot remove the content" - I don't even.

Please, [read this](http://programmers.stackexchange.com/questions/26548/what-is-the-default-software-license) and educate yourself.

**Comment by Stealthkibbler** [comment]
And you think anyone will give a shit? You think this is going to incriminate anyone because they downloaded a copy of gooncode? This isn't going to do jack all, the only reason why this issue arose is because the developers of Goon thought it would be smart to make their code closed to anyone outside of their team and then when to no surprise someone leaks it, it starts a dramastorm.

Even if they had it officially trademarked or copyrighted it wouldn't mean shit regardless of the circumstances, as long as it was closed source someone was bound to release it and in the upcoming week everybody will stop caring because its goon anyway.

**Comment by AsV9** [comment]
I do not care what you do. I, on the behalf of Yogstation, does not take responsibility for what you choose to do. Unless an official goonstation statement permits us to we will not use this. You're free to read the code and learn from it but none of it goes into this repo. You can do whatever the fuck you want with it, Stealthkibbler.

**Comment by Stealthkibbler** [comment]
Then i will and i shall leave it on my desktop where it shall stay for the rest of eternity because I cant be fucked learning gooncode.

**Comment by oisin100** [comment]
Does goonstation even have a Repo anymore?

**Comment by ToGWtF** [comment]
As much as I would want features from Goon to play with, without having to play with the Goon community, I don't think many of them would fit into our community.

**Comment by shrimptk** [comment]
They could still prosecute for theft of intellectual property, so slapping their hard work on our server is a **BIG** no-no.

**Comment by AsV9** [comment]
'Ehh. Technically, Goonstation can't claim owning SS13. So if they can't prove to a court they are so far away from any other codebase they are a different game they really do not have a court case. Unless the original creator of SS13 pops in, that is.

It's more about ethics at this point and just to clarify, we will reject any pull request with goon code in it.
Coderbus and probably other servers will aswell.

**Comment by Alek2ander** [comment]
If anyone can claim owning it they can. The original creator of SS13 is part of the goon dev team, and all other servers are based on leaked goon code.

**Comment by darkwahn** [comment]
It'd be annoyingly difficult (at best) for them to try anything from a legal perspective for using their code.

**Comment by Time-Green** [comment]
The tags man, the tags

CRITICAL FUCK

**Comment by Xantam-13** [comment]
They have given us, and every SS13 server permission. This can be closed.
