### ISSUE TITLE
THE MYSTERY OF THE INVISIBLE C4

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation-classic#433]
### Expected Behaviour

Makes the C4 on the heater go invisible, but the C4 still stays there however you cannot see it.
### Steps to reproduce the problem

12:10:09 - H4zardZ1 - 1. Turn a space heater on

12:10:09 - H4zardZ1 - Ticket created by H4zardZ1

12:10:29 - H4zardZ1 - 2. Place a C4 at the space heater
12:10:51 - H4zardZ1 - 3. Turn off the Space heater
12:11:06 - Stealthkibbler/(Stealthkibbler) - What does it do?
12:11:35 - H4zardZ1 - It makes the C4 nosprite, and you can´t rightclick examine it
12:12:02 - Stealthkibbler - Alright will put it up on github, it probably just needs a new sprite since I assume the heater swaps sprites

**Comment by ToGWtF** [comment]
> attach remote signaller to c4
> drag space heater 
> leave infront of HoP door
> HoP leaves his office to beat(off) a clown

aand boom goes the dynomite

**Comment by PineappleWolf** [comment]
So basically the state of the icon from the space heater causes the c4 to be wiped.

The question is if it will still explode after it nosprites. If not, the C4 is just getting erased due to a change in state of the thing it was placed on, otherwise, a sprite glitch.

**Comment by Cruix** [comment]
> attach remote signaller to c4
>  drag space heater 
>  leave infront of HoP door
>  HoP leaves his office to beat(off) a clown

You can't use signalers once the C4 has been placed on something.

**Comment by ShadowDeath6** [comment]
Why would you want to put a c4 on a space heater otherwise?

**Comment by ToGWtF** [comment]
You can add a signaller before you place c4 thought right?

**Comment by Cruix** [comment]
You can add the signaler and use it to set off the c4, but once you place the c4 on something, the detonate wire stops working.
