### ISSUE TITLE
Make Thermals Cooler

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#437]
At the moment, thermal vision just grants the SEE_MOBS flag, letting you see people through walls. I would like to change it so that it instead puts a transparent red-orange overlay on mobs (and some other hot objects, like active space heaters), visible through walls and darkness. If the mob's body temperature is very low (a dead body in space), they will not have the overlay, or their overlay will be dimmer.

I believe I can do this with icon blend procs so that if a piece of clothing has cover flags, it will make the limbs it covers dimmer, but still visible. This will make it easier to identify sec, since armor covers the chest. Clothing with limb thermal protection flags (fire suits and space suits) will make the limbs even dimmer, or possibly invisible. You will not see their clothing or what they are holding (unless it is a typically hot item, like a torch), and you will not be able to examine them.

Please discuss.

**Comment by DavidEdwards** [comment]
I love it.

It will be a lot of work for someone though.

**Comment by ShadowDeath6** [comment]
This isn't making thermals better though, if it removes the ability to examine people through walls.

**Comment by Cruix** [comment]
Changed the name.
Inb4 "thermals are hot not cool"

**Comment by ghost** [comment]
THERMALS ARE HOT, NOT COOL

CHANGE IT TO 'MAKE THERMALS AWESOME'

**Comment by ShadowDeath6** [comment]
Change it to "thermals nerf"

**Comment by Kmc2000** [comment]
We could be lazy and copypaste the drone code and i could reskin it into thermal blobs

And please have that toggleable, so it's dual mesons and thermals

**Comment by ShadowDeath6** [comment]
Stop nerfing shit because 'muh realism', nobody is going to buy thermals anymore if they don't get to actually know who's walking around.

**Comment by Cruix** [comment]
I'm not nerfing it because 'muh realism' I'm nerfing it because I want it to look cool. If it hurts too much, I can just add back the SEE_MOBS flag and it will be a tiny buff, since there will be a small number of things you will now be able to see through walls that you couldn't before.

**Comment by ShadowDeath6** [comment]
I'm speaking from experience here, but thermals are intended to give a strategic advantage by seeing people, like sec, through walls and preparing for them. Not only that, but antags like shadowlings probably wouldn't care about space heaters and care more about knowing the person they're going to ambush so they don't run into a scientist who's holding 6 laser cannons. This update would remove the ability to tell who's near, outside of some differently shaped blobs depending on armor which anybody can get.

**Comment by Kmc2000** [comment]
Solution: Thermal goggles

Night vision goggles sprite, cheaper than the normal thermals has cruix's thermal idea, muh realism achieved

**Comment by FluffySurvivor** [comment]
This is a huge nerf. 
no.
