### ISSUE TITLE
Ripley mining shuttle bug

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#438]
So, when you are in the mining shuttle and its underway, and you attempt to enter it, and the shuttle arrives before you finish, you cannot move unless respawned. I tried everything.
### Steps to reproduce the problem
1. Send mining shuttle
2. Enter and make it move
3. Enter a RIPLEY just before you arrive
4. Never ever move again. ((You are kicked out of the mech))

**Comment by Groudonmaster** [comment]
Probably due to the character being unable to enter the mech at the defined
location at the time.  If it's canceled beforehand it could probably cause
you to just freeze. Can this be recreated on the Eshuttle maybe?

**Comment by Time-Green** [comment]
Probably can. I think it works with everything that does the movement and smackdown thing.

**Comment by Groudonmaster** [comment]
Issue could also be the game is attempting to recognize you as inside a mech but you aren't so it isn't giving you the eject command so basically you're inside but not inside a mech at that time.

**Comment by ShadowDeath6** [comment]
Were you entering the mech from a chair? How did you enter it without being stunned from the shuttle moving? If you get stunned it should stop you from entering.

**Comment by Time-Green** [comment]
I got it from a ticket.

He told me he was entering the ripley while the shuttle moved, and when it stopped he was frozen.

I had to respawn him
