### ISSUE TITLE
More character creation slots (from 3 to x)

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#44]
opened by Xantam · about a month ago
Nature:
More character creation slots (from 3 to x)
Thread linked:
http://forums.yogstation.net/index.php?threads/other-crazy_drakkon.7679/
Base content:
What is your idea type?:
Other

Give us a short description of your idea?:
Character Slots

Give us a full description of your idea?:
Pretty self explanatory. May sound kinda useless to some, but some may simply like more character loadouts than the three available.

**Comment by AsV9** [comment]
This is part of what you get with BYOND on donating. I'm confused. Shouldn't we already have this for our donators?

**Comment by Xantam-13** [comment]
I think the idea was that donors want maybe 5 slots?

**Comment by X-TheDark** [comment]
Done.
