### ISSUE TITLE
New Modules

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#443]
1. Add forensic scanner as a module to secborg. Additional ideas can be posted as comments.

**Comment by PineappleWolf** [comment]
Sure, literally a line of code. Not a big deal.

**Comment by PineappleWolf** [comment]
will do it in mornin'

**Comment by Alek2ander** [comment]
:-1: This will make the detective super-useless, because why call him when you can get a supermachine to scan stuff instead

**Comment by ShadowDeath6** [comment]
Fuck no, secborgs already fuck antags up 24/7. Giving them a scanner is stupid and lets them shit all over you even more. :-1:

**Comment by FluffySurvivor** [comment]
This may be a thing ONLY if the secborgs combat abilities are reduced

**Comment by DavidEdwards** [comment]
Its a nice idea, but as Alek says, it completely screws over the Detective. It is their only real job, to detect, and if borgs can do it...
