### ISSUE TITLE
Xeno Firing Pin

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#445]
Just a firing pin that is as easy to get as a test range firing pin.

It only works on the mining asteroid and in Xenobiology

**Comment by ShadowDeath6** [comment]
Lasers do jack shit to miner mobs, and xenobio doesn't need guns.

**Comment by Time-Green** [comment]
I got the idea after the temperature pull was made.

It would be usefull in that way

**Comment by oisin100** [comment]
Sounds useful...

Inb4 CE changes every area to Xenobio

**Comment by Cruix** [comment]
> Inb4 CE changes every area to Xenobio

That's not how it works, you have to use the CE's blueprints. Already works with test range pins, I believe.

**Comment by ShadowDeath6** [comment]
Temperature gun pull made it so that they start with standard pins iirc

Edit: New temp gun update indeed does not require firing pins anymore

**Comment by ToGWtF** [comment]
No it does make it spawn with a standard pin installed. The default is to have a pin, adding pin = NULL removes it spawning with a pin

**Comment by ToGWtF** [comment]
@cruix 
Looks like theres a physical machine in test range (The thing that makes the targets move around) that the Test-pin has to be in range of to work

Could we just throw one with no controllers into xenobio and just increase the range of a little?

Edit: Or set it to be within "x" range of an different item in xenobio? If we make a xenpin that only Temp-guns spawn with, we have golems with SMG's with test range pins shooting anyone who comes inside

**Comment by ghost** [comment]
CE can just change areas to 'test range' anyway and all guns fire there, which is hilariously OP

**Comment by Greatbigben** [comment]
merged and closing
