### ISSUE TITLE
Walls on Walls

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#446]
You can place walls on wall girders with an RCD

Walls on Walls
<3

**Comment by GrayRachnid** [comment]
Feature
You can also place metal on girders, that sounds like a bug too.

**Comment by ShadowDeath6** [comment]
You can also make airlock walls for a similar reason, I believe. 
New meta is doublewalling the AI during malf

**Comment by oisin100** [comment]
> You can also place metal on girders, that sounds like a bug too.

Not a bug.

> You can place walls on wall girders with an RCD

Pliz dont patch... It sounds fun...

**Comment by Time-Green** [comment]
The thing was

Gray used that to fuck up a Hijack

Ok, so it is not a bug

**Comment by ShadowDeath6** [comment]
> metal on girders

That sounds like a bug, you shouldn't be able to do that.

:^)

**Comment by oisin100** [comment]
> Ok, so it is not a bug

Mhm, The Atmos containment has metal rods on reinforced walls.

**Comment by ghost** [comment]
It is a bug.

You are not able to use an RCD on a girder to create more walls, or should not be.

Patch this.

**Comment by GrayRachnid** [comment]
feature
been so for 3 years

**Comment by AsV9** [comment]
> Gray used that to fuck up a Hijack

okay so that's why he's calling it a feature, sounds like the gray I know

**Comment by GrayRachnid** [comment]
asv, this has been a thing for 3 years.

You don't even need an RCD to do it, it can be done without it.

And besides, the core issue is that you can put up a new wall before someone is able to take it down whether with metal or with an RCD.

**Comment by ShadowDeath6** [comment]
Just because it wasn't fixed doesn't make it a feature. 

It is funny, though.

**Comment by GrayRachnid** [comment]
This is literally the first time I see someone who calls it a bug.

It was never addressed as a bug in the past and now that a few people complain it's suddenly a bug.

**Comment by GrayRachnid** [comment]
http://i.imgur.com/V6bX9zf.png

**Comment by AsV9** [comment]
that's not intended behavior. if nobody reported it nobody is going to miss it being patched. the game doesn't revolve about which bugs you want to fix or not.

**Comment by GrayRachnid** [comment]
In your eyes maybe, but I don't see anybody from all the other servers complaining.

Nobody has removed this, if you want to call it a bug and remove it then feel free. Keep in mind that's shitty removing something which can be used creatively tho, unlike the stagnant rounds we keep getting now.
