### ISSUE TITLE
Make core upgrade great again (>implying it ever was)

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#447]
Buffs the malf ability core upgrade from being welder immunity to increasing its max health by 2x, great for when you get 3 lasergun clips dumped into you, but this time you don't die!

I guess it would increase its system integrity to 200% instead of 100%

**Comment by ghost** [comment]
Or just decrease vulnerability to fire by a shitload.

Tbh, the best thing you could do for core upgrade would just be to make AI's vulnerable to heat and plasma. And then core upgrade is worth something.

Hell, maybe core upgrade could offer a 50% resistance to EMP's-10 damage instead of 20-and immunity to being stunned by activating your core flasher, and decrease damage done by welders and lasers by 75% and brute by 25%.

**Comment by ShadowDeath6** [comment]
Or just increase max health to 200% since adding a bunch of resistances to things it's already immune to, like its wall flasher or plasma fire, is a nerf.

**Comment by Time-Green** [comment]
Excuse me but

AI core is completly fire proof.

The upgrade only prevents welders.
Burning plasma never harmed an AI

**Comment by ShadowDeath6** [comment]
Core upgrade is just newbie bait, it should actually be useful for something.

**Comment by AsV9** [comment]
Could we just not make the core completely laser proof with the upgrade, forcing the crew do go in and do brute damage? That could work.

**Comment by ShadowDeath6** [comment]
What are you asking, asv? That we DO make it laserproof or don't?
We would need to change the ways lasers affect silicons since currently they do brute damage to them.

**Comment by AsV9** [comment]
> That we DO make it laserproof

**Comment by ShadowDeath6** [comment]
We would need to change the way that the AI core damage systems work, but Asv's idea sounds interesting. Not sure it'd change much, though, since people usually make walls or put down vendors and then hit the AI with fireaxes.

**Comment by AsV9** [comment]
I've seen people stand in the upload doors and empty their lasers into the core before. So yeah.
