### ISSUE TITLE
Make headslug bursting make the slug monkey a changeling (Xenobio)

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#448]
### Expected Behaviour

Monkey created from headslugs via xenobio gets changeling antag status and powers. 
### Actual Behaviour

Monkey bursts from corpse but has no antag status, and by extension, no powers. 
### Steps to reproduce the problem
1. Spawn headsluggo from gold slime extract. 
2. Use sentience potion on headsluggo. 
3. Headslug implants an egg in a human corpse. 
4. Monkey pops out like 5 minutes later
5. Monkey is sentient and can be turned human via genetics
6. Monkey has no powers. 
7. Bitch in deadchat about not having infinite ling army. 

The reason for this is that headslugs aren't inherently changeling antags, and since lings get their powers from their antag status, they don't get powers.

Possible fix- force antag status onto people who become the headslug mob.

**Comment by oisin100** [comment]
Headcrabs no longer exist in the latest updates.

**Comment by oisin100** [comment]
Easy fix. Headcrabs have a separate mind holder for the actual ling mind `var/datum/mind/origin`

**Comment by Time-Green** [comment]
I am not a fan of making antags.

I AM a fan of making lingcurity

**Comment by FluffySurvivor** [comment]
LING FACTORY? 
GIMME

**Comment by ghost** [comment]
/tg/ has this and it's not unbalanced.

Interestingly, the changeling still has to obey their master there and basically it's just a ling forced to serve you.

It's quite fun and it doesn't make an antagonist per se, just grants the powers. Without objs they can't do anything their master doesn't want them to.

**Comment by ToGWtF** [comment]
@oisin100 
teach meeee

**Comment by ShadowDeath6** [comment]
PR when

**Comment by oisin100** [comment]
Ill do it then...

**Comment by oisin100** [comment]
Fixed in #550
