### ISSUE TITLE
Antag token system

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#45]
opened by Xantam · about a month ago
Nature:
Antag token system
Thread linked:
http://forums.yogstation.net/index.php?threads/other-albatros95.7619/
Base content:
((Xantam: let's keep it to one token a month, consider the amount of antags..))
What is your idea type?:
Other

Give us a short description of your idea?:
Antag token.

Give us a full description of your idea?:
1 Antag token. Can only be used once and only on a certain day of the week (e.g. Tuesday is Antag Donor Day - as in all donors can use antag tokens ONLY on Tuesday (or whatever day it's picked)). You only receive it if you donate 20$ or more.

**Comment by Hydre** [comment]
WHAT

NO

When the fuck did this even get considered?
I specifically remember us never even thinking about taking money for in game benefits ESPECIALLY antag tokens.

**Comment by DavidEdwards** [comment]
I don't know why this is such a big deal. 1 per month really isn't much.

**Comment by Hydre** [comment]
Because it defeats the entire purpose of RNG, and is unfair for other players which may make them want to leave.

**Comment by DavidEdwards** [comment]
Antag Token system is built in. However, not for donation. It is built so admins can track who has tokens easier.
