### ISSUE TITLE
Admin antag HUD doesn't work with gangs

### ISSUE THREAD

**Issue by Alek2ander** [yogstation13/yogstation-classic#450]
### Expected Behaviour

Admin antag HUD shows different colored icons for different gangs, and can distinguish bosses and normal gangsters
### Actual Behaviour

All gangsters show the same [?] unknown antag icon

**Comment by oisin100** [comment]
The issue is fixed in the next server update.

**Comment by Greatbigben** [comment]
This has been merged?

**Comment by oisin100** [comment]
It was.
