### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by Wardog390** [yogstation13/yogstation-classic#451]
a while back ephmeralis nerfed patches healing per tick or something along those lines so if that could get fixed so they are back to normal that would be awesome.
can this be an urgent push please?

**Comment by ShadowDeath6** [comment]
> wanting burn and brute patches to fullheal again

What a madman

**Comment by ghost** [comment]
This is already done and patches are reverted to normal.

By the way, patches always healed per tick, it's the stypic powder in them that heals per tick.

This can be closed.
