### ISSUE TITLE
Medborg = Clownborg

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#454]
### Expected Behaviour

Selecting Medical Cyborg module grants Medical Cyborg items.
### Actual Behaviour

I become a filthy clown.
### Steps to reproduce the problem
1. Get borged
2. Select medborg
3. Cry

**Comment by ParagonPrime** [comment]
Actually, this is slightly incorrect-

It DOES make you medborg, but then a selection of sprites appear- all for clownborg. Selection of any of the sprites causes you to become clownborg.

**Comment by ShadowDeath6** [comment]
I thought you were making a suggestion to replace medborg with clownborg and I was contemplating utilizing a variety of curses in this report. 

Does this actually make you mediborg but gives you a dropdown of clownborg skins, or do you not get any equipment? If it's the former, you can just relog and it should let you be medborg.  (SHOULD)

Priority critical please help

**Comment by ParagonPrime** [comment]
Former.

Yes, but... it still shouldn't be happening, right?

**Comment by PineappleWolf** [comment]
I fixed this.

**Comment by PineappleWolf** [comment]
Unless Gerogi didn't do the hotfix, it was patched and fixed in..https://github.com/yogstation13/yogstation/pull/455

**Comment by george99g** [comment]
See above
