### ISSUE TITLE
Borer permanently swaps minds with host

### ISSUE THREAD

**Issue by Alek2ander** [yogstation13/yogstation-classic#457]
Happened when I tried to Release host and Assume control kicked in during the release host delay. Can probably happen in other circumstances

**Comment by Time-Green** [comment]
Confirmed with Asv9

Also, when the host is swapped into the borer. He cannot move and is forced into RNG movement

**Comment by oisin100** [comment]
Should be fixed or atleast partially fixed. Re-open if you find more issues like this one.
