### ISSUE TITLE
Borer chemical bug

### ISSUE THREAD

**Issue by AsV9** [yogstation13/yogstation-classic#458]
### Expected Behaviour

Clicking cancel on the chemical secretion should.. well.. make nothing happen.
### Actual Behaviour

A message shows up saying "You squirt a measure of  from your reservoirs into 's bloodstream."
Also I'm not sure but does it also drain chemicals? I can't tell.
### Steps to reproduce the problem
1. Become borer.
2. Enter host and click secrete chemicals in borer tab.
3. Click cancel.

**Comment by ShadowDeath6** [comment]
It does drain chemicals.

**Comment by AsV9** [comment]
Nice to know.
