### ISSUE TITLE
Shadow's borer issue #2: Healing Chemicals have way too high a cost

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#459]
Healing chemicals cost way too much to ever be useful, plants can heal faster. (recommend 35 chemicals for healing chems)

**Comment by oisin100** [comment]
How about i bring the healing chem price down to 40 Chems(6 Uses from max). Increasing the dosage of each use will just provoke confusion.

**Comment by Stealthkibbler** [comment]
Add in a bigger variety of chems like calomel and omnizine but give them the higher costs, bicard and kelo can barely stabilize someone who is taking oxy damage.

**Comment by oisin100** [comment]
Borers have perfluorodecalin To cure oxy damage.

**Comment by oisin100** [comment]
> Add in a bigger variety of chems like calomel and omnizine but give them the higher costs, bicard and kelo can barely stabilize someone who is taking oxy damage.

Stahp hijacking! If you still think this is needed please open another issue!
