### ISSUE TITLE
Characters respawn when dead or observe as simple animals

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#46]
opened by Xantam · about a month ago
Nature:
Dead or observers can respawn as simple animals with 0 attack power.
Thread linked:
http://forums.yogstation.net/index.php?threads/other-xantam.7598/
Base content:
What is your idea type?:
Other

Give us a short description of your idea?:
Dead players re-spawning as creatures with chosen names

Give us a full description of your idea?: When you die, it's boring being dead.
Donors get the ability to respawn as a friendly creature. A friendly carp (perhaps as a different colour to stop mixing up), crab, cat, etc etc.
By doing so, you forfeit the right to have your body cloned.
Perhaps from this we can add other creatures into the game too.

**Comment by Groudonmaster** [comment]
The issue I see with this mainly is that people kill simple mobs anyways because we don't have it specifically in the rules that they can't. R.I.P. Muh valids
