### ISSUE TITLE
Cortical Borer - Influence Bug

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#461]
### Expected Behaviour

The ally message the borer and host get when influence reaches 100% to only appear once.
### Actual Behaviour

It appeared repeatedly after each given time.
### Steps to reproduce the problem
1. Infect a host.
2. Stay in host for awhile
3. Get a message like "You are one with _________ you both aid eachother in their needs and establish a mutally beneficial relationship." while you are at 100% influence.
4. It repeatedly displays that same message  after a certain amount of time.

**Comment by Time-Green** [comment]
If you assume controle, you will get the message You feel Secondary Borer (256)'s power grow to extreme levels. You beging to feel unbeatable.

As a bloody borer.

**Comment by oisin100** [comment]
This is probably caused by the borer using chems what decrease its influence. The message will get show every time your influence increases to 100.

**Comment by ShadowDeath6** [comment]
Never happened to me, but I didn't use chems that decreased influence.

**Comment by Super3222** [comment]
> This is probably caused by the borer using chems what decrease its influence.

Now that I look at it, it might have been caused by that. My host enjoyed the high I was giving him when I was squirting space drugs into his system.
