### ISSUE TITLE
Cult cannot sacrifice the dead

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#462]
### Expected Behaviour

You sacrifice a dead guy with one cultist and he gets sacrificed
### Actual Behaviour

He does not get sacrificed
### Steps to reproduce the problem
1. Get warden
2. Kill warden
3. Sacrifice him alone and realise you cant, then cry

I am sure you could sacrifice those with implants, and the warden was not their target

**Comment by ToGWtF** [comment]
It wont sacrifice him until a dead person clicks yes to become a shade. 

That's why if Shitlord A gets killed then sacrificed but Dickwolf B presses yes to be a shade as well,  Dickwolf B will spawn in as "Shade of Shitlord A"

**Comment by Time-Green** [comment]
Holy fuck.
I realise how many cult rounds I fucked up by not clicking the yes button then

**Comment by ghost** [comment]
Not a bugerrino.

**Comment by oisin100** [comment]
It might not be a bug. But its still a big issue.
