### ISSUE TITLE
Forensic scanner on used bandages 

### ISSUE THREAD

**Issue by Nirnael** [yogstation13/yogstation-classic#466]
### Expected Behaviour

Get DNA or fingerprints from used Nt emergency bandages
### Actual Behaviour

The forensic scanner is analyzing perpetually and doesnt allow you to get logs or scan anything else while in that state which makes the detectives job impossible if you mange to bug out both of your scanners.
### Steps to reproduce the problem
1. Scan nt issue bandage with forensic scanner
2. Wait however long you want
3. Try to scan anything

**Comment by oisin100** [comment]
Fixed in #504
