### ISSUE TITLE
Borer cancel

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#472]
### Expected Behaviour

When you ask to release the host, you expect to be able to cancel the process.
### Actual Behaviour

You click and release you didn't mean to. There is no way to cancel.

**Comment by oisin100** [comment]
GIT GUD!

Ill add a prompt.

**Comment by DavidEdwards** [comment]
What if you click and you did mean to, then decided you didnt actually want to?

Would a do_after function call work on a borer? Worth trying I think.

**Comment by oisin100** [comment]
> Ill add a prompt.

**Comment by oisin100** [comment]
Fixed in #476
