### ISSUE TITLE
Make duct tape shut people up

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation-classic#474]
Add a function to duct tape where, if you aim for the person's mouth, you attempt to tape their mouth shut, preventing them from speaking. It would take two seconds to tape them up, and the person can remove it from their mask slot instantly. This should not work on people wearing masks. If they are smoking, make em drop that cigarette.

**Comment by Time-Green** [comment]
Pretty good idea.
I have no idea how this will work out.

But we can finnaly kidnap people legitimately if this goes through

**Comment by ShadowDeath6** [comment]
Duct tape handcuffs when

**Comment by AsV9** [comment]
@Ephemeralis reverting ghetto armory at #482 makes duct tape not exist tho so just keep that in mind.
