### ISSUE TITLE
Add Shadowling thrall requirement scaling

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#477]
Shadowlings are so ungodly easy right now, especially with new shadow-walk. Drag through wall, cuff, win. 

Please increase thrall requirement for higher population, because shadowlings now will never ever lose because there are 15 civilian roles running around that nobody cares about and then shadowlings ascend and everyone says "Wait, shadowlings?"

Maybe like 5 thralls per shadowling so we have 20 thralls for 4 shadowlings and the regular 15 for 3, because this is just getting ridiculous.

**Comment by ghost** [comment]
8 shadowlings

40 thralls

gg

**Comment by ShadowDeath6** [comment]
when will we ever have 8 shadowlings

**Comment by Ephemeralis** [comment]
Surprise surprise, darkwalking is bullshit OP.
