### ISSUE TITLE
Borer suicide

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#481]
### Expected Behaviour

Nothing
### Actual Behaviour

Borer kills your body for the lulz
### Steps to reproduce the problem
1. Kill bekons
2. Bekons become borer
3. Bekons infects and makes you suicide

Like really, there should be a rule against this.
Bekons failed because my previous borer had me cuff  myself to prevent it.
But this is not fun at all

**Comment by oisin100** [comment]
> 2.1.1: Do not murderbone. Do not kill random people for no reason. 

Borers murdering people is against their goals. Their goals are to infect and reproduce. Killing people means less people to infect and thus less reproduction. The only reason a borer could possibly have to kill someone is in self-defense or in defense of other borers(EG, Host is actively hunting borers)

**Comment by Time-Green** [comment]
Oh, So next time I can just ahelp it if bekons is metagrudging and fucking with me like that?

**Comment by oisin100** [comment]
> Oh, So next time I can just ahelp it if bekons is metagrudging and fucking with me like that?

Yup.

**Comment by ghost** [comment]
Metagrudging at all is bannable outright.

You should probs make a player complaint, Tim.

Anyway.

Borers CAN kill their host if it's disobedient. That's sort of the whole thing of ODing people on bicard and drugs, ect.

What a borer can do to punish a disobedient host instead of toolboxing them to death under mind control is just immediately suicide.

**Comment by ShadowDeath6** [comment]
Will jumpstarting the host revive them from suicide?

**Comment by oisin100** [comment]
> Will jumpstarting the host revive them from suicide?

Yes

**Comment by Time-Green** [comment]
I was not surr about it, cuz the other admins all reacted with things like rip

**Comment by Super3222** [comment]
> I was not surr about it, cuz the other admins all reacted with things like rip

Classic Yogmins.

**Comment by ShadowDeath6** [comment]
More of a player issue IMO

Rip in mindworms

**Comment by Ephemeralis** [comment]
Suicide is partly OOC and shouldn't be possible. ODing host on drugs is different as it's an IC death. This needs to be fixed.

**Comment by oisin100** [comment]
Has been patched already.
