### ISSUE TITLE
Remove ghetto armory.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#482]
It's terribly thought out.

The sprites are godawful.

It's horribly unbalanced-We didn't need craftable armor at ALL, and craftable armor existing at all is absolutely fucking horrid.

You even added duct tape as an explicit item that ONLY serves the purpose of making ghetto weapons. What the hell?

It's horribly unbalanced, craftable armor is shit, the idea is childish, and let's not forget most of the items are easier to make and outright better than spears.

Swords that fucking have a random chance to embed glass. EMBED GLASS.

Do you know what embedding does? It causes insane bleeding and brute every time the person so much as scratches their asshole until it falls out, or they can rip it out and take a shitload of damage anyway. It's more powerful than the stunprod.

And yes, the sprites are legitimately a piece of glass stretched really long. 

And before you say 'no, wait, we can fix it lol' we don't need it. We already have a variety of craftable weapons, we don't need to add more stuff for some random greytider to go validhunting with.

We have a lot more shit to work on than some ridiculous childish suggestion for glass swords. They're outright better than the spear or fireaxe, craftable armor fucks the whole concept of balance-Seriously, the trenchcoat provides armor to EVERY PART OF THE BODY  

I'm not sure who gave this the OK in the first place but it's the least thought out shit since adding sleepsting to lings. Comment it out.

**Comment by ShadowDeath6** [comment]
I though the armor values were like the same as a sec jumpsuit.

**Comment by shrimptk** [comment]
Please remove it for further testing and improvements until it is _actually_ ready for public use.

**Comment by Yackitori** [comment]
But keep duct tape plz.

**Comment by shrimptk** [comment]
Resprite it first, and give it alternative uses, like making makeshift gags, or taping papers to the wall.

**Comment by ToGWtF** [comment]
sticky notes when

**Comment by ghost** [comment]
Armor values being equal to sec jumpsuit is still too strong.

**Comment by oisin100** [comment]
Coat has 9% brute resistance and Jumpsuit has 5%

**Comment by ParagonPrime** [comment]
Agreed here.

However.

There SHOULD be a one-handed ghetto weapon for use with riot shields. Such as, for instance, buffing onehanded spear damage a lil'.
Because riot shields are awesome as shit and there's nothing as badass as playing rev legionary with a spear... until you remember that spears are useless unless doublewielded/thrown.

**Comment by ghost** [comment]
> Coat has 9% brute resistance and Jumpsuit has 5%

TOO HIGH

WAY TOO FREAKING HIGH

**Comment by oisin100** [comment]
> TOO HIGH
> 
> WAY TOO FREAKING HIGH

You asked for these values...

**Comment by ghost** [comment]
i asked for 4%

**Comment by oisin100** [comment]
http://prntscr.com/acj0ht

**Comment by ShadowDeath6** [comment]
> gets what he asked for
> whines about what he asked for being too op

Ebin, Adam? 
Honestly I've only seen one person use them ever and I doubt I would use them since leather overcoats look cool as shit and are super rare unless you break into botany.

**Comment by ghost** [comment]
go ebin yourself

i was probably drunk when i suggested that

leather overcoat should provide 4 or 3 for it's ease of accessibility

**Comment by Kmc2000** [comment]
I can make better glass sword sprites if you want but the whole point of them is that they look shit

You're ductaping glass to metal, and with the black sword, dying it black

What the hell do you expect? you want good looking, aim for The refined sword

**Comment by ShadowDeath6** [comment]
Buff leather overcoat when

**Comment by Ephemeralis** [comment]
I'm going to fully revert these commits in a few days unless good reasoning is given as to why they should remain.

5/9 melee resist made craftable is the pinnacle of balance insanity coupled with the fact we have craftable health restoration already.

The sword splitting into glass fragments hurts my brain. I don't think people realize how powerful a mechanic embedding is and how much bleeding it inflicts over time. Plenty of "ghetto" weapons exist already and most of them are in a goddamn toolbox. Spears are already insanely good and have an even better embed, why do we need more?

If you want to make a base level armor class item accessible, add some very slight defense stat to the bulkier clothing items - maybe 2 to the overcoats as a whole, and 1 to leather/bomber jackets or something. 5 pretty much forces an extra hit to kill someone with most items and 9 is at least two extra hits, probably three after flooring.

**Comment by darkwahn** [comment]
Sword is probably the best addition to the game that's ever happened.

**Comment by Greatbigben** [comment]
this is still in game

**Comment by darkwahn** [comment]
As it should be.

Duct tape assistant is best.

**Comment by Super3222** [comment]
I'm surprised that this is still in game.
