### ISSUE TITLE
Doors smashing you to death.

### ISSUE THREAD

**Issue by Nirnael** [yogstation13/yogstation-classic#484]
### Expected Behaviour

Doors should not close while youre inside them
### Actual Behaviour

I got blocked by a mule bot exiting a maintenance door and wanted to click on the crate to see what it was carrying because it was sketchy and i was a detective but the door closed on me before i had a chance to go back so i fell on the ground then the door smashed me and i tried to get up when it opened but i couldnt because ss13 am i right? So it kept closing and opening without me having any chance to stand up which killed me.
### Steps to reproduce the problem
1. already explained

**Comment by Nirnael** [comment]
Never mind I guess the lamest way to die is intended

**Comment by oisin100** [comment]
Kek, They dont smash you unless they are hacked. Its intended.
