### ISSUE TITLE
Minebot pull icon overlaps with exosuit storage

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#486]
http://imgur.com/8q5QkAV

Can I also add that their hardsuit helm looks jarring on them, and really needs to be either resprited or made invisible?

**Comment by ShadowDeath6** [comment]
The helmet is an engi helmet, not a miner helmet.

**Comment by ghost** [comment]
I noticed this when I played. I'm fixing it now, but positioning things on the screen is complicated.
