### ISSUE TITLE
Hulk nerf

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#491]
Make punches stun for less. It's the same as stunbaton IIRC, just make it the same stun as tabling so the hulk can still spam kicking into crit but it can't do it with like 5 people.

**Comment by Super3222** [comment]
This'd be an easy nerf to make, but is it really necessary? Hulk was made harder to mutate awhile ago. Why are so many nerfs necessary? 

Hulks are suppose to be feared, if anything that's not a mech, isn't another hulk, or doesn't have a flash gets close enough to one of these rampaging they should get their punishment.

Also on the statistical side, tabling someone weakens for 2 and hulk punches currently weaken for 4. Stunbaton weakens and stuns for 7. Stunprod for 5.

**Comment by ShadowDeath6** [comment]
Because it's op and it cucks literally every single antagonist other than people who use knockout chems or ranged things.  Cult, oh, too bad your stuns don't work and your group is permanently stunned and kicked for 15 damage each. Shadowlings cannot do anything at all to them and can't even get away from them once the hulk is near. No genetic power is near as strong as this and it's ridiculously hard to counter bar lethal ranged weapons which a lot of people don't have access to. Reducing stuntimes at least lets people get away from stunbaton mcfist.

**Comment by ghost** [comment]
/tg/ nerfed hulk punch to not do any stun.

Which was good. You're already stun resistant, do shitloads of damage, and can smash through walls. You don't need stunbaton fists to go with it.

**Comment by ShadowDeath6** [comment]
I don't want to completely remove the effectiveness of hulk, it should still disarm to some extent. Making the stun lower should in theory fix that problem.

**Comment by ToGWtF** [comment]
I'm staying neutral on this

**Comment by Super3222** [comment]
To my knowledge /tg/ nerfed hulks punches to where instead of 5 brute damage, it did 15. (and removed stun like Adam said)

We could port that or nerf the rate it weakens people.

**Comment by FluffySurvivor** [comment]
Nerfing the stun duration will do nothing in a straight 1v1. Even with 2 secs of stun, you are still stunlocked by the punchstorm.

**Comment by DavidEdwards** [comment]
Done https://github.com/yogstation13/yogstation/pull/500
