### ISSUE TITLE
Remove Double Agents holy fuck

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#493]
### Expected Behaviour

Get a good antag role.
### Actual Behaviour

Get Double Agent.
### Steps to reproduce the problem
1. Ready up at roundstart
2. Start the round.
3. "You are the double agent!"

Remove DA please it's not fun and a lot of people can agree with me, just replace it with more traitors instead.

**Comment by ToGWtF** [comment]
Or pepper in the random "Protect X other agent at all costs" so at least you can be know that ONE person isn't going to try to kill you. DA is fucking nuts without a team-mate,  people running around killing other syndies just to loot their gear.

Maybe it will help stop the random medbay/hallway minibombing that people do as a last resort that does more damage to bystanders than their target

**Comment by ShadowDeath6** [comment]
Changing objectives would work fine, but every single DA round I see turns into a massive clusterfuck of syndie items since there are so many antags.

**Comment by ParagonPrime** [comment]
The chief problem with DA is that it raises the paranoia to an incredible level.

As in,

> be scientist
> try to get into genetics to upgrade the fucking machines
> ultraparanoid geneticist assumes i'm the DA hunting him and kills me

varying DA a tiny bit would indeed be great- have some agents have objectives to PROTECT another agent

**Comment by Super3222** [comment]
I remember a while back, a former Yog coder was going to make DA into a separate preference.

How about we pick up on that?

@ParagonPrime, and yes DA gives you some extreme paranoia. Almost as much paranoia I get whenever I'm playing HoS, and that's not good.

**Comment by ShadowDeath6** [comment]
DA preference would work perfectly.

**Comment by Stealthkibbler** [comment]
https://forums.yogstation.net/index.php?threads/double-agent-needs-a-different-preference-than-traitor.3438/

pls

**Comment by ghost** [comment]
Will force a guy to do this.

**Comment by Ephemeralis** [comment]
No.

**Comment by Stealthkibbler** [comment]
> No.
> @Ephemeralis 
> So there will be no preference? Why?
