### ISSUE TITLE
Borer Evolution Menu

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#494]
So i was thinking of some changes to Borers.

I thought about adding some sort of evolution menu with different trait trees.
Some example of these could be a Lethality tree(Allows the evolution of more lethal chems), Healing tree(Allows the evolution of more medical chems) And infectivity tree(Greater infectivity and some stat buff evolutions)

Each tree would have special end evolutions for example the Lethality tree could have last whisper as a end goal chem. Healing could unlock the ability to bring your host back from the dead. And infectivity would eventually allow the infection of different mobs(Such as sillicons)

The way it would work would be like any tech tree. You unlock the earlier things before you can unlock the later things. Unlocking evolutions would require you to drop a large ammount of chemicals in.

The tech tree would be shared by all borers but the prices for each tech would increase with the amount of borers alive. 10 Borers might take 2000 Chemicals to unlock a evolution.

Borers tech trees would be linked to their objectives. Eg one objective might be to infect the AI if so then the borers should evolve down the Infectivity tree

**Comment by Time-Green** [comment]
Interesting

**Comment by ShadowDeath6** [comment]
> infecting silicons
> infect AI
> ASSUME DIRECT CONTROL

Sounds cool.

**Comment by ghost** [comment]
no

they're good as is

making them powerful enough to infect silicons is shit and doesn't even make sense because borers are brain mobs

please don't, this is dumb

**Comment by ShadowDeath6** [comment]
Add infecting silicons, they're technically brains in metal shells

**Comment by Stealthkibbler** [comment]
Stat progression would be nice, the longer the borer stays alive the more it is rewarded with. The resource used for mutations/upgrades should just be the time the borer has spent alive. I think controlling silicons is too strong, the AI will just detonate the borg if it has a borer in it or lock it down until removed.

Lethality sounds nice but it derives from the purpose of the borer, which is to keep its host alive and survive, now the ability to unlock additional healing chems would be nice with the unlocks giving good descriptions of said chemical. The other tree just sounds like a passive buff tree on chem production etc.

As many people have said, they dont want borers the ability to outright kill their host using their chems. So do not make a lethality tree that encourages this.

**Comment by oisin100** [comment]
Alright, Well maybe ill make a stat tech tree. Earlier techs in the tree give the borers some buffs towards chem production, chem storage and stuff then as you get further into the tree you start to unlock features for your host for example Night vision or Nutrition generation...

**Comment by Stealthkibbler** [comment]
That is pretty much spot on, not only the ability for the borer to upgrade itself but the ability for it to reward its host through genetic upgrades provided the Borer has managed to survive so long.
