### ISSUE TITLE
Cortical borers who get their host zombified get kicked out

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#497]
...And roam about as a ghost. I'm not sure what happens to the orignal player who got infected as the one I was in was AFK (not logged out). I'm not sure what happened to the borer body itself but I'm guessing it has something to do with the zombfication code not overlapping well with the borers.

I'm assuming this isn't intended behaviour, as borers shouldn't actually die when their host dies, at least not without some sort of feedback

**Comment by oisin100** [comment]
Should be fixed in latest borer updates!
