### ISSUE TITLE
Medical Cyro

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#50]
opened by Ben · 13 days ago
What is the nature of the issue:Bleeding doesnt get removed when someone is dumped into the cryo tube
What steps must be taken to reproduce this error:
Get bleeding damage
Jump in cryo
not get healed
Any additional information? :

**Comment by Super3222** [comment]
For some reason I can't recreate this bug. Cyro cells seem to be working functionally.

How exactly did this happen? @george99g @BadminBen

**Comment by X-TheDark** [comment]
Not relevant anymore, Cryo fixes brute damage, which fixes bleeding. Closing.
