### ISSUE TITLE
Syndie Station Lighting In Regards to Phytosians

### ISSUE THREAD

**Issue by LesVegetables** [yogstation13/yogstation-classic#502]
### Expected Behaviour

The syndie station is lit up completely along with the shuttle and cabbages shouldn't take damage over time
### Actual Behaviour

You die a slow and painful death as a cabbage operative without your spacesuit in hard-suit mode on  both the station and the shuttle (this also doesn't always work it seems to be 50/50)
### Steps to reproduce the problem
1. Spawn as cabbage op
2. Die slowly and painful
3. Get admin healed without blowing up (hopefully)

**Comment by ShadowDeath6** [comment]
Make all ops start as humans, problem solved. :^)

**Comment by Super3222** [comment]
Phytosians are technically a nanotrasen project... furthermore, why would they be specialized into nuclear operatives when they can't even properly hide in he dark.

**Comment by ShadowDeath6** [comment]
SHADOWPEOPLE FOR NUKE OPS 2016

**Comment by Time-Green** [comment]
I would like to inform this also occurs on escape and arrival shuttle.
And probably more places with simulair lightning.

The deal its ussually not that bad on arrivals is, because you leave that quick.
And escape is flooded with light wielding people.

Elsewise, escape shuttle would kill you

**Comment by Ephemeralis** [comment]
This should not happen, and was supposed to be fixed by one of Taco's commits months ago. I'll look into it.
