### ISSUE TITLE
Hat-throwing (suggestion)

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#503]
If you were able to throw hats onto people's heads by aiming for their head and throwing, many keks would be had. Throwing a hat onto someone's head wouldn't push a hat they were alread wearing off of their head, it would only work on bare heads. Also, no helmets or anything that doesn't just go ontop of your head. This kind of thing would be a nice, non-harmful prank for the clown.

/shitpost

**Comment by FluffySurvivor** [comment]
:+1:

**Comment by DavidEdwards** [comment]
I really like this :> @yogstation13/initiate-coders Who wants it? :D

**Comment by Alek2ander** [comment]
Make sure helmets and headpieces for bio/bomb/space/hardsuits aren't affected. Also the wizard hat.

And it MUST work for Ian

**Comment by ShadowDeath6** [comment]
> throwing a fedora onto the chaplain, killing him immediately because le atheist face

**Comment by ParagonPrime** [comment]
this gives me an idea for a craftable weapon

> recipe for evil:
> 1 tophat
> a number of glass shards
> cablecuffs
> attach cablecuffs to tophat, attach glass shards to cablecuff-tophat assembly
> THROW TOPHAT AT PEOPLE AS SUPER DEADLY WEAPON, ODDJOB STYLE

must have
