### ISSUE TITLE
Oisin the Borer

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#505]
Adds Oisin, a Cortical Borer colored in the black and white tones of the mime. 

http://imgur.com/qUw29Up
http://imgur.com/4IA8raW
http://imgur.com/Q7e94A1

Has Borer abilities, such as chemicals, but can't reproduce, talk in Borer Hivemind, talk to its host, or assume control of its host.

Oisin would start off as a brainless mob, but xenobio / adminbus can make him sentient.

Coder references > player references

**Comment by ShadowDeath6** [comment]
Also we'd need an interesting description for him so if you have anything that sounds good, offer away.

**Comment by oisin100** [comment]
I suppose if it cant access most of its borers powers theres not really any problems... But your replacing mimekitty... How could you do that... If this were to happen it might be better to replace Lamar...
I love the fact that you want to name a ugly slimy slug after me!

**Comment by oisin100** [comment]
You could give the Warden or the QM a pet maybe...
I wouldn't mind replacing Mimekitty with Oisin but i want to hear some feedback on this before i make any changes.

**Comment by DavidEdwards** [comment]
No need to replace mime kitty. Adding a new pet for QM would be cool. Cargo has no pet.

**Comment by Kmc2000** [comment]
No

we are NOT replacing mimekitty

EVER

Go away and succ yourself, baby

Make it a QM pet

**Comment by oisin100** [comment]
I dont think it would look good if i made this... If we decide to get this done it would probably be a good idea to get another coder to do it...
~~would be really really cool.~~

**Comment by ShadowDeath6** [comment]
I want it to be a mimekitty replacement since we already have enough player recognition with the statue AND the animal, and that a black-and-white borer was the easiest to color. 
I guess we could make it a QM pet, just as long as it's not able to reproduce. 

Replace mimekitty 2556

**Comment by oisin100** [comment]
Could replace the obnoxious honkbot instead...

**Comment by Time-Green** [comment]
Killer timato when?

**Comment by Stealthkibbler** [comment]
Why not make it a clownish borer so its sole purpose is to invade the mind of sec and meme them.

**Comment by Alek2ander** [comment]
> Oisin would start off as a brainless mob

**Comment by ShadowDeath6** [comment]
> Oisin would start off as a brainless mob 

:^^^^)

**Comment by ShadowDeath6** [comment]
Also honkbot is a treasure and the perfect clown pet, he is irreplaceable. (Unless xenobio gets lucky)

**Comment by Stealthkibbler** [comment]
No need to replace, when you can add something new and cool. The old thing that people love can stay, adding the new one will make people who like the new one happy

**Comment by ShadowDeath6** [comment]
> people unironically liking the cat

**Comment by oisin100** [comment]
> Also honkbot is a treasure and the perfect clown pet, he is irreplaceable. (Unless xenobio gets lucky)

Cant Cargo order them?

We could always just give the mime another pet....
I don't really see a mime colored borer fitting with the QM... A normal borer might be a fitting pet for the QM. Or a red and black borer for the warden.

**Comment by ShadowDeath6** [comment]
Cargo can't order living things outside of the special event mobs. Honkbots are xenobio only. 
Oisin could be a friendly mob gotten from gold slime + water. 

Edit: I'll sprite some other colored borers for sec and cargo when I get home.

**Comment by ShadowDeath6** [comment]
http://imgur.com/4IA8raW

new sec sprite if Oisin becomes the warden's pet.

**Comment by ShadowDeath6** [comment]
http://imgur.com/Q7e94A1

Hail Cargonia! New sprite for the Quartermaster so he finally gets a cool pet as well.

**Comment by Wardog390** [comment]
why the fuck are you replacing mimekitty deny this so hard or make seperate mob.

**Comment by DavidEdwards** [comment]
@Wardog390 Won't be replaced. If theres a requirement to remove something, we can remove the statue.

**Comment by oisin100** [comment]
Well none of us want to remove mimekitty. And Cargo doesent have a pet. @ShadowDeath6 QM borer looks quite nice!

**Comment by ShadowDeath6** [comment]
> none of us want to remove mimekitty

I'm fine with it being cargo's pet. Hell, with the red color, it could even be another pet for the ops to have.

**Comment by oisin100** [comment]
> it could even be another pet for the ops to have.

Problem is im terrible at Ops...

**Comment by Stealthkibbler** [comment]
QM borer looks really nice, the color scheme on that goes well.

**Comment by Greatbigben** [comment]
is this for memes or has been added?

**Comment by ShadowDeath6** [comment]
I wish it was added ;_;

**Comment by Greatbigben** [comment]
Closing then
