### ISSUE TITLE
Remove shitty rev

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#508]
Make highpop rev have a 50/20 chance of being a clown uprising, where the clown gets a bike horn that works like the recruitment pen, HONK, he converts people into clowns with unremovable clown clothes, HONK who are also clumsy. 

Their goals are to prepare the station for arrival of the clown empire. 

Whether you decide to take this seriously or not is down to you, oisin suggested i post this so here it HONK

**Comment by oisin100** [comment]
:+1:  x :100: 

# HONKZILLA HAS RISEN

~~anything is better than rev~~

**Comment by ShadowDeath6** [comment]
:^)

**Comment by Kmc2000** [comment]
Oh my look at the time⌚ 

Time to ❌  rev? 

✅✅✅✅✅✅✅✅✅

**Comment by Kmc2000** [comment]
This has support now:
https://gyazo.com/1889c144cd09d08869987e986fc8ce1b

Also oak suggests making the clown have to bite people, which i like

**Comment by ParagonPrime** [comment]
suggestion, suggestion, ahoyyyyyy

make it so that you can only win rev by exiling the heads :^)
(if they commit suicide revs still win)

**Comment by oisin100** [comment]
> make it so that you can only win rev by exiling the heads :^)

What would happen if a rev "accidentally" killed a head though?

**Comment by Stealthkibbler** [comment]
Dont make it a 10% bite chance, that's really silly, 100% convert chance on the bikehorn seems fine, Clowns cannot use guns or stun weapons without a chance of borking themselves. Making their ability to takeover purely reliant on their PDAs and Banana peels and sheer numbers.

From what I witnessed, the very presence of many clowns causes a hivemind like behaviour to occur where all clowns begin to group better than 70% of nukeops teams.

**Comment by ghost** [comment]
Clowns work on a curious exponential growth system.

More clowns = More effectiveness. The stability of the station is converse to the number of clowns in radius to each other.

**Comment by Kmc2000** [comment]
HONK

Let's add this already, amirite?

**Comment by Greatbigben** [comment]
whats the decision on this?

**Comment by Kmc2000** [comment]
Can we just add this already?

**Comment by Super3222** [comment]
Council voted no. Close this.
