### ISSUE TITLE
New malf AI module

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#512]
Shortcircuit. 

After a 2 seconds delay of maliciously flashing, target APC emits an electric shock that deals 30 base burn damage and stuns in a 3x3 radius, scaling with the output power in the grid. Silicons are immune to this. 

If used on an hacked APC, it instead explodes in a blast that of a minibomb and the victory timer increases. 

Cost: 6 uses for 30 CPU

pls gimme

**Comment by ShadowDeath6** [comment]
Or it could use lights like the revenant overload does.

**Comment by Greatbigben** [comment]
op
