### ISSUE TITLE
Borers can suicide in a host, also not spaceproof.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#515]
### Expected Behaviour

Borers to be spaceproof.

Borers to be able to not instantly kill their host.
### Actual Behaviour

Borers can suicide in control of their host, permanently taking them out of the round, and making GG cheap instakills if they so much as suspect their host is heading to the kitchen or chemistry.

Borers are not spaceproof despite oisin citing that they would be.

**Comment by oisin100** [comment]
This was fixed already. Update the server!
Ill remove suicide.
