### ISSUE TITLE
Borer Salt

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#517]
Adam thinks borer chem recharge rate is too slow.

Recharge rate is currently 1 Chem per tick(A tick in byond can be really random. Ranging from a second to over 3 seconds)

Does this sound too slow to you? Should i increase the rate?

**Comment by Stealthkibbler** [comment]
Borer does feel somewhat sluggish.

**Comment by ShadowDeath6** [comment]
Don't increase regen if medical chems are 35 per use. I'd like to have costs of things reduced before regen is increased, since faster chems = faster borerspam and that's apparently _a bad thing_

**Comment by Wardog390** [comment]
> Don't increase regen if medical chems are 35 per use. I'd like to have costs of things reduced before regen is increased, since faster chems = faster borerspam and that's apparently a bad thing

i'd suggest making it 1.5 or 2 per tick and a remodel of chemical cost/storage/ETC like shadow says.

**Comment by Greatbigben** [comment]
was this fixed?

**Comment by oisin100** [comment]
I dont think so..

**Comment by oisin100** [comment]
Im doing a rework on how borer works. Ill do something about it in the re-work.
