### ISSUE TITLE
Mining drone HUD

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#519]
### Expected Behaviour

The HUD icons don't overlap, increased usability.
### Actual Behaviour

![ss13-miningdrone-hud](https://cloud.githubusercontent.com/assets/16806055/13667422/7f5e8266-e6b6-11e5-8d27-f5b5b610383c.png)
### Steps to reproduce the problem
1. Be mining drone.
2. Pull an object.
3. Have your HUD icons overlap.

**Comment by DavidEdwards** [comment]
Thank you for the report, but this is (should be) already fixed in #510 that is waiting for merge.

**Comment by 00aquir** [comment]
Thanks
