### ISSUE TITLE
Requested to make Viro Clearer

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#52]
opened by Ben · 11 days ago
What is the nature of the issue: Viro investigate is unclear when a virus is jumping around infecting multiple people. please work on making it clearer and solve the issue of . showing up in logs (Person X got the disease from .) What steps must be taken to reproduce this error:
Any additional information? :

**Comment by Groudonmaster** [comment]
If it doesn't define a source it's from a random event occurrence.  That's the only time I've had that occur.

**Comment by Hydre** [comment]
I brought this up.

Sometimes disease source is blank, even though it's not a random event

Way of infection is vague as fuck, if even present.
For example: 'syringe' and not even mentioning who injected.

It's just plain broken as sometimes necessary information is missing.
Could be structurally improved as well

**Comment by Groudonmaster** [comment]
I think that occurs when a syringe gun is used
