### ISSUE TITLE
Engineering mini events

### ISSUE THREAD

**Issue by Chuggachar** [yogstation13/yogstation-classic#522]
Some cool mini random events so that engineers and atmos techs have more to do, IE APC's frying, a pipe bursting things like that. Post more ideas below.

These could happen fairly often every 10-30 minutes or so.

**Comment by oisin100** [comment]
We have electrical storm. Thats already super annoying.

**Comment by Chuggachar** [comment]
This wouldn't be electrical storm these would be much more small scale and give engineering something to do.

**Comment by ShadowDeath6** [comment]
Anomaly damage, elec storms sometimes break APCs, sometimes break lights, plasma in a room, not to mention bombs and shit.

**Comment by Time-Green** [comment]
Well.
Problem is most engineers dont even know how to use metal and just walk around with gloves doing nothing.

I love the idea, but I am pretty sure engineer is the bloody incompetent to do anything

**Comment by Super3222** [comment]
> Anomaly damage, elec storms sometimes break APCs, sometimes break lights, plasma in a room, not to mention bombs and shit.

Eh breaking lights is kinda the jaintors, unless they don't feel up to it.

**Comment by ShadowDeath6** [comment]
> janitors doing anything ever

**Comment by ghost** [comment]
make door safeties in some location randomly turn off so they squish people

**Comment by Chuggachar** [comment]
These wouldn't be big events announced with the centcomm thing they'd be small events that engineers/atmos techs would have to find and fix, and if there are too many incompetent engineers perhaps engineers actually having more to do will make people want to play it more.
There is enough quiet time between the big random events and bombs etc for the engineers to go out and fix these it just means engineers won't have fuck all to do during those times.

**Comment by oisin100** [comment]
> having more to do

This is the reason i don't play engineer. Pretty much every round a bomb goes off or singularity is hacked or there's plasma floods. There's SOO much for engineers to do every round already that it no longer is fun because of the constant problems what happen EVERY single round.

**Comment by Chuggachar** [comment]
Whenever i play engineer there's barely anything to do except wait around untill things like that happen, if you're a competent engineer then you can deal with those issues these aren't issues that would take half an hour to fix like a bomb these are issues that would take a few minutes to fix. If you have too much to do as an engineer then you're either playing a very chaotic round or you're just not very good at engineer.

**Comment by ghost** [comment]
I already included this in my issue req above yours.

Get cucked.

**Comment by Time-Green** [comment]
Problem with fixing the big breaches is that the hardsuits are always gone.
Them you wonder "Who is working with them?"

Then you see 2 suicided engineers in hardsuits outside escape

**Comment by Ephemeralis** [comment]
Cool idea, but Oisin has the right of it. Engineers already have fucktons to do in most rounds - they don't need more stress.
