### ISSUE TITLE
ADAM HAS ANOTHER GIANT FUCKLOAD OF IDEAS-ENGINEERING EDITION

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#528]
So, there are a lot of issues wrong with engineering.

Specifically, engineering does not have much to do.

They set up the power, go braindead for 40 minutes, and then a bomb blows up the bridge and it's so tiring to fix nobody does it and just calls the shuttle.

So, I have devised multiple different systems relating to engineering to keep them involved in the round and no longer so insular. Divided into 3 different sections-_Department reworks_, _Management_, and _Events._

---
## Department reworks.

R&D has, to be frank, too much to do. It's ridiculous that science is responsible for upgrading and building machines that engineering is supposed to do. 

R&D is supposed to be developing new tools, yes, but not responsible for EVERYTHING. Engineering is the UPGRADES team, R&D is the DEVELOPMENT team.

So, to promote department interconnectivity-
### 1. Remove the 'stock parts' ability from R&D. R&D can no longer upgrade machines on it's own with RPED's.

Instead, add a 'parts manufacturer' to engineering. As science's levels go up and they sync, engineering can sync servers with R&D, thus granting them access to the nano-pico-femto tiers of parts. 

Engineers are now responsible for printing and upgrading machinery, and R&D is responsible for doing the work to grant them access to these parts. Engineers have more to do, and more department interconnectivity is required.

'BOO HOO I DON'T WANT TO WAIT 5 EXTRA MINUTES WAAAAAAH'

R&D isn't required anyway. It is a frivolity. At least now, engineering has more to do except resolve inane antagonist actions, and guess what, if you can't vomit out infinite resources 5 minutes into the round, now you know how everyone else feels when you turtle up in science behind 7 automatic dildo printers.
### 2. Remove the circuit imprinter from R&D and add it to engineering.

 Engineering is responsible for the construction of machinery and gear, science is responsible for devising it. Now, R&D has to actually leave science to get research up, meaning you can't powergame-beeline it anymore, and that R&D can't turtle up with their own private autolathe and exosuit fabricator and cloner on their own anymore. 

Since engineering does not have a chem dispenser, they will have to go to chemistry for sulphuric acid for the printer, minerals from cargo to print advanced circuitboards, and R&D will require them to print the necessary boards. They already have access to tech storage for replacement gear-it simply makes sense this way. R&D does the research, engineering syncs, prints the boards and builds the actual machines. Department interconnectivity and it forces people to leave their private fortresses for 5 extra minutes, more time for traitors to actually ambush them.
### 3. Computer servers.

Now this is hefty. I always found it a little silly that no matter how shit everything has gotten, you can still access the security records and set people to arrest, and there's no way to sabotage this aside from logging in and deleting it. You can always access computers no matter the situation.

So, change it. 

Engineering is responsible for the maintenence of the computer systems. The computer systems, either stored where the abandoned engineering room is now or somewhere in telecommunications, ensure people can actually log into computers, access records, use comms consoles, send messages to labor, ect. 

With a security system equal to telecommunications and a motion sensitive camera, it's a secure, cooled room where engineers are responsible for the maintenence of the computer systems, their upgrading (Upgrading the computer systems increases ease of navigation, access checks, maybe reduce network lag if you add network lag in as a feature).

Bomb the computer servers? Security computers go down, no more arrest records, the bots go inactive. Shut down the communication console systems? Good luck using a comms console, 'NO CONNECTION DETECTED.' Hack into one and reverse access? Clown has access to medical records and just labeled the Captain a 8000 year old vampire dickgirl.

Now that computers are actually MAINTANED, it both adds the option for more sabotage (always a good thing) and more department interconnectivity. It's a way to counter engineering now having a circuit imprinter-Shut down the computer servers, no more computers, no more private meme comms consoles.

There would be several computer managers. One for record storage-security and medical, one for tracking, managing camera systems and crew monitor consoles, one for communication services, managing comms consoles, one for science, managing science computers-Exosuit, robotics control, R&D, ect, one for engineering, managing all the different computers engineering has, including the telecommunications consoles, one for civillian usage, interfacing with ID consoles, cargo, ect.

There are a few options for fucking with them for your own gain beyond destroying them-Multitooling them can disable, or restrict, access locks dependent on console, meaning that you can set security records to be accessible to anyone with engineering access, or nobody at all (except the AI), disable AI control, interface directly with what is available (removing the ability to order specific things from the cargo consoles and such) et cetera. 

Emagging them does the same, but is the lazy man's method of fucking with them.

EMP's scramble everything seven ways from sunday, messing with records, availability, or if the computers are even on.

Granted, you have to have one of the actual computers in front of you to do shit like set people to arrest. You can't set people to arrest from the record management consoles, but you can give yourself access to them.

Disable the computer systems, computers will just not function. You can't modify records-no connection. You can't check suit sensors-no connection. You cannot upload laws to the AI-no connection. You can't make announcements-no connection to computer systems. You can check what power levels were before the computer system shut off, but no refreshing. You can't access camera consoles-no connection. 

You can still print circuitboards or whatever, but you can't sync until they're reset, meaning bombing the computer systems, if research is advanced enough, you can still repair them, so it's not a shuttle call, but if you don't have the required research levels, raid tech storage for it, and if you can't find the required boards, you're pretty fucked, time to ask AI to call the shuttle.
### 4. Power Management systems for the CE

Now, something I have always hated about engineering is it's set power up, go jack off in the bathrooms until the shuttle calls or someone makes a small bomb. There's no way to prioritize where power goes-If power starts failing, it's fix the cables or the whole thing shits itself and dies. 

So, power management consoles for the CE. CE can decide specifically where power is routed to on the station from the Power Control Console in his office, prioritizing. 

Power starts failing? Route most power from cargo to science so they can print some power cells. A lot of injured? More power to the medical bay! Meteors incoming? 'DIVERT ALL POWER TO SHIELDS!'

Yes shields I'll get to those in a second shut up man

This way, the CE can choose which areas to prioritize power wise-A power sink will still make itself the #1 priority automatically, but he can choose in a pinch if power is failing to route power to X, or Y, or specific machinery.

He can also cut powerflow to specific areas-If someone keeps spamrecalling from science/science has gone rogue, cut off powerflow there. It's not like remote APC toggling-it's still gonna have active equipment-but APC's stop charging and pretty soon the power dies there. Or he can even increase power drain from specific areas up to a set amount to drain APC's faster.

Multitooling specific wires or buttons on the power control console has the ability to power surge-Dumping enough power into a specific APC, area, department, ect, that it triggers something along the lines of an electric storm. The more power in the grid, the more potent the power surge-A basic solars setup would bust a few lights, a level 3-4 singularity would fry an APC and fuck up some doors, bust a computer or two with EMP's, if you wire the whole thing directly into the grid you have revenant-tier lightning bulb shocks, broken machines, shocked doors, electrical storm grade fried APC's...

Granted, certain areas-Like the bridge or telecomms-Have separate power controllers so that people would have to go there to fry them, and the AI core itself is entirely immune to that shit so you can't remotely cuck an AI. Also, the machine would have a cooldown after use, and triggering it triggers a safety alarm that resets the wires, meaning after the use, not only are there cries of 'CE TRAITOR', but the machine resets.

That's only if you use the loud overload function, though.

Slowly setting specific departments to overload rather than dumping a metric fuckton of volts into the grid, so that the APC is gaining slowly more power than it can handle, is a far subtler and more efficient means of sabotage, slowly breaking APC's, overloading lights, ect.

So you have two options, The massive clusterfuck dump of electricity to fuck a department over some, or a slower sabotage that fries the electric grid over time, fucks with power, ect, and will continue slowly until people start noticing the adverse effects, lights blowing out, apc's triggering safety locks and turning off...

This ties in very well with the next two parts of the suggestion.
### 5. Machines function faster and more effectively the more power they have.

The more power in the grid, the more effective they are. Running off solars not only might cuck the department that has to deal with lower power, but also slow machines down over time. 

Not a lot of power in the grid? Sleepers are a lot slower to function, only inject small amounts of units. Cloning is sluggish. Autolathe prints things slowly. Brig cell timers might glitch out and fuck up. Mounted flashes probably just won't flash much at all. Rechargers will recharge slower. Machines will print slower. Cyro will operate slower.

Lots of power in the grid? Autolathe prints shit fast. Ore refiner processes faster. Cloner runs faster. Cyro is more effective. ect ect.

Now not only is there a legitimate reason to wire into the grid-Speedy appliances-So that you can't immediately call anyone who wires into the grid a traitor, the CE's power management systems are also much more effective. Diverting lots of power to specific departments will massively increase their efficiency, meaning that in a pinch, medbay can take all of cargo's power if nobody's in cargo and operate a lot faster, power can be rationed around depending on what needs it most presently, emitters can have energy dumped into them to fire faster...

Granted, again, past a certain point, machines will blow out with too much power and break. Upgrading parts would not only increase the potency of the machine and it's speed, but also increase it's resistance to power surges, meaning that it can run a lot faster on more power. A femto autolathe with tons of power in the grid will vomit out parts almost before you can click it, femto cloners with lots of power diverted to genetics will clone a lot faster. But if you dump the whole grid into the cloner on stock parts, not only will machines just burn out and stop working until the power goes down, but when multitooled, removing the safety triggers, you get lights exploding and APC's frying and machines going kraka-boom.

Yes, it's a very potent sabotage tool. That's the point-it's gonna be heavily monitored, has a cooldown and resets after use, and takes a lot of time and effort to set up (wiring into the grid, allocating specific power) but it's very potent. Moreso than even blowing borgs.
### 6.  Shields!

What kind of shitty futuristic space station doesn't have cool energy disruptor shields? The more power flowing into shields, meteors have less impact, ionic storms or telecommunication shortages are less potent or frequent, et cetera.

Shields are taxing on power, however, so without a full solar array, the turbine, and the singularity all running at full blast and wired into the grid, you won't be able to have shields running above 25-40% and cockblock ionic storms and such.

Shields would also have to be set up by engineering at the start of the shift-Flying around, wrenching them into place, welding them down, applying cables, screwdrivering, and then locking them with an ID card. They'd be placed towards the external areas of the station and, when toggled on, provide a thin, small bubble shield the same way breach shielders do, but less massive and expandy as they do. Mostly just a cosmetic effect, they would on low power basically only block space dust. Toggled to around 30-40% power, they stop carp and such from managing to get too close to the station immediately-carp can still penetrate the shields, but they take some time. It also slows down people passing by in a hardsuit. They also disrupt energy weapons fire like tazers and lasers, but not bullets, and catch some meteors before they hit, as well as lowering the frequency or impact of electrical or telecommuncations storms. Dumped all the way to 100% power, which would deprive most of the station of power-even with everything wired into the grid it's going to shut off most equipment and even environmental power-they're going to fully insulate against meteors, people entering from space, carp, ionic storms, ect.

So unless engineering sets up around 3 singularities from cargo and wires them to the grid, keeping the shields at 100% power and cockblocking antagonists simply won't happen. Hell, if you're only running off the singularity you simply won't have enough power in the first place.

Impacts on the shields strain the generators-The more impacts, eventually the power requirement raises exponentially and they shut down. 100% shields are not entirely and completely impenetrable, but they're a significant obstacle along the level of rwalls. But hit it enough and the shield network will burn out for some time.

Again, the CE can divert more or less power to shields, to get that old timey spacey feeling of 'DIVERT ALL POWER TO SHIELDS, METEOR STORM INCOMING'

For obvious reasons the AI cannot interface with the shield generators, and without an engineering cyborg hacking the power control console, cannot power surge.

---
## Management

Now we're on to management itself.

This is short, just 1-2 ideas.
### No. 1. The singularity produces less power.

The singularity produces WAY more than enough power currently.

It should produce just enough to keep the station afloat at stage 3-purple sing. Enough to power current equipment without power failures, unlike solars. Add one or two more machines, not much. Set up an emitter battallion to fight a blob? Oops, arrivals is losing power, CE get on that and start diverting power.

Obviously wiring into the grid produces more power than SMES basing.

Stage 4-Dark blue-Is going to be at the power tier we are currently at, producing shitloads of power. The downside is that it's somewhat unstable, needs watching, and close to being released.
### No. 2.Solars won't produce enough power on their own.

 Do a full solars setup? Not only will machines run sluggishly, but departments will periodically lose power. Replace that sing containment field or use the turbine, or order a new sing crate from cargo. Otherwise, if you're running on solars, expect departments to occasionally lose power, the CE to spend a lot of time with his dick stuck in the ceiling fan trying to fix power from his console, lights to shut off very quickly.
### No. 3. Cameras operate based on power, netted to the equipment APC!

No power? No cameras! No more big brother watching your every move. Shadowlings are suddenly more potent as they snip the power net! Power sabotage is bad for everyone, not just crew! Power sinks suddenly are AI blinding nightmares! Turn off environment on an APC? Cameras shut off, accompanied with camera alarms.

No more AI's turning off equipment at shift start to prevent emagged borgs from getting in. No more AI's spamtoggling power off in the bridge when subverted! The greatest nerf to big brother of ALL TIME!

Malfunctioning AI's 'reactivate camera network' or 'upgrade camera network' powers are still entirely functional. Upgraded cameras and reactivated cameras are immune to power failures and will still function even with no power.

Crew can add power cells to cameras, just like you can upgrade cameras with plasma, carrots, analyzers, ect, to make them run even when there is no power. 

---
## Events

Engineering events!
### 1. Power surges!

The same deal as the CE fucking with the console!

Power will surge. Depending on how much power is in the grid, vending machines might bust, spew their contents very fast, computers will end up with broken glass, lights will break, machines will burn out, doors will open, toggle emergency access, or end up shocked, APC's might fry.

This is accompanied with a message from central command-'Power surge detected in station power network. We apologise for the inconvenience-please restore afflicted departments.'

This way it means people can tell the difference between the CE being a whore and RNG being a whore.
### 2. Power failures!

Just like is in the administrator secrets panel. SMES except for AI core and tcomms and bridge are drained, APC's shut off, lights go out, (The sing containment is still the same) accompanied with a message from centcomm-

'Power abnormality detected in (STATION NAME) systems. Power has been temporarily shut off until we can restore the network, we apologise for the inconvenience.'

Five or eight or so minutes later, power is fully restored, again, just like in the administrator secrets panel, leaving the SMES at the same level they were before, with the message from central command-

'Power has been restored to the station. We apologise for the inconvenience.'
### 3. Increase the frequency of disastrous shit!

Telecommuncations anomalies, electrical storms, will both happen more often.

Re-add meteors-now that lag is being fixed with BYOND 510, we can re add them as an event!

Telecommunications anomalies will also kill the computer network. Electric storms will bust computers and scramble status displays. APC's will not only fry, but emit shocks, machines will stop functioning or even emit a fireball like CLF3 does, 

God help you if you're hacking a door when an electric storm hits, because any door with maint panels open in the afflicted area will get shocked!
### 4. Add 'exposed cables' to maintenence!

Wandering maint is now hazardous. Fucking around in maint? Be careful not to step on a live, exposed cable, or you'll shock yourself. 

You can use wirecutters on cables to expose them. Laying exposed cables around is a great way to shock people-Connecting an exposed wire to the grid will show an adminlog. Not for every cable, but just the once along the pathway, so that admins will know.
### 5. Door malfunction events!

Doors will sometimes malfunction. A message may or may not be provided to the crew, but wires will scramble sometimes on specific doors, doors in afflicted areas may bolt suddenly, open, shock, toggle emergency access, or more! Some areas are protected from this, such as the AI upload, vault, and gravity-Anywhere HIGH security, where doors are guarded, cannot be afflicted. More public areas like engineering, medbay, the front of the brig, might be hit by this. Shocked doors can also be the work of shitty luck, not just angry rogue AI's or deliberate sabotage! It's probably still the AI though, so reset it anyway.
## 6. Miscellaneous errors in Computers/PDA!

PDA messaging systems will sometimes be infected by a piece of adware, which engineers or scientists or basically anyone with access will have to troubleshoot. Otherwise, it'll send obnoxious messages to your PDA every five minutes or so, nagging you to buy Syndi-cat brand smokes or Robusta Cola. You can fix it simply by toggling the PDA messenger in tcomms off and on.

Computers however, will be afflicted with far more horrifying, destructive pieces of terror...

ADWARE POPUPS.

You forgot to install norton Anti-virus (Space edition) for some reason, and now the computer servers are infested with popups and viruses.

Records will be randomly deleted, modified, or added, as though they were hit with an EMP. Access might get scrambled.

Trying to change the traitor clown's status to arrest? Too bad, you're redirected to www.4norasin.com and asked if you want to download their free screensavers. Enjoy clicking X angrily and screaming at the engineers to fucking fix it already or watch the station be buried under annoying popups and adware!

Emagging the computer servers also uploads malicious viruses to them, that are a lot more fucky-with, scrambling records, accessibility, and unlocking illegal functions such as tracking anyone near the computers like an eye in the sky (webcams hooray).

---
# Frequently asked questions.
1. TOO MUCH WORK REEE-

Get over it.
1. TOO MUCH WALKING I DON'T WANT TO LEAVE MY DEPARTMENT REEEE-

Get over it.
1. BUT ENGINEERS ALREADY HAVE SO MUCH TO DO-

No they don't. They have nothing to do except validhunt, set up the engine, or call the shuttle when something gets bombed because bombs suck to repair.
1. What about the shuttle call if computer servers are down and AI is dead/braindead/rogue?

In case you didn't know, the shuttle will automatically call if all comms consoles are destroyed and the AI is dead or AFK. It automatically comes in 25 minutes.

If AI is rogue though, you're pretty fucked, you might as well start repairing computer systems, and if you can't repair them at all admins will probably intervene to call it.
1. BUT WOW WHAT ALL THE GRIEF THIS COULD BE USED FOR-

Hello. I am an admin. I would like to introduce you to the department which has no purpose but making bombs to blow up the station with nothing to stop them but other admins.

**Comment by Yackitori** [comment]
I like it.

(Just don't make adware too op)

EDIT: Didn't know that was part of the code. Oops.

**Comment by Groudonmaster** [comment]
> I like all of it, except the last part. How will someone be able to call the shuttle IF:
> 
> AI's dead/braindead and you can't get it to call the shuttle
> Computer servers are down
> 
> **What about the shuttle call if computer servers are down and AI is dead/braindead/rogue?
> In case you didn't know, the shuttle will automatically call if all comms consoles are destroyed and the AI is dead or AFK. It automatically comes in 25 minutes.**

**Comment by ShadowDeath6** [comment]
> forces you to put a retarded amount of power in the grid
> punishes you for it

This isn't goon, let the people enjoy their full apcs without punishing them for it/letting the AI do 80 damage doorshocks.

**Comment by oisin100** [comment]
Im interested in doing the servers, adware, shields, exposed wires in maints and CE control computer(Inb4 Shadowling CE cuts off all power)

**Comment by ghost** [comment]
shadow what

how does it punish them

firstly it's hard to put a retarded amount of power in the grid because the standard sing just barely meets station power req in my suggestion

and then secondly literally all you get is buffs for it

**Comment by Super3222** [comment]
This looks very interesting and promising.

Literally almost every round you'll get the Engineer who has almost nothing to do but wait for another explosion to happen.

We could also use the help of mappers for this project.

**Comment by shrimptk** [comment]
_DID SOMEONE SAY MAPPERS?!!_

**Comment by shrimptk** [comment]
**AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA**

**Comment by Stealthkibbler** [comment]
> Engineering is responsible for the construction of machinery and gear, science is responsible for devising it. Now, R&D has to actually leave science to get research up, meaning you can't powergame-beeline it anymore, and that R&D can't turtle up with their own private autolathe and exosuit fabricator and cloner on their own anymore.
> 
> Since engineering does not have a chem dispenser, they will have to go to chemistry for sulphuric acid for the printer, minerals from cargo to print advanced circuitboards, and R&D will require them to print the necessary boards. They already have access to tech storage for replacement gear-it simply makes sense this way. R&D does the research, engineering syncs, prints the boards and builds the actual machines. Department interconnectivity and it forces people to leave their private fortresses for 5 extra minutes, more time for traitors to actually ambush them.

@AdamElTablawy 
This is the only issue I have with this whole idea, mainly because not only does it take away something science has but it actually doesn't affect the Research department at all. Robotics already has its own circuit imprinters, remove the dispenser and imprinter in R&D and people will just break into Robotics and use the ones in there, this will lead to civil wars in the science department as scientists try to jack the robotiscists shit because engineering is on the other side of the solar system. (R&D can also just make their own chem dispenser and protolathe using the robotics imprinter and cannibalizing machines for stock parts anyway.)

If engineering is going to have a imprinter it needs to have a chem dispenser, the dispenser in R&D is there for a reason, so the scientists do not have to rely on chemistry to even make basic circuits, during a research build, in order to be extremely efficient you will need to de-construct lots of boards, each board needs around 20-25 sulphuric acid, the dispenser in science produces 100 units of sulphuric acid at an extremely slow rate, but just enough to get what you need. I not long ago played on Hippie and TG and I was easily reminded at why we have that dispenser there, after like 3 boards I needed to take a trip back to chem because they refused to share large beakers so I could only use so much, this slowed down research exponentially. If engineers need to do this it will just be a complete waste of time.

Eliminating a core element of Research and Development will only harm the gameplay that science has to offer, if you were going to actually give engineers the upgrade responsibility (Which is a good idea), don't force them to go to chem, at that point it essentially becomes padded game-play that no-one enjoys.

As for too much walking around, engineers generally have to move around a lot even when it comes to maintaining station power and fixing minor to major breaches, they are the most mobile job in the game as they are even granted access to spaceworthy hardsuits with inbuilt jetpacks. It would be preferably better if engineers didn't have to burrow from chem, allowing for more robust game-play by all departments involved.

The general idea is that yeah departments need to rely on eachother, but you make them self sufficient in the beginning, because everyone already needs to rely on mining to get anything better than the basic stuff. This way the department has everything it needs to start with, but if it wants the luxury/lategame stuff it needs to co-operate with other departments, an engineer should not have to completely rely on chemistry just to keep his department on its feet, it should be that he is able to sustain his department with the resources already given to him at roundstart and then if he wants to take his department to the next level he would then need the other department.

Thing is if you give them the ability to use a circuit imprinter and stock parts, engineers will just make their own R&D anyway, so unless a coder is willing to heavily and I mean HEAVILY make a ghetto version of the protolathe and circuit imprinter than this specific change will do nothing but rip out a core element of one department and split it into another for no good outcome.

Everything else looks like good shit though.

As for the power idea I can see engineers actually utilizing the auxiliary power supply above chapel and actually using Pacmans to maintain power in departments.

**Comment by ghost** [comment]
Alright.

So remove the imprinter from R&D.

Make a ghetto version of the imprinter in engineering that makes actual usage circuitboards (machinery), give the RD a locker of spare R&D circuitboards, and make robotics have a mech circuitboard imprinter.

If people are walking back and forth between departments, GOOD. It gives chemists something to do-currently, a large part of the interaction on other servers is giving out acid on request, so that they have things to do, and it gives antags more chances to attack people moving around the station.

Self sufficiency is not a good thing.

**Comment by Stealthkibbler** [comment]
What I meant is self sufficient is good at the start, where they can focus on setting the basics up, but if they want to acquire additional upgrades they then need to rely on other departments.

As for antag ambush most people play murderbone mary anyway and just go out on a whim to murder anyone in their way.

**Comment by ghost** [comment]
and then they get banned

**Comment by Stealthkibbler** [comment]
and then we have people like flufyy who ded everyone in 1 minute of game gg
