### ISSUE TITLE
Stop swarmers from breaking Dominators.

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#529]
> Be Gang
> Start dominator in turbine
> 100 Seconds left. Nobody left trying to attack the dominator
> A wild swarmer appears!
> Swarmer breaks through 2 Rwalls, Walks through ultra heated plasma fire, destroys dominator. All in 5 seconds.
> Becomes very salty

**Comment by Super3222** [comment]
Swarmers weren't meant for gang modes, so this really isn't a problem.

Also a delta based take over would technically halt them from expanding their legion of robotic termites.

I also think that the gold slime strange reagent reactions are getting nerfed.

**Comment by oisin100** [comment]
> Swarmers weren't meant for gang modes, so this really isn't a problem.

Strange reagent gold slime reaction

> Also a delta based take over would technically halt them from expanding their legion of robotic termites.

From what I've heard dominators dont destroy the station. They would have no reason to destroy a dominator except for the platsteel where they wouldent have to come all the way down from Xenobio just to eat 1 dominator when they can eat the Rwalls in the room they spawn in.

**Comment by Time-Green** [comment]
Oh my god.
I placed the dominator there.

And we were winning, and then boom.
A swarmer insta kills 2 rwalls, ignores the burning plasma and instakills the dominator

**Comment by X-TheDark** [comment]
Just remove them from the special reactions. I have no idea what the reasoning was behind adding it in there in the first place, it worked fine enough when it was in the normal mob list.

Also, you should see how much Revenant destroys gang rounds.

**Comment by Ephemeralis** [comment]
Swarmers aren't supposed to cause critical round-ending damage. Being annoying is fine, destroying a Dominator is not. Same deal goes for Revenant.

**Comment by ghost** [comment]
Revenants are god tier don't fuck with them

But yeah, swarmers aren't able to eat nukeop nukes or  APC's ect, no reason for them to eat dominators
