### ISSUE TITLE
Pussy non-hatch shadowling cant hatch nor ascend once 15 thralls are present

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#531]
### Expected Behaviour

Hatch and ascend
### Actual Behaviour

Try to hatch, and realize the whole shadowling tab is gone.
### Steps to reproduce the problem
1. Dont do shit
2. Wait for the other shadowlings to ascend
3. Cry because you cant hatch anymore

I tried alot, like turning them into non antag and back.
Respawning them and such.
I tried it myself for a test and I had no problems

In this round were 4 shadowlings. 2 hatched and the other 2 both ahelped about not being able to hatch nor ascend

**Comment by oisin100** [comment]
Any other details? Were they infected with anything(EG, Borers)? Sure they werent trolling you?

**Comment by Time-Green** [comment]
They werent. Both of them had it.

They were not infected at all.

Their whole freaking tab was gone, They could not commune either.

They could still tell shadowling/thralls apart and hear shadowcommune.

But thats it. The whole tab dissapeared.

The 2 people were commanderxor and some other dudes name I forgot

**Comment by oisin100** [comment]
I might have a slight idea why it happened. Ill have to check first.

**Comment by oisin100** [comment]
Found the problem. When a ascendant ascendes it removes all "hatch" spells from lings so any unhatched lings loose the chance to hatch thus loosing the chance to ascend.
