### ISSUE TITLE
THE MOST IMPORTANT SECURITY REWORK OF ALL TIME

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#532]
Make the armory have a Captain-level locker with one justice helmet on it.

If emagged, the justice helmet cannot be taken off or turned off without acid.

If you emag a security hailer, it cannot be taken off when worn and turns all speech into sechailer quotes (FACE THE WRATH OF THE GOLDEN BOLT).

Both are removable with acid, like barnyard.

**Comment by ToGWtF** [comment]
:+1:

**Comment by ShadowDeath6** [comment]
That's gonna be hard to code

**Comment by Kmc2000** [comment]
👍 x 100
