### ISSUE TITLE
Fractional Borers (bug)

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#538]
"A total of 1 borers with hosts got to centcomm alive. The borers needed 13.8571 hosts on the shuttle so they Lost!"

It displays a decimal req instead of an integer.

**Comment by oisin100** [comment]
Kek

**Comment by Wardog390** [comment]
that was a funny thing to see at round end.

**Comment by Greatbigben** [comment]
Closing because of merge
