### ISSUE TITLE
Gold Slime + Plasma not working

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#539]
### Expected Behaviour

Gold slime extract spawns 5 hostile mobs.
### Actual Behaviour

It flashes and does nothing.
### Steps to reproduce the problem
1. Inject gold extract with plasma.
2. Wait for it to spawn mobs.
3. Nuffin happens.

**Comment by MacHac** [comment]
Fixed in PR #546.

**Comment by ShadowDeath6** [comment]
rip this issue
