### ISSUE TITLE
Update preferences to avoid bitfields

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#544]
### Expected Behaviour

Make a game mode, allow users to play it.
### Actual Behaviour

Make a game mode, nobody can play it because Byond has shitty integers. 
### Steps to reproduce the problem
1. Make gamemode
2. Cry when you exceed the allowed size of an integer

**Comment by Time-Green** [comment]
Timato gamemode confirmed

**Comment by oisin100** [comment]
I feel ya...  Fix please.
