### ISSUE TITLE
Monkification

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#551]
### Expected Behaviour

Upon monkifying yourself with genetics, be able to control the monkey you turn into.
### Actual Behaviour

You're stuck on one space, while your monkified body walks around like a normal mob. It seems that you're still in a physical body, but you can't move it and it's invisible.
### Steps to reproduce the problem
1. Monkify yourself
2. Try to control monkey
3. Not be able to control monkey

**Comment by oisin100** [comment]
My fault. Fixed on next server update.
