### ISSUE TITLE
Medibot Suggestions

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#553]
It always sucks when you have to bring countless corpses to medbay due to some random incident, so why not give medibots a mode to drag corpses to the medbay treatment center? Corpse recovery would be very slow and interruptable, and there would be a limited number of activations for a limited time each. That way, it would only be used for real emergency. Also, healing the living would take priority, so medibots would stop carrying corpses and follow injured people. It would save medics time and make medibots a bit more useful. (Especially if people don't have their suit sensors on!) If hacked, it would space corpses out of the chaplain's mass driver when this mode is on. Thoughts?

**Comment by ShadowDeath6** [comment]
that would be OP as hell

**Comment by Rocks4Free** [comment]
> that would be OP as hell 

Well, here's an idea: corpse recovery would be very slow and interruptable, and there would be a limited amount of toggles for a limited time each. That way, it would only be used for real emergency. Also, healing the living would take priority, so medibots would stop carrying corpses and follow injured people.

**Comment by ghost** [comment]
still OP

also fairly impossible?

but still ridiculously overpowered

> drag captain's corpse out of maintnence
> 
> drag it away from a nukeop in space

**Comment by faultlesselm16** [comment]
how about make them only drag bodies they see while on patrol?

**Comment by Rocks4Free** [comment]
> how about make them only drag bodies they see while on patrol?

That was kind of the point, I guess I wasn't clear enough on that.

> drag captain's corpse out of maintnence
> drag it away from a nukeop in space

I don't think a medibot would ever go into space.

**Comment by ghost** [comment]
> hop gets killed in the hall 
> 
> medibot drags him off

**Comment by Rocks4Free** [comment]
> hop gets killed in the hall
> medibot drags him off

Implying that the tator wouldn't just break the medibot as it slowly drags away a corpse

**Comment by ghost** [comment]
> adding more annoying shit for a traitor to deal with as he pursues some obnoxious asshole bot
> 
> implying medibot wouldn't end up dragging people into fucking plasma fires or whatever and then getting stuck by space wind
> 
> implying 99% of the time this wouldn't move a corpse out of obvious locations into inaccessible locations
> 
> implying this wouldn't drag injured people into gang-controlled medbay
> 
> implying this wouldn't fuck up if medbay got bombed and it just dragged people into gaping hull breaches
> 
> implying this wouldn't just obnoxiously drag people away from a paramedic trying to defib them
> 
> implying this wouldn't lead to traitors accidentally getting revived because some cunt medibot dragged them off from a lynchparty
> 
> implying that making a medical robot that when emagged not only kills your target but spaces their corpse for you is not overpowered as dicks

**Comment by Cruix** [comment]
This is absolutely possible from a coding standpoint, by the way. It would be trivial to do if bots were simple animals, but drag code is so simple that it should be easy to make a ghetto drag for bots. Add an extra bot waypoint beacon in medbay and we're all set.

**Comment by ghost** [comment]
i mean the bot spacing the corpse

**Comment by Greatbigben** [comment]
is this getting added?

**Comment by Rocks4Free** [comment]
Haha no

**Comment by FluffySurvivor** [comment]
fuck no. 

medbots literally replace 90% of medbay all the time

bro do u even balance?

**Comment by X-TheDark** [comment]
1. Closing this due to responses.
2. Cyborgs can already drag a single corpse using Control+Click, so it seems that's what this issue was proposing in the first place?
