### ISSUE TITLE
Heavy X-Ray Lasers

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#556]
Literally every damaging energy variant has a heavy version, even ebows and pulses.

Add heavy xray launcher for mechs, it would be unlocked by syncing robotic fabricators to an R&D server with xray lasers researched. Basically an xray laser but D O U B L E  (burn) D A M A G E.

The name of the laser module can be debated.

**Comment by ghost** [comment]
hahahahaha no

no more buffs to sci we already have mechs that can literally fire rocket launchers 

X-ray laser for 40 burn damage in addition to it's radiation shit is basically asking for an unkillable nightmare

**Comment by ShadowDeath6** [comment]
Heavy lasers do 40 damage and you can rapid fire them

This is exclusively for mechs because they're ass against blob right now and they could stand to be better against it in lategame.

**Comment by Time-Green** [comment]
I would love it if someone put those in the AI core turrets and have the whole crew die because the clown got inside

**Comment by ShadowDeath6** [comment]
> put them in turrets

they would be mech only, so you can't use them like regular guns.

**Comment by ghost** [comment]
the issue is that not only would it be good for blob
it'd kill EVERYONE if you printed one of these, even unintentionally, because 40 burn + radblast USA

the better option here is to make standard Xray lasers for mechs

instead of heavy laser xrays

**Comment by ShadowDeath6** [comment]
The only problem with having it fire standard X-Rays is that the firing rate for mechs is outclassed by sheer spam of regular weapons. I guess regular ones would work pretty similarly, though.

**Comment by Stealthkibbler** [comment]
All mech weapons fire at a slower rate than their hand held counterparts, even the solaris laser cannon fires much slower than a laser cannon printed from R&D. This is because when using them you're in a giant mech, you're extremely resistant to almost all damage and you can wear a hardsuit inside the mech to improve your internal armor and damage resistance.

**Comment by ShadowDeath6** [comment]
Against a blob, the slowness of a mech is almost always what kills you since the blob can run up and hit you like 10 times before you can get a shot off.

**Comment by Greatbigben** [comment]
is this getting approved? or not?

**Comment by FluffySurvivor** [comment]
it doesn't have to necessarily double the damage

making the bolt travel a longer distance works too

**Comment by Time-Green** [comment]
Just make it admin only?
