### ISSUE TITLE
Aghosting with tickets

### ISSUE THREAD

**Issue by Wardog390** [yogstation13/yogstation-classic#558]
### Expected Behaviour

when Aghosting out of body not have to refresh tickets to fix replies sent to players.
### Actual Behaviour

if you Aghost out replies do not show up in ticket for admin sending and do not flash out in a players screen, but player can still see your response in chat, unsure if in ticket aswell.
### Steps to reproduce the problem
1. Aghost
2. Respond to a ticket

(formatted this properly enjoy)

**Comment by ShadowDeath6** [comment]
it's super annoying when it doesn't make any noise and doesn't show up in chat, just the popup

**Comment by Stealthkibbler** [comment]
This is actually a pretty big deal, I had a situation where I had banned a player because he couldnt see my messages and I couldnt see his in the ticket. Should be fixed ASAP.

**Comment by Greatbigben** [comment]
is this merged?

**Comment by Wardog390** [comment]
I'm unsure if this has been merged @DavidEdwards

**Comment by DavidEdwards** [comment]
Matsu had an issue with this, he was going to make a report, then he tried again next round and it had no issue. Wardog, could you test this again?

**Comment by Wardog390** [comment]
To clarify and this is replicate-able AFAIK , if you have an open ticket and then aghost for whatever reason and send a reply, the message does not show in the ticket for the sender and will continue unless the ticket is refreshed.
i did it by accident again yesterday.
