### ISSUE TITLE
Tesla makes objects glitch out

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#565]
When an object that gets shocked by the tesla sends another bolt out, it makes the object face whatever the bolt goes to, which ends up with air alarms and lights floating in the air.

**Comment by Greatbigben** [comment]
is this confrimed?

**Comment by Groudonmaster** [comment]
I've had this occur with windoors sometimes so yeah confirmed

**Comment by AsV9** [comment]
New tesla is nicer to objects, I believe this has been fixed.
