### ISSUE TITLE
New MC lag removal

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#566]
https://github.com/tgstation/-tg-station/pull/16089

We should implement this.

If someone takes it on, please set yourself assignee or ask me to set it.

Bear in mind, I have already changed our MC to do something similar to this. However, MSOs version does it much better. So our MC will not match up with theirs entirely.

**Comment by oisin100** [comment]
I could take a look if you like. I thought cruix was working on this already though..

**Comment by ToGWtF** [comment]
Oh god I saw this earlier, it was beautiful

**Comment by oisin100** [comment]
Alright, Illl start working on it. It will take a bit to port since /TG/ subsystems are quite different than our own.

**Comment by Super3222** [comment]
> Alright, Illl start working on it. It will take a bit to port since /TG/ subsystems are quite different than our own.

:+1:

**Comment by oisin100** [comment]
#574
