### ISSUE TITLE
Blast shutters at Labor Camp do not toggle when selected by player using the button

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#571]
### Expected Behavior

Press the button inside the NW security room at the labor camp, privacy shutters close to prevent people from breaking in and calling the shuttle back and forth immediately.
### Actual Behavior

Button appears to toggle as per usual, privacy shutters do not close. Tested with Security, Warden, and HoS.
### Steps to reproduce the problem
1. Select a security or command role with access.
2. Click the Privacy Shutter button in NW room of Labor Camp.
3. Watch as nothing happens to prevent people from recalling the labor shuttle immediately.

**Comment by DavidEdwards** [comment]
@yogstation13/initiate-coders perhaps a good task for one of you?

**Comment by ToGWtF** [comment]
I see the problem. The blast doors are labled "laboroffice" but the button is "labor"

**Comment by ToGWtF** [comment]
I see the problem. I'll try to fix

**Comment by Greatbigben** [comment]
Merged and closing
