### ISSUE TITLE
Sleepy pens supposedly have 2 uses instead of 1.

### ISSUE THREAD

**Issue by Ephemeralis** [yogstation13/yogstation-classic#575]
### Expected Behaviour

Sleepy pens should only be able to be used once on an organic target ever, before being rendered useless.
### Actual Behaviour

Sleepy pens can be used twice, either on the same target, or once on the initial target and then again on the second target.

This was not ever intentional and greatly inflates the value of the pen as a traitor item.

**Comment by ShadowDeath6** [comment]
I think they were supposed to be 2 uses.

**Comment by ToGWtF** [comment]
I don't think so. I can't recreate this though

**Comment by Greatbigben** [comment]
is this confirmed?
