### ISSUE TITLE
Changeling ghost bug.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#58]
Step 1: Monkey or lesser form.

Step 2: Automatically ghost then get cremated because of it.

Also happens with genetic monkey syringes. Seems to happen if they're moving at the same time as they transform.

Should also mention it's really fucking hilariously abusable by xenobiology because if you click the headslug with a setinence potion and the ling's ghosted you get a pet headslug that can burst into a pet changeling, as you can with the gold slime thing.

**Comment by Super3222** [comment]
This was fixed. @george99g <3

**Comment by george99g** [comment]
Closing this then.
