### ISSUE TITLE
Borers die to explosions while in their host

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#582]
### Expected Behaviour

Be invincible while inside a host.
### Actual Behaviour

Host gets hurt, not killed by an explosion, and the borer dies while inside
### Steps to reproduce the problem
1. Be inside a person
2. Person gets hit by an explosion
3. Borer dies.

**Comment by Super3222** [comment]
If the explosion is strong enough to do enough damage to kill the host, than imagine their skulls caving in and crushing the parasite.

Though that's just a realistic approach, I'm not sure if they were expected to survive or not.

**Comment by AsV9** [comment]
I'm calling `feature`

**Comment by ShadowDeath6** [comment]
They were originally intended to survive anything that doesn't completely obliterate the host's body. And if the skull caving in would kill the borer, it would break the brain and make the body uncloneable.

Also remember that this isn't even high yield bombs, it's just regular bombs like minibombs or grenade launchers that do this as well.

Hell, this might even be critical since the new borer meta turns into "run to chem and make a 100u potassium+water grenade to kill the borer and just get healed scot free."

**Comment by faultlesselm16** [comment]
didnt he say that the explosion didn't kill the host while it killed the borer and if so then that may be a bug

**Comment by oisin100** [comment]
It wasnt intended.... But im gonna call this a feature... I should probably make the dead borer get kicked out of the body though.

**Comment by ShadowDeath6** [comment]
Fix merged, woo
