### ISSUE TITLE
Use gibs to clonepod people

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#584]
### Expected Behaviour

You can extract the blood from gibs and use it to clone someone in hydrophonics
### Actual Behaviour

Gibs are empty

**Comment by Cruix** [comment]
This is intentional, gibbing is difficult to do and designed to permanently take a player out of the game, unless they have their genetic data stored somewhere beforehand.

**Comment by Time-Green** [comment]
Ah ok. Thought it was just an oversight

**Comment by ShadowDeath6** [comment]
But it's literally their organs and stuff on the ground, it's not like there's not blood inside the bloody remains of their body.
