### ISSUE TITLE
NOTICE TO CODERS

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#585]
I had a discussion with TFP. We will start creating issues for any projects we start that are not covered by an issue already.

Two examples:
1. If you are fixing a bug that is already noted in our issues list, then you do not need to create a new issue. Simply reference that issue in your PR as usual.
2. If you are working on something NEW, either a completely new feature or addition to current features, you need to make a new issue. That issue should be a basic outline of the functionality you intend to implement. This gives our players more of a hand in guiding the direction of the code base.

If for whatever reason, you require secrecy in your code (if you are trying to surprise the players for example) then contact me about it.

**Comment by Notamaniac** [comment]
Can't you just have the discussion in the PR instead rather than making a new issue on it?

**Comment by DavidEdwards** [comment]
A PR is created upon work being finished.

I don't want coders to spend days writing something, only to be disheartened later on.
