### ISSUE TITLE
DA Preference

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#587]
### Expected Behaviour

RNG traitor.
### Actual Behaviour

RNG double agent.

Anyway. A similar issue, #493 was taken down which asked for DA to be removed. However in this issue the main focus is to make it a separate preference.

I know that some people of this community love DA, but some us dread it on the other hand. Sometimes we don't always just want to kill a guy and than wait in a closet until the shuttle is called. 

Though I am not saying DA is completely bad, in some cases it's actually a pretty fun and engaging mode. However if a player wants to play classic traitor, than they should be able to do that without worrying about getting DA.

Other Links:
https://forums.yogstation.net/index.php?threads/double-agent-needs-a-different-preference-than-traitor.3438/

**Comment by Time-Green** [comment]
Please do add it. It is the reason I have traitor disabled. I fucking hate DA

**Comment by Stealthkibbler** [comment]
one day...one day...

**Comment by ShadowDeath6** [comment]
remove DA >:^(

**Comment by ShadowDeath6** [comment]
> not closing merged issues

**Comment by Cruix** [comment]
> > implying coders aren't lazy shits
