### ISSUE TITLE
Borers remove the gang hud

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#589]
### Expected Behaviour

You get infected by a borer and are still a gang.
### Actual Behaviour

You lose your gang hud. You wont see your Gangs G and the gang wont recognize you either. But you still are a gangsters.
1. Become gangster
2. Get borerered
3. Get killed by your own gang\
   (He does not need to assume controle)
   I think its a glitch caused by the borer hud. Not sure

**Comment by oisin100** [comment]
Ah, I overlooked that... Sorry...

**Comment by oisin100** [comment]
I could possibly move the borer hud to the left hand side of the players head instead of the right.

**Comment by oisin100** [comment]
Fixed in #603

**Comment by Cruix** [comment]
This happened again to a cultist. He was still a cultist, but lost the hud icon, confusing his fellow cultists. I de-culted and re-culted him, and this seemed to fix it. However, the borer left him, and he lost the hud again, and was subsequently slaughtered by his fellow cultists.

**Comment by oisin100** [comment]
Strange... Ill take another look.
Possibly related to #632

**Comment by Cruix** [comment]
Relevant ticket stuff:
12:40:24 - penguinfisher - okay cruix it worked for a little bit but I was slaughtered cuz it broke again i guess.
12:40:24 - penguinfisher - Ticket created by PenguinFisher
12:40:41 - Cruix - Did the borer take over again?
12:40:46 - PenguinFisher - No. The borer was ejected.
12:41:06 - Cruix - Probably the removal of the borer hud messing things up
12:41:15 - PenguinFisher - I guess. To gihub!
12:42:08 - Cruix - There is an old issue about this, I will reopen it
12:42:17 - PenguinFisher - Okie thank you
12:42:31 - PenguinFisher - As a note: I can see everyone else´s hud but they cant see mine
12:43:12 - Cruix - Can you see yours?
12:43:15 - PenguinFisher - No.

**Comment by Greatbigben** [comment]
fix is incoming for this

**Comment by AsV9** [comment]
Assuming this is fixed.
