### ISSUE TITLE
Cult bug.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#59]
Step 1: Draw a sacrifice rune.

Step 2: Place a monkey on the rune.

Step 3: Sacrifice the monkey.

Monkey doesn't dissapear but drops a soulstone. Click the monkey with a soulstone and as usual for soulstones it offers the shade to ghosts. Thus, infinite shades can be made from one monkey.

I've only tried it once but holy fuck.

**Comment by Super3222** [comment]
I tested this. I drew a sacrifice rune, placed a monkey, tried to sac them. A soul stone dropped, and after a split second the monkey gibbed and the soul stone dissapeared. It may have been fixed already.

**Comment by ghost** [comment]
Soulstone still shouldn't be provided afaik.

**Comment by AsV9** [comment]
I tried fixing this and got even more confused..

**Comment by X-TheDark** [comment]
Could not reproduce locally with latest master build - monkey is gibbed without soulstone. 

Will continue to try to reproduce.

**Comment by BadminBen** [comment]
please confirm testing results so this issue may be closed

**Comment by ghost** [comment]
Closing.
