### ISSUE TITLE
One more hardsuit in engineering

### ISSUE THREAD

**Issue by mitchellduttry** [yogstation13/yogstation-classic#590]
### Expected Behaviour

Players use the hardsuits for engineering jobs and put the suits back when they are done with them.
### Actual Behaviour

Players take the hardsuits for their own personal use.
### Steps to reproduce the problem
1. Start the round.
2. Player takes the suit and never returns it.
3. Other engineers cannot complete their objectives.

**Comment by mitchellduttry** [comment]
I always play as an engineer; I love the job, it is always fun to me. I always want to hook up all the solar arrays to the station but whenever I go to get a hardsuit they are both missing. I message everyone in engineering but they never return them, end up dying, or a drift in space. Could we have one more hardsuit in secure storage that is only authorized by the Chief Engineer or the AI.

**Comment by Super3222** [comment]
Nice job :+1:

This could be done, but at the same time it seems like an IC problem.

We could add to the map a space suit crate (which carries the old timey space suit you can buy from cargo), which requires EVA access. I believe the engineers wouldn't be able to open it themselves.

But anyway, if this isn't a recurring problem each round than you could try ordering the space suit crate from cargo or getting one from EVA.

P.S. if any engineer keeps going space exploring with the engie hardsuit each and every round than I suggest telling an admin about it so they can get jobbaned.

**Comment by mitchellduttry** [comment]
I think I will try ordering a space suit crate from cargo. And If the engineers keep taking the suits, I'll let the admin know. Thank you, @Super3222

**Comment by FluffySurvivor** [comment]
Yes, more hardsuits :+1:

**Comment by ToGWtF** [comment]
Against. Makes it too easy for every engineer to grab a hardsuit and start making armory heists from space.

With only two suits, you can at least narrow down who the perp is by finding who has the second suit

**Comment by Universum01** [comment]
Maybe a little complex but i think perhaps just have the suit storage logs who takes the suit out, it can log to one of the console in that same room. Then at least your can still have 2 and if there both missing you know who to talk to/ tell the CE about. 

As it is all you can do it call out Who took all the hardsuits and hope someone speaks up and does not ignore you because they like to feel safe in it.

**Comment by Greatbigben** [comment]
against this. will close in 24 hours if not futher comments
