### ISSUE TITLE
You can breathe any gas as if it were oxygen

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#592]
Reported by Adam.
### Expected Behaviour

You die of oxyloss when you are breathing from air that does not have enough oxygen in it.
### Actual Behaviour

The checks for species that breathe non-oxygen gasses think that the fact you don't breathe those gasses means you are able to breathe where you are.
### Steps to reproduce the problem

Spawn in as atmos tech.
Fill a tank with pure N2.
Don your hardsuit and jump into space.
Breathe forever because you don't consume n2 but you also don't take oxy damage.

**Comment by ghost** [comment]
yay merged
