### ISSUE TITLE
Make Nukies Great Again

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#596]
### Expected Behaviour

Nukies win by being competent
### Actual Behaviour

Keekmando the Medical Cyborg "finds" the syndie shuttle and spaces the nuke 3 minutes after they arrive because they announced war.

or

Baldy McOnlyplayedforthreedays steals an EVA suit and waltz's into your shuttle to find himself a 10mm pistol that convineintly goes past your eshields and waits in a locker for you to return to your shuttle

or

I find your shuttle and bomb the fuck out of it by putting a proxy-bomb sensor inside your front door to kill you and your shuttle
### Proposals

Proposal 1.
Issue #386 
     - Possible addition, Syndie nuke anchors can be cut with an extremely long (120+ second) action timer with a welding tool. No one sets the timer above 60 seconds anyway, so this is no easy way to force a minor victory but it is a legitimate threat to nukies who get cocky and set the timer to 5 minutes before returning to their outpost for celebratory drinks

Proposal 2.
Make Cayenne useful. Give Cayenne mega space carp stats(debateable) and make it attack anyone/thing not wearing an Agent ID or without a syndicate implant. Can either be used to defend the syndie shuttle, or brought as a free weapon/distraction.

Proposal 3.
Make the walls of the shuttle Rwalls, so they can't be instantly RCD'd into and robbed.

Proposal 4.
Non-syndicate cyborgs can no longer interact with the Syndicate shuttle door button, or the console to move the shuttle.

Proposal 5.
We put some guns on the fucker
![](https://i.gyazo.com/f90bebeac55d66c27af19ca20eb27c06.png)

**Comment by ShadowDeath6** [comment]
Put a turret on the wall below the locker in the bridge so it can shoot at people trying to come in from the doorway. (symmetry is for cucks)

Add all these options pls :^)

**Comment by Super3222** [comment]
I'd agree with turrents on the syndicate ship. Enough turrents that it could actually defend every point of it.

Also changing the walls into reinforced walls would help, but would not stop people from thermiting in.

Therefore why we need turrents, and lots of em.

**Comment by ToGWtF** [comment]
I don't want the turrets to be an instant kill. Having more than 2 on each side means you get hit with 3+ bullets at once, their range is basically view-distance iirc. Its more of a deterrent, as with all my proposals. Enough so that you would have to have either a jetpack or a some other propellant to change your direction in space, and approach it from the back. 

Could possible lower their range/firerate but they have no cover opening animation so they fire virtually the second they target you. 

Another possibility is the turrets are only activated upon calling war, so they _will _be a great threat

**Comment by ghost** [comment]
Rwalls is stupid.

Everything you just said is stupid EXCEPT-

Disabling AI control on the button-

And turrets.

Add the turrets to the outside of the shuttle so that they can aim at any area, no blindspots.

You can still kill them with laser fire ect, but people can still legitimately break in, just with more organization and difficulty than prior.

Also make the syndi shuttle walls bombproof, so that setting off a bomb won't annihilate the shuttle console and render it GG-You'd have to get into the syndi shuttle to bomb it.

**Comment by ToGWtF** [comment]
nah, thats too many turrets. having them like this still means you have to get behind it rather than just jumping from station-side to land right at the door

**Comment by killerx09** [comment]
Well Keek is banned, so issue resolved?

**Comment by Super3222** [comment]
> Well Keek is banned, so issue resolved?

No

**Comment by ShadowDeath6** [comment]
Somebody do this reeeeee

Borgs 2op pls nerf nuke spacing

**Comment by X-TheDark** [comment]
Since Proposal 5 has been implemented, should this be closed or are there other proposals from the list that should be added?
