### ISSUE TITLE
Xenobiology Smart Fridge

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#597]
### Expected Behaviour

Screwdriver a Slime fridge to mess with wires
### Actual Behaviour

It turns invisible

Refer to #304 and #302 
I'll fix in the same way after work tomorrow, no actual need to screwdriver them anyway as you cannot rebuild them if they are taken apart

**Comment by ShadowDeath6** [comment]
smart storages have no maintanence mode icon state, this is probably the reason.

**Comment by Notamaniac** [comment]
Can't smart fridges be upgraded?

**Comment by ShadowDeath6** [comment]
Yes, but it doesn't do anything.

**Comment by ToGWtF** [comment]
If you use the Bluespace Rapid Part Exchanger it just deletes all items in the smart fridge. Good way to piss off a bartender.

**Comment by Greatbigben** [comment]
merged closing
