### ISSUE TITLE
Simple mobs cannot speak

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#598]
### Expected Behaviour

Slimes you sentient potion call you Senpai.
### Actual Behaviour

They actually can't talk at all.

**Comment by ShadowDeath6** [comment]
:')

**Comment by oisin100** [comment]
This was intended.

**Comment by nazitra** [comment]
Slimes at least should be able to speak, otherwise you can't tell if giving commands or saying 'hello slimes' works on the nonsentient ones.

**Comment by ghost** [comment]
I don't know if this was changed, but Minedrones can't speak at all.

**Comment by ToGWtF** [comment]
> Slimes at least should be able to speak, otherwise you can't tell if giving commands or saying 'hello slimes' works on the nonsentient ones.

Or you can't tell if they are actually sentient/ they cant tell you they are
No one can hear slimes scream "wait, i'm alive dude"

**Comment by oisin100** [comment]
You can still use Emotes.

**Comment by nazitra** [comment]
Slimes can't use 'me' emotes.

**Comment by oisin100** [comment]
No simple mobs can. You need to use *nod *shake and *flip to prove your sentience.

**Comment by Cruix** [comment]
Not an intended feature, I broke this when I added the ability for simple mobs to understand the human language but not be able to speak it. 2 line fix is being tested as we speak.

**Comment by ghost** [comment]
and now there's a fix yay
