### ISSUE TITLE
NTSL breaks borg radio 

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#600]
### Expected Behaviour

Make NTSL and borgs can hear and talk in radio
### Actual Behaviour

Borgs can still talk in radio, but Cant hear any of it.
### Steps to reproduce the problem
1. Upload NTSL script
2. Be borg. and rip
   Even if disabled. Borgs still wont hear it. I had to drag a radio behind me

**Comment by Cruix** [comment]
I cannot reproduce this. Was your speaker enabled? Do you know exactly what script was uploaded?

**Comment by Time-Green** [comment]
My speaker was enabled. Everyone could hear me but I couldn't hear them.
It happened twice in a row.
I think it was the script you used

**Comment by Cruix** [comment]
I haven't uploaded a tcomms script in ages

**Comment by Time-Green** [comment]
Oh, then it was Oisin sorry,

**Comment by ShadowDeath6** [comment]
never heard of this happening before. What did the script do?

**Comment by oisin100** [comment]
> What did the script do?

Pretty much everything.

Ill take a look at my updated NTSL code. Maybe i fucked up somewhere with my $uuid variable?
