### ISSUE TITLE
Shadowpeople as a playable race from round-start

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#607]
Now that they're finally able to see in the dark, shadowpeople are actually viable to be a playable race. Obviously they'd be a much harder race to play than players are used to, similar to the hardmode plasmaman race on tg's codebase. The only foreseeable problem with this is the way that shadowpeople interact with emergency shuttle turfs, since they technically count as lit tiles.

**Comment by Time-Green** [comment]
Emergency shuttle tiles don't count as lit because phytosians die without their PDA light.
And no.

All what its going to cause is lights over the whole station being destroyed.
So everywhere will be dark. 
This is a terrible idea.

**Comment by Greatbigben** [comment]
against this for now maybe in the future this can be looked into again

**Comment by Greatbigben** [comment]
will close in 24 hours if no further comments

**Comment by Greatbigben** [comment]
Closing
