### ISSUE TITLE
Make tesla engine harder to set up.

### ISSUE THREAD

**Issue by penguinfisher** [yogstation13/yogstation-classic#609]
Right now all you gotta do is move one thing over and leave the PA on all round to make infinite power to the station; while lord singulo needs radiation collectors (that can potentially ruin engineering through plasma leaking) and someone to baby sit it while he grows up big and strong.

With the Tesla all you gotta do is flip the on switch and BLAM-O! we done did it.

Suggestion: Start tesla coils + grounding rods somewhere else in engineering and set them up manually. It has potential to ruin engineering just like the sing setup process does.

**Comment by ToGWtF** [comment]
I agree. There should be more risk to the Goofball engine. Random events that require attention, more effort required to set it up.

**Comment by TehFlaminTaco** [comment]
I like that it's set and forget. I'm personally apposed to the station also trying to kill everyone whilst ten or so traitors or whatever is doing it with them.

**Comment by ShadowDeath6** [comment]
singulo is like 5 minutes of prep compared to tesla's 2 minutes, and the plasma collecters have never needed refilling as long as I've played.

I'd be happy with making the rods start somewhere else so it requires more work.

remove tesla though :^)

**Comment by TehFlaminTaco** [comment]
Fak u.

Nah but seriously, I like a risk free tesla.
For me, Singuloth was just a hassle that resulted in too many new engineers fucking over a traitor's round and getting themselves job banned.

If people want rogue tesla, then they sabotage the tesla.
EZPZ.

**Comment by EMT321** [comment]
Whats with the necessity for a power source that is gonna kill you because fuck you engineering?

Frankly, I find it takes just as long to set the sing as it does the tesla, with the only appreciable difference is that you wont get job-banned because someone forgot to change the setting on the PA.

**Comment by penguinfisher** [comment]
There's literally no way to not fuck up engineering when you use tesla right now. All I want is for the coils and rods to start somewhere else so there's might be a _chance_ that they'll fuck it up. 

With sing you can release plasma all over engineering and ruin everything- or you can fuck up coils and ruin everything.

There's no reason to not use tesla right now as it's low effort and ez mode.

**Comment by Greatbigben** [comment]
not much you can add to it other then moving items around that i can think of.

Possibly make it so the rods over heat once in a while and you have to repair it. Special grounding methods have to be taken so you dont get fried. 

just like in real life!!!! 

(meh just move the rods and call it a day)

**Comment by penguinfisher** [comment]
That's all I want is the rods and coils to be moved. 

No plasma = sing loose. 

Coils not wired right = Tesla loose 

Ez balance

**Comment by Greatbigben** [comment]
is this in progress?

**Comment by penguinfisher** [comment]
I'd totally do it of someone would send me a basic guide or some shit on mapping.

**Comment by Greatbigben** [comment]
Mapping ain't that hard honestly just fuck with it and see what happens
