### ISSUE TITLE
Zombies sometimes spriteless.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#61]
Step 1: Get infected.

Step 2: Zombify.

Step 3: Have no sprite except for your underwear.

Please remove being chased by a pair of panties and a bra trying to eat your flesh, ERP is not allowed

**Comment by Groudonmaster** [comment]
Can confirm, generally only involving the asian and oriental skin types but it may apply to any skin that isn't caucasian or black because we don't have icon states defined

**Comment by BadminBen** [comment]
had this problem last night when random zombie event popped up

**Comment by Hydre** [comment]
> Step 3: Have no sprite except for your underwear.

I don't see the issue

**Comment by Super3222** [comment]
This may or may not have been fixed in the recent update. I tried testing it myself by choosing each race, getting zombified, and not turning invisible.
I had a look through the zombie.dmi file and found nothing out of the ordinary.

**Comment by ghost** [comment]
happened just today, Captain didnt' know what was happening and ahelped 'WHY ARE PANTIES BITING ME'

**Comment by DavidEdwards** [comment]
Fixed finally.
