### ISSUE TITLE
Let ghosts enter empty soulstones

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#617]
Title. Lets ghosts enter cultist soulstones similarly to posibrains, which in turn lets the ghosts play as constructs.

Additionally, let players ghost in and out of soulstones so they can chill out in deadchat instead of either ghosting which permanently fucks them, or suffering in a stone for all eternity. Cultists could not use soulstones without an active person in them to make constructs, obviously.

**Comment by ToGWtF** [comment]
Eh. Letting them ghost back and forth is meh since you can just keep a soulstone in your pocket to feed you info,  but you can already astral journey anyway so ehhhhh

**Comment by ShadowDeath6** [comment]
obviously it would be treated the same as it is for posibrains (metagame).

**Comment by Super3222** [comment]
Hmm, I've made up my mind about a few things. I got a plan for this, so I guess I'm claiming it.

On a side note, I don't think ghosts entering soul stones is a good idea. If a cultist WANTS someone to become a construct, they crit/kill them and than hit em with it. Not leave it out in the open like a drone / posibrain.

**Comment by Greatbigben** [comment]
will close when merged

**Comment by ShadowDeath6** [comment]
The ghost wouldn't be able to inhabit the stone without them leaving an empty one on the ground a la droneshell
