### ISSUE TITLE
Giving a revhead a traitor uplink isn't logged.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#62]
It's a default option for revheads to have an uplink, since they used to spawn with one, they can be granted one with traitor panel.

However, this isn't logged in adminchat.

So you get revs running around with sleepypens, emags, and sing beacons, if an admin decides to grant the revheads uplinks.

Probably maybe might want to log that.

**Comment by Cruix** [comment]
It looks like there is a button in the traitor panel to give the revhead an uplink, but it doesn't do anything. Are you sure this actually works?

**Comment by ghost** [comment]
It works. I've done it before when the revhead bug shows up and revheads can't convert people. 

...with prior asking if I could, of course.

Also private testing.

**Comment by Cruix** [comment]
Ah. I was thinking about the "Reequip (gives traitor uplink)" button, which actually does do nothing. You must have been taking about the "Uplink: Give" button.
