### ISSUE TITLE
Not enough engi lockers

### ISSUE THREAD

**Issue by Orelbon** [yogstation13/yogstation-classic#621]
### Expected Behaviour

Enough engineering lockers for all
### Actual Behaviour

only two engineering lockers 
### Steps to reproduce the problem
1. walk into engineering
2. see lack of lockers
3. cry

**Comment by ShadowDeath6** [comment]
This is a mapping issue, honestly. For some reason there are unused lockers with engineering jumpsuits but they aren't on the station so people who transfer to engi can't wear the jumpsuit.

**Comment by Super3222** [comment]
Also, and I've been meaning to make an issue about it, there's no engineering wardrobe either.

Every other department has a wardrobe keeping the departments clothing.

**Comment by Greatbigben** [comment]
there are engi lockers they dont count as wardrobe they are secure lockers

**Comment by Greatbigben** [comment]
ill add more to the map

**Comment by Greatbigben** [comment]
look like this was handled so closing

**Comment by Cruix** [comment]
Don't close it, the PR has not been merged yet. If we keep closing issues as soon as the PR exists, some PRs are going to be rejected and the issues will be forgotten and never solved.

**Comment by Greatbigben** [comment]
it has been merged
