### ISSUE TITLE
Lighting/shadows

### ISSUE THREAD

**Issue by Orelbon** [yogstation13/yogstation-classic#622]
### Expected Behaviour

Shadows /lighting works normally 
### Actual Behaviour

Don't work correctly at all
![bug2](https://cloud.githubusercontent.com/assets/12041669/13897305/75264ae4-ed83-11e5-9450-a69be829a0ef.PNG)
![bug 1](https://cloud.githubusercontent.com/assets/12041669/13897306/7527075e-ed83-11e5-83cd-3b43da274095.PNG)
### Steps to reproduce the problem

Unknown

**Comment by Cruix** [comment]
Eat a battery. Being hungry as preternis makes you go partially blind.

**Comment by Orelbon** [comment]
ill take this into consideration.
