### ISSUE TITLE
Phytosians die in places such as arrivals/escape/syndicatehuttle

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#623]
### Expected Behaviour

Lalala I am not dying and am a happy cabbage lalalala
### Actual Behaviour

OH GOD THE LIGHTNING IS BUGGED ON ARRIVALS AND ESCAPE AND I AM NOT GETTING LIGHT PLS HALP MEEEEEEEEHEHHHHH
### Steps to reproduce the problem
1. Be phytosian
2. Stand in arrivals
3. Die of malnourishment.

**Comment by Cruix** [comment]
Duplicate of #502

**Comment by Time-Green** [comment]
I know, I thought this was forgotten. Since well, it was never fixed

**Comment by oisin100** [comment]
> I know, I thought this was forgotten. Since well, it was never fixed

It hasn't... Just none of us want to fuck with the lighting...

**Comment by ParagonPrime** [comment]
I don't know much about coding, but can't you just edit the map to place in some physical lights and then set them to be invulnerable?

**Comment by Greatbigben** [comment]
ill add some more lights to the map
