### ISSUE TITLE
Add a game config file option to disable Tesla

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#627]
We need to be able to stop players from starting up the Tesla without changing the codebase, and it should be persistable.

It should have an option here:
`config/game_options.txt`

The map can be left alone, but there should be something that "breaks" in engineering that stops the system from working when the variable is set (for example, through game.options.txt).

**Comment by ShadowDeath6** [comment]
one step closer

**Comment by ghost** [comment]
how about admins delete the tesla

**Comment by oisin100** [comment]
> persistable

**Comment by Iamgoofball** [comment]
whats the problem with the tesla

**Comment by DavidEdwards** [comment]
It has been lagging our server to buggery. I want to keep it in as an option, but to keep it out via a config option if we don't want it.

I'd rather that than remove it entirely.

**Comment by Iamgoofball** [comment]
Sorry, what? It shouldn't be lagging. You have the MC lag fix, and the tesla is inherently designed to be less laggy than singulo. Get in the skype chat, I'll start combing over tesla code and seeing what you fuckwits did to my code babby

**Comment by MrsTonedOne** [comment]
https://github.com/yogstation13/yogstation/blob/dev/code/modules/power/tesla/energy_ball.dm#L74

**Comment by ghost** [comment]
jesus christ autism
