### ISSUE TITLE
Switchblade Inital damage

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#629]
### Expected Behaviour

Switchblades do low damage when not extended and high damage when extended.
### Actual Behaviour

Switchblades spawn not extended but with full damage, giving you a 20 damage weapon that fits in your pocket until you toggle it once.
### Steps to reproduce the problem
1. Be gang leader, spawn switchblade.
2. Put in pocket.
3. Take out of pocket and shank a guy without taking the 0.1 seconds to press z to extend it.

**Comment by ToGWtF** [comment]
If you change force = 20 under the initial proc to force = ""   it doesn't register hits until after you open it for the first time to set it to 20, and closing it resets it back to 1 force.   Hacky fix but meh

**Comment by Cruix** [comment]
No reason to make it blank, just make the initial force 1 and throw force 5.
