### ISSUE TITLE
AI Switch to Network Labor not correct

### ISSUE THREAD

**Issue by Universum01** [yogstation13/yogstation-classic#631]
When AI I tried switching to network to Labor and it took me to CMO office, i cannot get to the labor camera network.
I was MALF at the time if that had anything to do with it.
https://youtu.be/9hQNI6O9OWk

**Comment by ShadowDeath6** [comment]
I think you need to click 'show camera list' so you can actually access the cameras on the network.

**Comment by Universum01** [comment]
Yes when your AI you can do that and go through the camera list to find the one one want( of the 100's) just thats not what this post is about, its not about ways around this bug, its about posting this bug so it can be fixed :)

**Comment by Wardog390** [comment]
Effectively the AI cannot jump to labour, i know this is a problem I've tested it myself.
