### ISSUE TITLE
medical HUD stops working

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#632]
### Expected Behaviour

Human medical HUD works.
### Actual Behaviour

Human medical HUD stops displaying health several times in a round, has to be taken off and put back on again.
### Steps to reproduce the problem
1. Equip medical HUD as Medical Doctor.
2. After a while, it stops working for some reason.
3. Become sad.

**Comment by ParagonPrime** [comment]
Same applies to sechud.

I've actually unwittingly arrested a few people under suspicion of them not appearing on the sechud (which, I believe, is a trait Morphs have)- only to remove it and replace it and the icons suddenly reappear.

**Comment by Cruix** [comment]
Is it just after a long time, or is there something that needs to be done to trigger it, such as disconnecting and reconnecting?

**Comment by 00aquir** [comment]
It happens right in the middle of work, as I said, "for some reason". Long intervals enough so that you don't even realize that you no longer see the HUD anymore. Maybe random, maybe when everybody's off the screen, maybe when something else happens, no idea.

**Comment by DavidEdwards** [comment]
Next time you have one on, could you keep a close eye on it? See if you can spot a pattern?

**Comment by 00aquir** [comment]
Of course but when it happened I didn't realize when it disappeared even the second time. Although it was a busy round.

**Comment by 00aquir** [comment]
Hm. I played another round, fewer players, same equipment, nothing happened now.

**Comment by Greatbigben** [comment]
need a study pattern to go off random testing is like finding a needle in a haystack
