### ISSUE TITLE
Labcoats

### ISSUE THREAD

**Issue by Orelbon** [yogstation13/yogstation-classic#635]
### Expected Behaviour

Lab coats would have pockets
### Actual Behaviour

lab coats do not have pockets, even though they are spirited onto the lab coat.
### Steps to reproduce the problem

1.Get a lab coat 
2. Try to put something in it
3. be disapointed

**Comment by ToGWtF** [comment]
They give a suit storage slot for syringes/medical scanners,  so that's kinda a pocket

**Comment by ShadowDeath6** [comment]
They only hold certain things, mostly medical stuff like pillbottles and whatnot.

**Comment by Super3222** [comment]
Not a bug, this is an in-game feature.

Coats/Armors/Hardsuits only allow you to carry certain things. Feel free to close this

**Comment by Orelbon** [comment]
ah ok
