### ISSUE TITLE
Overhaul antag selection system

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#642]
Right,

As we're all aware, the ratios for people being selected for antag is... really skewed. While some people end up antag more often than not (according to Adam, one player has a chance of about **75 percent** of being antag), others basically never seem to get it.

So! Let's overhaul RNGesus a bit and make it more fair. Because let's face it, there's really no logical argument against people having a RELATIVELY FAIR chance of being antag.

Basically, let's make it so that, the more often you're antag, the lower your chances of being antag become- so if you roll lucky twice, you've got a lowered chance on the third time. And vice-versa; if you've had a long streak of being nonantag, you'll have a higher chance of being an antag in subsequent rounds. This also applies within antags themselves; if you've gotten one type of antag a lot, your chances for other types goes up.

Should be relatively simple and is fair to everyone.

**Comment by DavidEdwards** [comment]
The system should be entirely random.

The players list is shuffled / randomized (I think twice even) during the selection process.

I would be open to a check based on previous round(s) "luck". This will involve database work, so I should probably take this one.

**Comment by Time-Green** [comment]
This seems like a really cool idea. And it makes variations more common.

I like it, alot

**Comment by FluffySurvivor** [comment]
I disagree with having reduced chance of antagging in subsequent rounds. That would create really weird patterns of antagfishing, so no. 

Admins should never interfere with things such like antag selection, admins will abuse this to make sure certain players never get antag.

**Comment by Time-Green** [comment]
> increases fluffies cult chance to 100%

**Comment by DavidEdwards** [comment]
I certainly won't let admins change the values. 

It would be a weighted system. 

Whereby:

Each time you antag, decreases the weight. 
Each time you don't get antag, increases the weight.

Capped to a min and max.

It really doesn't need to be more complicated than that.

**Comment by ParagonPrime** [comment]
Okay, let's remove the admin-bus bit entirely, then. DavidEdwards seems to have it, though the min/max should scale with server population/number of antags in the round a bit.

Edited.

Also, Fluff- what's your reasoning? "Weird antagfishing patterns"? All this does is make it so that you can't be the tator three, even four rounds in a row, as I've witnessed with some people. Not even you, necessarily.

**Comment by FluffySurvivor** [comment]
> increase fluffies cult chance to 100%
> uninstall

**Comment by X-TheDark** [comment]
Also, how would this work with having the preference off/quiet rounds? Weight is not changed at all?

**Comment by ShadowDeath6** [comment]
It probably wouldn't influence you since you didn't WANT to be that antag in the first place. 

Now that double agent has a preference this would work pretty well imo

**Comment by DavidEdwards** [comment]
It would only affect people who are eligable in that given selection process. So if you have quiet or no preference, your weight would be unchanged.

**Comment by Greatbigben** [comment]
fluffy always get antag so im all for this

**Comment by killerx09** [comment]
Guess this can be closed now.
