### ISSUE TITLE
improvised weapon - blowdart

### ISSUE THREAD

**Issue by apneaman** [yogstation13/yogstation-classic#646]
### Expected Behaviour

To be able to craft a single use syringe gun from paper+duct tape+pipe. For shooting spitballs at Hos or the odd cyanide dart that would break it upon use
### Actual Behaviour

Find nothing but dodgy swords and a pneumatic cannon for sadists.
### Steps to reproduce the problem
1. Settle for an IED instead
2. Cry myself to sleep in perma

**Comment by ghost** [comment]
Yeah

**Comment by ghost** [comment]
It may prove too powerful, though.

**Comment by apneaman** [comment]
Thats why i think the single use factor is important as a single 15U syringe is fairly harmless and easy to fight back against or call for help. unless its chloral made up in chemistry in that case you most likely have access to a syringe gun anyway.

**Comment by Notamaniac** [comment]
>  a single 15U syringe is fairly harmless

You have no idea.

**Comment by ShadowDeath6** [comment]
> a single 15u syringe is fairly harmless

Except when it's filled with 3u of 5 different traitor chemicals.

**Comment by ghost** [comment]
A single 15u syringe can kill almost anything, even a xenomorph, with the right mix.

Last whisper, any sort of blackpowder + heating mix, phlogistion and napalm, unstable mutagen + neurotoxin, neurotoxin + pleufloradecalin, or even just formaldehyde is going to fuck you six ways from sunday.

Craftable weapons are not a good thing in the first place.

**Comment by apneaman** [comment]
Thanks for the input i understand your point.

**Comment by Greatbigben** [comment]
adam they are good actually for those sneaky tators

**Comment by ghost** [comment]
yeah but it's overpowered

esp in something like rev

**Comment by X-TheDark** [comment]
Perhaps this could go a different direction - make something like a Syringe deconstruct-able into a Syringe Needle that could be dipped into a solution to get 1/2u of that solution (that maybe you could fire from this or apply in melee range).

If you use it on someone (in melee range), they get the "You feel a tiny prick" kind of thing. Basically, a ghetto microhypo that someone can use to sow panic (HELP, LINGS) among the crew or maybe do something clever with a chem or two.

**Comment by X-TheDark** [comment]
Closing this soon enough if no further discussion arises, as there's no consensus as to whether or not this is needed.
