### ISSUE TITLE
Remove PALADIN lawboard from AI upload at roundstart. 

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#652]
Too easy for people to make (force) AI le validhunter meemee, it should require at least minimal work from R&D.

**Comment by ParagonPrime** [comment]
Eh, I kinda disagree with this considering how rarely I see the AI being Paladin'd anyway.

Like, seriously. I almost never see it, even when the station's starting to tear apart. While I in concept support people being made to work a little for their omnipotent Nukeop-destroyer, in practice, this really isn't necessary: AI gets Paladin'd so rarely anyway.

**Comment by ShadowDeath6** [comment]
It's shitty when the powergaming RD or captain comes in to paladin you as AI and gets mad and ahelps you because it's the start of the round and you can't assume they'll upload because meta.

**Comment by ParagonPrime** [comment]
okay so, idea

replace paladin in AI core with corporate and make youse have to do some research for that paladin

fair is fair

**Comment by Notamaniac** [comment]
What's to stop people from simply using purge and uploading freeform laws though?

**Comment by ToveyAyyLmao** [comment]
Everyone is an idiot maybe?

**Comment by ToGWtF** [comment]
Paladin _should_ break AI's, since how can they define evil.  Robocop is better.

**Comment by ghost** [comment]
PALADIN might as well be renamed VALIDHUNT.

It's just an easy to go to lawset for the AI that says 'KILL THE ANTAGS AND DO WHAT SEC/HEADS TELL YOU TO DO' and there are never any issues with it.

Which is boring.

the AI is a tool for the station, not security's pet bitch, and uploading PALADIN basically just makes it an all seeing validhunt eye that gases you with plasma if it sees you with an esword.

**Comment by Alek2ander** [comment]
> It's shitty when the powergaming RD or captain comes in to paladin you 

Well why do you have to be a shitty paladin? You are not forced to validhunt. "Punish" is vague, "threaten" is vague, "innocent" is vague, "evil" is very vague.

**Comment by ShadowDeath6** [comment]
There was some post about silicon policy that said that PALADIN was intended to be lawful good and you can't loophole it to be a dickwad, basically making you subject to the whims of heads/sec since you have to obey the "lawful" force.

**Comment by X-TheDark** [comment]
I'd add the "You are not to kill/harm" (depends on how you want it to work) clause to it, since it's not supposed to kill anyone (although harm could be justified for protection, etc).

**Comment by ParagonPrime** [comment]
Leave PALADIN as it is- but change the rules and such surrounding it.
1. Let the AI define evil a little more loosely. As in, if sec starts being shit, you can punish them by gassing them all with N2O
2. Remove it from upload, replace with Corporate. Give it a research requirement.

Also,

> purging just to upload freeforms
> inb4 AI lasers you to death just as you try and accepts newfound freedom

(though the only time i was ever purged i was pretty nice...)

**Comment by Universum01** [comment]
As someone who plays AI ALOT (AI-Jim) even i get PALADIN'ed im often too busy putting out fires to even do much with it, i does not get much use.

**Comment by Alek2ander** [comment]
Ugh, just leave it. If an AI wants to be shit it will find a way. Paladin still allows you to troll security by punishing evil traitors with bad poetry and ignore that guy stealing the ablative armor because he's not threatening anyone. And if the captain orders you to uphold space law you respectfully refuse because that would mean you support the evil corporations.

**Comment by ShadowDeath6** [comment]
Too bad you get ahelped for not validhunting like a good little robot.

**Comment by ghost** [comment]
Yeah, you get yelled at if on PALADIN and you're not validhunting the shit out of anything per silicon policy.

'WHY ARE YOU BOLTING DOWN THE BRIG'

'Sec is killing people, murder is evil!'

'THEY'rE SEC AND EXECUTING SOMEONE IT'S FINE YOU'RE PALADIN REEEEEEEEEEeeee'

**Comment by ShadowDeath6** [comment]
# REMEMBER THIS IS NOT REMOVING THE PALADIN BOARD FROM THE GAME

This is just making it only available through R&D so you need at least some effort to apply it.

**Comment by Greatbigben** [comment]
fix the conflicts so this may be closed
