### ISSUE TITLE
New Gamemode/Event: Inter-stationary Battle

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#656]
### Gamemode Name:

Inter-stationary Battle
### Gamemode Behavior:

Two stations, possibly Nanotrasen and Syndicate respectively, are poised in a battle. Each round starts with the stations' respective crewmembers arriving in locations on the station. The station would be commandeered by around 2 Commanders, Generals, etc. (Heads of Staff) that would determine strategy and tactics for this battle as well as making sure things don't fall apart and directing internal station work. Roles for sub-command crew members could be communal, so there would be all access for everyone, or individualized roles, like on our current stations, which would require more work to set up.
Each station would have its own map or maybe stay together on one large z-level. Warriors from each station can attack the opponent at any time via hardsuits, shuttles, etc, however it is advised(rule-wise) that they abide by the command orders.
The battle(round) would end when either all members of an opposing faction(station) are slaughtered or when the integrity of a station is reduced to a certain, very low percentage.

This seems like it would be something very large to have in rotation, so it would be good if it occurred at a very low chance or if it was by admin interaction only.
I may assume responsibility for programming this gamemode, but it will be difficult for me.
Open to ideas in the comments.

**Comment by Time-Green** [comment]
Yesyesyesyesyesyesyeysyeysyeysyeysyeysyesyeysyeysyeysyeys

**Comment by Notamaniac** [comment]
I personally don't think gamemodes with a heavy emphasis on ss13's ~~shitty~~  combat system would work out but I could be wrong.

**Comment by ToGWtF** [comment]
Steal-.... I mean port space pods and have giant space battles

**Comment by X-TheDark** [comment]
My biggest gripe is how many players would this need to work out nicely.
Also, while I don't see anything wrong with this, this new gamemode overlaps with Gangs heavily, since you basically kill opposing gang members in that mode.
Truth be told, this kind of thing MAY work out, since we could port something like Space Pods for space combat.

**Comment by ghost** [comment]
It would work smoother now than before considering that Yog now gets around 50-80 people at times compared to the usual 30-50 from before.

**Comment by ParagonPrime** [comment]
@Notamaniac _cough_90 percent of nukeops_cough_

Anyways, this does sound cool. Maybe even have one or two people on each station be a "defector" working for the other side that has to try and sabotage the station they're on to assist the other station.

**Comment by Notamaniac** [comment]
I've got a personal bias against nuke ops gamemode, as ops literally have guns that kill you flat in one click, and either ends up with all the station dead, or nuke ops failing miserably and getting themselves spaced. But yeah personal opinion and stuff

**Comment by EMT321** [comment]
The amount of lag on the station, all of atmos, etc x2. I dont realistically ever see this happening though, the coding would be fairly massive.

**Comment by oisin100** [comment]
> The amount of lag on the station, all of atmos, etc x2. I dont realistically ever see this happening though, the coding would be fairly massive.

I think the server could handle it. As for the coding part it would be quite a lot to do but also not too much at the same time.

As for the gamemode itself it would be pretty cool and fun to play at the same time.

**Comment by DavidEdwards** [comment]
I actually really like this idea.

Two smaller stations on the same z-level. We could have various defensive systems like shields, turrets, all of which don't function at the start.

The hardest part of this game mode would be making the map to go with it.

**Comment by Kmc2000** [comment]
I love this

Want me to map two stations on the same z? 

It would take a while... and id need code help.... but... 

I could probably do it in time

**Comment by ghost** [comment]
It would be great to have your help, KMC. Inevitably it will take a long time.
We could maybe make a new branch and have it contributed to by several members of our development team. If anyone has ideas for this, please contribute by posting your ideas in the comments.

**Comment by Axemeaquestion** [comment]
We could make it two ministrations to reduce lag.
