### ISSUE TITLE
White listing Detective

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#66]
We all know that large group of shitters who play detective for the sole purpose of powergaming the shit out of sec and running around the station nailing anyone in the face with a rubber bullet who dare try to stop them. Hell, the detectives revolver isn't even for making arrest, **He's not allowed to make arrests in the first place.** Just for the sake of all that is holy, preserve the last semi-stable RP role on the station before it falls victim to the graytiding shitlords. 

Oh look, the /tg/ wiki article literally telling what not to do as detective. 
https://tgstation13.org/wiki/Detective

**Comment by george99g** [comment]
What exactly do you want to happen code-wise?

**Comment by shrimptk** [comment]
No one cares about the old suggestions forum anymore, so basically, Whitelist it baby.

**Comment by george99g** [comment]
Which reminds me of #67 which we still haven't got implemented, even after the council vote went through.
We could probably use that to implement this.
