### ISSUE TITLE
Soaked improvised bandages literally do the same thing as normal bandages

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#663]
### Expected Behaviour

Soaked bandages to heal burn, because it's soaked and the first thing you do to a burn is apply cold water
### Actual Behaviour

Heals brute instead
### Steps to reproduce the problem

Literally craft a soaked bandage and watch as it does nothing else that a normal improvised bandage would do

**Comment by ShadowDeath6** [comment]
I thought this was intended so you couldn't heal like all the most common damage in the game, but it would be pretty useful if it healed burn.

**Comment by Notamaniac** [comment]
If it wasn't intended to heal burn, then why was it added in the first place?

**Comment by Super3222** [comment]
Soaked bandages are suppose to heal burn

This is a bug

**Comment by Notamaniac** [comment]
Yeah looking at the code it's there, but the table craft recipe for it makes a normal improv bandage. Pretty easy one line fix, just change it  to

`/obj/item/medical/bandage/improvised_soaked`

in recipes_medical.dm
