### ISSUE TITLE
Revenants up and die at random when using abilities

### ISSUE THREAD

**Issue by nazitra** [yogstation13/yogstation-classic#664]
### Expected Behaviour

Be spoopsy ghost, fly around shocking lights and making clonepod soup.
### Actual Behaviour

Die even if you have more than enough essence to use your abilities. No clonepod soup for you.
### Steps to reproduce the problem
1. Be ghost
2. Pray to RNG, become revenant
3. Die, rage to the heavens

**Comment by Time-Green** [comment]
I fully agree. I had enough essence and died the same way. And then Donny took it....

**Comment by nazitra** [comment]
...only to die doing the same thing, trying to shock lights. >:(

**Comment by ShadowDeath6** [comment]
> not using nothing but transmit to fuck with people

**Comment by Wardog390** [comment]
please fix.

**Comment by Time-Green** [comment]
Ok, I had 100 essence and bought defile for 30e
And then died. Like whhhyyyy?????

**Comment by Greatbigben** [comment]
is a fix in progress?

**Comment by penguinfisher** [comment]
can confirm that defile is fuked. I had 45E and bought defile for 35 after having all my other abilities and just up and died.

**Comment by X-TheDark** [comment]
This might be related to some lag issue, as it's impossible to reproduce on a local server (tried for 1 hour). So currently, I'm not sure if this can be fixed, as the reason for this cannot be isolated. Will try to find something.

**Comment by X-TheDark** [comment]
Unfortunately, this seems to be just plain impossible to reproduce locally. Please reopen the issue **if you find any additional information under what circumstance beyond "at random when using/buying abilities" this happens.**
