### ISSUE TITLE
Use electrified doors/grilles as ghetto defib

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#665]
### Expected Behaviour

Throw corpse against electrified door/grille, have decent chance of defibrillating them in a super robust way
### Actual Behaviour

Throw corpse against electrified door/grille, have no chance of defibrillating them in a super robust way, cry.
### Steps to reproduce the problem
1. Kill person
2. Throw against electrified door/grille
3. Realize ineffectiveness
4. Cry

**Comment by ghost** [comment]
that doesn't work because defibs don't work like that

you can't just wrap jumper cables around your cock and expect to get revived

defibs are a precisely timed electric pulse applied to the location of the heart

throwing someone into a shocked door is just making them bacon

**Comment by Notamaniac** [comment]
> you can't just wrap jumper cables around your cock and expect to get revived

10/10

**Comment by ToGWtF** [comment]
> you can't just wrap jumper cables around your cock and expect to get revived

That's just Tuesday night

**Comment by ParagonPrime** [comment]
> adam
> gets pissed with me when i make suggestion for realistic stuff because "ss13 isn't realistic mang"
> gets pissed with me when i make suggestion for nonrealistic stuff because "ss13 gotta be realistic mang'
> what

**Comment by ShadowDeath6** [comment]
He gets mad at you for shit ideas that he doesn't like and makes realism excuses to validate that dislike

**Comment by Wardog390** [comment]
i want this.

**Comment by FluffySurvivor** [comment]
fuck no. 
This would make reviving people much more common and easy thus fucking over balance. Now every "robust" shitlord assistant can just instant defib corpses he finds in maint. Bombing genetics/stealing defibs as antag will become useless. 

BALANCE > REALISM

**Comment by Greatbigben** [comment]
Closing in 48 hours if no further comments

**Comment by Greatbigben** [comment]
Closing
