### ISSUE TITLE
Add drone shells to the station z-level

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#668]
Ticket:
12:03:02 - Codeyday - What's the reason for no maintenance drones on the normal station at round start? I love being maintenance drone and just wandering around fixing things but every time I gotta grab the one on derelict and then ask if someone'd be so kind as to TP me there since robotics never make them

12:04:12 - Halueryphi - I mean robotics could just make it.

12:04:19 - Codeyday - But they neverrr dooooo

12:04:25 - Halueryphi - Well that sucks :P

12:04:40 - Codeyday - And since the only people able to be drones are observers/ghosts, there´s no way for them to exactly be like "hey maybe you should make some drones"

12:04:56 - Cruix - You can get from the derelect to the station

12:05:01 - Cruix - There is a teleporter you can get to

12:06:15 - Cruix - Do you think there should be some on the station at round start?

12:07:12 - Codeyday - Yeees, only like one or max two or people would purposefully observe every single round just to be one, but sometimes it´s nice to be able to have that little impact in the round without having to worry about being murdered, having to murder someone, getting your job done (as much), RP with people, etc.

12:07:39 - Cruix - I'll make an issue on Git for it

12:07:43 - Codeyday - Neato :D

**Comment by Super3222** [comment]
Bad idea, I'm actually against this.

Drones shouldn't be on the z level for a number of reasons. One of them is already listed, they are an item of RESEARCH. If you do not do the research and the engineers are incompetent, don't expect things to come so easy to you. Items that are obtainable by a branch of the station that's literal purpose is to make everyones lives easier shouldn't be handed out at roundstart.

I typed some more, but I ended up deleting it all so..

**Comment by Notamaniac** [comment]
Not to mention you can use the drones on the derelict to get onto the station and then do R&D so you can make more drones

**Comment by Greatbigben** [comment]
against this

**Comment by Silvaplex256** [comment]
I'm against this. Any half-decent R&D crew can research drones in less than 10 minutes.

**Comment by FluffySurvivor** [comment]
Against. Drones generally abuse their laws to fuck with people, so no.

**Comment by ShadowDeath6** [comment]
> not using secret powergane jutsu to teleport from derelict to station

**Comment by Greatbigben** [comment]
Will close in 24 hours if no further comments

**Comment by Greatbigben** [comment]
Closing
