### ISSUE TITLE
Head role whitelist

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#67]
Add an Ultra preference for head roles to people who have been accepted into a whitelist.

**Comment by killerx09** [comment]
(Also AI)

**Comment by BadminBen** [comment]
gonna need to work out the white list first

**Comment by george99g** [comment]
We kind of need the code to put the whitelist into, before we get the actual whitelist.
Everything will be normal even if nobody is on it.

**Comment by Hydre** [comment]
Eeeh didn't we once have heads jobs whitelisted?

Could've been a different server but I don't really think this is a good idea.

EDIT: Unless you mean by ultra preference that whitelisted just get priority over non whitelisted

**Comment by george99g** [comment]
> EDIT: Unless you mean by ultra preference that whitelisted just get priority over non whitelisted

Exactly!

**Comment by Hydre** [comment]
Oh well that's a good idea

**Comment by BadminBen** [comment]
is this being worked on?

**Comment by DavidEdwards** [comment]
It is quite high on my list - unless someone else takes it over. I am
working on Predators right now - since I have been promising Kmc I'd work
on that for ages.
