### ISSUE TITLE
Wizards doesnt spawn nuke_tools

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#670]
### Expected Behaviour

You spawn with the box of essentials to steal the nuke core
### Actual Behaviour

You don't

**Comment by Silvaplex256** [comment]
"You don't"...?

I don't see why not. It would be a challenging new objective for wizards.

**Comment by Super3222** [comment]
I've seen this problem before, a fellow on the TS had encountered it once.

Wizards have the possibility of spawning with an objective to steal the nuke core. This however is impossible, unless I've missed something, without getting the syndicate's mini screwdriver.

**Comment by ToGWtF** [comment]
It is an objective, the problem is you dont' spawn with the box full of tools and the nuke core container. You have to send an Ahelp to get one spawned for yourslef

**Comment by Silvaplex256** [comment]
WELP. I just realized what you meant.

So it isn't a feature request, it's a bug involving the nuke box not spawning. Got it!

**Comment by Super3222** [comment]
I don't think the syndicate is associated with the wizards federation.

The WF are just pissed of wizards that heard nanotrasen calling them results of twisted genetic mutations.

I suggest the objective just gets removed, it also doesn't seem like their place to want a nuclear core.

**Comment by ParagonPrime** [comment]
It's Wizard Federation, not Wizards OF Federation... e.e

**Comment by Super3222** [comment]
> It's Wizard Federation, not Wizards OF Federation... e.e

I WAS TIRED.
