### ISSUE TITLE
Admins/Donor Features

### ISSUE THREAD

**Issue by Wardog390** [yogstation13/yogstation-classic#674]
### Expected Behaviour

Admins getting every single donator benefit.
### Actual Behaviour

unable to use preferences to change OOC colour and ghost form.
### Steps to reproduce the problem
1. Apply for admin.
2. Attempt to change settings in preferences.
3. Cry.

**Comment by ToGWtF** [comment]
i figured ooc color for mods/codermins was set for each rank.

**Comment by Groudonmaster** [comment]
Ghost form isn't for admins, you can set ooc color in preferences. Or at least I can but I'm byond member so that may be why

**Comment by Time-Green** [comment]
You are right wardog. We need to change that.

**Comment by matskuman5** [comment]
You can change OOC colour as admin. Just go to setup character and game preferences.

**Comment by DavidEdwards** [comment]
Example:
![untitled](https://cloud.githubusercontent.com/assets/1585923/14042794/ab068a58-f27d-11e5-956c-6ab046dbf263.png)

**Comment by DavidEdwards** [comment]
Wardog has clarified.

We need ability to change this in the preferences tab.

Admins should also be able to change their ghost. Seeing as they can just do it by VV anyway - it makes sense to make it easier for them too.

**Comment by DavidEdwards** [comment]
@yogstation13/initiate-coders this is a good one for an initiate, who wants it?

**Comment by ghost** [comment]
I can try, but it will take some time.
