### ISSUE TITLE
De-converted Cult Gibbing

### ISSUE THREAD

**Issue by FlamePrince** [yogstation13/yogstation-classic#675]
### Expected Behaviour

Chaplain deconverts cultist and it deconverts them.
### Actual Behaviour

Chaplain deconverting cultist and it gibs them.
### Steps to reproduce the problem
1. Feed cultist 100u Holy Water
2. Hit with Bible
3. Hit with null rod

Note: does not work every time, but has happened twice.

**Comment by Greatbigben** [comment]
hilarious honestly
