### ISSUE TITLE
Space-Cleaner does not clean when gravity is off

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#676]
### Expected Behaviour

Clean up spraypaint with the space-cleaner bottle
### Actual Behaviour

It doesn't get cleaned
### Steps to reproduce the problem
1. Turn off Gravy machine
2. Squirt spraypaint on floor
3. Cry yourself to sleep because you are a failure and your father was right

**Comment by oisin100** [comment]
Sounds like physics in action to me.

**Comment by ToGWtF** [comment]
true but it still cleans blood just fine, just not spraypaint

**Comment by ShadowDeath6** [comment]
Use a crowbar or a mop. Spraying things in the air with no gravity is supposed to not work.

**Comment by X-TheDark** [comment]
Eh, either this is how it's supposed to work (in which case "cleaning blood" is inconsistent behavior and should be fixed as a bug) or this is, in fact, a bug that needs to be fixed.
