### ISSUE TITLE
Polaris - New race

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#681]
Nanotrasen's secretive research labs have spewed out yet another hybrid being, the polaris or codename: P. O. L. A. R, a fusion between man and bear. 

They fight with their claws, doing  aunathi bit more than  (lizard) damage but have fat fingers (like hulk) so they cannot use ranged weapons. 

Their warm fur allows them to have heightened cold resistance BUT if they do too much excersise in warm rooms, they get too hot and overheat.... 

Their cold resistance would give them a bit longer in space, but only about a minute or so.  

I can sprite icons for this if: 

> A.  People like it
> 
> B.  adam doesnt shit all over it

If you think they'd be unbalanced, tell me why so i can edit this.

**Comment by Kmc2000** [comment]
Ignore the typos, phone keyboard

**Comment by Super3222** [comment]
> if they do too much excersise in warm rooms, they get too hot and overheat....

What the hell?

**Comment by ghost** [comment]
stop

**Comment by ToGWtF** [comment]
give them a speech filter that makes everything they say growls and roars

**Comment by ShadowDeath6** [comment]
No more animal races >:^(

**Comment by FluffySurvivor** [comment]
> cant use guns

You realize how underpowered this is?

**Comment by penguinfisher** [comment]
How about we make the bears a little more beefy (120 health)? Their unarmed does a little more damage like lizards. 

Their downside could be that they get hungry really fast and have to eat all the time or they walk slower than humans who forget to eat.
