### ISSUE TITLE
Some med changes

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#685]
Bruise packs and ointment suck dick and patches also suck dick.
1. Reduce bruise pack self application time to 4 seconds, so you can't use it in combat but it's not shit to heal yourself anymore.
2. Make patches have an 8 second self application time. A single 50u stypic patch will heal 300u brute damage-50u on application and 250u on reagent ticks. So now you can't spamheal in combat. Bruise packs are the cheap quick common solution where patches are the slower, more powerful alternative.
3. Unnerf healing patches.

The patch nerf is almost universally hated for making it so that when chemistry actually does their jobs, the patches are useless and barely heal for a while until they suddenly start fixing 250 brute. The suggestion I made above removes the crucial issue about self medication being too easy and yet rewards chemists for making synthflesh patches because their patches are now once again effective, but not as effective as self medication.
1. Make pills be able to be force fed to someone in 3 seconds, and instantly if they're in an agressive grab, to make it so that patches are not infinitely superior to pills in every way.
2. Make patches not work through hardsuits or biosuits. This is another reason why patches > pills- you can apply patches at any time, pills suck ass if you need to remove clothing to take them.

**Comment by ShadowDeath6** [comment]
medical is in good spot right now outside of 2 patches healing all damage of their type

**Comment by X-TheDark** [comment]
No, 50u of powder healing 300u worth is absolutely ridiculous. Patches were nerfed for a very good reason - medbay is the best way to get yourself healed. Sleeper/Cryo is the way to go, with patches being a rather crappy alternative.

It may not be a popular state of affairs, but I personally see nothing wrong with making "healing on the go" absolutely crappy and you having to visit medbay and rely on medical staff (or medborg) to be healed effectively. Against.

**Comment by ghost** [comment]
Except right now they heal the exact same ridiculous amount of 250u from heal over time from the reagents.

The only buff patches would get here is that their initial on-touch heal benefits would return. 

How about removing stypic and silver sulfadine's heal over time entirely, hm? So that they're the on-the-skin-contact chems they're inteded to be.

As for the 'but wah wah its good if you go to medical and wait lol' argument it's really, really, REALLY not.

Don't you DARE make that argument.

You want to know why?

Because medical is just as shit. Unlike any other med system, doctoring is not enjoyable. On paramed or baymed or goonmed, doctoring is fun, as there are complications to deal with and surgery to do that's also fairly easily supplemented by chems to keep people in the round. So their long medical times? They're actually fun for the doctor to do, rewards competence.

Here? None of that.

You're artificially forcing people to go and sit in medbay for 10 minutes while some autist doctors shove their cocks in bruise packs and complain they know what they're doing. Unlike bay or paramed, where their longer med js balanced around being fun for the doctor and rewarding skill, there's none of that here.

If you're injured you go into a sleeper or cyro for five minutes or you spend time with someone clicking you with a bruisepack. There's nothing to our med-you're making it take longer with no reward for it taking longer, unlike para, bay, or goon.

You're forcing people to go to med and get treated either way, because only chemists can make those healing patches. But on one hand, chemists are useful again-becauee frankly with the patch nerf so that they can't make any useful healing patches and just sit in a corner doping up or spamming leporazine so they can go validhunt ops.

But one optjon speeds up tgmed to what it was intended to be, and one option artificially slows down the whole thing, makes a medical chemist effectively useless-after all, you can do anything they do with cryo and sleepers-and really just dampers everything with no benefit.

One option is what tgmed is jntended to be-speedy healing to get non-dead people jn the round faster (dead people don't benefit from this whatsoever, which encourages not being a lazy trajtor)-and one artificially slows down the whole thing for no benefit. It makes it what people hate about the other med systems, without what people like about the other med systems.

You want to know why eph's prior patch change was shit? That's why. It slowed medical a shitton for no benefit.

Perhaps you misunderstood me-a single patch ALREADY heals 250u of damage over time. And doesn't heal immediately.

Eph removed the heal on touch without removing the actual offender that heals 250u brute damage itself.

So, remove stypic and silver sulfadine healing when in the body but readd patches healing on contact.

Then, patches of 50u stypic will heal 50u brute, not 300u fucking brute, or 250u as they do now. 

All in all, this is more a patch nerf than a patch buff-it readds their original functionality, but it removes the stupid overpoweredness of patches healing 300u prior.

It also takes 8 seconds to self apply a patch-the same it does to apply a bruise pack right now- meaning that you're already in med getting patches from the chemistry desk, ask a doctor to put it on you. Bam, people still have to go to med to get healed but at least right now you don't spend 10 minutes floating in a cryrotube because that's boring for the doctor and you.

To top it off, patches won't work through hardsuits, and the more limited bruisepacks are suddenly faster for self application. So then, medical starts to require competent chemists to start churning out patches which actually have a use now, because they're going to run out of bruisepacks and ointment much faster, and to top that off patches are finally equal instead of superior to pills, as patches would get nerfed to require biosuits and hardsuits to be taken off-which has the added bonus of preventing hardsuit clad chemists or engies or sec officers from spamming heal patches and meth in space in combat, creates moments of vulnerability for nukeops where they take off their hardsuits to self medicate or encourages buying of the unused syndie medical kit, ect.

And finally, patches having an 8 second self application time basically kills self medication heal on the go using patches the same way 8 second bruisepack application did-takes too long, people would rather a doctor do it for them. Finally, not only can you spam chemical patches midfight like meth and synthflesh as a chemist, but the 8 second application time in comparison to my suggested bruisepack/ointment 4 second application time means that white medkits see actual use again, and self medication using those medkits at the least requires someone to be standing still for 12-16 seconds or so, clicking every limb. It's faster than where doing that took about a minute to do, and yet long enough that someone's going to end up lingering around in medbah for a while-not to mention that bruisepacks and ointment are nonreplenishable, meaning either competent chemists need to get to work or you need to visit cargo and ask for more white medkits.

So yes, this is entirely beneficial in every way-nerfing overpowered chems and patches, buffing pills, increasing departmental cooperation, giving chemists shit to do, encouraging bruisepack and ointment use, making midfight combat patches no longer viable, speeding up medbay so it's no longer obnoxiously long while still requiring people to go to medbay for treatment and healing. Furthermore, nothing is lost at all-nothing becomes over or underpowered, the rate of people coming to med for healing is increased, and to top it off-

Eph's patch change was supposed to make people go to doctors for treatment and you're already arguing that going to med is going to turn into on-the-go healing while this is exactly what it removes and stops. Eph's change left patches still instant apply with a 250u over time healing rate for 50u of stypic or silver sulfadine. This patches makes patches an 8 second self apply that will heal 50u brute or burn instead of 250u or pre-nerf 300u. 

It kills instant self medication for all but the most patient using patches, which is fine as unlike bruisepacks they apply to the whole body, not a single limb-and makes self medication with bruisepacks take shorter, meaning it'll still take a while to heal the whole body, but it's no longer going to take a full minute.

So yes, nothing lost at all and everything gained. This is one idea I can say there are no downsides whatsoever to, and if you think there are i'll be happy to explain why you're wrong on that regard because, and I cannot stress this enough; this fixes like seven problems with current med at once.

**Comment by Greatbigben** [comment]
adam you been making alot of cock references in this git hub chill out son the salt isnt that real. Once i seen that i immediately dismissed the rest of your argument. you dont have to be a ass to be convincing.

**Comment by ghost** [comment]
How about don't dismiss it then?
