### ISSUE TITLE
[Suggestion] A All channels options for tcomm scripts

### ISSUE THREAD

**Issue by Universum01** [yogstation13/yogstation-classic#688]
Really if you want to add a script to telecommunications (i always add the jobs script for everyone) then you have to do it over and over for each channel. 

A simple ALL Channels option when selecting a channel would do wonders.

https://youtu.be/A2PoXBsqXoo

**Comment by killerx09** [comment]
You can kinda do it already if your script is compatible. MAGNI can be installed on one channel, and provided you follow the instructions will apply to all channel.

Also, this is unlikely to go through, because no one has touched NTSL for ages.
