### ISSUE TITLE
Gold jetpack doesn't show up in your hand

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#689]
### Expected Behaviour

Hold the jetpack in your hand and it becomes apparent that it's on there from a visual perspective
### Actual Behaviour

It's invisible.
### Steps to reproduce the problem
1. Hold the gold jetpack in your hand

**Comment by Notamaniac** [comment]
From a glance at the inhand dmi file, I can't see the golden jetpack sprite. I'll see if I can get to work recolouring the jetpack sprites, and if I'm not mistaken I should be able to label it jetpack-gold and everything should work out swell.

**Comment by FluffySurvivor** [comment]
how are you supposed to sneak cap's jetpack on the shuttle now ?

**Comment by ToGWtF** [comment]
@Notamaniac Exactly what I did. Good work! :)

**Comment by Groudonmaster** [comment]
Yeah I was told about this awhile back when I added this. I never got around to fixing it though unfortunately I'll handle it if noone else wants to

**Comment by Greatbigben** [comment]
closing this since it seems handled
