### ISSUE TITLE
Remove mulligan

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#697]
### Expected Behaviour

Wait for a 30 minute blob round where a quarter of the station is gone and the shuttle 3 minutes from landing to end when blob is finally killed
### Actual Behaviour

5 people get random traitor/ling status
### Steps to reproduce the problem
1. Kill blob or wizard
2. Wait for round to end
3. People get antag

Mulligan is literally not fun in the slightest, and all it does is extend a round when a much better experience could be had by just ending and going on to a new one. Who wants to play traitor with 3 minutes to get the nuke auth disk and kill HoS when literally everyone on the station has lasers to kill blob?

**Comment by Time-Green** [comment]
There is a time cap on it, and we can disable it with one press of a button

**Comment by ShadowDeath6** [comment]
Then make it so it starts disabled instead of starting enabled, maybe?

**Comment by FluffySurvivor** [comment]
Yes please, remove mulligan. :+1:

**Comment by utahclock** [comment]
I support removal of mulligan
