### ISSUE TITLE
Regular blob tiles have way less health than they did before.

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#698]
Blob tiles have really low health, probably like 10-15. A single laser, a welder, stunbaton, or anything that does ~10 damage will kill unpowered (not glowing) blob tiles. This was intended for the EMP blob if I recall correctly, but this happens with EVERY blob.

https://github.com/yogstation13/yogstation/issues/696 for a similar (the same) issue

**Comment by AsV9** [comment]
doooplicate

**Comment by ShadowDeath6** [comment]
yeah but mine is better :^)

**Comment by AsV9** [comment]
not really I didn't understand shit before I read the other tile.
call me stupid...

you'd probably be right..

wait
