### ISSUE TITLE
Revenants never spawn.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#70]
Step 1: RNGsus triggers revenant on wizard round with 30 dead and swarms of ghosts.

Step 2: Revenant doesn't happen.

Step 3: Cry.

Revenant never actually spawns the mob, even after all conditions are met and the event triggers.

**Comment by Cruix** [comment]
What admin messages does the event trigger, if any?

**Comment by Groudonmaster** [comment]
If there's enough players the game will state the event triggered despite nothing happening

If there aren't enough it will state that it failed and the amount of dead people there are currently.

**Comment by george99g** [comment]
Seems like this was fixed by #85
