### ISSUE TITLE
Blobs not showing correct chemicals on examine.

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#700]
> fighting blob
> blob splits
> examine new blob
> shows the chemical of the old blob

From what I can guess, a tile will always show the chemical of the blob that created it, regardless of the blob's actual color.

Let's say for example a dark matter blob, which is purple, splits and creates a lexorin blob, which is light blue. The old tiles that were converted into new light blue tiles still show the chemical "dark matter" on examine, which makes discerning the actual blob's chemical really difficult with all the new colors that've been updated.

**Comment by AsV9** [comment]
This shouldn't be too tricky to fix.

**Comment by ghost** [comment]
I'll attempt to fix it.

**Comment by Greatbigben** [comment]
has this been fixed?

**Comment by X-TheDark** [comment]
I am not sure if this is a bug or not. 

The thing is, when a blob "pulses" another blob (the thing that makes it change color), it doesn't actually change ownership of that tile (and hence, doesn't change the chemical it has).

So I am not sure what should be fixed about this - should the color not change or should the chemical of the blob be changed to the color it gets from another blob?

**Comment by ShadowDeath6** [comment]
The way it used to be was that the chemical changed to match the color of the blob tile.
