### ISSUE TITLE
Idea: Neuro-Signaller-ing

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#702]
### Expected Behaviour

Signallers can induce neuro-motor effects when implanted into a living person such as paralysis, stunning, dropping items, falling, impaired speech, blurry vision, druginess, etc...
### Actual Behaviour

Signallers do nothing inside of someone.
### Steps to reproduce the problem
1. Obtain 1 humanoid and 2 signallers along with surgical tools
2. Open the humanoid up and implant 1 signaller
3. Grasp the other signaller and send a signal that will activate the implanted signaller
4. Watch as nothing happens except beeping noises

**Comment by Cruix** [comment]
> Implying that making your target go _beep_ _beep_ constantly until they suicide isn't the best form of murder.

**Comment by ParagonPrime** [comment]
Should only work for Preternis! Cut 'em open to get a menu suspiciously similar to a hacking menu. Cut wires until you find the one you want, hope you haven't killed the fucker in the process, attach signaller, profit.

**Comment by FluffySurvivor** [comment]
GHETTO MINDSLAVING. 
ALL MY YES :100:  x :+1:

**Comment by Greatbigben** [comment]
jesus i dont know what to say about this
