### ISSUE TITLE
Borer icon bug. Returned

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#708]
### Expected Behaviour

Nothing
### Actual Behaviour

Gang icon dissapears when ifnected by borer
### Steps to reproduce the problem
1. be gang
2. be borer
3. Get killed by your own gang

I thought coders fixed this, but it's still happening

**Comment by FluffySurvivor** [comment]
oh this shit again?

**Comment by oisin100** [comment]
Ye, bugfix was never merged.... I closed it by accident...
