### ISSUE TITLE
Borer Icon overriding others

### ISSUE THREAD

**Issue by Greatbigben** [yogstation13/yogstation-classic#710]
when infected with a borer the gang icon is overridden instead of dropped down or flickered. this leads to confusion as to who is or isnt in your gang

**Comment by Greatbigben** [comment]
oh it seems the fix was never merged

**Comment by Greatbigben** [comment]
[https://github.com/yogstation13/yogstation/pull/683](url)

**Comment by oisin100** [comment]
Aye, I need to fix the conflicts however. Should be done soon.

**Comment by Greatbigben** [comment]
thanks

**Comment by oisin100** [comment]
Fixed.
