### ISSUE TITLE
Make swarmers a random event

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#711]
I think gateway was supposed to be a thing but it died and swarmer random events died along with it. 

Swarmers are really rare right now, like close to borers or xenos, and they're a fun and interesting thing that brings players back into the game. I would like for a random event to exist that spawns a swarmer shell somewhere in maint or something so it happens more often.

**Comment by ToveyAyyLmao** [comment]
The problem is xenos are OP and change the round signifcantly. Borers dont change any gameplay unless its gangs, where they de gang everyone, and swarmers just force an eventual shuttle as no one wants to sit on the station when all of maint is gone. They ain;t interesting enough and they break rounds.

**Comment by ShadowDeath6** [comment]
They can be killed pretty easy if you catch them fast enough and a shuttle call isn't necessarily bad if the round is past the point of being fun.

**Comment by ToveyAyyLmao** [comment]
But they cause the round to no longer be fun. And an individual swarmer kill isnt the issue. By the time they are discovered the entire bottom hand of maint is gone and there is atleast 20 of the bastards running about.

**Comment by ShadowDeath6** [comment]
They would probably only spawn 45 mins - an hour into the round, not like they're going to be solo shuttlecall.

**Comment by Greatbigben** [comment]
Gateway was supposed to be in but with the server coughing up a storm and no mapper help it died a slow slow painful death. Building a new map from bottom up is harder then it sounds
