### ISSUE TITLE
Make constructs drop the player's soulstone upon death

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#712]
Makes construct cult more functional oh fuck

Title basically, prevents players from being totally permafucked by dying as construct (artificer, wraith, juggernaut)

It would let other cultists pick up the soulstone and then give them another body. 

I consider a construct shell to be like a big shell(no shit) and the soul stone just kind of sits in there until the body is destroyed where the stone would pop out.

**Comment by Super3222** [comment]
They are meant to be fucked.

**Comment by ShadowDeath6** [comment]
This is a dumb issue
