### ISSUE TITLE
Feature suggestion: Bees For Botany

### ISSUE THREAD

**Issue by killerx09** [yogstation13/yogstation-classic#713]
https://github.com/tgstation/-tg-station/pull/16262

Adds bees to botany, helping botanists grow plants.

Thoughts?

**Comment by DavidEdwards** [comment]
[My thoughts](https://www.youtube.com/watch?v=Xs-tl6GBOBo)

**Comment by ParagonPrime** [comment]
[As soon as this gets implemented, I'm doing this](https://youtu.be/PYtXuBN1Hvc)
