### ISSUE TITLE
Tempgun is still complete garbage

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#715]
### Expected Behaviour

Use temperature guns as a slightly more efficient xenobio tool/ weapon if you have an emag
### Actual Behaviour

They take like 3 minutes to change temperature
### Steps to reproduce the problem
1. Make tempgun
2. Set temperature to max freeze or max heat
3. Wait ages for it to turn the correct shade of blue or red. 

For what reason was this a thing? 

"oh you don't need to change its temperature" 
Well maybe I want to freely alter my temperature to shoot emagged fire beams at people or burn revs who try and fuck with me.

**Comment by ToGWtF** [comment]
yeah its so you can't instantly set it back from 1000k after shooting people and make it look non-emagged.

**Comment by ShadowDeath6** [comment]
I think it'd be pretty obvious that you emagged it if you shoot someone and they suddenly ignite.

**Comment by ToGWtF** [comment]
it also has an in-hand and item sprite to show that its temperature is past normal

**Comment by Greatbigben** [comment]
The insta fire ball i meh lower to about 20 secs that's more then enough in game time

**Comment by ToGWtF** [comment]
It only takes like 30-45 seconds...

**Comment by ShadowDeath6** [comment]
> old tempgun still better than new tempgun because you can instantly set temperatures

**Comment by Greatbigben** [comment]
So what is this about?

**Comment by ToGWtF** [comment]
Considering being set on fire is virtually the same as being disabled/tased (As you have to leave the fight to either A) Find a fire extinguisher B) Stop-Drop-And become a sitting duck or C) Take a considerable amount of burn damage) I think its fairly balanced. It has to have some sort of drawback. I didn't make it too big to fit in backpacks like TG/VG did so you can carry multiple temperature guns
