### ISSUE TITLE
DEAR GOD JESUS THE LAG

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#717]
# ATROCIOUS LAG

ABSOLUTELY, RIDICULOUSLY, UNBELIEVABLE, WORLD-SHAKING LAGSPIKES

randomly started today, EVERYONE has it, NOBODY knows what causes it

it's an absolutely critical issue- take down the server and **DO NOT PUT IT BACK UP UNTIL IT'S FUCKING FIXED REEEEEEEEEEEEEEEEEEEEEEEEEEEE**

**Comment by Time-Green** [comment]
I think I ERP'd to hard with Canna and the server started to puke

No but really, It's horrible lag. .ping was a minute

**Comment by ParagonPrime** [comment]
![](http://i.imgur.com/u81dXGh.gif)

**Comment by ShadowDeath6** [comment]
Figgs ur shid coders :^DDDD

**Comment by Trojanplunder** [comment]
Literally just happened again when the HoP started ERPing in his office. I blame the ERP.

Edit: Went away and then happened again when the HoP started ERPing again. ERP is now the confirmed cause.

**Comment by Trojanplunder** [comment]
Don't mean to doublepost here, it just went away and then he HoP started ERPing again. ERP is now confirmed to be the problem.

**Comment by oisin100** [comment]
If its high ping its probaly not related to the code. I heard something about DDOS attacks on discord although i wasnt really paying attention
.
