### ISSUE TITLE
Collector array disappears

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#720]
### Expected Behaviour

Collector array stays in its place.
### Actual Behaviour

Around Server time 2016-03-28 16:35 (just now), collector array on the left side apparently disappeared after a while. When I asked Admin about it he said it just vanished, and spawned a new one. I've seen the collector array missing in different shifts, even though we started with all of them.
### Steps to reproduce the problem
1. Be engineer.
2. Start Tesla, (crowbar the plasma tank which was placed by others out?), close the engineering shutters.
3. After a while find one collector less.

![collectorarray-bug](https://cloud.githubusercontent.com/assets/16806055/14081623/eb714ffc-f50b-11e5-884c-19253bd627bb.png)

**Comment by ShadowDeath6** [comment]
Probably the tesla bolts bugging shit out again. It makes some machines like doors just up and vanish sometimes when hit.
