### ISSUE TITLE
Statue near primary tool storage

### ISSUE THREAD

**Issue by MaxBurakhovich** [yogstation13/yogstation-classic#723]
### Expected Behaviour

Statue should be named Max Gingerbeard
### Actual Behaviour

But it is named Max Gingerbread
### Steps to reproduce the problem

Step1: Change 1 variable from "Max Gingerbread" to "Max Gingerbeard"

**Comment by Time-Green** [comment]
I THINK I CAN HANDLE THIS.
THIS IS MY TIME TO SHINE
edit: I did it, now to figure out of the hell git works

**Comment by Cruix** [comment]
> Map editor inexplicably changes 4000 lines from a simple varedit

**Comment by nazitra** [comment]
I'm against this rename.

GINGERBREAD IS DELICIOUS

**Comment by ToveyAyyLmao** [comment]
Yeah I dont like this. It'll break the current balance of ling AIs.

**Comment by nazitra** [comment]
...ling AIs have what to do with a typo'd statue?

**Comment by Groudonmaster** [comment]
Nazitra look at what you typed and figure it out :p

**Comment by Super3222** [comment]
I thought AsV9 was just mocking him, and made it intentional hah.

**Comment by ShadowDeath6** [comment]
Feature
