### ISSUE TITLE
Not enough light in Perma Isolation for plant-people

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#724]
### Expected Behaviour

Place a confirmed traitor in perma isolation, with blast doors raised. Walk away. 
### Actual Behavior

Prisoner dies due to lack of light.
### Steps to reproduce the problem
1. Place plant-person in perma-isolation.
2. Plant person dies due to lack of light.

**Comment by ShadowDeath6** [comment]
the blast doors were closed in that round, there's normally enough light

**Comment by EMT321** [comment]
It was tested at round end without blast doors closed. Same result.

**Comment by EMT321** [comment]
Upon further investigation, it appears that closing the shutters at all prevents light from entering, even if they are re-opened later.

**Comment by penguinfisher** [comment]
Someone's a bit salty ;^)

**Comment by ShadowDeath6** [comment]
I'm salty that the confirmed plant traitor ahelped EMT for putting him in the darkroom and got revived >:^(

**Comment by Greatbigben** [comment]
Place more lights

**Comment by ShadowDeath6** [comment]
Just put a lightbulb on the inner window, problem solved

**Comment by DavidEdwards** [comment]
> Upon further investigation, it appears that closing the shutters at all prevents light from entering, even if they are re-opened later.

Lets find the reason why the shutter stops future light coming through.

> Just put a lightbulb on the inner window, problem solved

I don't want to bodge this error. If it can happen here, it can happen in other places too.

**Comment by EMT321** [comment]
I'm not sure if closing the shutters doesn't break the bulbs.
