### ISSUE TITLE
Reduce the cost of Gang Implanter

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#728]
### Expected Behaviour

People use the gang-implanter to convert high profile targets to their gang.
### Actual Behaviour

They beat enemy gangsters to death with fire extinguishers because it costs too much
### Adam's thoughts

```
[8:02 AM] Adam El-Tablawy: okay so
[8:02 AM] Adam El-Tablawy: idea
[8:02 AM] Adam El-Tablawy: reduce gang implanter influ cost
[8:02 AM] Adam El-Tablawy: to 15
[8:02 AM] Adam El-Tablawy: instead of 30
[8:03 AM] Adam El-Tablawy: the reason they're never bought is that they're super expensive
[8:03 AM] ToGWtF: ^    can always revert later if its unbalanced
```

**Comment by Time-Green** [comment]
Couldn't you beat them in the head to have a change to deconert?
Or was that rev only...

**Comment by ToGWtF** [comment]
No to break a loyalty implant/convert another gangster you need to use gang implanter. So that 30 points at round start is a big risky move when trying to subvert the HoP.

**Comment by FluffySurvivor** [comment]
the implant breaker cost 30 influ as well before the nerf ( it used to instantly convert with no need for pen follow-up) so a price reduction would've been appropiate a long time ago

**Comment by ShadowDeath6** [comment]
tfw sec gets fucked during gang even more
tfw you use a fourth of your loyalty implants to ensure one ganger doesn't immediately get converted again
tfw they can wait 3 minutes and buy 3 gang implants and a gang pen to remove 6 loyalty implants and convert them to gang

**Comment by ToGWtF** [comment]
better than getting murdered because you resisted getting gang pen'd. also makes it easier to recruit sec members rather than just validsalid them

**Comment by ToveyAyyLmao** [comment]
Im sorry but I literally see gangs win every round. A buff aint necessary in my eyes. Hate dying? Dont die.

**Comment by ToGWtF** [comment]
Its not a buff tbh. It just makes it more viable to NOT kill someone. Its a win/win for everyone involved

**Comment by ShadowDeath6** [comment]
not sec
