### ISSUE TITLE
Ultra job preview in character prefrences broken?

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#737]
### Expected Behaviour

Show the correct job for the highest priority job chosen.
### Actual Behaviour

Gets shown naked person.
### Steps to reproduce the problem
1. Set job to Ultra
2. No clothes worn in character preview. http://prntscr.com/alxpb5

**Comment by AsV9** [comment]
The job display thing shows whichever job is set to the 'High' setting.

**Comment by oisin100** [comment]
> The job display thing shows whichever job is set to the 'High' setting.

Mhm, With the addition of the Ultra setting it would be nice to display the highest priority and not just the one on "high" however.

**Comment by X-TheDark** [comment]
Right now, working as intended, as many jobs as you want can be set to Ultra and it's a tossup between all the jobs selected for display purposes. Will be dealt with along with 738, if we decide to change it to have only one job selectable with Ultra.
