### ISSUE TITLE
Ultra Job Prefererence allows for multiple choices.

### ISSUE THREAD

**Issue by AsV9** [yogstation13/yogstation-classic#738]
### Expected Behaviour

You can only set one role to Ultra.
### Actual Behaviour

You can set every head role to Ultra at the same time.

**Comment by DavidEdwards** [comment]
Why only one?

**Comment by Groudonmaster** [comment]
Because you can only set one to High

**Comment by X-TheDark** [comment]
Currently, working as intended. Making it possible to select as many jobs as you want on Ultra was a design decision, not a bug, I'll see if this needs to be changed.

**Comment by DavidEdwards** [comment]
The point of the system is to make sure that the head roles have someone competent in them. In this case it makes more sense to allow one person to apply for Ultra on as many as they want. That way we are more assured of having a competent player in a head role.

Take for example this scenario:
- Player1 - Competent Ultra player
- Player2 - Competent Ultra player
- Player3 - Competent Ultra player
- Player4 - Normal player

Player1, Player2 and Player3 set ULTRA to Captain.
Player4 sets HIGH on Head of Security

We now have two competent players without a head role.

@X-TheDark and I discussed this, and it seemed better to allow Ultra to be multi-select.

**Comment by X-TheDark** [comment]
Yup, no reason NOT to allow multiple jobs to set to Ultra, but then again, no reason TO do it either. This can go either way. 

Kn0ss0s explains very well why we decided to use multiple-select system rather than a single-select one.

EDIT: This is completely up to council decision. If they want single-select, it's not a problem to implement this.

**Comment by AsV9** [comment]
I labeled this balance and not bug for a reason, @DavidEdwards (@X-TheDark) . It's a decision we should make.

While I think Kn0ss0s nails it with his reply, it makes little sense to be allowed to select unlimited jobs for the highest preference, then 1 job for the 2nd highest, then unlimited jobs for the 3rd and 4th preference.

**Comment by DavidEdwards** [comment]
Well, I don't really have an issue with High being unlimited either.

We could also keep it how it is, and explain it like the old levels are "preference" and the Ultra level is "experience / competence".
