### ISSUE TITLE
Lua-ish programmable laptops.

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#739]
I was thinking of adding programmable laptops to the game what could be programmed using a language like LUA or NTSL to allow players to create their own fun little ASCII games on them.
I would also like to give these computers a "ping" function what would allow them to "ping" various consoles across the station and receive information so that the computers are actually usefull for something other then ~~ASCII porn~~ ASCII minigames.

Some uses of these could be:
- Dwarf Fortress in SS13
- Automated announcements from comm consoles
- Automated checking for crew deaths
- And im too lazy to post any more examples

To stop the "ping" function from being abused there would probably be a cooldown on how often each machine can be pinged. But the cooldown could possibly be decreased by using better capacitors. The "ping" would also be able to take in arguments to send the pinged machine specific details, E.g ping(commsconsole.x, commsconsole.y, commsconsole.z, '?message="Test Announcement"')
Every ping command would also require you to pass in a secret password for the machine your trying to access to prevent meta and abuse. The secret password could possibly be obtained by hitting the machine with a multitool.

Some example of machines what could be pinged:
- Ping AI would send the AI a private binary message
- Ping comms console would make a announcement
- Ping Crew manifest would return a list of crewmembers
- Ping crew monitor with a crew members name would return that crewmembers health state.

As for stopping players from creating infinite loops i thought of a couple of options
1. Limit each program to a certain loops per tick. EG max loops per tick = 100 then a loop with 200 iterations would take 2 ticks to complete.
2. Easier option: Limit loop size. Loops will run 100 or so times before they kill themselves. You would not be able to embed loops into loops.

Programs would also be limited to a max number of lines to prevent massive spam from Ctrl+V

I've done a small amount of work but something like this will take me a while. I've got exams coming up so i wont be too active for the next few weeks.

**Comment by ToGWtF** [comment]
inb4 command line ping flood on the ai by guy wearing a mime mask named "anonymous"

**Comment by oisin100** [comment]
> cooldown on how often each machine can be pinged.

**Comment by Kmc2000** [comment]
Do you want sprites for this @oisin100? 

If ya do, disc cord me. The idea sounds neat, and ascii porn sounds entertaining.

**Comment by ShadowDeath6** [comment]
ascii porn is entertaining

**Comment by Super3222** [comment]
anonymous mime figures out a way to break the cooldown and flood the system

**Comment by ShadowDeath6** [comment]
I hope this gets merged so I can send the AI lewd messages via binary

**Comment by Kmc2000** [comment]
Sprites done
