### ISSUE TITLE
Suit Inbuilt Jetpack cannot be toggled

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#741]
This doesn't work:

/obj/item/weapon/tank/jetpack/suit

Not sure of its expected behaviour.

**Comment by Kmc2000** [comment]
Basically when you try toggle it, nothing happens at all.  It should run off tanks in your suit but it doesn't.

**Comment by ToGWtF** [comment]
This for engi/CE/Atmos hardsuits? Those are the only ones with jetpacks

**Comment by Super3222** [comment]
You need an oxygen tank inside of your suit storage.

**Comment by X-TheDark** [comment]
You must have an oxygen tank in your suit storage (hardsuit) for it to activate. Feel free to reopen this if there's something to add.
