### ISSUE TITLE
firesuit EVA

### ISSUE THREAD

**Issue by apneaman** [yogstation13/yogstation-classic#742]
### Expected Behaviour

Ending up in breached area of ship while fighting the blob in full firesuit/internals and dying from too much pressure damage
### Actual Behaviour

Taking no damage whatsoever
### Steps to reproduce the problem
1. Take a firesuit
2. Stand in a breached area of the ship
3. Beat blob to death with fire extinguisher

**Comment by Super3222** [comment]
Eh... Atmospherics may have been moving slow in the area...

I know firesuits provide a small amount of protection against EVA, but I'm pretty sure it should make you take absolutely 0 pressure damage.

**Comment by apneaman** [comment]
This was on blob last night. Back half of holodeck was completely open beat the blob back off the holodeck at sometimes standing in space. I would understand pressure protection in small changes but this was legitimate space walking
