### ISSUE TITLE
CRITICIAL Secborg Bug

### ISSUE THREAD

**Issue by rweber89** [yogstation13/yogstation-classic#745]
### Expected Behaviour

Either for nothing to happen, or make sure that if the borg runs out to respawn a new pair of zipties in its storage/active slot.
### Actual Behaviour

Zipties vanished. Pressed ´z´ hotkey twice while having zipties as active item. It produced cable coil and I was out of options to restrain people.
### Steps to reproduce the problem
1. Add weapon to slot 1
2. Add stunbaton to slot 2
3. Add zipties to slot 3
4. Press ´3´ to set zipties as active
5. Press ´z´
   ( Cable coil appears with a system message)
6. Press ´z´
   ( As above )

**Comment by ShadowDeath6** [comment]
might need to make borg zipties a different type of ziptie, like energy cuffs. You can fix this with a module reset.

**Comment by Super3222** [comment]
This was my fault, and I will fix it.
