### ISSUE TITLE
succ baby

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#746]
coders pls add to the medborg selectable list :^(

http://imgur.com/y9EORZm

**Comment by Kmc2000** [comment]
It's so shitty it's good

😏

**Comment by ParagonPrime** [comment]
yes please god yes

**Comment by Blukey** [comment]
pretty delicious if you ask me

:ok_hand:

**Comment by ShadowDeath6** [comment]
:ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand:

**Comment by ShadowDeath6** [comment]
> pretty delicious if you ask me

pretty succ-ulent
