### ISSUE TITLE
Have the AI drop a posibrain/MMI if EI NATH'd

### ISSUE THREAD

**Issue by nazitra** [yogstation13/yogstation-classic#747]
### Expected Behaviour

Wizard gibs the AI, AI can be rebuilt if anyone gives a fuck and the wiz doesn't take the brain (just like borgs can be)
### Actual Behaviour

AI is gone without a trace and Taco has no TALKING BRAIN to carry around in the collection.
### Steps to reproduce the problem
1. Be wiz
2. Gib the AI
3. Have no one to gloat at, if you are Taco

**Comment by ShadowDeath6** [comment]
ei nath too fair and balanced you can't change anything about it ever sorry
