### ISSUE TITLE
Make pink slime extracts useful

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#748]
When injected with sugar, spawns lazarus injector.
Useful for reviving mobs, obviously.

**Comment by Super3222** [comment]
Ask a miner.

**Comment by ShadowDeath6** [comment]
> > > > > > > > > > > implying miners are ever useful to anyone ever

**Comment by ToGWtF** [comment]
yeah thats too easy to get ahold of lazarus injectors

**Comment by ShadowDeath6** [comment]
it's either science having semi-easy access to laz injectors or not having access at all, and I'd like it to be a thing since xenobio is kind of the the go-to place for monsters.

**Comment by apneaman** [comment]
Make them spawn a growth hormone. Doubles slime growth rate. Works generational like a stabilizer
