### ISSUE TITLE
Admin observer interaction verb

### ISSUE THREAD

**Issue by Hydre** [yogstation13/yogstation-classic#751]
We really need a way as admins to interact with computers and pumps and such when we're observing.
Maybe a verb that toggles interactions?

Because right now it's impossible to do any of this without going into vars or spawning yourself in.

**Comment by DavidEdwards** [comment]
Absolutely for this. :+1:

**Comment by X-TheDark** [comment]
Yup, also adding #241 just because it's related so it can be found more easily once this is done.

**Comment by Time-Green** [comment]
I am not that good at coding, but I actually think I can copy and imitate enough code to get this to work.
And I am already halfway.
Edit:Its going very well

**Comment by Time-Green** [comment]
OK. I ABSOLUTELY CAN'T DO THIS

I have learned alot trying to tho, but this is to much for me
