### ISSUE TITLE
Ultra defaulting back to Never.

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#752]
### Expected Behaviour

Stop going back to never and giving me annoying jobs.
### Actual Behaviour

Defaults back to never and gives me janitor. Cry in a corner.
### Steps to reproduce the problem
1. Set 'AI' preference to Ultra
2. Round restarts
3. AI preference is back to Never

If its any help im using a donor slot for my AI setup.

**Comment by X-TheDark** [comment]
Make sure to hit the "Save Setup" button. This happens with all jobs resetting when your profile is reloaded if you didn't save the setup using the button.

**Comment by oisin100** [comment]
Yep, I always do. It still resets.

**Comment by X-TheDark** [comment]
Any additional information? Does it reset after the round-end thing?

**Comment by oisin100** [comment]
I have no idea at what point it resets. It just seems to default back to never at the next round. Ill try again next round.

**Comment by X-TheDark** [comment]
Yup, this does indeed, reset your preference from Ultra to Never. Damn, I'll see if I can fix this.
