### ISSUE TITLE
REPLACE RANDOM RNG KNOCKDOWNS WITH CRITS

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#753]
### Expected Behaviour

The person that is better armed wins the fight, unless the enemy combatant is really skilled
### Actual Behaviour

Melee combat is pure luck, depending on who knockdowns first with their melee weapons.
### Steps to reproduce the problem
1. Be nuke op
2. Get RNGed by the power of the un-adrenable unconscious toolbox knockout.
3. See how useless skill is.

So I am proposing a healthier version of RNG combat : crits. When you engage in a fight, you SHOULD be able to know how you can outplay by evaluating the enemy's capabilities. It doesn't work because random stuns are stupid and unexpectable. Overall, keeping the satisfaction of that "big hit" while making combat fair.
Of course, this only applies to melee brute dmg weapons.

**Comment by X-TheDark** [comment]
Get dunked on by lady luck, scrub. Get better at RNG.

But in all seriousness, RNG of melee combat really does need adressing, I'm not sure if it should be replaced by crits (meaning no knockdown ever) or do something along the lines of /tg/ where the stun chance is proportional to the damage the weapon does.

**Comment by ParagonPrime** [comment]
well, RNG knockdowns should stay a thing- it makes sense that, in a fight, you might get a lucky swing on an enemy with a heavy metal object and send them sprawling.

but it should be a lot more specific. it's a lot harder to beat down a guy in an ARMORED HARDSUIT with a mere toolbox; RNG should remain to some level, but we need to adress damage vs armor a lot more.

so yeah, if somebody's got riot gear and you whack them with a toolbox, they should have basically no chance to be knocked down. meanwhile, when that guy swings an active stunbaton at your unarmored ass, you should go down pretty fast.

a few ideas, then:
1. remove esword knockdown. what, an immaterial, energy-based weapon designed for CUTTING is suddenly great at... knocking people to the floor? come on. should instead do a bit of extra stam damage, tho, so it doesn't become totally inane for chases.
2. in a melee duel, depending on how you're equipped against an agressor, you should be able to have a chance to block enemy attacks. this depends on what weapon you have, what weapon the enemy has, how much damage you've taken, etc. if a weapon is significantly better, like an esword against a metal rod, there should be a high chance of breaking the block, stumbling the defender back a little and making them drop their weapon. that chance also increases with damage dealt to your enemy, but specifically how damaged their hand that is holding the weapon that is blocking is (if you're using your right hand to attack your left hand should still be able to block, a la riot shield)

**Comment by X-TheDark** [comment]
Yeah, the 2.point sounds like the system /tg/ have in, where weapons and armor have a block_chance thing, if I remember correctly.

**Comment by ShadowDeath6** [comment]
Git gud, rng combat is important and if you get shit on by a toolbox as the antag with the most guns it's your fault. Also adding shit like blocking stuff with toolboxes or whatever will make traitoring significantly harder and will probably reinforce le combo cafe uncounterable meemee

**Comment by ParagonPrime** [comment]
we're not really suggesting that, shadow

just

a toolbox shouldn't be able to somehow knock out a guy in a super-expensive purpose-built combat armour that can easily defend them against bullets and focused energy blasts

like, knock down for a moment? eh, maybe, if you get enough momentum on the swing- but KNOCK UNCONSCIOUS? nah

**Comment by FluffySurvivor** [comment]
> rng combat is important
> therefore actual skill is meaningless

it's not only nuke ops, it is a global issue that happens in every gamemode in each melee fight and it's absolutely ridiculous that you can outplay the shit out of your opponent only for him to get that gg no re stun off

**Comment by ghost** [comment]
crits is retarded, shoo.

if you want to see how fun crits are go play some tf2, demoman is fair and fucking balanced.

i'd agree with reducing knockdown chance against those wearing hardsuits or armor, but that would require a complete refactor on how knockdowns work, because right now knockdown and KO chance are calculated by an object's force, and so naturally wearing armor will reduce damage and thus naturally reduce knockdown chance.

Unless you want to remove it entirely for certain weapons that'd require a complete refactor of knockdown code to depend on something else other than object force and then applying these changes to EVERY SINGLE ITEM IN THE GAME.

**Comment by ParagonPrime** [comment]
well, let's think about real weapons- the weapons most likely to knock you down are large, blunt, and heavy, typically swung at an unarmored head.

so, let's change things slightly- make things like knives, eswords, and spears have a lower chance of knockdown than, for instance, metal bars or toolboxes. then it becomes almost like a choice- do you want a higher chance to stun your enemy, at the cost of reduced damage? or do you feel confident enough that you'll land sufficient hits to be able to skip the stun and focus on solid damage?

if i may compare it to nukies- it's like the C20r vs the M90GL. Lower damage with high knockdown chance, versus high damage with no knockdown chance. Everybody has personal preference and one will save you when the other won't.

similar idea here

as for how to code it, well, that'll take a while, and probably a bit of nitpicking for specific items- but this isn't exactly a super high-priority thing, so i wouldn't mind waiting for it

**Comment by ShadowDeath6** [comment]
> demoman is balanced
> 
> > > > > > > implying not megasalt

Also nerfing esword you fucking what

Also also: adam literally just said that knockdown or KO is based on damage, I don't know for certain if that's true but it would require a fuckton of work on every item if it's item-based and a fuckton of work to redefine the ultimate meme that is combat

**Comment by ParagonPrime** [comment]
as i said, it's not a priority at all
with a bit of common sense ("hmm, it's probably easier to beat down a dude with a metal bar than a kitchen knife") a single guy can, slowly, work through and modify every item in the game- just randomly, on an off day, pop in, change 5-10 numbers, and go off again.

after a while we'll see updates.

and no, not nerfing esword as such; just reducing knockdown chance to minimal, because knocking someone down with an esword makes ZERO sense. it would instead be changed to do some pretty ridiculous stam damage so getting a good hit on a guy doesn't let them escape, no sir

**Comment by ghost** [comment]
> STAMINA DAMAGE ESWORDS

_VOMITING NOISES_

**Comment by ShadowDeath6** [comment]
Protip
no buffing eswords
no nerfing eswords
buff ebow instead xddd
