### ISSUE TITLE
Gateway + Destinations

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#76]
The Gateway is already in the code, and the recent update to Centcom added it in a tiny little back room complete with exile implants. Sadly, without the required coding implementation the Gateway doesn't really work, or have any good places to go. I'd like to be able to map out some new destinations with some lads but the coding will have to be done by someone else (Taco),
kthx

**Comment by Hydre** [comment]
Bear in mind that the gateway often caused a lot of lag due to extensive maps being loaded up since it's always random. Or at least that's how it used to be. (HNNGHH jungle map)

**Comment by shrimptk** [comment]
/tg/ fixed this problem by only loading whatever away mission is active each round during the server start, and having the map load during the first 15 minutes of the round while the gateway _'callibrates'_

**Comment by Hydre** [comment]
But doesn't that create 15 minutes of lag?

**Comment by shrimptk** [comment]
Not really, it loads pretty slowly over the period causing a really insignificant amount of lag, so when the map finally loads in, its like nothing ever happened.

**Comment by Hydre** [comment]
Hmm, I'd be up for this. Send all scum to some random ass place to see if they can survive there...

I like it, just needs some survival-esque maps then

**Comment by Groudonmaster** [comment]
I approve if we put in the load over time

**Comment by shrimptk** [comment]
@Hydre I got the mapping part, maybe @AsV9 and some other dudes can get together with me on this.

**Comment by BadminBen** [comment]
im down. we making new maps or using the ones thats in the code?

**Comment by Hydre** [comment]
I'd say we make our own, I'm getting into mapping as well so..

Or if tg has some dank maps we could pick from those as well

**Comment by shrimptk** [comment]
/tg/ has a solid number on the git that just need to be ported. But I say we make a few of our own just for good measure.

**Comment by ghost** [comment]
Do note that most away missons come with very, very strong rewards for completing them. At least, the ones on /tg/.

Assuming you do implement this, we'll have to make some policy changes and some balance changes revolving around the fact that even on the simplest, easiest away mission people can come back with fucking singularity hammers and wands of fireball and healing.

**Comment by Hydre** [comment]
Eh, people who get sent through there have to be implanted with an implant that prevents them from being able to return.

At least that's how it used to be

**Comment by shrimptk** [comment]
Exile implants that make people explode on returning to the station are an optional feature that can be obtained from a locker in the gateway room with armory level access, and to address Adam's balancing concerns, most of the more dungeon-style away missions require people to get the to the end of a ridiculous maze of mobs and traps with limited support from the outside to even get to the gateway back home, so sometimes this loot is well earned (So if we're going to have an Energy Axe just chill in the bridge all the time this is pretty fair.) Obviously I'll make sure these make sense as to what loot can be obtained pertaining to each specific away mission, like getting syndicate pistols from Operative mobs and such.

**Comment by shrimptk** [comment]
I also had a few ideas that for yog unique away missions, so whoever wants to work on these with me can pm me or whatever and we'll get things going.
