### ISSUE TITLE
Borers spawn way too late in the round

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#765]
### Expected Behaviour

Borers having enough time to greentext
### Actual Behaviour

Borers physically incapable of greentexting because they can't reproduce in the 15 minutes it takes for the shuttle to come and leave the station
### Steps to reproduce the problem
1. Be borer spawned at 13:00 with shuttle 5 minutes from docking
2. Require 10 borers to escape
3. Auto redtext ;_;

**Comment by oisin100** [comment]
Git gud. Same happens with revenant.

**Comment by ShadowDeath6** [comment]
revenants happen like all the time and it's fine

also revenants aren't held by time constraints like chemical regen

**Comment by Alblaka** [comment]
We either have to make borers apears more early, which means they could screw over other game modes more, WHICH IS GOOD BECAUSE IT WOULD BREAK UP THE GAME MODE META.
Or alternatively just scale the amount of borers required to greentext on time, as well (less, the longer the round's already running).

**Comment by Groudonmaster** [comment]
Borers ten minutes in please

**Comment by Cruix** [comment]
How long, on average, does it take for a bored to reproduce once it has a host?

**Comment by ShadowDeath6** [comment]
If a borer is solely focused on reproducing, meaning no chemicals for healing, punishing, host being knocked unconscious, etc, it takes probably 3-4 minutes if I could give a rough estimate. However, borers aren't usually doing nothing but reproducing, so they need to wait the extra time for any other abilities they use.
