### ISSUE TITLE
Ticket Bug

### ISSUE THREAD

**Issue by SKR6DarkVoid** [yogstation13/yogstation-classic#766]
### Expected Behaviour

Able to restart server
### Actual Behaviour

If a player has the last ticket and resolves it them selves it disables the option to restart the server for round end
### Steps to reproduce the problem
1. player makes ticket
2. player resolves their own ticket
3. server does not have the restart option because an admin did not resolve the last ticket, a player did.

**Comment by ShadowDeath6** [comment]
:^)

**Comment by FluffySurvivor** [comment]
b-but muh restart breaking

**Comment by Time-Green** [comment]
IMO plebs shouldn't be able to close them at all.

**Comment by SKR6DarkVoid** [comment]
Unfortunately plebs are able to resolve their own tickets if there is no answer to them or an administrator has not claimed the ticket.

I believe a few lines of code to prevent players from resolving their own tickets should fix the bug itself, for example, when the lines are added, a player makes a ticket, it completely removes the resolve button from the players view, disabling them from resolving their ticket.

**Comment by FluffySurvivor** [comment]
Only player-made tickets can be closed by the plebs themselves

**Comment by SKR6DarkVoid** [comment]
> Only player-made tickets can be closed by the plebs themselves

True, and I feel that feature should be removed for them to resolve their own ticket, especially if its the last one, as it bugs the restart option for administration, even restart votes don't work during the bug even if I deadmin,  

OR

Add the hard restart option for ModV2's <-- this would be easier IMO, its just another flag to add to the admin-ranks.txt file.
