### ISSUE TITLE
Immovable rod bug = Impossible repair

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#768]
### Expected Behaviour

Immovable Rod stops existing after the event.
### Actual Behaviour

Repair is not possible if the rod returns to the same place repeatedly if it cannot find enough material and continues to fly and breach the area forever.
### Steps to reproduce the problem
1. Have immovable rod event.
2. Have small amount of material in the way.
3. Don't try to repair the area, ever.

This is stupid -> ![ss13-immovablerod-bug](https://cloud.githubusercontent.com/assets/16806055/14226257/5a89cf48-f8dd-11e5-9f95-a4016e8e0291.png)

**Comment by Time-Green** [comment]
The immovable rod spawns in a random z-level and direction.
Once in the 1000 times it will loop through station and cause lots o' keks

**Comment by oisin100** [comment]
But its fun watching multiple people get slaughtered by the rod...

**Comment by ShadowDeath6** [comment]
feature

**Comment by FluffySurvivor** [comment]
Looping rods are retarded, no doubt. 
Yet, not a bug.

**Comment by 00aquir** [comment]
Well I hope the coders didn't intend for it to go like that.

**Comment by ghost** [comment]
feature
