### ISSUE TITLE
Wizard round modifications

### ISSUE THREAD

**Issue by Xantam-13** [yogstation13/yogstation-classic#77]
Suggestion:
Remove EI NATH - Disintegration. Makes players miserable as they die. And too easy for wiz. 
Remove polymorph wand from the summon spell. It's enough to grief rounds.

**Comment by B1gb3ast** [comment]
But I haven't had my ONE PUUUUNCH wizard round yet.

**Comment by Super3222** [comment]
If this flies, rip the ultimate combo of ei nath + magic missle.

**Comment by Xantam-13** [comment]
Give wizards a challenge

**Comment by ghost** [comment]
Against.

Wizard is supposed to be ridiculously overpowered.

Ei nath is already inhand. Should stick. Perhaps make it so that if the wizard accidentally clicks themselves they also gib.

Suggestion-Remove bind soul, it's way worse than Ei Nath. At least Ei Nath wizards you can shoot.

Summon magic should create antags just like summon guns does, otherwise we might as well totally remove summon magic since it's only an excuse to grief.

**Comment by Xantam-13** [comment]
Make EI NATH force-click then. Like Ling. Instead of just being stood there, click the spell then click the person. Giving them chance to run. I'm trying to make it more balanced, instagib is OP.

**Comment by ghost** [comment]
That's what it is now.

It's an inhand sprite.

You click the guy and they die. No more 'click spell as you run past and they explode'

**Comment by shrimptk** [comment]
Adam is right, playing wiz shouldn't be all about making having the hardest round ever as a solo antag, it should have enough variation in spells so you can make it easier or harder for yourself. The most recent changes to Disintegrate were enough to keep it balanced.

**Comment by Crazyhyperway** [comment]
This is a good idea. Makes wizard uber easy. 

Alternative idea: Give a cap on the spell per round?

**Comment by X-TheDark** [comment]
Maybe just replace it with Death Bolt? Same instant-kill potential, but harder to execute and doesn't work with stuns (if you make it work like fireball where you can't hit grounded targets).

**Comment by Silvaplex256** [comment]
Wizard is meant to be insanely overpowered. They can murderbone all the fuck they want and still be admired in deadchat. Against, as this is what wizards are meant to be.

**Comment by BadminBen** [comment]
Against removing the spell. thats the point, you think any super powered magical being doesnt have a fuck you spell? 

just accept the suffering.

Remove EI NATH - Disintegration. Makes players miserable as they die. 
I loled when i seen this honestly.

**Comment by Hydre** [comment]
We need a salt request tag

Tbh not everyone picks disintegrate. 
Perhaps raise the cooldown?

**Comment by george99g** [comment]
I'm guessing this was disagreed on, so closing.
