### ISSUE TITLE
Shadowling Ability Bug

### ISSUE THREAD

**Issue by LesVegetables** [yogstation13/yogstation-classic#775]
### Expected Behaviour

Ascended Shadowlings can use their abilities
### Actual Behaviour

Only lightning works
### Steps to reproduce the problem
1. be thralling someone
2. ascend while thralling them and having them grabbed (the thralling doesn't stop)
3. the only ability you can use is lightning and the person you were thralling teleports back to you at all times if they are pulled away

**Comment by ToGWtF** [comment]
You don't need to get a grab to thrall someone

**Comment by LesVegetables** [comment]
I know you don't have to have them grabbed but if you do while you are doing this the person will keep teleporting back to you and your abilities are all stuck on cooldown for some reason. The main issue seems to be ascending while performing other channeled actions
