### ISSUE TITLE
Is it a bird? Is it a plane? No, its a fighter pod!

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#778]
So @KMC2000 came up with the idea of porting http://wiki.ss13.co/Space_Pod from goon.
But then we talked about having construct able pods using pod walls and pod floors and a pod controller to make custom pods in any shape you want. A bit like Starmade if you have ever played that game before.
I think something like this could be possible in SS13 and not too hard to do codewise.

Thoughts on the balance and usage of such pods?

**Comment by Kmc2000** [comment]
Inb4 clown makes flying space penis and fires 50mml freedom dispensers at the syndicate shuttle and absolutely wrecks face

**Comment by ToGWtF** [comment]
relevant   https://www.reddit.com/r/SS13/comments/4bghos/we_have_done_it/
https://www.youtube.com/watch?v=Fz-EhPxlVvk

**Comment by ParagonPrime** [comment]
inb4 some idiots turns the WHOLE STATION into a pod

though i would like to be able to cut away the bomb testing range and just... fly off...

**Comment by ShadowDeath6** [comment]
Put a mass driver onto the pod and launch maxcaps at the station

**Comment by oisin100** [comment]
> Put a mass driver onto the pod and launch maxcaps at the station

That all part of the plan.

**Comment by Kmc2000** [comment]
If you can pull this off osin, i'll be damn impressed

(And the first clown to make a penis shut to)
