### ISSUE TITLE
Sleepers on the syndicate shuttle are unusable by syndies

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#779]
Probably since they require medical access to actually use. The only way I can see this being resolved is either by making sleepers be able to be used by people with syndicate access, or make a special child of the sleeper specifically tailored for them.

**Comment by Cruix** [comment]
I've been able to use them before, they are supposed to have the access restrictions lifted.

**Comment by Super3222** [comment]
I just tested this and it appears nukeops don't have access to them.

That is unless they emag the sleepers, which is a **bad** idea.

**Comment by Cruix** [comment]
Ah, the station must have been at red alert when I used it. This is an easy fix, I'll push it soon if I can make the map merger work.

**Comment by Cruix** [comment]
Ah, the station must have been at red alert the time I used them, so the access was temporarily lifted.

**Comment by ShadowDeath6** [comment]
It's for syndieborgs :^)

**Comment by Cruix** [comment]
Oh shit you're right I might have been a syndiborg then.

On a related note syndiborgs should stop their human masters from leaving the syndicate base so they don't get hurt because of law 1 and stuff but that's an issue for another day.

**Comment by ToGWtF** [comment]
easy. varedit the two sleepers to have req_access = list(150)   instead of list(5).

I would, but im retarded and my attempt left me with 1000+ changed lines

**Comment by Super3222** [comment]
> I would, but im retarded and my attempt left me with 1000+ changed lines

map merge
map merge
map merge

**Comment by ToGWtF** [comment]
You think I didn't?

**Comment by Cruix** [comment]
You ran "Prepare Maps" before changes and "Run Map Merge" after changes, right? And on "Run Map Merge" you selected z2, which is option 3?

**Comment by ToGWtF** [comment]
Yes, Yes, and Yes. 

Prepare Map
Open DM
Make Changes
Compile
Map Marge
Run Git
1000+/-
Cry
Drink
Cry some more
Drink some more
