### ISSUE TITLE
MAKE SPACE GREAT AGAIN

### ISSUE THREAD

**Issue by MacHac** [yogstation13/yogstation-classic#780]
# Space.  The Final Frontier.

Also, the most boring one.

People rarely go out in space anymore, and those that do don't bother to explore.  Why?  Because, thanks to the open source map and limited things to do in space, any player can have the position of everything worth having outside of the station memorized.
### How, you ask, can an open source station make things fun to explore again?

I propose that a new system be put in space, similar to the one that can be found on the asteroid.  On the asteroid, during the course of one's mining, one can locate a buried room full of LOOT.  This LOOT can range from valuable to worthless.  I propose that a similar system be put in place for the two empty z-levels, except scaled up a bit.  Ideally, space exploration would be high risk and high reward, with hostile mobs and valuable treasure.  And, it would be different every time.  One round, you might find an abandoned NanoTrasen ship, overrun by xenos but with a valuable treasure in the central vault.  Another round, you might see the remains of a space battle between a Syndicate shuttle and a Nanotrasen shuttle.  The loot and dangers would be different each time, and may not always be present at all.  This adds a sense of exploration.

Constructive, well thought out criticism is encouraged.

**Comment by ToGWtF** [comment]
Gateway maps when

**Comment by ShadowDeath6** [comment]
Inb4 traitors jump into space for eshields and guns from syndie ships

**Comment by ParagonPrime** [comment]
we can start just by varying loot spawns on existing z-levels; a new meta i keep seeing on nukies is stopping by the derelict teleporter for a free teleporter board. maybe change the chances of various high-importance things to spawn on certain z-levels?

**Comment by Kmc2000** [comment]
When i'm done with my super secret project, i can map you some old spess ships if you want

**Comment by MacHac** [comment]
Well, ideally, there would be two types of thing that could be found in space.  The first would be procedural, and very similar to the 'vaults' that are found in mining.  The other kind would be much larger, but much more limited. (i.e. it's not possible to have all or even most of the large things spawn at once)

@ShadowDeath6 Loot would be randomized and weighted, and more valuable loot would have more dangerous guardians nearby.  You can't rely on getting anything, although something of value is usually about.

**Comment by Super3222** [comment]
I'd love for space to be fun, engaging, and adventurous but with all the necessary limits so

> eshields and guns from syndie ships

doesn't happen.

I remember we had a gateway project going on, which Shrimp was working on. I'm pretty sure it's cancelled now.
#76 , #154

**Comment by MacHac** [comment]
Well, really, it depends on spawn rates.  I see nothing wrong with the VERY OCCASIONAL esword popping up, but only as rare loot.  More common stuff could include researchable items and materials, as well as fun things like costumes.

**Comment by Kmc2000** [comment]
Working on spess n' shit now
