### ISSUE TITLE
Testing cuffed grabbing and putting in transit pod

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#781]
Sometimes it seems that grabbing & pulling a cuffed person can be broken.

Tested with Nirnael.

> 12:02:56 - Nirnael - pulling with cuffs doesnt allow the cuffed to move
> 12:03:05 - Nirnael - and supposedly grabbing with grab intent shouldnt allow the grabbed to move unless resisted
> 12:03:16 - Nirnael - but grabbing with cuffs breaks everything
> 12:03:26 - Kn0ss0s - You managed to get me in there just fine though
> 12:03:40 - Nirnael - yeah but did you move before i tried to put you in?
> 12:03:51 - Kn0ss0s - Possibly not.
> 12:03:54 - Nirnael - well i did
> 12:03:57 - Nirnael - thats the thing
> 12:04:13 - Nirnael - when you move while im putting you in it works
> 12:04:30 - Nirnael - but when you move while im grabbing you it breaks restraint

**Comment by ToGWtF** [comment]
I think this was intended. A level one grab can just be walked out of, cuffed or not

**Comment by Cruix** [comment]
But if you are pulling them as well as grabbing, they should not be able to walk away if they are cuffed.

**Comment by DavidEdwards** [comment]
I think this needs more play testing, it could have simply been me failing to grab properly.

**Comment by ShadowDeath6** [comment]
Grabbing someone while pulling them will remove the pull, not sure about the other way around.
