### ISSUE TITLE
Remove statue room and replace it with Firefighting equipment

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#783]
### Expected Behaviour

Have places to hide
### Actual Behaviour

Slings get murdered in arrivals maint because they have no where to run

or 

traitors have no where to hide their misdoings
### LARGE LETTERS

The statues aren't even custom sprites, just renames of actual buildable sprites (Really, Mimekitty is the clown statue?)

They can be deconstructed at round start for free materials

NO ONE bothered to make any other statues

Naming statues after players to show achievements/praise them is apparently bad

**Comment by ShadowDeath6** [comment]
bring back garden tbh

the room to me is annoying honestly, it feels like coders / hardy / whoever did it just decided to remove a fun, however small, part of arrivals and turn it into a useless shit room

**Comment by ToGWtF** [comment]
Only thing I have to say about garden was I would rather have it a fully enclosed room to hide in.

**Comment by ShadowDeath6** [comment]
just remove the door from it so you can only access it through sekrit window

**Comment by Kmc2000** [comment]
Funnily enough i made custom icons to show the players

Buuuut nobody added them so shitty default statue cookie for you!

**Comment by ToGWtF** [comment]
discord me the sprites tomorrow, i had plans to re-add the statues to CentCom if we were allowed to make them reference players

**Comment by ghost** [comment]
use /tg/ box garden

**Comment by ParagonPrime** [comment]
only support if i get an AI core statue of Durandal :^)
