### ISSUE TITLE
More randomized seekrit loot

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#784]
### Expected Behaviour

Find phat lewt in hidden areas of maint
### Actual Behaviour

Its a worthless pipe painter that isn't even used anymore or a soviet uniform
### My idea

A new effect spawner thing that handles the randomized loot in maint, for seekrit loot. Collectable hats, pre-made ghetto weaponry, an extra chance for artifacts for R&D to research, fuzzy bunny slippers

**Comment by ShadowDeath6** [comment]
I think tg did that

phat loot

**Comment by ToGWtF** [comment]
Old server I used to play used to have monthly/bi-monthly map updates that moved the secret room around. It would be found the first round after update with mesons, but it was still fun to search for and be the first to find it
