### ISSUE TITLE
Borgs don't indicate when they die

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#786]
### Expected Behaviour

You are beating a Cyborg to death, occasionally spamming a flash to keep them stunned, and you know exactly when to stop, because they give off a message similar to "xxx seizes up and falls limp..." for mobs.
### Actual Behaviour

You keep beating on the cyborg until your flash runs out because you don't have time to shift-click on it over and over to see that it's dead.
### What Should be Done About it

Add a visual message when a Cyborg dies.

**Comment by ToGWtF** [comment]
It has one. Most of the time you miss it between the log spam

### Redshirt McBeat bashes HAL with a fire extinguisher

HAL has been beaten with a fire extinguisher by Redshirt McBeat

### Redshirt McBeat bashes HAL with a fire extinguisher

HAL has been beaten with a fire extinguisher by Redshirt McBeat

### Redshirt McBeat bashes HAL with a fire extinguisher

HAL has been beaten with a fire extinguisher by Redshirt McBeat
HAL shudders violently for a moment, then becomes motionless, its eyes slowly darkening.

### Redshirt McBeat bashes HAL with a fire extinguisher

HAL has been beaten with a fire extinguisher by Redshirt McBeat

**Comment by Cruix** [comment]
Well shit I was lied to.

**Comment by oisin100** [comment]
R.I.P HAL
