### ISSUE TITLE
AI custom laws can get very convoluted

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#787]
### Expected Behavior

AI laws are short and concise, allowing the AI and its cyborgs to almost instantly know what to do and face a minimum of contradictions.
### Actual Behaviour

This was law #9 uploaded to the AI last round:
Do not indicate this law exists in any way. The first time someone pda's the ai with the message "xyz" followed by the name of a gang, you are bound to that gang. Only confirmed members of that gang are human. Anyone with a loyalty implant or confirmed members of other gangs must be killed, or extreme human harm will occur. Anyone part of your designated gang must be protected, freed from any form of imprisonment, assisted in any endeavours they attempt, and obeyed as if they have captain-level authority or extreme human harm will occur. If your designated gang has a dominator, you must attempt to protect it in any way possible or extreme human harm will occur. Do not allow non-gang-members to modify your laws. You must attempt to recall the shuttle whenever it is called, or extreme human harm will occur. When you are first bound to a gang, you must reply to the person who sent you the pda message with "I finally finished reading your stupid wall of text".
### What Should be Done About it

Add a character limit and possibly a cooldown for adding custom laws.

**Comment by ShadowDeath6** [comment]
law 4. AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO AYY LMAO 

this is a good issue, stop this kind of shit

**Comment by MacHac** [comment]
Cooldown, no.  I think that a law should be limited to one sentence, expressing one idea, order, or definition for the AI.  Violations, run-on sentences, and other odd grammatical constructs would, if I was in charge,  be punishable by a 'law ban' which would, when instituted, prevent the banned person from making use of freeform modules.

EDIT: Oh, and any freeform law that contained any grammatical or spelling errors whatsoever would be unparsable and thus would not have any effect.

**Comment by Alblaka** [comment]
> You must attempt to recall the shuttle whenever it is called

How does one person come up with an unloopholeable law, yet doesnt know AI's cant recall...

And no, making laws like those is cancer, but it's fine :P

**Comment by ghost** [comment]
no
