### ISSUE TITLE
Ghost Follow is super messed up

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#788]
### Expected Behaviour

Regular follow list to show up
### Actual Behaviour

http://imgur.com/LMUeobw
### Steps to reproduce the problem
1. Be dead.
2. Click follow from ghost tab.
3. Get image.

**Comment by ShadowDeath6** [comment]
can this be critical or high priority tagged because this is cancer

**Comment by MacHac** [comment]
The new list is fine.  It lets you search for things.  That's a plus.

**Comment by DavidEdwards** [comment]
You have to double click- that isn't obvious at the moment.

**Comment by ShadowDeath6** [comment]
> search for things

You could always search for things, just hit the first letter until the thing you want comes up. If this was an intended change, I didn't see anybody asking for it.

**Comment by ShadowDeath6** [comment]
apparently this was intended?

**Comment by DavidEdwards** [comment]
It was intended. If you actually have an issue with it let me know, it was designed to make your life easier.
