### ISSUE TITLE
Honkbots murder malicious midid

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#789]
### Expected Behaviour

Play a midi, plebs rockin out
### Actual Behaviour

Some fuckboi honkbot honks near the host of the sound and stops all sounds, midi is killed, i cri
### Steps to reproduce the problem
1. Play midi
2. Be near a fuckboi honkbot
3. Cri, errytiem

**Comment by ShadowDeath6** [comment]
Honkbot honk projectile op

**Comment by Groudonmaster** [comment]
Solution: Don't play MIDIs while the server is already having issues.

**Comment by Kmc2000** [comment]
Issues of honkbots.....? 

This is literally playing a midi? ghosting around and being NEAR a honkbot

How is that having issues, it's a bug

**Comment by ShadowDeath6** [comment]
honkbots > admins confirmed a feature

**Comment by Groudonmaster** [comment]
Nah the runtimes and stuff. Gotta be delicate m8

**Comment by FluffySurvivor** [comment]
> honkbot application when
