### ISSUE TITLE
Make beepsky's lights alternate between red and blue, a la police car.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#79]
BEEP BEEP MOTHERFUCKER THE POLICE IS ON THE WAY.

**Comment by shrimptk** [comment]
This would look really cool with Taco's new lighting system, but if it were only active during arrests (e.g When beepers goes in for the kill) it would be kinda annoying to have it rapidly toggle on and off, however if it could be activated if someone called beepers using a PDA control and he started blaring lights and sirens on his way to the scene that would be fucking rad as shit.

**Comment by TehFlaminTaco** [comment]
Resolved.

**Comment by george99g** [comment]
Implemented by @Cruix with #84
