### ISSUE TITLE
Comms consoles don't work with head IDs randomly.

### ISSUE THREAD

**Issue by halueryphi** [yogstation13/yogstation-classic#790]
### Expected Behaviour

Trying to use a comms console with a head ID
### Actual Behaviour

Sometimes the head ID wont open the console, but another ID may.
### Steps to reproduce the problem
1. Have a head ID
2. Try to login to a comms console
3. Pray that it randomly lets you unlock the console.

**Comment by ShadowDeath6** [comment]
did you check if the console was powered?

**Comment by halueryphi** [comment]
Yes, I even tried taking apart a console from somewhere else that I made sure was powered and putting in a comms board from tech storage and the same thing happened. I ended up having to emag it to get it to work.

**Comment by ToGWtF** [comment]
Are you holding it? Equipped in your ID slot? In your PDA in your ID slot?

**Comment by halueryphi** [comment]
Oh god I'm an idiot. Please disregard.

**Comment by ShadowDeath6** [comment]
:^)
