### ISSUE TITLE
Coders get alerted about unclaimed tickets.

### ISSUE THREAD

**Issue by TehFlaminTaco** [yogstation13/yogstation-classic#791]
### Expected Behaviour

Coders sit happily in their ignorance of the tickets that remain unclaimed.
### Actual Behaviour

TICKET #2 IS STILL UNCLAIMED!
### Steps to reproduce the problem
1. Be a coder.
2. Tickets be made.
3. Be annoyed.

**Comment by MacHac** [comment]
I think that's just hooked into the adminlog.

Is it really that terrible to the tickets that the admins can't be assed to handle?

**Comment by TehFlaminTaco** [comment]
Basically, if only coders online, we can't sit there and ignore tickets like normal, because BOINK BOINK BOINK BOINK

**Comment by DavidEdwards** [comment]
Yeah that's a good point. If coders can't handle all kinds of tickets, they shouldn't be bugged about it.

That said, you can disable ahelp boink noises. Theres a preference for that.

**Comment by oisin100** [comment]
Perhaps make the boink noises preference also disable the ticket notifier.

**Comment by TehFlaminTaco** [comment]
I like to keep boink noises active incase I am boinked, or a ticket appears that requires me.
