### ISSUE TITLE
Xeno Surgery & Experimentation

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#8]
opened by Ben · 4 months ago
Currently when Aliens or Lings are captured they are put into Xeno Secure cell and have nothing else to do. its a research station so some amount of experimentation should be present.

**Comment by Hydre** [comment]
There is a pretty large thread on the forum somewhere discussing possible changes to lings.

EDIT: fountit http://forums.yogstation.net/index.php?threads/ling-blood-tests.2941/
