### ISSUE TITLE
sec armor idea - insulated vest/riot suit

### ISSUE THREAD

**Issue by apneaman** [yogstation13/yogstation-classic#800]
### Expected Behaviour

With the talk of balancing rev round maybe introducing new sec gear could help. Strictly armoury/RnD items as well

Insulated vest: function is similar to body armour except sacrifices brute protection for stun immunity only if targeted on chest would be useless against disabler

Insulated riot suit: same principle protects full body but leaves head exposed. Possibly add helmet extra to double as a tesla protection

Only have 2-3 in armory and the remainder would require high level research and resource.
### Actual Behaviour

Getting taken down by a suprise stunprod/taser and toolboxed to death outside of brig
### Steps to reproduce the problem
1. Notice a revolution in progress
2. Kit up in riot gear as a sec team ready to kick ass
   3.all Get tased by a naked assistant and toolboxed

**Comment by ShadowDeath6** [comment]
> be traitor
> take stunproof riot gear
> double esword
> literally invincible

**Comment by FluffySurvivor** [comment]
> non-antag stun immunity

ahahah wat. 

How about you don't let people close to you or dodge the tasers?

**Comment by Groudonmaster** [comment]
This actually sounds like a decent idea but I've got a branching idea. I'll reference it in just a moment.

**Comment by apneaman** [comment]
Ok then remove riot suit option from armoury and make it research 5 combat systems. 

But the vest is a decent option as it is only a chest protection. 
Another example of problem, rev round only 3 sec left, get kitted up in riot gear with the hos ,warden stays in the  brig. walk down the hall below brig two taser bolts fly up the hall from below followed by a bunch of guys with spears. Riot armor does nothing but delay the time until death while getting shitkicked by 3 at once

**Comment by Super3222** [comment]
> Ok then remove riot suit option from armoury and make it research 5 combat systems.

Not happening.

And we don't need a whole new suit that protects you from all-stuns. We can just make riot shields protect you from stun batons, which will in effect protect you from stunprods.

**Comment by apneaman** [comment]
I like it, seems like a balanced step in the right direction.

**Comment by ShadowDeath6** [comment]
> make it combat 5
> giving R&D roundstart access to stun immunity

AYY LMAO

**Comment by Super3222** [comment]
I'm working on it.
