### ISSUE TITLE
Ian is a 4th dimensional being

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#801]
No but really. Ian can go through airlocks and blast doors. Even windoors, but only in one direction so he cant go back out of them
# Feature?

**Comment by ShadowDeath6** [comment]
Ian was intended to have the same pass flags as drones, so yes, this was completely intended

**Comment by Groudonmaster** [comment]
It's still an issue then because windoors only allow Ian/Drones to go through one way then they're stuck

**Comment by ghost** [comment]
feature

**Comment by DavidEdwards** [comment]
Dont mess around Adam, this is a genuine bug if someone gets stuck because of it.

**Comment by ShadowDeath6** [comment]
Drones don't have that problem since all access and Ian can't get on tables by himself, so in the very unlikely case that he gets tabled and voluntarily moves through the windoor, he won't be able to get back, but this is probably extremely uncommon.

**Comment by ShadowDeath6** [comment]
@X-TheDark

**Comment by Groudonmaster** [comment]
Yeah but wasn't the point of adding the drone flags was to stop doors from opening?

**Comment by X-TheDark** [comment]
Yup, problem with windoors only checking these flags 1-way, so this actually is a bug that is specific with how windoors check for pass_flags defined on mobs. You can go in, but not go out without opening the windoor.
