### ISSUE TITLE
Some blobs are really bad

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#803]
### Expected Behaviour

All blobs to have their own nice effect to make them all somewhat equal
### Actual Behaviour

Certain blob types suck ass
### Steps to reproduce the problem
1. Be cryo blob
2. Reroll chem
3. Get energized fibers/EMP/Flammable Goo/Adaptive Nexuses
4. Die

**Comment by ShadowDeath6** [comment]
I'm gonna be fiddling with numbers on blob chems to see if it makes any noticeable difference, maybe also trying to fix EMP blob not EMPing on death ( or having a shittily low chance of EMPing on death) because that may or may not be a bug

**Comment by ghost** [comment]
EMP blob is supposed to EMP on dead

**Comment by ShadowDeath6** [comment]
I know, but since the EMP isn't visible it's hard to tell if it triggers or not.

**Comment by ShadowDeath6** [comment]
Succ
