### ISSUE TITLE
Traitor item costs

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#804]
I'd like to change costs on some traitor items, since some items are obscenely useful for their cost (emag) and some are borderline never used because they're not worth the cost (revolver ammo, 4 TC). I'll be making a thread on forums for feedback on other items but feel free to leave your opinion on this too. 
Thread on forums: https://forums.yogstation.net/index.php?threads/traitor-item-costs.10172/

**Comment by ghost** [comment]
Sure, I can see that. Reducing revolver ammo to 2 or 1 TC seems fair, seeing as you can hack an autolathe for the same.

Reducing revolver cost is good.

We can increase ebow cost and decrease esword cost, because eswords are never bought except in combination with the ebow.

Reduce the price of the silencer, too.

Increase emag cost to, say, 8 tc.

**Comment by ShadowDeath6** [comment]
I was thinking the same about emags, 8 tc seems good. 

I'm kind of 'eh' on ebow since you could say the same about it as the esword, and decreasing cost of esword makes dual esword much more potent.

**Comment by utahclock** [comment]
If you increase emag devrease hacked ai board

**Comment by ToGWtF** [comment]
hacked ai board is a crapshoot. normally you would think a player would enjoy getting to wreck shit as AI but once you hack them, they do everything in their power to loophole your law and fuck you over. the risk and price is not worth the reward

**Comment by ShadowDeath6** [comment]
Tbh I get kind of salty when I'm hacked/subverted as AI since I probably could have done something about it and then try to loophole it when I can.

AI board is 14 tc, that DEFINITELY needs lowering.

**Comment by Super3222** [comment]
rip combo cafe.

Oh wait, with this revamp I can still buy an emag and esword, emag testing range pins, and mass-print nearly an infinite amount of stun revolvers with no help from mining.

However, I would LOVE to see energy swords being used outside of combo cafe... and not just used for double eswords either.

**Comment by ShadowDeath6** [comment]
I don't want to nerf ebow >:^(

also combo cafe won't be killed, ebow and esword will be consistent with each other so buttbabies don't slap the controversial tag on my PR.
