### ISSUE TITLE
Regarding grief bombings

### ISSUE THREAD

**Issue by Hydre** [yogstation13/yogstation-classic#808]
We need a way to temporarily turn the bombcap to 0,0,0 to catch bomb griefers in the act without having to patch up a huge hole.

**Comment by DavidEdwards** [comment]
We already have the code to set the bombcap, perhaps a quick toggle switch would be good?
1. Default bombcap
2. Admin spots shenanigans
3. Admin clicks toggle, current bombcap value stored in a temporary variable, bombcap value set to 0
4. Shenanigans happen
5. Admin clicks toggle, bombcap set to value stored in temporary variable

@yogstation13/initiate-coders Should be relatively simple this one.

**Comment by Groudonmaster** [comment]
I'm pretty sure disabling atmos well also stop a bomb
