### ISSUE TITLE
Chemsprayers and the case of the missing reaction

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#812]
### Expected Behaviour

Bioterror chemsprayers cost 20 TC for Nuke ops, can come pre-filled with Traitorchems for ultimate crowd control

or

Chemsprayers cover a 3x3 area with water to slip people walking by

or 

Janitors fill it with space cleaner for ulitmate-instant no-slip cleaning
### Actual Behaviour

Reagent sprays were severely nerfed a year or so ago, and no longer inject chems upon being sprayed

or 

Chemsprayers only cover a 1x3 area with water

or

Actually this one works fucking beautifully.
### What can we do about it

We have a few options. At least how I see it
### 1.

 We re-enable chems to inject into someone upon being sprayed. This is the ONLY way to make the syndicate bioterror chemsprayer usefull again. As it is now, it comes with a number of super nasty bioterror chems, but the only reagent that takes effect is condensed capsaicin. This opens up a whole world of balancing issues. To do this, we would open up the way for round-start morphine spraybottles (Although not very effective) and acidsprays (Actually miss that one. Was the mediborgs only decent weapon while emagged). ~~That just sounds like too much trouble to deal with, and I think just isn't viable~~  Actually I'm not fully against it. We would just have to police people who grief with this. Doctors already get syringe guns fuck. Why not let them have fluacid sprays back
### 2.

 We make the Bioterror chemsprayer ditch the syndie-chems, and fill it to the brink with Pepper-spray and Space Lube. This would mean to use it, ALL agents would have to invest in no-slip shoes.  HOWEVER. The way the chemsprayer works now, rather than spraying a 3x3 area, it sprays a fucking **3x7 area**. Which, works well for spacecleaner as well. But holy shit. 3x7 area of lube. Fucking think of that. Thats glorious shitlording right there.
### 3.

 Think 2. without the lube. All pepper spray, lowered cost to laughably cheap. Seriously. It has 0 effect on security. Its just a way to control graytide armed with spears
### 4.

We let adam come up with a mix of cfl3 and phlog to put in it
### 5.

We ditch the item. Comment it out of uplink items. Hell, comment it out of the fucking code. They broke the thing so damn much I don't even want to look at it anymore.

**Comment by FluffySurvivor** [comment]
Totally up for a buff. The thing sounds too fun to just throw it down the drain.

**Comment by EMT321** [comment]
Just add it back to R&D already.

**Comment by ghost** [comment]
Add it back to R&D and let spraybottles inject chems again.

Adds more versatility to people using spraybottle murderchems, including the hilarity of spraybottle initro.

Plus the risk of spraying it while moving walking right into it and dying of your own deathmix as balance.

Clothes already block some injections, such as hardsuits and biosuits, + labcoats offer a minor resistance, so no reason not to.

**Comment by ShadowDeath6** [comment]
the only thing I'm against with this is making acid smoke/foam nades retardedly OP again

**Comment by oisin100** [comment]
> the only thing I'm against with this is making acid smoke/foam nades retardedly OP again

Who cares. I for one loved that.
