### ISSUE TITLE
Pinpointer doesn't show right position when disk is in the nuke.

### ISSUE THREAD

**Issue by halueryphi** [yogstation13/yogstation-classic#813]
### Expected Behaviour

If you space the nuke with the disk inside, the pinpointer should show where the new nuke disk spawns.
### Actual Behaviour

It shows a question mark even after turning it off and on after the new disk is spawned. This only happens when the old disk is spaced inside of the nuke.
### Steps to reproduce the problem
1. Put the disk in the nuke
2. Space it
3. Watch as your pinpointer gets broken for eternity.

**Comment by halueryphi** [comment]
Also for some reason the nukeop pinpointer also breaks, but it shows the disk as being underneath the table in the janitor's closet even though it isnt.

**Comment by ToGWtF** [comment]
It points to CentComs disk after the station one gets respawned.

**Comment by halueryphi** [comment]
Well if that's the case then I have ZERO idea why the nukeop pinpointer shows something different.

**Comment by ToGWtF** [comment]
Interesting. Captains pinpointer gives a ? when you space the disk, the nukeops points to CentComs disk.

**Comment by AsV9** [comment]
I swear to god this is the 2nd time I've fixed this wank ass bug.
