### ISSUE TITLE
Carpsuit

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#816]
### Expected Behaviour

you can swim with the fishies of the stars
### Actual Behaviour

the fishies of the stars eat you
### Steps to reproduce the problem
1. Space self
2. Find and befriend carp
3. Die
### Hao 2 fix

You should be able to combine a carp costume with a space suit (plus Syndie suit/Syndie hardsuit!). Literally all it does is make Carp love you no matter what.

totally not making this because i want CarpOps and spawning hundred of carp to slaughter the station

**Comment by FluffySurvivor** [comment]
all the yes
combine this with the carp extract buffs for marvelous results

**Comment by X-TheDark** [comment]
This only applies to Space Carp (from actual space), if you use the Dehydrated Carp thing, it won't attack you regardless of the suit thing (provided you use it in hand beforehand).

**Comment by ParagonPrime** [comment]
i know, but

a. fun gimmick thing that lets you tame normally spawned spess carp = fun
b. so you can actually look stylish when going full-carp strategy, less for the actual gimmick utility of it

**Comment by Super3222** [comment]
There's a space carp suit in the code that doesn't slow you down, and makes you recieve more brute damage because carps are wimpy.

It'd need some changes though for this.

**Comment by ParagonPrime** [comment]
I intend for this to be usable for nukies, sooo

**Comment by ToGWtF** [comment]
faction = list(Carp)  kek
