### ISSUE TITLE
Replace numerous dual-airlock sections with double doors

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#819]
As per this thread - https://forums.yogstation.net/index.php?threads/double-doors-but-why.10185/

Simple change. Replace a number of areas that have two airlocks side by side with a single double airlock. This will marginally reduce server strain, make an AI's job easier when it gets yelled at to set Sec to fast close, and generally pretty everything up a bit.

Not sure if there are any double door textures but the "standard" one that you can find on the escape shuttle medbay, but that should be dead easy to sprite.

Also, maybe make triple doors for the Primary Hallways and their entrances? But that can wait a while since we don't even have that in the code.

Current areas that would recieve such a change:

-Sec lobby area thing (4 doors to 2 doors)
-Medbay lobby
-Both Chapel entrances
-Both Library entrances (one shared with Chapel)

**Comment by ToGWtF** [comment]
I kinda like some areas only having one door. Easier to bodyblock certain people from getting in.

**Comment by timkoster1** [comment]
Why can't we make a 2x1 door?
They already exist on poaces such as escape shuttle.
Just some sprites and acces and this should work perfectly.

**Comment by TheSadFox** [comment]
If someone can be bothered to sprite additional two-tile airlocks, that would be pretty neat and would improve stations aesthetics a lot.

**Comment by DavidEdwards** [comment]
Consideration:

Security: That means you need two people to go through at once to stop unwanted people trolling security. Normally body blocking would ensure only one person can enter at once.

Sure, you can arrest anyone silly enough to get stuck in the between space. But it does mean extra work to limit the flow.

**Comment by apneaman** [comment]
For the sec door.. thats why there's a double layer door to prevent them entering. The problem is that if its out of sync there is not much you can do behind the desk to stop say a mob trying to rush sec once the door is open

**Comment by Notamaniac** [comment]
Keep in mind there are twenty frames of 32x64 pain to sprite for each individual double door, and there's going to have to be some sort of special case when someone decides to deconstruct the door.

**Comment by ParagonPrime** [comment]
we already HAVE dual airlocks
we just have to sprite red/yellow ones and blue racing stripe ones and then we're fucking golden

**Comment by apneaman** [comment]
I get the point about the sec door from the thread as it would be a pain if emagged to block. 

For construction not sure how to make it work. Possibly 2 airlock assemblys side by side plus an extra tool step merges them into one like the windows or contructing an assembly that takes up two tiles (one below one in front )

**Comment by Notamaniac** [comment]
Retextures are still painful to do, recolouring twenty sprites is not fun work

**Comment by Cruix** [comment]
We could alternatively solve this with code, and make pushing the button close both airlocks if either are open, and open both airlocks if both are closed.
