### ISSUE TITLE
Mod Jetpacks while they are on.

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation-classic#82]
Make it where... if a player toggles their jetpack while it's on their back they can pass over tables.

**Comment by shrimptk** [comment]
All jetpacks currently in ss13 are designed to only work in a weightless environment as a sort of 'guided thrust' system versus an actual jetpack. If this were to be implemented, it would have to only work if the requirements for the jetpack to function were met as well.

**Comment by Silvaplex256** [comment]
That doesn't mean jet packs shouldn't do this with tables when the gravity gen breaks.

**Comment by BadminBen** [comment]
Meh against this honestly. Pretend the ceiling isnt high enough to physically pass by while gilding,

**Comment by Groudonmaster** [comment]
> Can climb on top of and run on top of tables
> Can't glide horizontally past them?
> Ben at least make sense.
