### ISSUE TITLE
Add Diagnostic HUD's and Science Goggles to R&D, and nightvision versions.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#823]
Diagnostic HUD's are goggles that let you see a borg or bot's health, like a medHUD let's you see a human's health.

/tg/ has them, go look at their code as an example of what to port. They'd be unlocked alongside Sec and Medhuds in R&D.

Science Goggles let you examine containers to see what reagents are in them. Just add them to R&D alongside Sec and Medhuds.

Add nightvision versions of them too, unlocked along the same as the other nightvision things.

**Comment by Super3222** [comment]
Roboticists should also spawn with these like they do in /tg/.

**Comment by FluffySurvivor** [comment]
Aren't these a tad useless? 

Examining gives you a pretty good idea of the borg's health already tbh

**Comment by ghost** [comment]
Also lets you see medibots and borg charge

**Comment by Kmc2000** [comment]
Planning to nick tg's sprites as well badam? 

Or do you need sprites for this
