### ISSUE TITLE
Watch-list Flag edit button does not work

### ISSUE THREAD

**Issue by Crazyhyperway** [yogstation13/yogstation-classic#824]
### Expected Behaviour

I expected the button to edit the flag.
### Actual Behaviour

Type here what actually happens.
### Steps to reproduce the problem
1. Be on the watch list
2. Go to player panel, click "add to watchlist" 
3. Attempt edit, window does not pop up

**Comment by Groudonmaster** [comment]
I typically just remove and reapply.

**Comment by Crazyhyperway** [comment]
Of course, but mid round you may not be sure what the flag they have is.

Besides, the button exists so it should work.
