### ISSUE TITLE
Shadow's new shitty blobtype discussion issue

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#827]
refer to https://github.com/yogstation13/yogstation/pull/825

I forgot to make an issue for it oops

**Comment by Kmc2000** [comment]
How about hellwater

That would be fun and balanced

**Comment by ToGWtF** [comment]
alcoholic blob

**Comment by ShadowDeath6** [comment]
issues are for salt anyway
