### ISSUE TITLE
Incorrect Nuke Codes!

### ISSUE THREAD

**Issue by PineappleWolf** [yogstation13/yogstation-classic#828]
### Expected Behaviour

Admin gives nuke code
IT WORKS
### Actual Behaviour

Random code, doesn't work, can't self-destruct to destroy blob.
### Steps to reproduce the problem
1. Bitch at admins for nuke code after blob kills half the crew and remaining head of staff spam the request button
2. FINALLY GET CODE
3. Get disc
4. Put disc into self-destruct
5. Put code in.
6. CODE IS WRONG??
7. RAGE

**Comment by TehFlaminTaco** [comment]
Has something to do with the default type for the nuke code being different from the type it's expecting.
Admins need to manually force the code when it's asked for it.
But no matter what they set it to, does nothing.

**Comment by X-TheDark** [comment]
I set the code a few times to a number and people were able to successfully enter it, maybe blob auto-nuke code screws up the nuke proper.

**Comment by Cruix** [comment]
You have to manually set it as a number, setting it as text, which is the default, does not work.

**Comment by DavidEdwards** [comment]
Perhaps the lesson from this - is that we should make the system easier and less cryptic to use.

**Comment by X-TheDark** [comment]
Yeah, disallowing text and only accepting integers sounds good.

**Comment by Groudonmaster** [comment]
It's not that hard to figure out how to change it from text. Just hit (C) in the vv.

**Comment by PineappleWolf** [comment]
You misunderstand that people other than coders would understand that easily enough.

**Comment by ghost** [comment]
You misunderstand that people know they need to change it from text to numb.
