### ISSUE TITLE
Make QM an actual head of staff?

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#831]
### Expected Behaviour

Quartermaster to be an actual head
### Actual Behaviour

Isn't
### Steps to reproduce the problem
1. QM set to high
2. Join as QM
3. Cry when the revs ignore you because you're useless.

**Comment by Super3222** [comment]
Revs tend to ignore QM's because of their sunglasses or bum rush them with backup to rip them off and flash them.

And the QM shouldn't really be a head. Their department head is technically the HoP.

**Comment by AsV9** [comment]
Captain > HoP > QM > Assistants with shorts and caps.

**Comment by ParagonPrime** [comment]
QM should at least get fun toys like the other heads. Such as a desk announcement system, possibly a telebaton, and a unique PDA cartridge that allows you to remotely control the cargo shuttle (if an ID with relevant access is inserted)

**Comment by Groudonmaster** [comment]
When has a HoP ever interacted with cargo though? Once in a blue moon if you're lucky.

**Comment by ToGWtF** [comment]
He's got a cargo computer in his office

**Comment by DavidEdwards** [comment]
I'm against QM being an official head.

QM is generally a good role to pick if you are learning a leadership role, without running into the bannable nature of being an actual head.

**Comment by ShadowDeath6** [comment]
HoP leads QM. Rev rounds would play no differently since QM would get shitstomped because cargo is literally alway a cesspool of rev activity

**Comment by Kmc2000** [comment]
Solution: 

Give him a pet penguin

Why? 
So he gets the best bits of being a head but has no actual power except control over mr flibble

**Comment by ghost** [comment]
HoP runs cargo. QM is subservient to HoP.
