### ISSUE TITLE
Genetics Transformation via UI doesnt work

### ISSUE THREAD

**Issue by Alblaka** [yogstation13/yogstation-classic#832]
### Expected Behaviour

Using an UI injection will turn you into an exact copy of the person the UI comes from, both in appearance, face and voice.
### Actual Behaviour

Appearance changes, but voice and 'examineable identity' remain the old one, making it useless for disguising.
### Steps to reproduce the problem
1. Sedate poor victim.
2. Stuff into scanner.
3. Create UI Injector
4. Injector yourself, get the victim's appearance
5. Wear victim's ID and be displayed as 'Original identity (as Victim)'
6. OPTIONAL - Get lynched / wear mask and remain silent

**Comment by ShadowDeath6** [comment]
Use UE injectors.

also git the fuck gud

**Comment by Alblaka** [comment]
> Use UE injectors.

There's UI and SE.
UI is appearance, SE is special ability blocks/monkey.

Or am I missing something critical?

...

reads https://tgstation13.org/wiki/Guide_to_genetics

FFS THERES THREE INJECTION TYPES NOW?! Gah... nevermind then, close this
