### ISSUE TITLE
Gamemode - Woodland Critters

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#837]
I've had this as a [reminder in my inbox](https://www.youtube.com/watch?v=_dJQSIQwl6c). Thought I'd post it here.

I thought that South Park Woodland Critters would be hilarious.

**Comment by Kmc2000** [comment]
OH GOD SATANIC ANIMALS THAT RAPE EVERYONE OIN A GIANT BLOOD ORGY

Well.... 

Could be fun.....?

**Comment by DavidEdwards** [comment]
I had always imagined that the objective would be to gather items for the manger and a victim to summon the anti-space-jesus. Though this is an incredibly silly idea, and I really don't expect to do anything for it xD
