### ISSUE TITLE
Security Cameras list not popping up while using them. (Borg)

### ISSUE THREAD

**Issue by Crazyhyperway** [yogstation13/yogstation-classic#843]
### Expected Behaviour

The camera list would come up.
### Actual Behaviour

A borg used the security camera system in science, and he expected the window to popup showing the list. It got stuck viewing the camera, even if he logged out and logged back in. I managed to fix it by either changing sec_hud to 1, which was at 2 originally.
### Steps to reproduce the problem
1. Be borg
2. Use security camera system
3. ??

**Comment by ShadowDeath6** [comment]
Borgs not being able to use cameras is intended, not sure about the list bug though.

**Comment by Cruix** [comment]
I am fairly certain this is not intended. Borgs should be able to use camera consoles.

**Comment by Crazyhyperway** [comment]
I guess that is the problem.
