### ISSUE TITLE
Add a HuD for door functionalities, AI only

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#846]
### Expected Behaviour

Be malf, shock all the doors
### Actual Behaviour

Accidentally deshock doors because you don't know which doors are already shocked and which are not without checking manually and wasting time. 
### Steps to reproduce the problem
1. Be malf 
2. Shock
3. Deshock in confusion

So yeah, add a toggleable hud for non-obvious door functions, like safety override, shock and such.

**Comment by ParagonPrime** [comment]
Makes sense that an omnipotent AI should be able to see what it actually shocked.

Should also show bolts, if door is depowered, etc...

**Comment by Cruix** [comment]
#844 adds messages for when you shock/de-shock a door with alt-click.

**Comment by FluffySurvivor** [comment]
yeah that doesn't help besides spamming your logs

You need to SEE what you can alt-click and not
