### ISSUE TITLE
Ling weak pls buff

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#848]
### Expected Behaviour

Lings to have some chance to fight back after abductors / fixing themselves after being abducted
### Actual Behaviour

Lings are permafucked because they cannot do anything against abductors after being abducted
### Steps to reproduce the problem
1. Be ling
2. Get abducted
3. Try to fight back
4. Can't do shit
5. Have to deal with a retarded organ

Maybe porting the biodegrade ability that breaks cuffs or making panacea delete any nonhuman organs and replace them with regular organs.

**Comment by Super3222** [comment]
> panacea delete any nonhuman organs and replace them with regular organs.
> 
> deletes nonhuman organs
> all of other changeling organs get deleted
> no longer a changeling
> gg

Also biodegrade doesn't just break cuffs, it breaks straight jackets as well, and other things that restrain you.

If the agent did their job, and probed you to see if you were a changeling or not, than they would've let you go possibly (since you're working for the same person, someone don't bring up the 'hold on here, antagonists can kill whoever they want xdddd  i want their loot' bullshit.' To me it's like saying you could kill another rev because you wanted their access). However abductor - chang interactions are always interesting when you transform into one of them.

**Comment by ShadowDeath6** [comment]
The only problem, super, is that it's nigh impossible to kill an abductor as ling unless they're bad and don't use sleep mode.

**Comment by TheSadFox** [comment]
> Be ling
>  Get abducted
>  Try to fight back
>   Can't do shit
>   Have to deal with a retarded organ
> 
> Be ling
>   Run away as soon as you see an obvious as fuck dildo sprite
>   Don't have to deal with a retarded organ

Or just deal with the fact that abductors can cuck you?

**Comment by ShadowDeath6** [comment]
you can't run away from stun+sleep cheese, seiko

**Comment by ghost** [comment]
Deal with spooky abductors or just use your bullshit stun resist powers to resist out.

Or just vomit spiderlings on their shuttle and watch as they don't notice until they're suddenly killed by giant spiders.

**Comment by ShadowDeath6** [comment]
adam, you can't use bullshit stun resist when you're KOed
literally abductors can stun+sleep faster than you can kill someone with a pulse rifle

**Comment by FluffySurvivor** [comment]
yo what do you mean

unless you're standing next to the portal it's very hard to get stunned/sleeped 

> melee
> claims uncounterable 
> ahahahah

**Comment by ShadowDeath6** [comment]
> abductor hides in corner
> tases ling
> sleeps
> totally counterable git gud kiddo xDDDD!!

**Comment by FluffySurvivor** [comment]
> not using adrenals
> deserves to get cucked

**Comment by TheSadFox** [comment]
> Gets suprised
> With thermals
