### ISSUE TITLE
Cursed Katanas from abandoned crates dont have nodrop

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#850]
### Expected Behaviour

Cursed Katana from the "Cursed Items" event cannot be dropped or put into any inventory slots
### Actual Behaviour

Miners fine one in an abandoned crate that has slot_flags = null but can still be dropped since the event didn't trigger.

**Comment by ShadowDeath6** [comment]
you mean the regular katana from crates?

**Comment by ToGWtF** [comment]
it can either be the regular one or katana/cursed  which cannot be put into a backpack/belt slot and is part of a random event that makes "cursed" items that cannot be dropped

without the event triggering, the katana isn't made undroppable.
