### ISSUE TITLE
Antag Weight Information

### ISSUE THREAD

**Issue by TehFlaminTaco** [yogstation13/yogstation-classic#852]
We need an easy way for players to see how much antag weight they have, in preferable both word and number form, so they can get an idea of what 400 weight actually means.

**Comment by ShadowDeath6** [comment]
now I can see how much RNG has been gimping me :+1:

**Comment by DavidEdwards** [comment]
My first impression was to close this with the comment "I don't want people gaming the system knowing what their chances of being an antag are".

However, thinking about it a couple more times, I don't think that would really happen.

Open to thoughts on this one.

**Comment by ParagonPrime** [comment]
I don't think people are really gonna try to 'game the system' any more than they used to.

I mean, the idea of 'if I don't get antag this round I'm gonna suicide' has been around for ages, way before the weight system.

No, letting us see our weights is a good thing- maybe even that of others in the lobby pre-roundstart? Or just our weight vs the 'default' weight.

**Comment by DavidEdwards** [comment]
Definitely NOT letting users see each others weights. That is a recipe for disaster. Then you will have a better idea of who may become an antag.

**Comment by ShadowDeath6** [comment]
I wanna see my antag chances though

Also maybe make a system to see what the number means as per the OP
