### ISSUE TITLE
The big bad shadowling salt issue / recommendations

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#853]
### Expected Behaviour

Shadowling to be balanced
### Actual Behaviour

it isn't
### Steps to reproduce the problem
1. Play shadowling
2. Ascend in 30 minutes because it's ezmode
3. spam "ayy lmao" in broadcast

Recommendations:
1. Icy veins cannot put out torches at all
2. Flares have a chance (25% or so) to resist being put out from icy veins
3. Loyalty implants in addition to regular surgery can dethrall people
4. Shadowlings can't enthrall braindeads / ghosted players
5. Remove / decrease mute time on glare so people can scream when they're being violated
6. Decrease glare's stun time

**Comment by ToGWtF** [comment]
I can make shadowwalk require a certain number of thralls, and make dragging people while shadowwalking require a neck grab.  

Before they had shadowwalk, all it took was a persistant borg spamming its flashlight on an off to chase them down in maint

**Comment by ShadowDeath6** [comment]
shadowwalking isn't the problem you pleb, it's the vastly overpowered actual abilities shadowlngs have

**Comment by ParagonPrime** [comment]
Only problem with not being able to thrall braindeads is that people will ghost just as they're being thralled just to dick with the slings.

**Comment by Alek2ander** [comment]
:smiling_imp: AYY LMAO :smiling_imp:

**Comment by Super3222** [comment]
Buy floodlights from Cargo...

**Comment by ShadowDeath6** [comment]
Super, floodlights are an area thing, so a shadowling can just run up, glare someone, pull them away, and drag them for 10 seconds while they're stunned and muted.

Also, ghosting COMPLETELY takes someone out of the round, so it's not like people are going to do it as soon as they get captured.

**Comment by abdbla** [comment]
"Also, ghosting COMPLETELY takes someone out of the round, so it's not like people are going to do it as soon as they get captured"

You'd think people aren't shit, but they are. 

"Recommendations:
1. Icy veins cannot put out torches at all
2. Flares have a chance (25% or so) to resist being put out from icy veins
3. Loyalty implants in addition to regular surgery can dethrall people
4. Shadowlings can't enthrall braindeads / ghosted players
5. Remove / decrease mute time on glare so people can scream when they're being violated
6. Decrease glare's stun time"
1. Make it something like 25% chance not to put out 
2. Flares are too easy to get to resist icy veins 
3. This sounds reasonable 
4. Refer to previous segment 
5. This sounds reasonable if it's not lowered to 15 seconds mute. 30 second mute is better
6. No.

**Comment by ShadowDeath6** [comment]
1. Shadowlings have more than enough stuns to get away from people and making it instant gg teleport through walls with one ability is annoying. Torches take SOME time to get and they should be harder to put out.
2. eh, whatever
3. as long as you agree I guess
4. If people wanna permanently take themselves out of the round, whatever. Going braindead while being enthralled doesn't do anything, the shadowlings just can't INITIATE enthrall on people who are braindead.
5. Glare right now is an instant GG. If a shadowling gets you they have a stupid amount of time to take off radio and you can't do shit. Getting a chance to yell is fair.
6. le totally fair 20 second stun meme

**Comment by ghost** [comment]
Okay.

So here's how we're going to fix it.

Firstly.

Enthralling-No longer penetrates loyalty implants. No more cheese enthralling sec officers. Implanting people has a use.

Dethralling surgery-make last step require a scapel to remove the organ, not hands, so mediborgs can deconvert too. Speed up time of steps so it's no longer an absurdly long annoying process with a thrall glaring at you ever 3 seconds.

Icy veins-

No longer extinguishes torches.

No longer extinguishes flares.

They were never intended to be extinguished and the change that made them extinguishable is dumb.

Shadowwalking-
Move at golem walkspeed when in walls, so you can't cheese around hiding in walls endlessly.

Enthralling braindeads/ghosteds-
No longer works.

Glare-

It's a ridiculously powerful stun. It lasts thirty seconds of stun and mute-enough to cuff, strip radio, and drag off to a secure area and grab a fucking bag of chips before they can call for help again.

Reduce time to thirteen seconds of stun and seventeen seconds of mute-So you have to be closer to someone to glare.

'buh buh shadowling cant get peoplea nymore XXXXD'

Thralls.

Thralls have no purpose right now and are basically useless.

So.

Give thralls glare from 3 seconds of stun to 8 seconds of stun.

Make it also mute for 8 seconds.

Long enough to stun and cuff and possibly remove headset.

Thralls can now cover the gap in shadowling potency.

**Comment by ghost** [comment]
If you disagree, reminder that shadowlings have a fucking 95% winrate.

**Comment by ShadowDeath6** [comment]
95% is balanced1!!!!1

**Comment by Cruix** [comment]
> Dethralling surgery-make last step require a scapel to remove the organ, not hands, so mediborgs can deconvert too

I never even thought of this, mediborgs are unable to do several important surgeries. They should probably get a special tool that works the same as a hand does for surgery, that drops whatever it takes out on the ground. It's bad enough that they can't put implants in people, they can't even take them out, so there is basically no reason to do surgery as a medborg.

**Comment by ShadowDeath6** [comment]
tg made it so that the tumor thing is an organ and can be removed in organ manip.

**Comment by EMT321** [comment]
Re-add the floodlights to brig at round start.

**Comment by Cruix** [comment]
>tg made it so that the tumor thing is an organ and can be removed in organ manip.

It is not an organ, dethralling is its own unique surgery that is only selectable on thralls.

**Comment by ShadowDeath6** [comment]
I said tg did it.

**Comment by abdbla** [comment]
"No longer extinguishes flares"

Everything else is fine compared to this, if we re-add non extinguishable flares, itll be Grey Tide the Shadowling: Electric Bogaloo
Let them extinguish flares, but make torches immune.

"Shadowwalking-
Move at golem walkspeed when in walls, so you can't cheese around hiding in walls endlessly."

You can just light up the wall to make them unable to escape. No need to reduce walk speed.

**Comment by FluffySurvivor** [comment]
I like the idea of making slings more dependent on thralls.

**Comment by Super3222** [comment]
> Re-add the floodlights to brig at round start.

After the MC broke, we reverted the code. We've gotten the recent changes to the code back, but it seems that recent map edits have been reverted. I'll ask Taco about it. @TehFlaminTaco

**Comment by Super3222** [comment]
Sorry for the double post but @AdamElTablawy 

Here are a few points from your post.

> Enthralling-No longer penetrates loyalty implants. No more cheese enthralling sec officers. Implanting people has a use.
> Give thralls glare from 3 seconds of stun to 8 seconds of stun.
> 
> Make it also mute for 8 seconds.
> 
> Long enough to stun and cuff and possibly remove headset.

So now that there's no longer a point to enthralling loyalty implanted people, you might as well use your OP stun with no counters and murderbone the lot of them.

**Comment by Groudonmaster** [comment]
Changed in #890
