### ISSUE TITLE
Remove nukeops shuttle's ability to fly to derelict teleporter

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#854]
### Expected Behaviour

Spending the TC to buy a useful asset, the teleporter board, is a decision taken strategically
### Actual Behaviour

Nukies fly to derelict teleporter, ransack teleboard, free teleporter and telebombing the station.
### Hao 2 fix

It's the newest meta I'm seeing basically every single nukeops round, and it's getting a bit old.

Just remove the nukie shuttle's ability to fly to the derelict teleporter. I mean, the ability to go to other zlevels is kinda cool- but not ones that give you a super valuable asset for free. Yeah, sure, you can get shit from the regular derelict- but aside from the SWAT helmet and somewhat useless (for nukies) police baton, there's nothing of interest that you can't get on your own shuttle anyway.

And yes, you can technically just jetpack off into space until you hit the right z-level anyway, but it's riskier, slower, and actually makes you put a tiny bit of fucking effort into getting your free loot.

**Comment by ShadowDeath6** [comment]
> implying 40tc is worth the teleporter board

**Comment by FluffySurvivor** [comment]
bby it's fine

telebombing is balanced

**Comment by ghost** [comment]
yeah but there's no reason to have it in the uplink if you can just get it for free

reduce teleporter board to 30 TC and remove it from derilect teleporter

**Comment by ToGWtF** [comment]
Lower it to like 10 TC. Theres two spots they can get a free board from, if they want to spend 10 minutes doing that and not attacking right away.

Even with it being free, most people don't bother to go get one and use it.

**Comment by EMT321** [comment]
40 TC precludes its use to war, at which point the crew can just space all the beacons and make it worthless. Plus, you'll make it impossible for people to teleport back from the abandoned satellite.

**Comment by ToGWtF** [comment]
The risk you take in leaving your shuttle off-zlevel and relying on using a teleporter to return to it greatly  outweighs the advantages of instantly teleporting straight onto the bridge. We all know how hopeless 99.9% of nuke ops teams are in carrying out the most simplest of plans, why punish them for wanting to take a different plan then the normal meta

**Comment by ShadowDeath6** [comment]
There HAS been a huge increase in telebombing lately

**Comment by ParagonPrime** [comment]
Tog, it _is_ the meta

Like, almost every single round

**Comment by EMT321** [comment]
I've been the main proponent of it. I've seen it used by others less than 5 times, as both a suggestion from other nuke ops (who I assume learned it from me), and as a regular crewmember.

**Comment by Super3222** [comment]
They don't just go for the derelict teleport, they go for the NASA stations' as well. There's a teleporter circuitboard there.

Now let's add some of the syndicate lore into this. The syndicate KNOW that there's a teleporter on the derelict. Why?

Apart of the derelict lore, **SPOILER** there was an agent that tried blowing it up. The syndicate would have known about the station, and the outline of it as it does with SS13.

**Comment by ParagonPrime** [comment]
I'm a big proponent of lore, but game mechanics > storyline. At least in the sense that this current state of affairs allows you to get a 40 TC item (that's two tator uplinks!), for free, with absolutely minimal effort (if you can use a jetpack and internals, you can get the board- you don't even need to find the z-level.)

**Comment by EMT321** [comment]
Bear in mind, doing this will prevent any SPESS adventures who manage to get to either of those locations from returning to the station in a reliable way.

**Comment by ParagonPrime** [comment]
Not really.

You can still normally fly out into space with jetpack and suit- what you can't do is use the syndi shuttle to find it guaranteed in two minutes- all by just removing the option from the console. 

Why you'd care at all about space exploration when nukies are confirmed, christ knows.

**Comment by EMT321** [comment]
I mean in the plethora of cases where it's not nuke ops, and someone gets randomly stuck there after floating off solars/mining.
