### ISSUE TITLE
Left of toolbox heaven there is a maint door that everyone can enter

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#855]
### Expected Behaviour

I CAN'T ENTER REEEEEEEE
### Actual Behaviour

You can
### Steps to reproduce the problem
1. Be assistant
2.  Click door
3. REEEEEEEEEEEEEEEEE

**Comment by Super3222** [comment]
what

oh the storage

**Comment by ghost** [comment]
why did we remove maint access from assistants again

**Comment by ToGWtF** [comment]
The green door? Or an actual maintenance door?

**Comment by Time-Green** [comment]
A maintenance door. I was to lazy to include a pic, but it takes 5 seconds to figure out

**Comment by ToGWtF** [comment]
rip. my bad. i rushed out that mapchange it looks like

**Comment by Groudonmaster** [comment]
Solved in #860
