### ISSUE TITLE
EMP repairs cut cameras

### ISSUE THREAD

**Issue by Alblaka** [yogstation13/yogstation-classic#856]
### Expected Behaviour

Cut cameras are like PHYSICALLY BROKEN. And unpowered. EMP doesnt even affect them.
### Actual Behaviour

EMP will EMP cut cameras, meaning they will turn on again after EMP wears off, including AI notification.
### Steps to reproduce the problem
1. Cut camera
2. Set up cult base on mining
3. Do cult research, EMP a camera in the process
4. Be forced to idle behind a rune wall to hold off security sent in by AI because camera suddenly works again.

**Comment by ShadowDeath6** [comment]
It wasn't reactivated by EMP, you cut it again for some reason and reactivated it.

**Comment by Alblaka** [comment]
Just reproduced this with adminhelp on server. Cut camera, EMP rifle. EMP wears off, camera is active again.

**Comment by Nirnael** [comment]
It doesn't actually show anything, it's only the animation that runs, but the camera itself in the camera list is deactivated so nobody can see through it, I suppose it's a cosmetic fix, I'll get onto it.
