### ISSUE TITLE
warden gear portable security alarm

### ISSUE THREAD

**Issue by apneaman** [yogstation13/yogstation-classic#858]
### Expected Behaviour

To function like the armoury alarm sending an alert to sec personal. Similar design as the porta flash but with proximity sensor instead. Replaces one of the portable flashes in armory
### Actual Behaviour

It doesn't exist letting the Greytide makes secret tunnels into perma and armory  via the labor shuttle dock almost every round blocking doors and theres not much to prevent them as there is no alarm except for using all the portable barriers or waiting to ambush them basically wasting time.
### Steps to reproduce the problem
1. Play warden
2. Check labor shuttle dock
3. False walls everywhere

**Comment by ghost** [comment]
Hm.

What if instead of the above you could make bounced radio-prox sensor assemblies that send an alert over the frequency they're set to when triggered?

Ie screwing a sec radio to a prox sensor would send an alert as in 'Proximity sensor beeps ''Proximity sensor triggered at X''

**Comment by apneaman** [comment]
That sounds like an excellent idea. kind of a more informative extension of the current signaller/proxy alarm setups. 

Was more aiming for something that can be wrenched to the floor however so whoever trips it cant just steal it straight away
