### ISSUE TITLE
Give borer it's own perf

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#862]
### Expected Behaviour

OH I CAN DISABLE BORER WHILE ALSO BEING ALIEN REEEEE
### Actual Behaviour

> observe
> alien event triggers
> No available ghosts
> FUCK MY FUCKING CUCKING LIFE I WISH I HADN"T HAD IT DISABLED BUT I HAD CUZ I DUNT LIKE BUURERRR
### Steps to reproduce the problem

Really, why don't we have this yet?

**Comment by AsV9** [comment]
Because nobody has coded it yet. Maybe you could do that ;^)

**Comment by Time-Green** [comment]
You challenged me. I will now do everything to get that to work.

**Comment by ShadowDeath6** [comment]
We don't have it yet because everyone likes borer :^)

**Comment by AsV9** [comment]
@timkoster1 Let us know in #coder if you need assistance.

**Comment by Super3222** [comment]
When do you ever get alien anyway (talking universally)?

When was the last alien event anyway? I haven't been to one in over two weeks...

To be honest, I kind of like all of the different aliens that belong to SS13's preference be BE_ALIEN, but eh. I guess it doesn't really matter. However the spam of BE_THIS, BE_THAT, BE_THISAGAIN,and BE_THISTHING is going to eventually make a pretty long list.

**Comment by Time-Green** [comment]
I have actually been made alien by random events once.
Observing kinda pays of now and then.

**Comment by oisin100** [comment]
#871 Thanks for saving me the work tim <3
