### ISSUE TITLE
New item ideas

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#864]
Ghetto weapons, hopefully less OP than the Ghetto Armory stuff!

//Club//
Simple craftable weapon intended to be wielded alongside a taser or riot shield and a bastardization of the spear's damage with the stunprod's stun potential. Same size as stunbaton.

Recipe: Weld together 2 metal rods. Weld 3 metal to assembly. Optional - Use cablecuffs on assembly, and use gauze/makeshift bandge/etc. for grip (slightly increasss knockdown chance).

Stats: 40% (45% chance when upgraded) 3-second knockdown chance on hit, 11 damage regardless of intent.

//Makeshift riot shield//
Perfect when used in combination with the club, but shittier than the proper version.

Recipe: Use a welder on a single metal rod to form a handhold. Attach handhold to two metal sheets. Weld assembly. Optional - attach plasteel sheet. Weld assembly.

Stats: Noticeably worse than the riot shield (not sure of the numbers for either), with lower chance to block all types of impacts. Will still save your life occasionally. Also breaks after it has absorbed 250 points of damage (500 for reinforced version)

//Khyber Station Laser Gun//
Totally not a weapon designed by Khyber Pass IN SPACE.

Recipe: Attach 2 metal to modular reciever. Attach plasteel sheet. Attach micro-laser (any type). Attach glass. Attach power cell. //No firing pin required//

Stats: Shoots slower than the standard energy weapons, deals only 15 damage, and uses a whopping 5000 battery per shot- plus, you can't use it in rechargers, so you have to manually eject and recharge each power cell. This is ameliorated by the fact that,
A. It's a laser gun you can make easy but not easy enough to let any assistant run around with,
B. You can pop out the power cell and slot in a new one, no recharger required, and keep firing (though you still won't get too many shots off, and better keep a screwdriver handy...)
C. No firing pin required

**Comment by Super3222** [comment]
Paragon, how much do you love watching an army of non-antag greytiders storm into the brig and make it a slaughter house

**Comment by X-TheDark** [comment]
I hate to put words into Adams mouth, but he'd probably go "Craftable weapons are shit".

Other than that, great ideas, I do like them, I think.

**Comment by MacHac** [comment]
Club:

> Lets see, I could make a stunprod and carry around a blunt object for whacking people's heads in, or I could weld 3 metal rods together and get it all in tool!

Makeshift Riot Shield:

> Rev round
> 10 minutes in
> Heads cowering in brig trying to figure out how to escape the greytide
> Said greytide has been oddly quiet for the last 5 minutes
> Suddenly, 10 people rush the brig with shields
> Officers fire on them
> Only 5 injured, 2 go down
> Others rush in and start beating on all the heads
> Heads can't escape because the clubs the greytiders were using kept them stunned

Khyber Station Laser Gun:

> Be traitor
> Decide to kill target with lasers
> Break into cargo
> Lathe modular reciever
> Break into EVA
> Steal plasteel sheets
> Break into Science
> Steal micro laser and 30k battery
> Steal some glass as well
> Put them all together
> Plug in battery
> Run up to target
> Start shooting him
> BANG BANG BANG BANG BANG BANG _click_
> All 6 shots landed
> Entire 30k power cell expended
> Target is still standing
> Off yourself with syndicate revolver in shame

**Comment by ghost** [comment]
no

**Comment by FluffySurvivor** [comment]
NO. 

PLEASE LEARN THAT RNG HAS NO PLACE IN COMBAT

**Comment by ParagonPrime** [comment]
hence reasonably large stun chance on club

riot shields are unfortunately all about rng; the block chance SHOULD be 100 but isn't. Hopefully with a change the REAL shields can have a 100% block chance and the ghetto version a shittier chance

**Comment by ParagonPrime** [comment]
also the Khyber Station Laser does take a fair damn bit of work for something noticeably weaker than a standard egun, plus requires research to be good enough to have batteries with a decently high cap

just in case you don't want to/can't rob the armory

**Comment by Kmc2000** [comment]
Have the gun have a 20% chance of overheating and burning your hands. 

Make the shield have a 30% chance to shatter on each absorbtion 

Club?....ehhhhhhhh

Or you know... not

**Comment by ghost** [comment]
mixing stunprods and spears is bad and i'm shutting this down, sorry

also, buildable lasers, in any form, were long ago ruled out as overpowered-there's a reason the only other thing is the improvised shotgun which can only fire weak lasers with cooperation from science as a tablecraft ez to get weapon with no mineral req.
