### ISSUE TITLE
New gang bling

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#865]
### Expected Behaviour

You look dope, riding around on a bike, uzi in one hand, beer bottle in the other
### Actual Behaviour

Gang is steamroll
### Steps to reproduce the problem

So i had a talk with @super3322 

We want to add some new cosmetic and functional items to gangs. 
1. chains, you can clip these onto your jumpsuit, and have the gang name engraved on them
2. Bikes, for 50 influence, you can buy a harkey davidson bike, that is basically a janicart that makes obnoxious VROOOOM noises
3. A limo
   For the low low price of 200 influence, you can buy a goddamn limo, which gives you masses of influence gain, but cant take a large beating, this would be to drive the b0ss around in

4.*Beat
x is hit by his chains in the chest as he bangs on the dashboard
1. More gun variety
   Mainly SMGs and more attractive pistols

Feel free to yell at how unbalanced it probably is because every idea i have seems to be, or suggest new ideas

**Comment by Kmc2000** [comment]
I meant harley davidson*

**Comment by ToGWtF** [comment]
Boomboxes. Placeable like a dominator, gives a secondary source of influence income for defending it. Rather than give an announcement to the whole server, only gives an announcement to current gang members that your enemy has placed one.

**Comment by Silvaplex256** [comment]
I could sprite this.

**Comment by ghost** [comment]
gangsters need to convert people by hitting them with mixtapes, not pens

gangsters with drugs in their system should yield extra influence

**Comment by DavidEdwards** [comment]
I don't want bikes or cars on the station. They really have no place on it outside of admin bus.

I am totally for bling though. The captain medal code could be purloined to give this functionality.

**Comment by Kmc2000** [comment]
> gangsters need to convert people by hitting them with mixtapes, not pens
> 
> gangsters with drugs in their system should yield extra influence

YES, Mixtapes produced by boomboxes? so you can slap someone with a deadly mixtape

Also @Silvaplex256 I've already started spriting this stuff, so not a whole lot of point in you doin' it

**Comment by Kmc2000** [comment]
@DavidEdwards 

We have the janicart and secway, I can understand not wanting the limo, but are bikes that different?

**Comment by DavidEdwards** [comment]
Honestly, I really think that adding any (more?) motor vehicles to the game unless they have a strict purpose will be a big detriment to the game.

I think they would feel far too out of place.

We _could_ work with a gangster mech?

**Comment by Kmc2000** [comment]
> gangster mech

SOLID GOLD BATTLE MECH?

Well more like a ghetto ripley or a golden ripley

**Comment by Super3222** [comment]
> So i had a talk with @super3322

**Comment by ToGWtF** [comment]
power armor when

**Comment by ParagonPrime** [comment]
wearing jumpsuits casual style as gangsta gives 1% extra brute protectipn. wearing bandanas on head/caps flipped backwards also gives 1% extra brute prot.

and of course, saggy pants as a gang outfit!

and the boss should be able to order a Golden Throne- a mobile throne that he can ride around in to generate extra influence.

**Comment by ToGWtF** [comment]
working on a boombox placeable machine like a dominator, that gives bonus influence based one how many gangsters standing within 2-3 tiles of it each income cycle. costs 30 influence and can only be placed once.

**Comment by Super3222** [comment]
@ToGWtF 

Alright, but I'll still be working on what the issue describes minus the vehicles.
