### ISSUE TITLE
Cult converting someone controlled by a borer converts the borer but not the host, and doesn't show cult badge

### ISSUE THREAD

**Issue by MasterPenguin5** [yogstation13/yogstation-classic#866]
### Expected Behaviour

Host gets dragged onto convert rune, cultists yell in cult language, cultists then shake hands with their newly converted member with his/her fancy new Cthulhu badge above his/her head.
### Actual Behaviour

Host gets dragged onto convert rune, cultists yell in cult language, cultists take a moment to wonder why host hasn't been converted, cultists proceed to beat host to death for not having one of their fancy Cthulhu badges, then wonder why the borer that pops out of the host's ear has the badge instead.
### Steps to reproduce the problem
1. Get a borer in you.
2. Get dragged onto convert rune and attempt to be converted.
3. Don't get converted, and then wonder why that borer is also a cultist.

I forgot to screenshot it, but it was interesting to see "Cortical Borer the animal" in the list of cultists at the end of the round.

I guess this does sort of make sense since the borer is in control at the time, but the host not being recognized as a cultist doesn't really make sense.

**Comment by ParagonPrime** [comment]
borer being culted sounds fucking hilarious, keep it- but cult host too

**Comment by ShadowDeath6** [comment]
Technically being culted as borer wouldn't do anything since their objectives take ultimate priority.

**Comment by MasterPenguin5** [comment]
Exactly why converting someone with a borer should convert the host and not the borer, or convert both (because I agree cult borer is funny) but don't give the borer cult objectives/make it say something that the borer has higher priority. Or at least have the host marked as cult after convert so the other cultists don't then murder and/or sacrifice the host for not getting converted.

**Comment by Alblaka** [comment]
> Technically being culted as borer wouldn't do anything since their objectives take ultimate priority
> But then you can have the borer join the chantings.

But yes, if converted, either both host and borer should be converted, or neither.
