### ISSUE TITLE
ED with toy lasers get real stun batons

### ISSUE THREAD

**Issue by Alblaka** [yogstation13/yogstation-classic#868]
### Expected Behaviour

Make a Honk ED with a Tag laser gun to give the clown a friend / sparring partner.
### Actual Behaviour

Perma stun once anyone touches it.
ED's with tag guns get a free stunbaton they employ when attacked, whilst supposed to being completely unarmed. 
### Steps to reproduce the problem
1. Build ED with a TAG gun
2. Hit it

**Comment by EMT321** [comment]
Someones just salty they got smacked around for 20 minutes for punching an ED with a crowbar. The lasers used to do stamina damage, as I recall.

**Comment by Alblaka** [comment]
Nope, Tag lasers only cause stamina damage when you're wearing the tag armor. Oh and they can the white-swammy blind effect if aimed for the eyes (but ED cant do that).

And ye, that 20 minute stunlock was annoying. Moreso because I thought this bug had been fixed ages ago.

**Comment by ShadowDeath6** [comment]
Not a bug, beepskies can use unpowered stunbatons, EDs are more advanced therefore can do more meme shit.

**Comment by Alblaka** [comment]
Beebsky is literally a stunbaton attached to a helmet.

ED with a TOY LASER is supposed to be a makeshift honkbot annoying type.

I fully agree that ED's with TAZERS should have the tools to actually arrest people. But the TOY ED having a stunbaton that he cannot even use unless triggered by aggressions sounds like a bug to me.

**Comment by ShadowDeath6** [comment]
Don't mess with the honkbot then :^)

**Comment by EMT321** [comment]
"Help, I cant punch robots that cost 15 metal without a consequence"
