### ISSUE TITLE
New lighting system bug.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#87]
http://imgur.com/R25vOx2

Apparently for Silvaplex-And a few other people going by OOC chat-The new dynamic lighting dicks the shit out of people's game, leading to all-white, all black, or just crashing them. Asked Silva, apparently it's because there's a lighting script that fucks with OS, just like goon's lighting does.

Yeh.

**Comment by Silvaplex256** [comment]
Welp, just started an issue and saw this.  Can confirm, will link a screenshot soon. Running 64bit Linux with Windows xp running in Vbox. Only workaround I've seen is to either beef up Wine to handle BYOND, or run natively in Windows (something I can't do).

**Comment by george99g** [comment]
Do you have the hardware-based graphics enabled in the Byond pager, @Silvaplex256 ?

**Comment by AsV9** [comment]
If this is the case this is pretty bad.

**Comment by TehFlaminTaco** [comment]
Issue is OS/VM doesn't support the blendmode BYOND uses.

**Comment by X-TheDark** [comment]
This also happened to me in Windows XP (native). Reconnecting seemed to fix the issue for me. Also, this happened only after the round end (next round), rather than when connecting to the server.

**Comment by TehFlaminTaco** [comment]
Is there any chance I can pin this down to, "Why for the love of god are you still using XP? Even microsoft doesn't support it"

**Comment by X-TheDark** [comment]
Nope. And I'm only providing the information. I'm not asking for this to be fixed, since as I said, reconnecting fixes this for me every time and this only happened once in like 3 days.

**Comment by TehFlaminTaco** [comment]
Requesting Issue labled "Unsolvable"

It's Byond/client's fault, not ours.

**Comment by Hydre** [comment]
I'm not sure if this has been mentioned anywhere but when I toggle darkness off as a ghost, shadows -instead of disappearing- just become a darkened shade of the turf and anything above it is perfectly lit.

http://prntscr.com/9udxnd

I'm using win7

**Comment by TehFlaminTaco** [comment]
Technically a feature, that I added to help shadowlings and help see the difference between pitch black areas. I may change it or just find a different method for slings to see where they can and can't go quickly.

**Comment by Hydre** [comment]
Oh I see, that's pretty smart

**Comment by TehFlaminTaco** [comment]
Fixed in PR #141

**Comment by george99g** [comment]
Closing
