### ISSUE TITLE
[Admin Tool / Feature] Jobban System

### ISSUE THREAD

**Issue by SKR6DarkVoid** [yogstation13/yogstation-classic#870]
### Expected Behaviour

A suggestion for a new system and or feature.

If X is jobbaned from all Engineering Roles, X goes to HoP to be switched to engineering.
HoP inserts the ID, and attempts to select Engineering.
Error Message "Error, Unable to interface with the selected position" shows meaning they are job-banned. 

Not saying this to get lazy, but to make it easier to keep track of job-bans, that way players are not getting themselves perma'd for switching jobs that they might of forgotten they were banned from.

Even though Common Sense does apply here.

Whats your guy's / gals / machine's / bots thoughts on this.

**Comment by ParagonPrime** [comment]
Causes problems.

For instance, guy gets jobbaned from Engineering for whatever reason.
He then plays Captain/HoS/whatever.

One of two things happens:
1. He still has access. And can presumably griff around there if he really wants to.
2. He doesn't have access. This creates a huge problem for two reasons.
   A. If he's required to get in there and hunt down a criminal, well shit, he can't. He has no more access!
   B. You go off the captain to get his ID to get into Engineering. Oh, oops! This Captain's 'all access' ID didn't have fucking Engineering access on it. Tough shit!

Plus, two more logistical problems:
1. If you're banned from a job with multiple accesses (say, CMO)- does that mean that, as a viro, if you try to upgrade your ID to medbay storage, tough shit, no access!
2. IDs are sort of impossible to tie to a particular player- this obviously creates a lot of tactical uses but an absolute OOC nightmare. If this is implemented, all you have to do is knock over some dude who does have relevant access and go ham.

Overall, nice idea... but with glaring, glaring holes that may never be resolvable.

**Comment by Kmc2000** [comment]
> wot para said

He meant the actual fekkin job, not the associated acesses, even if they abuse around it and go grief,  then we can ban them for it for griefing anyways. 

What this would do is keep stuff neat, which i like. 

May also be nice to have a blacklist sent by NT to the HOP so they can see who shouldn't be who (Ie.  Arthur daelen, Station engineer, reason: extreme incompetance

**Comment by ParagonPrime** [comment]
a. i don't play SE on Daelen, because Satou is my "tough manual labour/sec" character
b. fekk youuuuuuu
c. ehhh, sorta makes sense. i'd agree with a literal blacklist for the HoP (adapted into the comms console- whenever a new person arrives who happens to be blacklisted, the console will display an alert stating their name and what they're banned from)
