### ISSUE TITLE
Rainbow jumpsuit has no alt-sprite

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#874]
### Expected Behaviour

roll your jumpsuit down
### Actual Behaviour

be nekked
### Steps to reproduce the problem
1. Type step 1 here.
2. Type step 2 here.
3. Type step 3 here.

**Comment by Super3222** [comment]
I seriously thought that was suppose to happen to the rainbow jumpsuit... something weird.
