### ISSUE TITLE
mining pretty branch

### ISSUE THREAD

**Issue by utahclock** [yogstation13/yogstation-classic#877]
Adds working properly branch titled mining.

So contributes can collaborate and work on Adams mining rework request as its a large task

**Comment by utahclock** [comment]
I'm p r branch not pretty or properly stupid loaner phone

**Comment by Super3222** [comment]
I'd be up for working on the mining rework, but I still have some other projects to finish.

Mac and Taco have also talked about this on #coder.

**Comment by utahclock** [comment]
We just need a git hub min to make a profit branch for mining project so folks can contribute

**Comment by utahclock** [comment]
Gray pr branch. Stupid phone
