### ISSUE TITLE
Discussion : Changing Gamemode chances

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation-classic#879]
### Proposal
- Do you guys think we need to change the chances for gamemodes to happen?
- Should we think about implementing gamemode weights, similar to antags (save it to a global savefile, ala round number or something)?
- Anything else, go ahead, propose, that's why I'm making the issue.

Current values available [here](https://github.com/yogstation13/yogstation/blob/dev/config/game_options.txt#L83).

I've heard people complaining about the relatively high chance for Rev/Gang/DA/Whatever. Do you think we need to change that?

**Comment by ShadowDeath6** [comment]
Traitor and traitorchan to 10%
Rev and DA to 0%
Blob to 15%
:^)

**Comment by Time-Green** [comment]
Creating a weight system?
That sounds great, more variation always is

**Comment by FluffySurvivor** [comment]
Cult and rev both to 0 until they get their much-needed reworks.

Bigger chance on nuke ops and gang to compensate.

**Comment by ToGWtF** [comment]
traitorabductor needs more testing, set it to 10 :^)

**Comment by oisin100** [comment]
Server can handle meteors now. We should put it back into rotation. I like the chances of traitor round right now. Rev needs lowering though...

**Comment by Time-Green** [comment]
Rev does need lowering, and shadowling and blob needs a bit more

**Comment by AsV9** [comment]
These values are actually slightly outdated. The new values are as follows:

```
PROBABILITY TRAITOR             6
PROBABILITY TRAITORCHAN         6
PROBABILITY DOUBLE_AGENTS       6
PROBABILITY NUCLEAR             10
PROBABILITY REVOLUTION          7
PROBABILITY CULT            8
PROBABILITY CHANGELING          0
PROBABILITY WIZARD          9
PROBABILITY MALFUNCTION         10
PROBABILITY BLOB            10
PROBABILITY METEOR          0
PROBABILITY EXTENDED            0
PROBABILITY GANG            9
PROBABILITY RAGINMAGES          0
PROBABILITY SHADOWLING          9
PROBABILITY ABDUCTION           0
PROBABILITY TRAITORABD          5
PROBABILITY TRAITORABDCHAN      5
#total 100
```

**Comment by ShadowDeath6** [comment]
> ragen magen not 100%

Asv made a typo again xdddd

**Comment by Alblaka** [comment]
I would say add raging and meteor on a low chance (1 or 2 would be fine) just to add the POSSIBILITY.
As well, maybe incrase the abductor modes by some points for further testing and scale them back down later.

Wouldn't mind a weight system though, would reduce the chance of triple-rev-in-a-round

**Comment by Super3222** [comment]
A weight system would actually be pretty great, similar to the antagonist weight.

After at least 40-50 rounds, all weights could come to the average point. So we don't have any completely off game mode weights.

Rev does need a rework, but it's not like we've come up with a concrete and balanced idea. I don't feel that the chances, based on what AsV9 posted, needs to be lowered.

Gang and DA... I'm not sure where the complaints are stemming from.

**Comment by ParagonPrime** [comment]
The issue someone made (where I suggested a LOT of good balances) on rev seems to have been buried, go revive it.

Otherwise, full approval.

Though there should be a small chance of Abductor Nukies. Just for the hilarity of it.

**Comment by ghost** [comment]
Traitor and ling and traitorling need to be more common than any other gamemode.

Lower ops chance, sling chance, and blob chance.

Reduce rev and cult to 0 until a new thing can be implemented for them.

Malf is fine as is.

Take DA out back and beat it with a shovel.

Add meteor with chance 2.

**Comment by Alblaka** [comment]
> Traitor and ling and traitorling need to be more common than any other gamemode.

They are, by definition of lowpop.

**Comment by FluffySurvivor** [comment]
> Traitor and ling and traitorling need to be more common than any other gamemode.

Those are low pop gamemodes. In high pop these fucking suck,especially ling.
