### ISSUE TITLE
White screen - dynamic lighting system

### ISSUE THREAD

**Issue by Silvaplex256** [yogstation13/yogstation-classic#88]
Dynamic lighting is glitched for Windows vms. Fills screen with white tiles that make it impossible to see anything, Hud unaffected, will post more info when I get home.

**Comment by george99g** [comment]
@TehFlaminTaco

**Comment by TehFlaminTaco** [comment]
Cannot replicate, also, functionally cannot my my Coloured Lighting's fault, if it was anything, it would have existed before my coloured lighting, that, or the machine you're running it on has outdated graphics drivers that do not support multiplex blending.

Client Issue.

**Comment by TehFlaminTaco** [comment]
This is a duplicate of #87

**Comment by george99g** [comment]
> This is a duplicate of #87

Closing this then.
