### ISSUE TITLE
Teleporter console at bridge does not do anything

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#880]
### Expected Behaviour

remote teleport acces, not like it's usefull
### Actual Behaviour

It is not linked at all. It also can't be linked, I tried. Kinda pointless

Creds to Nirneal for discovering btw

**Comment by EMT321** [comment]
Its functionally useless with the modern telesci anyway. You'd need a telepad right there to do anything remotely constructive.

**Comment by Super3222** [comment]
I'm pretty sure it was added there because the original mappers needed another computer to complete the bridge layout.

But yeah, it's been known as a pretty useless machine. Unless you do what EMT describes.
