### ISSUE TITLE
New traitor item?

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#882]
Fingerprint gloves , 4TC , non suspicious looking fingerless gloves, when you hug someone (this will convert them to black gloves, so a bit more suspicious) it will steal their fingerprints! and , upon wearing them will let you mimic that person's fingerprints, so you can do all your emagging and nasty things , but blame someone  else for it!

Then just click the gloves to convert them back via space magic

(Note that fibers still exist, so a chameleon jumpsuit would be needed as well)

Thoughts?

**Comment by oisin100** [comment]
Why would anyone touch them?

**Comment by Time-Green** [comment]
Wanna bet, when they get purchased, the person that bought it accidently touches it
And loses 4 tc

**Comment by FluffySurvivor** [comment]
4 tc for something that is basically useless and can easily backfire

good meme

**Comment by Alblaka** [comment]
Make it so that you can wear the gloves and they scan prints by hugging someone. And stay fingerless.

Next level meta: Kill anyone hugging you whilst wearing fingerless gloves.

**Comment by Kmc2000** [comment]
Forgot to add the part where you can revert them

HONK

Also updated, hugging is a good idea

**Comment by ghost** [comment]
This is stupid.

Traitors can already swap prints by using medical or sec records, for free.

This is a fairly useless niche item that also spoonfeeds traitors something that they could get in 3 minutes of effort and costs too much.
