### ISSUE TITLE
Space Station freezing

### ISSUE THREAD

**Issue by Sandvik5** [yogstation13/yogstation-classic#885]
### Expected Behaviour

To not freeze when I click on a console, or when I look into other people inventory.
### Actual Behaviour

Try to find out if the problem is on my end or on the developers hand.
### Steps to reproduce the problem
1. Type step 1 here.
2. Type step 2 here.
3. Type step 3 here.

**Comment by Time-Green** [comment]
Can you explain it a little bit more?

**Comment by oisin100** [comment]
It sounds like its your end. Byond is notoriously slow when it comes to things like that. Perhaps you could give us some info on your system specs?

**Comment by Kmc2000** [comment]
Ss13 hates crossfire and other equivalents, i got this crap with it, turned it off, worked fine

**Comment by Sandvik5** [comment]
Okay so I am using a desktop 
System Model: XPS 8700
Processor: Intel(R) Core (TM) i5-4460 CPU @ 3.29GHz (4 CPUs), 3.2GHz
Memory: 12288MB RAM
DirectX Version: DirectX 

I can launch the game fine but when I try to join it, it will say space station 13 (Not Responding) at the top, but after a few seconds it will come back up. This also happens if I am trying to say open my pda, or trying to look into another person inventory.

**Comment by faultlesselm16** [comment]
this happens to me sometimes when i open my pda or other stuff like it and its only started recently within the last 2 weeks or so maybe a new update made it do this?
system specs 
Processor: Intel(R) Core(TM) i3-4130T CPU @ 2.90GHz, (4cpus) 2.9GHZ
memory: 8192MB RAM
System Model:   ASM100
directx version: directx 11

**Comment by Time-Green** [comment]
Oh, I thought he meant freezing as in cold

**Comment by Groudonmaster** [comment]
Try updating to BYOND 510. If you've already done that ensure your system isn't running any useless processes in the background because this sounds like it could be caused by a lack of RAM.

**Comment by oisin100** [comment]
> Okay so I am using a desktop

It should work fine... Do as groudon says.
