### ISSUE TITLE
A not shit traitor item

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#886]
Pickpocket gloves.

Cost: 2 tc.

Sprite- black gloves.

Description- 'A pair of sticky, shiny black gloves.'

Detective fibre scanner display-'fibres from a shiny glove.'

Use-

Multiple.

They provide no insulation from shock, but work as regular black gloves otherwise-even black gloves reduce shock damage.

In the strip menu, they allow you to see the contents of belts and backpacks before you pull them off. You can also directly remove items from belts and backpacks, even if they're on someone else.

Items pickpocketed go directly into the inhand, not on the floor.

You are able to see what is in someone's pockets in the strip menu.

Pickpocket speed is vastly increased-removing id's or items from pockets takes about the same time as it does that slipping someone on soap stuns them. 

Removing items from backpacks or belts takes 3 seconds.

All of these are as silent as regular pickpocketing-the person being stolen from will not notice unless they move, at which point they will feel their pockets, id, or backpack/belt/anything in suit storage (this includes tazers in an officer's armor, the cmo's hypo on his labcoat) be 'nimbly grasped at'.

Suit storage stripping takes normal strip time but is otherwise silent.

Strip time all around is reduced by 33%. For anything.

The gloves also allow you to directly place items in belts/backpacks/pockets with increased speed.

Now, remember all of this requires you and the person to be standing still. If they so much as fart they'll notice and you're sailing out the airlock.

This offers both great potential in theft, or framing (hide an emag in your target's backpack and scream for sec to arrest him, or assasination (hide a grenade in your target's pocket/steal the oxygen tank right off the ce's hardsuit in the middle of space).

It also allows for more amusing shit, like slipping the captain, tearing his jumpsuit off and filling his backpack with pictures of your ass before jumping into disposals leaving him confused, humiliated and naked.

Remember all of this is only good if someone's standing still and they'll notice very fast you just stole something from them when it's gone after you slip them.

**Comment by Cruix** [comment]
> Be atmos tech
> Get tank full of plasma/N2O mix
> Place in target pocket
> toggle target's internals
> laugh manically

**Comment by ghost** [comment]
exactly

**Comment by ShadowDeath6** [comment]
You actually can't toggle on internals unless the item is in exosuit storage.

**Comment by Super3222** [comment]
Riot shields should be a hard counter for this.

**Comment by ShadowDeath6** [comment]
Close this >:^(
