### ISSUE TITLE
Dying messages (Suggestion)

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#887]
### Expected Behaviour

If your damage is between 100-150 and you're bleeding, you can write something short (4-7 characters depending on damage) in your blood on the nearest wall/floor and you die instantly afterwards. It takes ~10 seconds, and being hit interrupts it.
### Actual Behaviour

Not an actual thing, even though it would be cool.
### Steps to reproduce the problem
1. Tator shanks you, too lazy to kill you from crit
2. You try to write a dying message in blood
3. You can't, because it isn't a thing

Srsly tho, this would be cool.

**Comment by Nirnael** [comment]
Isn't the point of crit to be in coma, not being able to do anything?

**Comment by Rocks4Free** [comment]
> Isn't the point of crit to be in coma, not being able to do anything? 

Pretty sure you can already whisper one last message while in crit and it kills you, why not a dying message? Getting hit would interrupt it, so it's preventable for attackers.

**Comment by Kmc2000** [comment]
Make it have a limit of four letters ( avoiding  Gorg mwrlins kill with esword he alien, with 4 itd be vague like: GORG or SORD) , and cost masses of blood so that you get fucked unless medical are competant and know how to IV

**Comment by Nirnael** [comment]
well it cant cost masses of blood in the sense that you extract your blood, you just take whatever you bled, so technically it doesnt cost anything

**Comment by Rocks4Free** [comment]
> Make it have a limit of four letters ( avoiding Gorg mwrlins kill with esword he alien, with 4 itd be vague like: GORG or SORD) , and cost masses of blood so that you get fucked unless medical are competant and know how to IV

Or, have the number of letters dependent on how much damage they have, since that would make more sense. 100-115 = 7 letters,116-125 = 6 letters,  126-135 = 5 letters, 136-150 = 4 letters.
