### ISSUE TITLE
Malf

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#891]
### Expected Behaviour

Crew can win
### Actual Behaviour

A good AI can never be killed
### How to fix
1. Make shunting from your core add an extra 200 seconds to nuke timer so crew can fucking get to you in your space base in tcomms.
2. Make deconstructing malf APC's add an extra 100 seconds to the timer, since right now deconstructing them is a waste of time and barely adds anything to the timer..

**Comment by ParagonPrime** [comment]
100 seconds? what an un-round number

make it 60 or 120 seconds

**Comment by ShadowDeath6** [comment]
> ripley finds 3 apcs
> timer set from 400 to 700

no

Also it's more along the lines of "bad crews don't win". You can cuck an AI in seconds with minimal work as scientist or being proactive and finding the AI early.

**Comment by Kmc2000** [comment]
If the crew band together, they can murderise an ai quite nicely

If they're bad they dont  deserve to win

**Comment by Groudonmaster** [comment]
Irrelevant with #884
