### ISSUE TITLE
Eswords need armor pen

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#894]
### Expected Behaviour

Eswords being at least a bit decent against multiple armored hostiles.
### Actual Behaviour

They are trash.
### Steps to reproduce the problem
1. Call ERT as tator because fluffy is nice
2. 1v5
3. Hit the fuckers 30 times, not even one of them drops.

**Comment by X-TheDark** [comment]
> 1v5

I think I've found the problem and unfortunately, this probably shouldn't be fixed by code. Making E-Sword capable of beating odds like that is something that should never happen.

**Comment by FluffySurvivor** [comment]
yeah but it takes an eternity to even slash a sec officer to death

the cost efficiency of eswords dramatically drops when used against armored targets

**Comment by X-TheDark** [comment]
Also, for reference:
- Attacking naked human = 30 damage.
- Attacking ERT armor person thing = 21 damage

**Comment by ghost** [comment]
armor is literally fucking paper

but sure, give eswords some level of AP

**Comment by ShadowDeath6** [comment]
Le beam of light penetrating opaque materials

Just aim for arms or legs on sec, it might not do 30 damage but it'll kill them a lot faster than aiming for chest. 

If this becomes a 6 fucking tc item it should not be MORE powerful than it already is.

**Comment by ParagonPrime** [comment]
Lightsabers are lightsabers and lightsabers cut through shit ez.

They should be able to have decent armour penetration. And, of course, be much, much harder to disarm when activated.

**Comment by FluffySurvivor** [comment]
1. Lightsabers (and eswords ofc) actually emit plasma. Hot af plasma. Not light. 
2. I used it (a double esword actually) in combo with tasers, the situation where it was supposed to excel, but it let me down.

**Comment by doerakpoes** [comment]
Dubble E swords can defeat 1v5 atleast the odds are better

**Comment by ParagonPrime** [comment]
woah fluffy tone down the starwars fanboy you're making me look inadequate

_ahem_

either way it should be able to cut through fucking... What the fuck is our "standard" armour made of anyway?

**Comment by X-TheDark** [comment]
As Adam said - Paper. That's the standard (t)issue material.

**Comment by Super3222** [comment]
> That's the standard (t)issue material.

that joke is what the issue is asking for... punnetrating armor

**Comment by ToGWtF** [comment]
sec jumpsuit is 10 brute resist.   giving eswords armour_penetration = 10  negates that and makes it do the full 30 damage rather than ~20-ish.

 Means, if you target arms or legs, you do more damage than if you target chest because the armor vest is an extra 25 brute resist
