### ISSUE TITLE
VIRUSES AREN'T CURABLE AT ALL

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#895]
### Expected Behaviour

Cure a virus and develop antibodies so you can no longer get a disease
### Actual Behaviour

Everyone on the station has brain AIDS or fucking skin burn that doesn't go away ever
### Steps to reproduce the problem
1. Get level 7 biohazard virus
2. Cure it
3. It comes back
4. ask admin to cure it
5. IT DOESN'T GO AWAY

If this is a dupe of another issue then fuck me
Critical priority also pls

**Comment by FluffySurvivor** [comment]
Was this fixed?

**Comment by Nirnael** [comment]
I just tested it and it seems to be working fine.

**Comment by Cruix** [comment]
There is probably a runtime in a specific symptom.

**Comment by Cruix** [comment]
And I accidentally hit close and comment

**Comment by Nirnael** [comment]
It seems like whoever createad certain diseases gave them a cure but made them incurable, literally 1 constant is all it took to fuck shit up. But i dunno if this was intended so until it's clear i'm not fixing it.

**Comment by oisin100** [comment]
Fixed in #951
