### ISSUE TITLE
Heart rate sensors

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#896]
Idea's pretty simple, heart rate is in the code, why not use it

It works as a singaler, when your heart rate reaches a point you define, it sends a pulse on that frequency. 

You would attach it to a jumpsuit to use it, and would also show your current heart rate on examination

Medical would start with two of them, in storage, they would be researchable at around the level you get the mass spectrometer (Someone post that here, not great at RD) 

why? 

Well imagine the fun circuits you could make with this: 

.A bomb that detonates upon your death

.A door that bolts when your heart rate drops (hide your secret stash of syndi goodies)

.Bolt all the doors in critical areas upon death (Great for nuke ops! deny that disk)

.As a captain, if you drop unconscious, have it page the HOS or CMO / others so they know you are in danger

.As a traitor, fool them into wearing it so that you can track whether they are alive. 

NOTE it would be on when heart rate == Defined, and when it returned to this place, so if you got knocked out, and woke up again, it would count as two. 

Thoughts?

**Comment by ToGWtF** [comment]
yes. yes. absolutely. ghetto deathalarm implants

**Comment by EMT321** [comment]
Why not just port the health sensors from TG?

**Comment by Time-Green** [comment]
Problem is, I checked th code, and the heart rate only has dead or alive. No specifics

**Comment by Kmc2000** [comment]
Still works @timkoster1

Just have it toggleable on Death or on revival
