### ISSUE TITLE
Allow normal gangsters to use gang pens to check for gang/implant status (without being able to convert)

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#898]
### Expected Behaviour

Gangsters solocarrying if they are robust.
### Actual Behaviour

Gangsters can't do much because they lack target identification.
### Solution

title.

Firstly, gang leaders will be able distribute gang pens, which furthers cooperation between the boss and the homies, by bringing the possibility of choices, instead of "JUST GIVE EVERYONE GUNS".

Secondly, if a (robust) gangster from a weak gang kills an enemy boss he will be able to snowball the shit out of everything with his pen and possibly bring his gang the victory through a flashy comeback.

**Comment by ghost** [comment]
Here's a better idea.

Give gangleaders chameleon sechuds, so that they can distribute disguised sechuds to their gang buddies to see who is implanted, but not who is in another gang.

**Comment by Nirnael** [comment]
But gangsters can see their fellow gangsters, I don't see what's the problem.
