### ISSUE TITLE
Nano-Sword

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#899]
I was thinking of something to code, that is within my leage.
I know there is a red-alert locker, but it's not used yet.

My idea was:
Nano-Sword 
Desc: A quick reminder that the syndicate isn't the only one with advanced weapons
What does it do? : It is an energy sword that can only be activated by loyalty implanted personell. Can be toggled to do stamina damage.

If it's to OP or weak. Just tell me

**Comment by Kmc2000** [comment]
Doesn't seem very in character really, NT are known to use e-swords already, as DS come with them in their pockets.

What i would like to see is a telescopic stun mace, that can lethal or stun, could be more in theme with ss13.

**Comment by ghost** [comment]
ert has esword and stamina damage sword would be cancer

**Comment by Time-Green** [comment]
Oh yeah.
And stamina damage will be really high.
And is optional, you can just toggle it to murder mode.

And maybe replace the ERT swords with them?
Also, changing damage back to 30 then.

**Comment by ShadowDeath6** [comment]
ERT doesn't have nor need eswords. Stamina damage is annoying already, ESPECIALLY when you make an item do stamina and damage simultaneously.

**Comment by Time-Green** [comment]
Not simultaneously. Toggleable.

**Comment by ghost** [comment]
ERT has esword

so does deathsquad

stamina damage sword would be really fucking cancer because you already have a stunbaton but on the other hand you can chain sword someone endlessly with no cooldown to keep them permastunned forever

**Comment by TheSadFox** [comment]
> ERT has esword

ERT have switchblades afaik, unless its swapped for an esword on the pulse carbine team (don't remember honestly).

**Comment by Super3222** [comment]
ERT's with switchblades are fucking stupid. Enough said.

An esword variation for nanotrasen? I like it.

Not so sure on the stamina damage.

**Comment by Kmc2000** [comment]
But deathsquids already use eswords, NT literally have them

Fuckit, ill sprite something for this. If it looks badass we can add it

**Comment by ghost** [comment]
No
