### ISSUE TITLE
Call of clown: Zombies

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#903]
### Expected Behaviour

HONK
### Actual Behaviour

HoNk :0)

New game mode, tiiiiiny chance of happening

Clown is infected with zX241-b, a dangerous virus that causes rapid mutation and decay of the greymatter, it is transmitted through bodily fluids

The upshot of this is if infected, you become a cluwne. 

The clown would start by being infected, and would need to bite people to infect them, the process would take two seconds, so he'd have to slip them first HONK

Literally zombies but with clowns, all speech is converted to honks and they are forced to wear clown gear. 

HONK

**Comment by ghost** [comment]
Just stop, Kmc

**Comment by X-TheDark** [comment]
I don't think we need this.

**Comment by ToGWtF** [comment]
Zombie needs to be an actual game-mode though

**Comment by Groudonmaster** [comment]
If this is a meme issue please close it KMC. We already have enough of those.

**Comment by Super3222** [comment]
Call of Clown: Zombies
C O C Z
Cocz
Cocks

**Comment by FluffySurvivor** [comment]
> Call of Clown: Zombies
> C O C Z
> Cocz
> Cocks

Ayy lmao

But yeah replace _vomit noises_ **cult** with standard zombies.

**Comment by Kmc2000** [comment]
This actually wasn't entirely a joke, i made an issue about this before and it got traction, with people liking it, but it got lost in the spam

**Comment by ghost** [comment]
close this
