### ISSUE TITLE
Remove Pizza Bomb Gibbing

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#91]
From what I heard, a while back someone got upset because they got gibbed by a tator with C4, or a minibomb, and decided to nerf both so that neither gibbed. By this logic, putting the C4 in a cardboard box wouldn't make much difference, but for only 2 more TC, you can plop a pizza box on someone's corpse and splatter their meaty chunks all over some shitty corner of maint. So if you want to continue the buttmad nerfing frenzy, take away gibbing and we all go home happy.

**Comment by X-TheDark** [comment]
It costs 2 TC more though.

**Comment by AsV9** [comment]
alternatively, make pizza slightly more expensive.

**Comment by ghost** [comment]
No, pizza's perfectly expensive as is. For 2 more TC than a minibomb you get the ability to gib your target only if they're directly on top of the pizza box.

Frankly, re-add C4 gibbing corpses and minibombs gibbing too. We need more lethality, not less.

**Comment by Super3222** [comment]
Pizza bombs were probably meant for giving them to your target as a gift, and watch them go boom as they open it.

The way people generally use them in a more robust way is pistol'ing their target into crit and/or miniebowing them in a stunlock than tossing over the pizza bomb after activating it.

So in conclusion, remove DA.

**Comment by Hydre** [comment]
If you wanna balance it out while removing the gib from it, make the kind of box random. Nobody already opens pizza boxes anymore because of this shit.
Adding gibbing back to C4 is a terrible idea

**Comment by shrimptk** [comment]
@Hydre I actually really like that Idea, replacing the super-meta'd Pizza box with a normal or random container item (e.g briefcase, med kit, toolbelt etc.) would be way better and harder to meta. 

Just imagine, some lone John Sweeps looking for a med kit to patch up his wounds so he can get back to power gaming, but when he pops open that brute kit, **he gets his dick blown off.**

**Comment by shrimptk** [comment]
Sort of like an airlock charge, but for containers

**Comment by Kmc2000** [comment]
+1 To hydre's suggestion, spriting now

**Comment by shrimptk** [comment]
@Kmc2000 I love you

**Comment by BadminBen** [comment]
would have to be coded to different icon states

**Comment by Hydre** [comment]
> spriting now

I don't believe we need new icons though..

**Comment by X-TheDark** [comment]
I agree with shrimp - make "pizza bomb" a plantable charge for any container, like that mousetrap-syndibomb core thing (if that's a thing).

**Comment by shrimptk** [comment]
/tg/ Literally just removed Pizza bombs all together because coding and sprites were terrible, and added bomb core instead which allows you to make a pizza box explosive.

**Comment by BadminBen** [comment]
I agree with the above just alter it to be about to be put in any container. Assistant opens tool box. BOOM!

**Comment by ghost** [comment]
that's called mousetrap + C4 ben

**Comment by B1gb3ast** [comment]
I tried doing this but I suck, apparently I can't recycle the code for clown masks that change the sprite and name.

**Comment by Groudonmaster** [comment]
_would have to be coded to different icon states_
What why?

**Comment by BadminBen** [comment]
f you wanna balance it out while removing the gib from it, make the kind of box random. Nobody already opens pizza boxes anymore because of this shit.

As stated by hydre to answer your question

**Comment by shrimptk** [comment]
Pizza bombs are meta'd to all hell. Container charge > pizza bomb

**Comment by Kmc2000** [comment]
Sprited, le AsVeeeee is working on it
