### ISSUE TITLE
Alien Bug

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#916]
### Expected Behaviour

Alien devours you, admins see it
### Actual Behaviour

It is unlogged.
### Steps to reproduce the problem
1. Have a hunter devour someone

**Comment by ToGWtF** [comment]
i dont think admins need a message when someone gets eaten by a xeno, we already have so many

devour doesnt get logged but grabbing does

**Comment by ghost** [comment]
He doesnt mean giant blue text
It just doesnt show up in view variables

**Comment by ghost** [comment]
Can close?

**Comment by X-TheDark** [comment]
Indeed, it can.
