### ISSUE TITLE
Add Mining Voucher to QM locker

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#920]
### Expected Behaviour

Person most readily responsible for miners has a mining voucher.
### Actual Behaviour

Person who is overwhelmed by requests for all access/desire for HoPcurity has a mining voucher they will never use.
### Steps to reproduce the problem
1. Be QM with no/absent HoP.
2. Attempt to give miners a voucher for increased effectiveness.
3. Contemplate grand theft and trespass in order to break into HoP office and steal the voucher.

**Comment by FluffySurvivor** [comment]
i am dumb hold on

**Comment by FluffySurvivor** [comment]
adressed, @EMT321 or someone else please close.
