### ISSUE TITLE
Can't Vend Objects with Certain Characters in Their Names

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation-classic#921]
### Expected Behaviour

You can vend stuff you put into the chem/viro/kitchen fridge
### Actual Behaviour

You name something with an ampersand or an apostrophe and it becomes unvendable
### Steps to reproduce the problem
1. Name something with an ampersand or apostrophe
2. Put it in vendor
3. Cry because your DNA aide and stimulant disease is unvendable

**Comment by Cruix** [comment]
We need a label just for smart fridges.
