### ISSUE TITLE
Bedsheet togas

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#922]
### Expected Behaviour

Be able to make bedsheets into awesome-looking exosuit for making your 2d spessman look sophisticated and/or pacifist
### Actual Behaviour

Only be able to make shitty capes
### Steps to reproduce the problem
1. Have bedsheet
2. Try to fold toga
3. Cri

**Comment by ToGWtF** [comment]
bedsheet ghosts when

**Comment by doerakpoes** [comment]
YES
