### ISSUE TITLE
Changeling Augmented Eyesight

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#923]
### Expected Behaviour

Changelings can see in the dark and have thermal vision with this evolution.
### Actual Behaviour

As a changeling, I only had thermal vision, and no night vision.

**Comment by ShadowDeath6** [comment]
It works correctly as long as you're not wearing eye protection.

**Comment by ghost** [comment]
I had medical scanners on.

**Comment by Cruix** [comment]
That will block it.

**Comment by FluffySurvivor** [comment]
why is that intended ?
eye protection shouldn't block night vision tbh

**Comment by Greatbigben** [comment]
its intended it seems
