### ISSUE TITLE
Changeling Readapt Bug

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#925]
### Problematic Behavior

As a changeling, I adapted armblade, augmented eyesight, and a shriek.
I then re-adapted and I could see through walls and everything beyond them as long as there was light. This might have something to do with the augmented eyesight bug that I wrote about in my last issue.

**Comment by Cruix** [comment]
When you respec'ed, was the augmented eyesight on or off?
_Someone_ was changing bitflags with the wrong operators again.
https://github.com/yogstation13/yogstation/blob/a2a12d87d0000ab5d0ddb0ea3ba4fea2f62f6ec4/code/game/gamemodes/changeling/evolution_menu.dm#L407-L408

**Comment by ghost** [comment]
I think it was off.

**Comment by Cruix** [comment]
Then it all makes sense. Using the "-" operator when it was off caused the sight bitflags to get all messed up. Pushing fix right after I test it.
