### ISSUE TITLE
Laserguns sometimes shoot like 20 lasers instead of 1

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#929]
### Expected Behaviour

Fire laser gun, get one laser
### Actual Behaviour

http://i.imgur.com/xXO7a30.png
### Steps to reproduce the problem
1. Fire laser gun
2. Get one shot or get 20 shots

**Comment by ghost** [comment]
known bug, if you fire it at pointblank the next shot hits liek 50 times

**Comment by ParagonPrime** [comment]
F-F-F-F-FATALITY

**Comment by FluffySurvivor** [comment]
umad brooooo

legit _RNG COMBAT_

**Comment by X-TheDark** [comment]
Well, at least noone can complain that they are weak anymore.

**Comment by Super3222** [comment]
Wait, what the hell?

**Comment by Groudonmaster** [comment]
It's just visual. It doesn't actually injure the player past the first shot, has been tested multiple times.

**Comment by ghost** [comment]
it uh

it does injure the player past the first shot

this has instantly husked people

**Comment by Groudonmaster** [comment]
Wot. It's advanced since I last saw it then. Last I saw it only the first shot injured and the rest were just sounds and text in the chatbox
