### ISSUE TITLE
Green blob (disorienting fluid) causes permanent and irremovable brain damage

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#930]
### Expected Behaviour

You cure the braindamage normally.
### Actual Behaviour

Get pumped full of mutadone and mannitol, it doesn't go away.
### Steps to reproduce the problem
1. Get afflicted with green blob chem
2. Try to cure it.
3. Go finish the blob core with your 2 xray lasers.
4. Still have braindamage and die reeeee.

**Comment by Time-Green** [comment]
Some things can't be cured

**Comment by ShadowDeath6** [comment]
clumsy mutation isn't brain damage

also it should get cured by mutadone

**Comment by FluffySurvivor** [comment]
Important to note i was ahealed as well and it still didn't go away.

**Comment by oisin100** [comment]
> Important to note i was ahealed as well and it still didn't go away.

I dont think aheal removes mutations.

**Comment by TheSadFox** [comment]
> dont think aheal removes mutations.

It does, or did back in my times and induced rage of multiple geneticists.

**Comment by ShadowDeath6** [comment]
I'm pretty sure aheal doesn't remove mutations, hence why aheal doesn't fix being shanked in the eyes with a screwdriver.

**Comment by FluffySurvivor** [comment]
shadow you broke the game reeeeeeee
