### ISSUE TITLE
Borgs do not have the new mod clicks.

### ISSUE THREAD

**Issue by AsV9** [yogstation13/yogstation-classic#932]
#844

Borgs should have it to make life easier.

**Comment by ParagonPrime** [comment]
I had it as serviceborg earlier today. Will have to see tho.

**Comment by Cruix** [comment]
I have tested and they do.

**Comment by AsV9** [comment]
Huh, weird. I tried using the speed override while playing borg yesterday and it wouldn't work properly.

**Comment by Cruix** [comment]
Ah, I thought you meant the messages. Tested again and they don't have the speed override hotkey. I will fix this tonight.
