### ISSUE TITLE
Limit blob core shunting.

### ISSUE THREAD

**Issue by penguinfisher** [yogstation13/yogstation-classic#934]
### Expected Behaviour

Get the crew to work together to take down blob menace.
### Actual Behaviour

Blob shunts core 34 times and you lose despite everyone giving 110%
### Steps to reproduce the problem
1. Blob round.
2. Grab emitters and rally the troops
3. cry because assistants walk into your beams and the core is constantly moving.

Give it a limit of one or two core movements. That's it.

**Comment by ShadowDeath6** [comment]
salt, it costs 80 chems, that's most of the blob's points.

**Comment by penguinfisher** [comment]
much salt. that blob shunted at least 4 or 5 times while expanding at the stupid rate it has it right now. just a suggested nerf to add to the list.

**Comment by Time-Green** [comment]
Blob is way to OP.
I agree with penguin, there is going to be a nerf thread for blob soon. 
This fits in.

**Comment by ghost** [comment]
80 chems is easy to get
