### ISSUE TITLE
(Secondary antag) Chimera

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#936]
### General idea

A new mini antag, to spice the game up a bit, this guy would start off as something incredibly small, such as a mouse, and would have the unique ability to rapidky evolve based on circumstance, the practical upshot being that: If it comes in contact with another animal, it can mimic certain traits from it and add it onto its own form. 

It would be limited to four traits, each animal wpuld have primary and secondary characteristics, primary would be apearance, secondary an advantageous feature. 

So you could have a mouse, that that takes on a corgi's warm furr, granting heat resistance, a cat's fine eyesight (dark vision) and the bite of a monkey. 

This could be both harmless or deadly depending on what it got into contact with, if you only stocked monkies on station, harmless, but if a miner decided to bring home a dead basilisk as a trophy, things coukd get ugly. 

Certain trait combos however would be harmful to the creature, a few ideas: 
Cat and dog: The pieces are physically repulsed by each other, and can barely be held on to (lowering his health massively) 

Bassically any obvious opposites would clash and be a danger. 
#### Objectives:

Take on a beneficial gene from: a corgi

Attain a total of 100 health, to ensure longevity

Attain cold resistance

Attain space resistance (dolphins and carp)

Chance: Lower than rev, and at least 10  of type: /mob/living/simple_animal on station

Lore: 

Nanotrasen's labs have been breached by animal rights activists, who knows what could have gotten out? 

Why? more antags are always nice, and i feel its good to have one that doesn't NEED to kill. 

If anyone feels like doing this, i can make a full combo list etc.  etc. 

Cheers

**Comment by X-TheDark** [comment]
GET OUT OF HERE, STALKER.

**Comment by Kmc2000** [comment]
And of course, the bigger the mob, the more health it would get

**Comment by ShadowDeath6** [comment]
I actually had an idea like this a while back, where basically a small thing spawned in maints and could eat things to get bigger and bigger and eventually become some horrible monster that could shit on everyone ever

**Comment by Kmc2000** [comment]
> ling

Yeah, this critter would need smart thinking, do i want that warm furr and space resist so i can go swimming, or more offence in case i get dunked...? 

Could be fun

**Comment by TheSadFox** [comment]
> Expecting players to be smart

**Comment by doerakpoes** [comment]
YES agar.io + SS13 best combination!

**Comment by Robertruler77** [comment]
Needs METUL BAWKZEZ ability.

1/10 not enough Carron
