### ISSUE TITLE
Randomized AI lawset at round start

### ISSUE THREAD

**Issue by The-Lieutenant** [yogstation13/yogstation-classic#937]
The idea here is really simple. It's boring for the AI to run the default Asimov lawset at the start of each round. 
There are piles of other lawsets in the upload room, and many of them are never, ever used. I often wonder why they're there in the first place.

I have a simple idea that could add some versatility and intrigue to the AI. 

At the start of every round, a random lawset from a whitelisted "safe" pool of lawsets would be selected and applied. 
Thus, the AI might end up on Asimov, or Corporate, or Asimov ++, or Equality, etc.
 Of course, stuff like "02 is toxic to humans" and the like would best be left off the pool of possible lawsets. But maybe adding the ability for a malf/traitor AI to end up with one of those would be cool as well.

**Comment by Kmc2000** [comment]
Already a PR made on this by groxic

**Comment by ghost** [comment]
Pull request #906

**Comment by The-Lieutenant** [comment]
Oh... I'm new-ish to github. Is there anything I need to do to merge this with your PR?

**Comment by ShadowDeath6** [comment]
You can just close the issue.

**Comment by oisin100** [comment]
Groxic already made a PR For this. Go to #906
