### ISSUE TITLE
Spacing the nuke

### ISSUE THREAD

**Issue by MacHac** [yogstation13/yogstation-classic#939]
### Expected Behaviour

Nuke ops are a force to be reckoned with, requiring the crew to work together to fight them and kill them.
### Actual Behaviour

The second they see the wardec (or a redsuit), every powergaming assistant on the station raids EVA so that they can be the one to space the nuke.
### Steps to reproduce the problem
1. Nuke ops
2. Ops go quiet
3. Get disk
4. Nuke spaced
5. Another ops round
6. Ops go loud and wardec
7. Find captain
8. Get disk
9. Nuke spaced

Every ops round is pretty much the same. Some assistant welds into the side of the shuttle, grabs the nuke, and throws it into space within 10 minutes of ops arrival because ops have no metashield regarding shuttle locations.
###### Give op shuttle badly needed metashield
- No more cases where every miner, engineer, and assistant immediately comb the shuttle locations for ops
- More work for admins
- Players hate being told not to metagame
###### Give op shuttle automated defenses
- Allows ops to leave shuttle largely unattended
- Static turret setups can be memorized, and then countered with metaknowledge
- See: AI core
###### Let ops buy another nuke for TC
- Gives an emergency mulligan
- Most ops spend their TC at the start of the round, so useless for most teams
###### Give ops nuke locator so they can retrieve nuke
- Allows for 'muh immersions'
- Not feasible on a timer
- Random Z level barriers do wierd things to nuke (floating in space forever, ending up on the other side of the station, ect)
- Requires Z level indicator on nuke locator
###### Tell ops to git gud
- Yeah, right
- Ops is already more difficult than most antag types
- Ops becomes boring for the crew and the ops because no matter what happens, all the rounds end the same way
- The odds of none of the nukies being stupid enough to get the nuke spaced approaches 0

Thoughts?  Ops is dull as hell right now, because Urist McMiner is going to space the nuke regardless of what happens on the station.

**Comment by MacHac** [comment]
Before someone says it, I know that there's easy counters to this kind of thing. (Leaving a guard)  The problem is that nobody uses said counters, and that makes ops pointless and repetitive and boring regardless of all the strategy nobody is smart enough to use.

**Comment by Kmc2000** [comment]
Make the nuke start anchored, and need the syndicakes to unanchor. 

Metashield shuttle locations, combing them for the shuttle is bullshit meta

Allow ops to buy moveabke turrets to protect the nuke

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/875

**Comment by MacHac** [comment]
I personally think that #875 should include a metashield, but it would help the problem as is.

**Comment by hawkname** [comment]
Make the shuttle assistant proof; Walls cannot be welded, doors can only be activated with syndies card/military PDA, windows unbreakable. Agree with shuttle location knowledge being meta. The shuttle should be a staging point of assault for nuke ops, not the holy grail for every engineer to fly around looking for it.

**Comment by ToGWtF** [comment]
#596   

I also had some other ideas that could be worked in.

Proposal 1.
Issue #386 
- Possible addition, Syndie nuke anchors can be cut with an extremely long (120+ second) action timer with a welding tool. No one sets the timer above 60 seconds anyway, so this is no easy way to force a minor victory but it is a legitimate threat to nukies who get cocky and set the timer to 5 minutes before returning to their outpost for celebratory drinks

Proposal 2.
Make Cayenne useful. Give Cayenne mega space carp stats(debateable) and make it attack anyone/thing not wearing an Agent ID or without a syndicate implant. Can either be used to defend the syndie shuttle, or brought as a free weapon/distraction.

Proposal 3.
Make the walls of the shuttle Rwalls, so they can't be instantly RCD'd into and robbed.

Proposal 4.
Non-syndicate cyborgs can no longer interact with the Syndicate shuttle door button, or the console to move the shuttle.

**Comment by Kmc2000** [comment]
> buff cayenne

Or you know, add in the freshly nerfed tactical harness for tacticarp warfare 

But for 20tc, those things are ungodly

**Comment by Super3222** [comment]
> Give op shuttle badly needed metashield

This is desperately needed. Sorry guys, but it shouldn't be a coincidence. Buy pinpointer's, and when you find the ship just report back over comms. Or you know, don't if they get bombed. Tough shit.

> Give op shuttle automated defenses

Yeah, I think ToGWTF had added turrets to the map (they already existed in code). They work in both war and non-war situations, thankfully. This was merged awhile ago.

I'd like to suggest that the walls of the syndicate space shuttle get changed to reinforced walls.

> Let ops buy another nuke for TC

That sounds great, but in return it'd have to cost a lot of TC. Still a fair amount though.

**Comment by ghost** [comment]
they're adding turrets, remember

**Comment by ghost** [comment]
i suppose you could also make the nuke start anchored, so while raiding the shuttle is possible, spacing the nuke is not as easily possible

also metashielding the syndie shuttle is dumb because jesus christ do you think they floated in on a goddamn mattress? nah, just make it hard to raid so that a dedicated team can take it down

mechanics discouragement is infinitely superior to rules discouragement

**Comment by ghost** [comment]
again, always-active gun turrets that target anything not with a syndie ID and fire 30-40 damage bullets + stamina means that one assistant is going to get assfucked and you'll need a whole team to raid the shuttle

**Comment by MacHac** [comment]
Adam, consider that any assistant with a toolbelt and conference room access can be inside the AI core in under five minutes.  Any static turret setup can be gamed and will be gamed.

**Comment by ToGWtF** [comment]
The turrets will be a deterrent. Easily bypassed by floating in space and throwing something to redirect yourself. Hell, you can push a locker in space and jump/jetpack behind it. And if you've landed at the armory,  they can't even shoot you if you're breaking in from behind.

I COULD make them do the full 60 damage on War mode instead of 25,  but two concerns A) 60 damage per shot from two turrets is insta-rip  and B) You get between the turret and its target and get cucked

**Comment by Greatbigben** [comment]
Just make the walls unbreakable
