### ISSUE TITLE
Detective Revolver vs blob

### ISSUE THREAD

**Issue by Friggs** [yogstation13/yogstation-classic#941]
### Expected Behaviour

Detective's Rubber bullets not doing much against a blob
### Actual Behaviour

Blob gets a path ripped through it by rubber bullets
### Steps to reproduce the problem
1. Fire a revolver at a blob
2. Watch the destruction

**Comment by ghost** [comment]
Might as well just port /tg/'s entire blob.

**Comment by ShadowDeath6** [comment]
This happens with any projectiles, including buckshot or lasers. It happens SOMETIMES.

**Comment by ToGWtF** [comment]
Because detectives revolver does the same damage as a fireaxe. Fireaxe can actually be used somewhat reliably against a blob
