### ISSUE TITLE
alien queen stops escape shuttle from leaving

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#945]
### Expected Behaviour

have fun as xenos
### Actual Behaviour

shuttle gets called the second they see you

having an alien queen on station zlevel should delay the shuttle from being able to leave the same way blob does

**Comment by ShadowDeath6** [comment]
Random blobs don't delay shuttle though :^)

**Comment by ToGWtF** [comment]
i can make them

**Comment by Cruix** [comment]
That could screw over antags with escape objectives

**Comment by ToGWtF** [comment]
xenos already screw over antags. so does zombie but thats an RNG event where xenos are either bussed in or found on mining (even less rng chances of it spawning)

**Comment by Super3222** [comment]
RNG antags shouldn't be able to automatically stop escape shuttles.

> That could screw over antags with escape objectives

**Comment by Alblaka** [comment]
And back we are too my concept of a 'biohazard shuttle' that increases shuttle timer to 20 min when RNG spawned biohazards are present.

**Comment by Super3222** [comment]
> Alblaka not refrencing his issue

#411

**Comment by ToGWtF** [comment]
Sure. making a shuttle take an extra 10-20 minutes doesnt sound like that much.
