### ISSUE TITLE
Hud on invisible mobs.

### ISSUE THREAD

**Issue by Nirnael** [yogstation13/yogstation-classic#952]
### Expected Behaviour

Shouldnt appear
### Actual Behaviour

Appears
### Steps to reproduce the problem
1. Stealthed predator can be seen on sec hud.

I'm asigning this to myself to see if i can fix it.

**Comment by Super3222** [comment]
Predators going invisible isn't a feature yet.

It must have been invisimin.

**Comment by Kmc2000** [comment]
Can confirm, was bussed in using invisimin

**Comment by Nirnael** [comment]
Oh well, still shouldn't show the hud.
