### ISSUE TITLE
Phytosian Nukeops

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#953]
### Expected Behaviour

Have phytosian selected as a race. Become Human when chosen for newcops.
### Actual Behaviour

Be phytosian newcop. Die from lack of light in maints and other areas.
### Steps to reproduce the problem
1. Become nukeop.
2. Team goes into maints. Cry in a corner as you realize you cant follow them.
### Possible Fix
1. Give nukeops some sort of handheld light
2. Convert Phytosian nukeops into human nukeops.

Theres a desk lamp in the infiltrator cockpit but you cant fit it into your pockets. 

Inb4 "git gud"

**Comment by ToGWtF** [comment]
Want to play a race with OP healing? Well you gotta enjoy the downsides as well

Although forcing nukeops to the same species would be interesting.  RNG each nukeop team to a different species. So a full team of Unathi,  or Preternis,  ect.

**Comment by ParagonPrime** [comment]
Phytosian nukies is actually surprisingly awesome. Especially considering the innate healing that space will give you.

This is the only time I'll say this, but...

git gud

**Comment by Kmc2000** [comment]
> flashlight

Or you know, the light from the helmet in space mode?

**Comment by oisin100** [comment]
> Or you know, the light from the helmet in space mode?

Doesent give enough.

**Comment by Time-Green** [comment]
It does, it just does not lit space tiles. And in space you barely heal due to reasons

**Comment by ShadowDeath6** [comment]
Use desk lamp

**Comment by Super3222** [comment]
> Want to play a race with OP healing? Well you gotta enjoy the downsides as well

This. Phytosians were never meant for new cop raids.

**Comment by Cruix** [comment]
But you don't know that you are going to play as a nukeop before round start.

**Comment by Groudonmaster** [comment]
#Human best race

**Comment by Super3222** [comment]
> But you don't know that you are going to play as a nukeop before round start.

Than make nuclear operatives always spawn as humans. #HumanElitism

Better yet, make all of the nuclear operatives spawn as the SAME race as the LEADER.

**Comment by ShadowDeath6** [comment]
Why would I wanna be a special snowflake race not of my own volition
Make all ops start human or keep it the same and git fukkin gud
