### ISSUE TITLE
Can't walk along/next to plating in space

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#965]
### Expected Behaviour

People in space can walk along plating (I think they are floor tiles) in space. They walk next to it, not directly on it.
### Actual Behaviour

A person in space can only walk on top of plating but not use it for propulsion like you can with lattices and such.
### Steps to reproduce the problem
1. Walk out of airlock (eg. arrivals airlock)
2. Look for nearest plating/lattice structure
3. Propel yourself towards the plating structure and try to walk next to it, but not on it.
4. Fail and die in space.

**Comment by Time-Green** [comment]
Gravity logic
If this would be changed, deactivating the gravity generator wouldn't change a single thing

**Comment by ghost** [comment]
Oh. I see.
