### ISSUE TITLE
Borer Host Stats

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#966]
Give borer the ability to view the stats of the host, similar to what using a health analyzer would do.

**Comment by Groudonmaster** [comment]
Can't you do that just by taking control of the host?

**Comment by ghost** [comment]
Yes, but it's inefficient, takes time, causes more mild distrust from host, and you can't inject chemicals when you assume control. I can't heal my host well if all I see of them is just their body lying on the floor.

**Comment by ToGWtF** [comment]
You can already shift-click to see if your host is damaged, since different damage types show up

**Comment by ShadowDeath6** [comment]
Can't tell if toxins though

**Comment by Groudonmaster** [comment]
Well I mean, if they're not visibly injured, and they've kind of just passed out, it's kind of obvious.
