### ISSUE TITLE
Artificer floor cult spell does nothing

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#967]
### Expected Behaviour

It makes cult floors
### Actual Behaviour

It just replates the floor
IT works in space though
### Steps to reproduce the problem

Be artificier

Use spell

Nothing

Also can you just make artificers make cult floors automatically as they pass over a tile

**Comment by FluffySurvivor** [comment]
I have the solution right here.
**REMOVE CULT**

**Comment by Alblaka** [comment]
> Also can you just make artificers make cult floors automatically as they pass over a tile

Why would you suggest to nerf cult by making the only not-as-obvious constructs hyper obvious?

**Comment by ShadowDeath6** [comment]
I think I heard once that they don't make cult floor because narsie used to do that and turning every single turf it came across into cult floor made the game lag like ass so it was replaced with regular floors

Also it does name it to "engraved floor", it just doesn't change the icon

**Comment by ghost** [comment]
lag is dead and gone so lag-sie is no longer an issue

@Alblaka artificers should never leave  the cult base anyway unless partnering with a construct for repairs/murderbone so this is more mechanics discouragement for shitty artificer play

not to mention artificers are easily noticeable like all constructs-they don't have a 'stealth' mode

**Comment by ShadowDeath6** [comment]
Give artificers cloak when
