### ISSUE TITLE
Extra Content like faction,relation,home system,etc

### ISSUE THREAD

**Issue by itus2k** [yogstation13/yogstation-classic#97]
*Facion and Relationship : ex:i am an agent of nanotrasen i totaly loyal to he i will never do nothing who can hurt nano trasen in my life,Standard Factions : Syndicate,nanotrasen and Space Wizard Federation.
*Skils : ex :i am expert in close combat
*ic Caracter History: ex:i was an loyal agent of nanotrasen in past.
*Home Planet and System: Ex: sol/sun
*Launguage:Diferent space launguage like xenomorph and the most common launguage to most un common (you will know by jobs Ex:Captain)

**Comment by ghost** [comment]
what

**Comment by ghost** [comment]
what the fuck

**Comment by X-TheDark** [comment]
Why? What would this even add to the server?

**Comment by itus2k** [comment]
rp informations,WHy is in station,nanotrasen relation ship why be an traitor ro special role (launguage= if found another race ) (and can do some new game antagonists) (new launguages will permit the antagonistis talk in a real secret code this will turn station more real)

**Comment by X-TheDark** [comment]
I see, it's an interesting concept, I suppose. My personal opinion is that Yogstation is fine where it is now, in regards to roleplay and it's enforcement and this feature is not necessary.

**Comment by AsV9** [comment]
This adds nothing to a low-RP server of real value towards players in general.

**Comment by Super3222** [comment]
Sorry bud, this is the wrong type of server for that.

**Comment by george99g** [comment]
General agreement is to not work on getting this in.
I'll just close the issue.
