### ISSUE TITLE
New Chem: Liquid Darkness

### ISSUE THREAD

**Issue by MacHac** [yogstation13/yogstation-classic#970]
#### What if there was a chemical that could remove light?

Well, that would probably be pretty kickass.
##### It's like pyrosium, but removes light.  (and also doesn't make fire)

Made by mixing stabilized dark matter with cryostylane, liquid darkness is a blinding chemical with a twist.  When poured on a surface, it acts as a 'reverse light': It sucks light from the surrounding area, dimming flashlights and forcing your enemies to fight in the dark.
#### Why would we need that?
- As a traitor, use it to hide bodies, or like a smokebomb for a quick escape.
- As a nuke op, spray areas with it and laugh as your night vision leaves you immune.
- As a shadowling, have the janitor run around and mop floors with the stuff.
- Conceal areas from the AI's camera lights.
- Force enemies to walk into traps in the dark.

**Comment by ShadowDeath6** [comment]
so is this supposed to be on reaction or just dim any tile that it's applied to

**Comment by Super3222** [comment]
Awkward dark tile spots? People will think that lights broke again.

Though this does sound cool and I like it, but it's not very logical to be honest.

**Comment by TehFlaminTaco** [comment]
I am not coding that.
I refuse to touch the lighting engine like that.
(It will hate me)

**Comment by MacHac** [comment]
A dimming agent, not a reaction.  You splash it onto a tile, and it reacts with oxygen in the air or in the mixture to drain light from the area.
