### ISSUE TITLE
Lich Wizard Phylacteries are Immpossible to Find

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation-classic#976]
### Expected Behaviour

There are counters to Lich wizards.
### Actual Behaviour

Cruix goes lich every time he rolls wizard and gets outrobusted by the crew at least 5 times, but still lives because his phylactery is in a 1x1 room you can only get into by ethereal jaunting.
### Solution

Make the pinpointer locate phylacteries.

or

Make using ARISE!!! drop an item on the lich's old body that points toward the phylactery, possibly deactivating when the ability is off cooldown, to give the wizard a chance to hide it again after a few minutes.
EDIT:
or

There is a revenant-style beam from the old body to the new body for around 10 seconds after the lich "dies".

**Comment by X-TheDark** [comment]
Doesn't dying as Wizwoz leave a visible_message to everyone in range that [X]'s remains have flown to [INSERT_AREA_NAME_HERE]?

Other than that, a more visible indications would be good. Or at least let the detective or something scan the remains to "trace the aether energies to their origin".

**Comment by PineappleWolf** [comment]
Actually the AI has tracked me to my Phylactery before, I was pretty sure the pinpointer did that. Otherwise I am unaware about how the AI tracked me.

**Comment by ghost** [comment]
the message is only 'it flies to the northwest.'

Give it a sort of revenant-style beam that leads to the phylactery when the lich dies.

**Comment by ShadowDeath6** [comment]
tg did it
