### ISSUE TITLE
powersinks suck ass

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#977]
### Expected Behaviour

it actually drains enough power to shut off lights, equipment, ect, and is a serious inconvenience
### Actual Behaviour

sometimes it depowers the central hallway vending machines and nothing else
### Steps to reproduce the problem

1.buy powersink
2. attatch powersink
3. it powerstinks.

seriously you can't even use it if someone set up the tesla or sing and even if you decon the fucking smes it still won't drain power

increase powerdrain by a fuckton and give it a bigger explosion capacity pls

**Comment by oisin100** [comment]
It blows up before it does anything usefull :(

**Comment by ShadowDeath6** [comment]
It's stupidly powerful if you use it before engine is up, especially if you decon the smes
The problem is that people use it when smes are fully charged
