### ISSUE TITLE
detomatrix buff

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#978]
### Expected Behaviour

it's a good item
### Actual Behaviour

it has a random chance to fucking blow up your entire uplink for no reason
### Steps to reproduce the problem

buy

use

explode

can we remove the random chance for explosions and failures? no other antag item in the entire game has a random chance to say 'XXXXXXXXXXXXXXXXXXD DIE'

**Comment by ToGWtF** [comment]
Not to mention it has a chance to outright fail like 40% of the time

**Comment by oisin100** [comment]
RNG Should not be a thing in situations like this.
