### ISSUE TITLE
Galoshes don't block lube

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/yogstation-classic#992]
This makes no sense. As is, lube is stupidly overpowered area denial.

**Comment by Super3222** [comment]
Don't know whether this is necessary or not, but it's probably not. The point of lube is to be an area denier, and than if galoshes could block lube than the buff to the no-slip shoes wouldn't mean anything.

You could kill the jaintor, steal his galoshes, and spare yourself from spending TC.
