### ISSUE TITLE
Give secHuD's a hotkey.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#997]
Hold Ctrl + W + click to set the person you clicked to arrest with sechuds. Doing so again takes them off arrest. Ctrl + alt + click allows you to set arrest reason.

Because sometimes people lag out when setting people to arrest with sechuds-shift click plus click arrest is usually more difficult on a moving target than just going to the computer.

Examining someone with sechuds on tells you their arrest reason.

**Comment by X-TheDark** [comment]
I'm not sure BYOND by itself provides a way to check what keys (besides modifiers - Ctrl/Alt/Shift) a person has pressed when he clicks.

**Comment by ShadowDeath6** [comment]
> try to set someone on arrest
> run directly into the wall when you hit 'w'
